// File generated from our OpenAPI spec by Stainless.

package com.telnyx.api.models.webhooks

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.api.core.jsonMapper
import com.telnyx.api.models.calls.CustomSipHeader
import com.telnyx.api.models.calls.SipHeader
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CallHangupWebhookEventTest {

    @Test
    fun create() {
        val callHangupWebhookEvent =
            CallHangupWebhookEvent.builder()
                .data(
                    CallHangupWebhookEvent.Data.builder()
                        .id("0ccc7b54-4df3-4bca-a65a-3da1ecc777f0")
                        .eventType(CallHangupWebhookEvent.Data.EventType.CALL_HANGUP)
                        .occurredAt(OffsetDateTime.parse("2018-02-02T22:25:27.521992Z"))
                        .payload(
                            CallHangupWebhookEvent.Data.Payload.builder()
                                .callControlId(
                                    "v3:MdI91X4lWFEs7IgbBEOT9M4AigoY08M0WWZFISt1Yw2axZ_IiE4pqg"
                                )
                                .callLegId("428c31b6-7af4-4bcb-b7f5-5013ef9657c1")
                                .callQualityStats(
                                    CallHangupWebhookEvent.Data.Payload.CallQualityStats.builder()
                                        .inbound(
                                            CallHangupWebhookEvent.Data.Payload.CallQualityStats
                                                .Inbound
                                                .builder()
                                                .jitterMaxVariance("2.74")
                                                .jitterPacketCount("0")
                                                .mos("4.50")
                                                .packetCount("591")
                                                .skipPacketCount("9")
                                                .build()
                                        )
                                        .outbound(
                                            CallHangupWebhookEvent.Data.Payload.CallQualityStats
                                                .Outbound
                                                .builder()
                                                .packetCount("0")
                                                .skipPacketCount("0")
                                                .build()
                                        )
                                        .build()
                                )
                                .callSessionId("428c31b6-7af4-4bcb-b7f5-5013ef9657c1")
                                .clientState("aGF2ZSBhIG5pY2UgZGF5ID1d")
                                .connectionId("7267xxxxxxxxxxxxxx")
                                .addCustomHeader(
                                    CustomSipHeader.builder().name("head_1").value("val_1").build()
                                )
                                .addCustomHeader(
                                    CustomSipHeader.builder().name("head_2").value("val_2").build()
                                )
                                .from("+35319605860")
                                .hangupCause(
                                    CallHangupWebhookEvent.Data.Payload.HangupCause.CALL_REJECTED
                                )
                                .hangupSource(
                                    CallHangupWebhookEvent.Data.Payload.HangupSource.CALLER
                                )
                                .sipHangupCause("603")
                                .addSipHeader(
                                    SipHeader.builder()
                                        .name(SipHeader.Name.USER_TO_USER)
                                        .value("1234")
                                        .build()
                                )
                                .addSipHeader(
                                    SipHeader.builder()
                                        .name(SipHeader.Name.USER_TO_USER)
                                        .value("<sip:111@192.168.1.1>")
                                        .build()
                                )
                                .startTime(OffsetDateTime.parse("2018-02-02T22:20:27.521992Z"))
                                .state(CallHangupWebhookEvent.Data.Payload.State.HANGUP)
                                .addTag("tag-01")
                                .addTag("tag-02")
                                .to("+35319605860")
                                .build()
                        )
                        .recordType(CallHangupWebhookEvent.Data.RecordType.EVENT)
                        .build()
                )
                .build()

        assertThat(callHangupWebhookEvent.data())
            .contains(
                CallHangupWebhookEvent.Data.builder()
                    .id("0ccc7b54-4df3-4bca-a65a-3da1ecc777f0")
                    .eventType(CallHangupWebhookEvent.Data.EventType.CALL_HANGUP)
                    .occurredAt(OffsetDateTime.parse("2018-02-02T22:25:27.521992Z"))
                    .payload(
                        CallHangupWebhookEvent.Data.Payload.builder()
                            .callControlId(
                                "v3:MdI91X4lWFEs7IgbBEOT9M4AigoY08M0WWZFISt1Yw2axZ_IiE4pqg"
                            )
                            .callLegId("428c31b6-7af4-4bcb-b7f5-5013ef9657c1")
                            .callQualityStats(
                                CallHangupWebhookEvent.Data.Payload.CallQualityStats.builder()
                                    .inbound(
                                        CallHangupWebhookEvent.Data.Payload.CallQualityStats.Inbound
                                            .builder()
                                            .jitterMaxVariance("2.74")
                                            .jitterPacketCount("0")
                                            .mos("4.50")
                                            .packetCount("591")
                                            .skipPacketCount("9")
                                            .build()
                                    )
                                    .outbound(
                                        CallHangupWebhookEvent.Data.Payload.CallQualityStats
                                            .Outbound
                                            .builder()
                                            .packetCount("0")
                                            .skipPacketCount("0")
                                            .build()
                                    )
                                    .build()
                            )
                            .callSessionId("428c31b6-7af4-4bcb-b7f5-5013ef9657c1")
                            .clientState("aGF2ZSBhIG5pY2UgZGF5ID1d")
                            .connectionId("7267xxxxxxxxxxxxxx")
                            .addCustomHeader(
                                CustomSipHeader.builder().name("head_1").value("val_1").build()
                            )
                            .addCustomHeader(
                                CustomSipHeader.builder().name("head_2").value("val_2").build()
                            )
                            .from("+35319605860")
                            .hangupCause(
                                CallHangupWebhookEvent.Data.Payload.HangupCause.CALL_REJECTED
                            )
                            .hangupSource(CallHangupWebhookEvent.Data.Payload.HangupSource.CALLER)
                            .sipHangupCause("603")
                            .addSipHeader(
                                SipHeader.builder()
                                    .name(SipHeader.Name.USER_TO_USER)
                                    .value("1234")
                                    .build()
                            )
                            .addSipHeader(
                                SipHeader.builder()
                                    .name(SipHeader.Name.USER_TO_USER)
                                    .value("<sip:111@192.168.1.1>")
                                    .build()
                            )
                            .startTime(OffsetDateTime.parse("2018-02-02T22:20:27.521992Z"))
                            .state(CallHangupWebhookEvent.Data.Payload.State.HANGUP)
                            .addTag("tag-01")
                            .addTag("tag-02")
                            .to("+35319605860")
                            .build()
                    )
                    .recordType(CallHangupWebhookEvent.Data.RecordType.EVENT)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val callHangupWebhookEvent =
            CallHangupWebhookEvent.builder()
                .data(
                    CallHangupWebhookEvent.Data.builder()
                        .id("0ccc7b54-4df3-4bca-a65a-3da1ecc777f0")
                        .eventType(CallHangupWebhookEvent.Data.EventType.CALL_HANGUP)
                        .occurredAt(OffsetDateTime.parse("2018-02-02T22:25:27.521992Z"))
                        .payload(
                            CallHangupWebhookEvent.Data.Payload.builder()
                                .callControlId(
                                    "v3:MdI91X4lWFEs7IgbBEOT9M4AigoY08M0WWZFISt1Yw2axZ_IiE4pqg"
                                )
                                .callLegId("428c31b6-7af4-4bcb-b7f5-5013ef9657c1")
                                .callQualityStats(
                                    CallHangupWebhookEvent.Data.Payload.CallQualityStats.builder()
                                        .inbound(
                                            CallHangupWebhookEvent.Data.Payload.CallQualityStats
                                                .Inbound
                                                .builder()
                                                .jitterMaxVariance("2.74")
                                                .jitterPacketCount("0")
                                                .mos("4.50")
                                                .packetCount("591")
                                                .skipPacketCount("9")
                                                .build()
                                        )
                                        .outbound(
                                            CallHangupWebhookEvent.Data.Payload.CallQualityStats
                                                .Outbound
                                                .builder()
                                                .packetCount("0")
                                                .skipPacketCount("0")
                                                .build()
                                        )
                                        .build()
                                )
                                .callSessionId("428c31b6-7af4-4bcb-b7f5-5013ef9657c1")
                                .clientState("aGF2ZSBhIG5pY2UgZGF5ID1d")
                                .connectionId("7267xxxxxxxxxxxxxx")
                                .addCustomHeader(
                                    CustomSipHeader.builder().name("head_1").value("val_1").build()
                                )
                                .addCustomHeader(
                                    CustomSipHeader.builder().name("head_2").value("val_2").build()
                                )
                                .from("+35319605860")
                                .hangupCause(
                                    CallHangupWebhookEvent.Data.Payload.HangupCause.CALL_REJECTED
                                )
                                .hangupSource(
                                    CallHangupWebhookEvent.Data.Payload.HangupSource.CALLER
                                )
                                .sipHangupCause("603")
                                .addSipHeader(
                                    SipHeader.builder()
                                        .name(SipHeader.Name.USER_TO_USER)
                                        .value("1234")
                                        .build()
                                )
                                .addSipHeader(
                                    SipHeader.builder()
                                        .name(SipHeader.Name.USER_TO_USER)
                                        .value("<sip:111@192.168.1.1>")
                                        .build()
                                )
                                .startTime(OffsetDateTime.parse("2018-02-02T22:20:27.521992Z"))
                                .state(CallHangupWebhookEvent.Data.Payload.State.HANGUP)
                                .addTag("tag-01")
                                .addTag("tag-02")
                                .to("+35319605860")
                                .build()
                        )
                        .recordType(CallHangupWebhookEvent.Data.RecordType.EVENT)
                        .build()
                )
                .build()

        val roundtrippedCallHangupWebhookEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(callHangupWebhookEvent),
                jacksonTypeRef<CallHangupWebhookEvent>(),
            )

        assertThat(roundtrippedCallHangupWebhookEvent).isEqualTo(callHangupWebhookEvent)
    }
}
