/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BucketOps
 */
public class BucketOpsTest {
    private final BucketOps model = new BucketOps();

    /**
     * Model tests for BucketOps
     */
    @Test
    public void testBucketOps() {
        // TODO: test BucketOps
    }

    /**
     * Test the property 'bytesSent'
     */
    @Test
    public void bytesSentTest() {
        // TODO: test bytesSent
    }

    /**
     * Test the property 'bytesReceived'
     */
    @Test
    public void bytesReceivedTest() {
        // TODO: test bytesReceived
    }

    /**
     * Test the property 'ops'
     */
    @Test
    public void opsTest() {
        // TODO: test ops
    }

    /**
     * Test the property 'successfulOps'
     */
    @Test
    public void successfulOpsTest() {
        // TODO: test successfulOps
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

}
