/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomerServiceRecordPhoneNumberCoverage
 */
public class CustomerServiceRecordPhoneNumberCoverageTest {
    private final CustomerServiceRecordPhoneNumberCoverage model = new CustomerServiceRecordPhoneNumberCoverage();

    /**
     * Model tests for CustomerServiceRecordPhoneNumberCoverage
     */
    @Test
    public void testCustomerServiceRecordPhoneNumberCoverage() {
        // TODO: test CustomerServiceRecordPhoneNumberCoverage
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'hasCsrCoverage'
     */
    @Test
    public void hasCsrCoverageTest() {
        // TODO: test hasCsrCoverage
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'additionalDataRequired'
     */
    @Test
    public void additionalDataRequiredTest() {
        // TODO: test additionalDataRequired
    }

    /**
     * Test the property 'recordType'
     */
    @Test
    public void recordTypeTest() {
        // TODO: test recordType
    }

}
