/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.telnyx.sdk.model.AmdDetailRecord;
import com.telnyx.sdk.model.ConferenceDetailRecord;
import com.telnyx.sdk.model.ConferenceParticipantDetailRecord;
import com.telnyx.sdk.model.MediaStorageDetailRecord;
import com.telnyx.sdk.model.MessageDetailRecord;
import com.telnyx.sdk.model.SimCardUsageDetailRecord;
import com.telnyx.sdk.model.VerifyDetailRecord;
import com.telnyx.sdk.model.WhatsAppConversationDetailRecord;
import com.telnyx.sdk.model.WhatsAppDetailRecord;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DetailRecord
 */
public class DetailRecordTest {
    private final DetailRecord model = new DetailRecord();

    /**
     * Model tests for DetailRecord
     */
    @Test
    public void testDetailRecord() {
        // TODO: test DetailRecord
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'completedAt'
     */
    @Test
    public void completedAtTest() {
        // TODO: test completedAt
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'sentAt'
     */
    @Test
    public void sentAtTest() {
        // TODO: test sentAt
    }

    /**
     * Test the property 'carrier'
     */
    @Test
    public void carrierTest() {
        // TODO: test carrier
    }

    /**
     * Test the property 'carrierFee'
     */
    @Test
    public void carrierFeeTest() {
        // TODO: test carrierFee
    }

    /**
     * Test the property 'cld'
     */
    @Test
    public void cldTest() {
        // TODO: test cld
    }

    /**
     * Test the property 'cli'
     */
    @Test
    public void cliTest() {
        // TODO: test cli
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'deliveryStatus'
     */
    @Test
    public void deliveryStatusTest() {
        // TODO: test deliveryStatus
    }

    /**
     * Test the property 'deliveryStatusFailoverUrl'
     */
    @Test
    public void deliveryStatusFailoverUrlTest() {
        // TODO: test deliveryStatusFailoverUrl
    }

    /**
     * Test the property 'deliveryStatusWebhookUrl'
     */
    @Test
    public void deliveryStatusWebhookUrlTest() {
        // TODO: test deliveryStatusWebhookUrl
    }

    /**
     * Test the property 'direction'
     */
    @Test
    public void directionTest() {
        // TODO: test direction
    }

    /**
     * Test the property 'fteu'
     */
    @Test
    public void fteuTest() {
        // TODO: test fteu
    }

    /**
     * Test the property 'mcc'
     */
    @Test
    public void mccTest() {
        // TODO: test mcc
    }

    /**
     * Test the property 'mnc'
     */
    @Test
    public void mncTest() {
        // TODO: test mnc
    }

    /**
     * Test the property 'messageType'
     */
    @Test
    public void messageTypeTest() {
        // TODO: test messageType
    }

    /**
     * Test the property 'onNet'
     */
    @Test
    public void onNetTest() {
        // TODO: test onNet
    }

    /**
     * Test the property 'profileId'
     */
    @Test
    public void profileIdTest() {
        // TODO: test profileId
    }

    /**
     * Test the property 'profileName'
     */
    @Test
    public void profileNameTest() {
        // TODO: test profileName
    }

    /**
     * Test the property 'sourceCountryCode'
     */
    @Test
    public void sourceCountryCodeTest() {
        // TODO: test sourceCountryCode
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'rate'
     */
    @Test
    public void rateTest() {
        // TODO: test rate
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'cost'
     */
    @Test
    public void costTest() {
        // TODO: test cost
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'parts'
     */
    @Test
    public void partsTest() {
        // TODO: test parts
    }

    /**
     * Test the property 'recordType'
     */
    @Test
    public void recordTypeTest() {
        // TODO: test recordType
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'startedAt'
     */
    @Test
    public void startedAtTest() {
        // TODO: test startedAt
    }

    /**
     * Test the property 'endedAt'
     */
    @Test
    public void endedAtTest() {
        // TODO: test endedAt
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'callLegId'
     */
    @Test
    public void callLegIdTest() {
        // TODO: test callLegId
    }

    /**
     * Test the property 'callSessionId'
     */
    @Test
    public void callSessionIdTest() {
        // TODO: test callSessionId
    }

    /**
     * Test the property 'connectionId'
     */
    @Test
    public void connectionIdTest() {
        // TODO: test connectionId
    }

    /**
     * Test the property 'callSec'
     */
    @Test
    public void callSecTest() {
        // TODO: test callSec
    }

    /**
     * Test the property 'participantCount'
     */
    @Test
    public void participantCountTest() {
        // TODO: test participantCount
    }

    /**
     * Test the property 'participantCallSec'
     */
    @Test
    public void participantCallSecTest() {
        // TODO: test participantCallSec
    }

    /**
     * Test the property 'isTelnyxBillable'
     */
    @Test
    public void isTelnyxBillableTest() {
        // TODO: test isTelnyxBillable
    }

    /**
     * Test the property 'conferenceId'
     */
    @Test
    public void conferenceIdTest() {
        // TODO: test conferenceId
    }

    /**
     * Test the property 'joinedAt'
     */
    @Test
    public void joinedAtTest() {
        // TODO: test joinedAt
    }

    /**
     * Test the property 'leftAt'
     */
    @Test
    public void leftAtTest() {
        // TODO: test leftAt
    }

    /**
     * Test the property 'destinationNumber'
     */
    @Test
    public void destinationNumberTest() {
        // TODO: test destinationNumber
    }

    /**
     * Test the property 'originatingNumber'
     */
    @Test
    public void originatingNumberTest() {
        // TODO: test originatingNumber
    }

    /**
     * Test the property 'billedSec'
     */
    @Test
    public void billedSecTest() {
        // TODO: test billedSec
    }

    /**
     * Test the property 'rateMeasuredIn'
     */
    @Test
    public void rateMeasuredInTest() {
        // TODO: test rateMeasuredIn
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'senderId'
     */
    @Test
    public void senderIdTest() {
        // TODO: test senderId
    }

    /**
     * Test the property 'recipientId'
     */
    @Test
    public void recipientIdTest() {
        // TODO: test recipientId
    }

    /**
     * Test the property 'messageStatus'
     */
    @Test
    public void messageStatusTest() {
        // TODO: test messageStatus
    }

    /**
     * Test the property 'recipientRegionCode'
     */
    @Test
    public void recipientRegionCodeTest() {
        // TODO: test recipientRegionCode
    }

    /**
     * Test the property 'whatsappErrorCode'
     */
    @Test
    public void whatsappErrorCodeTest() {
        // TODO: test whatsappErrorCode
    }

    /**
     * Test the property 'webhookReceivedAt'
     */
    @Test
    public void webhookReceivedAtTest() {
        // TODO: test webhookReceivedAt
    }

    /**
     * Test the property 'webhookId'
     */
    @Test
    public void webhookIdTest() {
        // TODO: test webhookId
    }

    /**
     * Test the property 'telnyxFee'
     */
    @Test
    public void telnyxFeeTest() {
        // TODO: test telnyxFee
    }

    /**
     * Test the property 'whatsappFee'
     */
    @Test
    public void whatsappFeeTest() {
        // TODO: test whatsappFee
    }

    /**
     * Test the property 'conversationId'
     */
    @Test
    public void conversationIdTest() {
        // TODO: test conversationId
    }

    /**
     * Test the property 'conversationOrigin'
     */
    @Test
    public void conversationOriginTest() {
        // TODO: test conversationOrigin
    }

    /**
     * Test the property 'whatsappBusinessAccountId'
     */
    @Test
    public void whatsappBusinessAccountIdTest() {
        // TODO: test whatsappBusinessAccountId
    }

    /**
     * Test the property 'invokedAt'
     */
    @Test
    public void invokedAtTest() {
        // TODO: test invokedAt
    }

    /**
     * Test the property 'feature'
     */
    @Test
    public void featureTest() {
        // TODO: test feature
    }

    /**
     * Test the property 'billingGroupId'
     */
    @Test
    public void billingGroupIdTest() {
        // TODO: test billingGroupId
    }

    /**
     * Test the property 'billingGroupName'
     */
    @Test
    public void billingGroupNameTest() {
        // TODO: test billingGroupName
    }

    /**
     * Test the property 'connectionName'
     */
    @Test
    public void connectionNameTest() {
        // TODO: test connectionName
    }

    /**
     * Test the property 'verifyProfileId'
     */
    @Test
    public void verifyProfileIdTest() {
        // TODO: test verifyProfileId
    }

    /**
     * Test the property 'verificationStatus'
     */
    @Test
    public void verificationStatusTest() {
        // TODO: test verificationStatus
    }

    /**
     * Test the property 'destinationPhoneNumber'
     */
    @Test
    public void destinationPhoneNumberTest() {
        // TODO: test destinationPhoneNumber
    }

    /**
     * Test the property 'verifyChannelType'
     */
    @Test
    public void verifyChannelTypeTest() {
        // TODO: test verifyChannelType
    }

    /**
     * Test the property 'verifyChannelId'
     */
    @Test
    public void verifyChannelIdTest() {
        // TODO: test verifyChannelId
    }

    /**
     * Test the property 'verifyUsageFee'
     */
    @Test
    public void verifyUsageFeeTest() {
        // TODO: test verifyUsageFee
    }

    /**
     * Test the property 'closedAt'
     */
    @Test
    public void closedAtTest() {
        // TODO: test closedAt
    }

    /**
     * Test the property 'ipAddress'
     */
    @Test
    public void ipAddressTest() {
        // TODO: test ipAddress
    }

    /**
     * Test the property 'downlinkData'
     */
    @Test
    public void downlinkDataTest() {
        // TODO: test downlinkData
    }

    /**
     * Test the property 'imsi'
     */
    @Test
    public void imsiTest() {
        // TODO: test imsi
    }

    /**
     * Test the property 'dataUnit'
     */
    @Test
    public void dataUnitTest() {
        // TODO: test dataUnit
    }

    /**
     * Test the property 'dataRate'
     */
    @Test
    public void dataRateTest() {
        // TODO: test dataRate
    }

    /**
     * Test the property 'simGroupName'
     */
    @Test
    public void simGroupNameTest() {
        // TODO: test simGroupName
    }

    /**
     * Test the property 'simCardId'
     */
    @Test
    public void simCardIdTest() {
        // TODO: test simCardId
    }

    /**
     * Test the property 'simGroupId'
     */
    @Test
    public void simGroupIdTest() {
        // TODO: test simGroupId
    }

    /**
     * Test the property 'simCardTags'
     */
    @Test
    public void simCardTagsTest() {
        // TODO: test simCardTags
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'uplinkData'
     */
    @Test
    public void uplinkDataTest() {
        // TODO: test uplinkData
    }

    /**
     * Test the property 'dataCost'
     */
    @Test
    public void dataCostTest() {
        // TODO: test dataCost
    }

    /**
     * Test the property 'assetId'
     */
    @Test
    public void assetIdTest() {
        // TODO: test assetId
    }

    /**
     * Test the property 'orgId'
     */
    @Test
    public void orgIdTest() {
        // TODO: test orgId
    }

    /**
     * Test the property 'actionType'
     */
    @Test
    public void actionTypeTest() {
        // TODO: test actionType
    }

    /**
     * Test the property 'linkChannelType'
     */
    @Test
    public void linkChannelTypeTest() {
        // TODO: test linkChannelType
    }

    /**
     * Test the property 'linkChannelId'
     */
    @Test
    public void linkChannelIdTest() {
        // TODO: test linkChannelId
    }

}
