/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.model;

import com.fasterxml.jackson.annotation.JsonTypeName;
import com.telnyx.sdk.model.EnumListResponseInner;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetEnumEndpoint200Response
 */
public class GetEnumEndpoint200ResponseTest {
    private final GetEnumEndpoint200Response model = new GetEnumEndpoint200Response();

    /**
     * Model tests for GetEnumEndpoint200Response
     */
    @Test
    public void testGetEnumEndpoint200Response() {
        // TODO: test GetEnumEndpoint200Response
    }

}
