// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.campaign

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TelnyxCampaignCspTest {

    @Test
    fun create() {
        val telnyxCampaignCsp =
            TelnyxCampaignCsp.builder()
                .brandId("d2ca9d69-641b-4131-83fa-5d0744f4c8a9")
                .campaignId("823d6b1a-6ed6-41a3-9c50-c8ff41b682ba")
                .cspId("cspId")
                .description("description")
                .mock(true)
                .addSubUsecase("string")
                .termsAndConditions(true)
                .usecase("usecase")
                .ageGated(true)
                .autoRenewal(true)
                .billedDate("billedDate")
                .brandDisplayName("ABC Mobile")
                .campaignStatus(TelnyxCampaignCsp.CampaignStatus.TCR_ACCEPTED)
                .createDate("createDate")
                .directLending(true)
                .embeddedLink(true)
                .embeddedLinkSample("embeddedLinkSample")
                .embeddedPhone(true)
                .failureReasons("failureReasons")
                .helpKeywords("helpKeywords")
                .helpMessage("helpMessage")
                .isTMobileNumberPoolingEnabled(true)
                .isTMobileRegistered(true)
                .isTMobileSuspended(true)
                .messageFlow("messageFlow")
                .nextRenewalOrExpirationDate("nextRenewalOrExpirationDate")
                .numberPool(true)
                .optinKeywords("optinKeywords")
                .optinMessage("optinMessage")
                .optoutKeywords("optoutKeywords")
                .optoutMessage("optoutMessage")
                .privacyPolicyLink("privacyPolicyLink")
                .referenceId("referenceId")
                .resellerId("resellerId")
                .sample1("sample1")
                .sample2("sample2")
                .sample3("sample3")
                .sample4("sample4")
                .sample5("sample5")
                .status("status")
                .submissionStatus(TelnyxCampaignCsp.SubmissionStatus.CREATED)
                .subscriberHelp(true)
                .subscriberOptin(true)
                .subscriberOptout(true)
                .tcrBrandId("BBRAND1")
                .tcrCampaignId("CCAMP1")
                .termsAndConditionsLink("termsAndConditionsLink")
                .vertical("vertical")
                .webhookFailoverUrl("https://example.com/failover-webhook")
                .webhookUrl("https://example.com/webhook")
                .build()

        assertThat(telnyxCampaignCsp.brandId()).isEqualTo("d2ca9d69-641b-4131-83fa-5d0744f4c8a9")
        assertThat(telnyxCampaignCsp.campaignId()).isEqualTo("823d6b1a-6ed6-41a3-9c50-c8ff41b682ba")
        assertThat(telnyxCampaignCsp.cspId()).isEqualTo("cspId")
        assertThat(telnyxCampaignCsp.description()).isEqualTo("description")
        assertThat(telnyxCampaignCsp.mock()).isEqualTo(true)
        assertThat(telnyxCampaignCsp.subUsecases()).containsExactly("string")
        assertThat(telnyxCampaignCsp.termsAndConditions()).isEqualTo(true)
        assertThat(telnyxCampaignCsp.usecase()).isEqualTo("usecase")
        assertThat(telnyxCampaignCsp.ageGated()).contains(true)
        assertThat(telnyxCampaignCsp.autoRenewal()).contains(true)
        assertThat(telnyxCampaignCsp.billedDate()).contains("billedDate")
        assertThat(telnyxCampaignCsp.brandDisplayName()).contains("ABC Mobile")
        assertThat(telnyxCampaignCsp.campaignStatus())
            .contains(TelnyxCampaignCsp.CampaignStatus.TCR_ACCEPTED)
        assertThat(telnyxCampaignCsp.createDate()).contains("createDate")
        assertThat(telnyxCampaignCsp.directLending()).contains(true)
        assertThat(telnyxCampaignCsp.embeddedLink()).contains(true)
        assertThat(telnyxCampaignCsp.embeddedLinkSample()).contains("embeddedLinkSample")
        assertThat(telnyxCampaignCsp.embeddedPhone()).contains(true)
        assertThat(telnyxCampaignCsp.failureReasons()).contains("failureReasons")
        assertThat(telnyxCampaignCsp.helpKeywords()).contains("helpKeywords")
        assertThat(telnyxCampaignCsp.helpMessage()).contains("helpMessage")
        assertThat(telnyxCampaignCsp.isTMobileNumberPoolingEnabled()).contains(true)
        assertThat(telnyxCampaignCsp.isTMobileRegistered()).contains(true)
        assertThat(telnyxCampaignCsp.isTMobileSuspended()).contains(true)
        assertThat(telnyxCampaignCsp.messageFlow()).contains("messageFlow")
        assertThat(telnyxCampaignCsp.nextRenewalOrExpirationDate())
            .contains("nextRenewalOrExpirationDate")
        assertThat(telnyxCampaignCsp.numberPool()).contains(true)
        assertThat(telnyxCampaignCsp.optinKeywords()).contains("optinKeywords")
        assertThat(telnyxCampaignCsp.optinMessage()).contains("optinMessage")
        assertThat(telnyxCampaignCsp.optoutKeywords()).contains("optoutKeywords")
        assertThat(telnyxCampaignCsp.optoutMessage()).contains("optoutMessage")
        assertThat(telnyxCampaignCsp.privacyPolicyLink()).contains("privacyPolicyLink")
        assertThat(telnyxCampaignCsp.referenceId()).contains("referenceId")
        assertThat(telnyxCampaignCsp.resellerId()).contains("resellerId")
        assertThat(telnyxCampaignCsp.sample1()).contains("sample1")
        assertThat(telnyxCampaignCsp.sample2()).contains("sample2")
        assertThat(telnyxCampaignCsp.sample3()).contains("sample3")
        assertThat(telnyxCampaignCsp.sample4()).contains("sample4")
        assertThat(telnyxCampaignCsp.sample5()).contains("sample5")
        assertThat(telnyxCampaignCsp.status()).contains("status")
        assertThat(telnyxCampaignCsp.submissionStatus())
            .contains(TelnyxCampaignCsp.SubmissionStatus.CREATED)
        assertThat(telnyxCampaignCsp.subscriberHelp()).contains(true)
        assertThat(telnyxCampaignCsp.subscriberOptin()).contains(true)
        assertThat(telnyxCampaignCsp.subscriberOptout()).contains(true)
        assertThat(telnyxCampaignCsp.tcrBrandId()).contains("BBRAND1")
        assertThat(telnyxCampaignCsp.tcrCampaignId()).contains("CCAMP1")
        assertThat(telnyxCampaignCsp.termsAndConditionsLink()).contains("termsAndConditionsLink")
        assertThat(telnyxCampaignCsp.vertical()).contains("vertical")
        assertThat(telnyxCampaignCsp.webhookFailoverUrl())
            .contains("https://example.com/failover-webhook")
        assertThat(telnyxCampaignCsp.webhookUrl()).contains("https://example.com/webhook")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val telnyxCampaignCsp =
            TelnyxCampaignCsp.builder()
                .brandId("d2ca9d69-641b-4131-83fa-5d0744f4c8a9")
                .campaignId("823d6b1a-6ed6-41a3-9c50-c8ff41b682ba")
                .cspId("cspId")
                .description("description")
                .mock(true)
                .addSubUsecase("string")
                .termsAndConditions(true)
                .usecase("usecase")
                .ageGated(true)
                .autoRenewal(true)
                .billedDate("billedDate")
                .brandDisplayName("ABC Mobile")
                .campaignStatus(TelnyxCampaignCsp.CampaignStatus.TCR_ACCEPTED)
                .createDate("createDate")
                .directLending(true)
                .embeddedLink(true)
                .embeddedLinkSample("embeddedLinkSample")
                .embeddedPhone(true)
                .failureReasons("failureReasons")
                .helpKeywords("helpKeywords")
                .helpMessage("helpMessage")
                .isTMobileNumberPoolingEnabled(true)
                .isTMobileRegistered(true)
                .isTMobileSuspended(true)
                .messageFlow("messageFlow")
                .nextRenewalOrExpirationDate("nextRenewalOrExpirationDate")
                .numberPool(true)
                .optinKeywords("optinKeywords")
                .optinMessage("optinMessage")
                .optoutKeywords("optoutKeywords")
                .optoutMessage("optoutMessage")
                .privacyPolicyLink("privacyPolicyLink")
                .referenceId("referenceId")
                .resellerId("resellerId")
                .sample1("sample1")
                .sample2("sample2")
                .sample3("sample3")
                .sample4("sample4")
                .sample5("sample5")
                .status("status")
                .submissionStatus(TelnyxCampaignCsp.SubmissionStatus.CREATED)
                .subscriberHelp(true)
                .subscriberOptin(true)
                .subscriberOptout(true)
                .tcrBrandId("BBRAND1")
                .tcrCampaignId("CCAMP1")
                .termsAndConditionsLink("termsAndConditionsLink")
                .vertical("vertical")
                .webhookFailoverUrl("https://example.com/failover-webhook")
                .webhookUrl("https://example.com/webhook")
                .build()

        val roundtrippedTelnyxCampaignCsp =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(telnyxCampaignCsp),
                jacksonTypeRef<TelnyxCampaignCsp>(),
            )

        assertThat(roundtrippedTelnyxCampaignCsp).isEqualTo(telnyxCampaignCsp)
    }
}
