/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.telnyx.sdk.models.NumberHealthMetrics;
import com.telnyx.sdk.models.PhoneNumberWithMessagingSettingsFeatures;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PhoneNumberWithMessagingSettings
 */
public class PhoneNumberWithMessagingSettingsTest {
    private final PhoneNumberWithMessagingSettings model = new PhoneNumberWithMessagingSettings();

    /**
     * Model tests for PhoneNumberWithMessagingSettings
     */
    @Test
    public void testPhoneNumberWithMessagingSettings() {
        // TODO: test PhoneNumberWithMessagingSettings
    }

    /**
     * Test the property 'recordType'
     */
    @Test
    public void recordTypeTest() {
        // TODO: test recordType
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'messagingProfileId'
     */
    @Test
    public void messagingProfileIdTest() {
        // TODO: test messagingProfileId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'health'
     */
    @Test
    public void healthTest() {
        // TODO: test health
    }

    /**
     * Test the property 'eligibleMessagingProducts'
     */
    @Test
    public void eligibleMessagingProductsTest() {
        // TODO: test eligibleMessagingProducts
    }

    /**
     * Test the property 'trafficType'
     */
    @Test
    public void trafficTypeTest() {
        // TODO: test trafficType
    }

    /**
     * Test the property 'messagingProduct'
     */
    @Test
    public void messagingProductTest() {
        // TODO: test messagingProduct
    }

    /**
     * Test the property 'features'
     */
    @Test
    public void featuresTest() {
        // TODO: test features
    }

}
