/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RegulatoryRequirementCriteria
 */
public class RegulatoryRequirementCriteriaTest {
    private final RegulatoryRequirementCriteria model = new RegulatoryRequirementCriteria();

    /**
     * Model tests for RegulatoryRequirementCriteria
     */
    @Test
    public void testRegulatoryRequirementCriteria() {
        // TODO: test RegulatoryRequirementCriteria
    }

    /**
     * Test the property 'recordType'
     */
    @Test
    public void recordTypeTest() {
        // TODO: test recordType
    }

    /**
     * Test the property 'criteriaType'
     */
    @Test
    public void criteriaTypeTest() {
        // TODO: test criteriaType
    }

    /**
     * Test the property 'criteriaValue'
     */
    @Test
    public void criteriaValueTest() {
        // TODO: test criteriaValue
    }

}
