/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for StopRecordingRequest
 */
public class StopRecordingRequestTest {
    private final StopRecordingRequest model = new StopRecordingRequest();

    /**
     * Model tests for StopRecordingRequest
     */
    @Test
    public void testStopRecordingRequest() {
        // TODO: test StopRecordingRequest
    }

    /**
     * Test the property 'clientState'
     */
    @Test
    public void clientStateTest() {
        // TODO: test clientState
    }

    /**
     * Test the property 'commandId'
     */
    @Test
    public void commandIdTest() {
        // TODO: test commandId
    }

}
