// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.messaging10dlc.partnercampaigns

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.jsonMapper
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TelnyxDownstreamCampaignTest {

    @Test
    fun create() {
        val telnyxDownstreamCampaign =
            TelnyxDownstreamCampaign.builder()
                .tcrBrandId("BBRAND1")
                .tcrCampaignId("CCAMP1")
                .ageGated(true)
                .assignedPhoneNumbersCount(3.0)
                .brandDisplayName("ABC Mobile")
                .campaignStatus(TelnyxDownstreamCampaign.CampaignStatus.TCR_ACCEPTED)
                .createdAt("2021-03-08T17:57:48.801186")
                .description("description")
                .directLending(true)
                .embeddedLink(true)
                .embeddedLinkSample("embeddedLinkSample")
                .embeddedPhone(true)
                .failureReasons("failureReasons")
                .helpKeywords("helpKeywords")
                .helpMessage("helpMessage")
                .isNumberPoolingEnabled(true)
                .messageFlow("messageFlow")
                .numberPool(true)
                .optinKeywords("optinKeywords")
                .optinMessage("optinMessage")
                .optoutKeywords("optoutKeywords")
                .optoutMessage("optoutMessage")
                .privacyPolicyLink("privacyPolicyLink")
                .sample1("sample1")
                .sample2("sample2")
                .sample3("sample3")
                .sample4("sample4")
                .sample5("sample5")
                .subscriberOptin(true)
                .subscriberOptout(true)
                .addSubUsecase("string")
                .termsAndConditions(true)
                .termsAndConditionsLink("termsAndConditionsLink")
                .updatedAt("2021-03-08T17:57:48.801186")
                .usecase("usecase")
                .webhookFailoverUrl("https://example.com/failover-webhook")
                .webhookUrl("https://example.com/webhook")
                .build()

        assertThat(telnyxDownstreamCampaign.tcrBrandId()).isEqualTo("BBRAND1")
        assertThat(telnyxDownstreamCampaign.tcrCampaignId()).isEqualTo("CCAMP1")
        assertThat(telnyxDownstreamCampaign.ageGated()).contains(true)
        assertThat(telnyxDownstreamCampaign.assignedPhoneNumbersCount()).contains(3.0)
        assertThat(telnyxDownstreamCampaign.brandDisplayName()).contains("ABC Mobile")
        assertThat(telnyxDownstreamCampaign.campaignStatus())
            .contains(TelnyxDownstreamCampaign.CampaignStatus.TCR_ACCEPTED)
        assertThat(telnyxDownstreamCampaign.createdAt()).contains("2021-03-08T17:57:48.801186")
        assertThat(telnyxDownstreamCampaign.description()).contains("description")
        assertThat(telnyxDownstreamCampaign.directLending()).contains(true)
        assertThat(telnyxDownstreamCampaign.embeddedLink()).contains(true)
        assertThat(telnyxDownstreamCampaign.embeddedLinkSample()).contains("embeddedLinkSample")
        assertThat(telnyxDownstreamCampaign.embeddedPhone()).contains(true)
        assertThat(telnyxDownstreamCampaign.failureReasons()).contains("failureReasons")
        assertThat(telnyxDownstreamCampaign.helpKeywords()).contains("helpKeywords")
        assertThat(telnyxDownstreamCampaign.helpMessage()).contains("helpMessage")
        assertThat(telnyxDownstreamCampaign.isNumberPoolingEnabled()).contains(true)
        assertThat(telnyxDownstreamCampaign.messageFlow()).contains("messageFlow")
        assertThat(telnyxDownstreamCampaign.numberPool()).contains(true)
        assertThat(telnyxDownstreamCampaign.optinKeywords()).contains("optinKeywords")
        assertThat(telnyxDownstreamCampaign.optinMessage()).contains("optinMessage")
        assertThat(telnyxDownstreamCampaign.optoutKeywords()).contains("optoutKeywords")
        assertThat(telnyxDownstreamCampaign.optoutMessage()).contains("optoutMessage")
        assertThat(telnyxDownstreamCampaign.privacyPolicyLink()).contains("privacyPolicyLink")
        assertThat(telnyxDownstreamCampaign.sample1()).contains("sample1")
        assertThat(telnyxDownstreamCampaign.sample2()).contains("sample2")
        assertThat(telnyxDownstreamCampaign.sample3()).contains("sample3")
        assertThat(telnyxDownstreamCampaign.sample4()).contains("sample4")
        assertThat(telnyxDownstreamCampaign.sample5()).contains("sample5")
        assertThat(telnyxDownstreamCampaign.subscriberOptin()).contains(true)
        assertThat(telnyxDownstreamCampaign.subscriberOptout()).contains(true)
        assertThat(telnyxDownstreamCampaign.subUsecases().getOrNull()).containsExactly("string")
        assertThat(telnyxDownstreamCampaign.termsAndConditions()).contains(true)
        assertThat(telnyxDownstreamCampaign.termsAndConditionsLink())
            .contains("termsAndConditionsLink")
        assertThat(telnyxDownstreamCampaign.updatedAt()).contains("2021-03-08T17:57:48.801186")
        assertThat(telnyxDownstreamCampaign.usecase()).contains("usecase")
        assertThat(telnyxDownstreamCampaign.webhookFailoverUrl())
            .contains("https://example.com/failover-webhook")
        assertThat(telnyxDownstreamCampaign.webhookUrl()).contains("https://example.com/webhook")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val telnyxDownstreamCampaign =
            TelnyxDownstreamCampaign.builder()
                .tcrBrandId("BBRAND1")
                .tcrCampaignId("CCAMP1")
                .ageGated(true)
                .assignedPhoneNumbersCount(3.0)
                .brandDisplayName("ABC Mobile")
                .campaignStatus(TelnyxDownstreamCampaign.CampaignStatus.TCR_ACCEPTED)
                .createdAt("2021-03-08T17:57:48.801186")
                .description("description")
                .directLending(true)
                .embeddedLink(true)
                .embeddedLinkSample("embeddedLinkSample")
                .embeddedPhone(true)
                .failureReasons("failureReasons")
                .helpKeywords("helpKeywords")
                .helpMessage("helpMessage")
                .isNumberPoolingEnabled(true)
                .messageFlow("messageFlow")
                .numberPool(true)
                .optinKeywords("optinKeywords")
                .optinMessage("optinMessage")
                .optoutKeywords("optoutKeywords")
                .optoutMessage("optoutMessage")
                .privacyPolicyLink("privacyPolicyLink")
                .sample1("sample1")
                .sample2("sample2")
                .sample3("sample3")
                .sample4("sample4")
                .sample5("sample5")
                .subscriberOptin(true)
                .subscriberOptout(true)
                .addSubUsecase("string")
                .termsAndConditions(true)
                .termsAndConditionsLink("termsAndConditionsLink")
                .updatedAt("2021-03-08T17:57:48.801186")
                .usecase("usecase")
                .webhookFailoverUrl("https://example.com/failover-webhook")
                .webhookUrl("https://example.com/webhook")
                .build()

        val roundtrippedTelnyxDownstreamCampaign =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(telnyxDownstreamCampaign),
                jacksonTypeRef<TelnyxDownstreamCampaign>(),
            )

        assertThat(roundtrippedTelnyxDownstreamCampaign).isEqualTo(telnyxDownstreamCampaign)
    }
}
