// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.number10dlc.campaign

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.jsonMapper
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CampaignListResponseTest {

    @Test
    fun create() {
        val campaignListResponse =
            CampaignListResponse.builder()
                .ageGated(true)
                .assignedPhoneNumbersCount(3.0)
                .autoRenewal(true)
                .billedDate("billedDate")
                .brandDisplayName("ABC Mobile")
                .brandId("d2ca9d69-641b-4131-83fa-5d0744f4c8a9")
                .campaignId("823d6b1a-6ed6-41a3-9c50-c8ff41b682ba")
                .campaignStatus(CampaignListResponse.CampaignStatus.TCR_ACCEPTED)
                .createDate("createDate")
                .cspId("cspId")
                .description("description")
                .directLending(true)
                .embeddedLink(true)
                .embeddedLinkSample("embeddedLinkSample")
                .embeddedPhone(true)
                .failureReasons("failureReasons")
                .helpKeywords("helpKeywords")
                .helpMessage("helpMessage")
                .isTMobileNumberPoolingEnabled(true)
                .isTMobileRegistered(true)
                .isTMobileSuspended(true)
                .messageFlow("messageFlow")
                .mock(true)
                .nextRenewalOrExpirationDate("nextRenewalOrExpirationDate")
                .numberPool(true)
                .optinKeywords("optinKeywords")
                .optinMessage("optinMessage")
                .optoutKeywords("optoutKeywords")
                .optoutMessage("optoutMessage")
                .privacyPolicyLink("privacyPolicyLink")
                .referenceId("referenceId")
                .resellerId("resellerId")
                .sample1("sample1")
                .sample2("sample2")
                .sample3("sample3")
                .sample4("sample4")
                .sample5("sample5")
                .status("status")
                .submissionStatus(CampaignListResponse.SubmissionStatus.CREATED)
                .subscriberHelp(true)
                .subscriberOptin(true)
                .subscriberOptout(true)
                .addSubUsecase("string")
                .tcrBrandId("BBRAND1")
                .tcrCampaignId("CCAMP1")
                .termsAndConditions(true)
                .termsAndConditionsLink("termsAndConditionsLink")
                .usecase("usecase")
                .vertical("vertical")
                .webhookFailoverUrl("https://example.com/failover-webhook")
                .webhookUrl("https://example.com/webhook")
                .build()

        assertThat(campaignListResponse.ageGated()).contains(true)
        assertThat(campaignListResponse.assignedPhoneNumbersCount()).contains(3.0)
        assertThat(campaignListResponse.autoRenewal()).contains(true)
        assertThat(campaignListResponse.billedDate()).contains("billedDate")
        assertThat(campaignListResponse.brandDisplayName()).contains("ABC Mobile")
        assertThat(campaignListResponse.brandId()).contains("d2ca9d69-641b-4131-83fa-5d0744f4c8a9")
        assertThat(campaignListResponse.campaignId())
            .contains("823d6b1a-6ed6-41a3-9c50-c8ff41b682ba")
        assertThat(campaignListResponse.campaignStatus())
            .contains(CampaignListResponse.CampaignStatus.TCR_ACCEPTED)
        assertThat(campaignListResponse.createDate()).contains("createDate")
        assertThat(campaignListResponse.cspId()).contains("cspId")
        assertThat(campaignListResponse.description()).contains("description")
        assertThat(campaignListResponse.directLending()).contains(true)
        assertThat(campaignListResponse.embeddedLink()).contains(true)
        assertThat(campaignListResponse.embeddedLinkSample()).contains("embeddedLinkSample")
        assertThat(campaignListResponse.embeddedPhone()).contains(true)
        assertThat(campaignListResponse.failureReasons()).contains("failureReasons")
        assertThat(campaignListResponse.helpKeywords()).contains("helpKeywords")
        assertThat(campaignListResponse.helpMessage()).contains("helpMessage")
        assertThat(campaignListResponse.isTMobileNumberPoolingEnabled()).contains(true)
        assertThat(campaignListResponse.isTMobileRegistered()).contains(true)
        assertThat(campaignListResponse.isTMobileSuspended()).contains(true)
        assertThat(campaignListResponse.messageFlow()).contains("messageFlow")
        assertThat(campaignListResponse.mock()).contains(true)
        assertThat(campaignListResponse.nextRenewalOrExpirationDate())
            .contains("nextRenewalOrExpirationDate")
        assertThat(campaignListResponse.numberPool()).contains(true)
        assertThat(campaignListResponse.optinKeywords()).contains("optinKeywords")
        assertThat(campaignListResponse.optinMessage()).contains("optinMessage")
        assertThat(campaignListResponse.optoutKeywords()).contains("optoutKeywords")
        assertThat(campaignListResponse.optoutMessage()).contains("optoutMessage")
        assertThat(campaignListResponse.privacyPolicyLink()).contains("privacyPolicyLink")
        assertThat(campaignListResponse.referenceId()).contains("referenceId")
        assertThat(campaignListResponse.resellerId()).contains("resellerId")
        assertThat(campaignListResponse.sample1()).contains("sample1")
        assertThat(campaignListResponse.sample2()).contains("sample2")
        assertThat(campaignListResponse.sample3()).contains("sample3")
        assertThat(campaignListResponse.sample4()).contains("sample4")
        assertThat(campaignListResponse.sample5()).contains("sample5")
        assertThat(campaignListResponse.status()).contains("status")
        assertThat(campaignListResponse.submissionStatus())
            .contains(CampaignListResponse.SubmissionStatus.CREATED)
        assertThat(campaignListResponse.subscriberHelp()).contains(true)
        assertThat(campaignListResponse.subscriberOptin()).contains(true)
        assertThat(campaignListResponse.subscriberOptout()).contains(true)
        assertThat(campaignListResponse.subUsecases().getOrNull()).containsExactly("string")
        assertThat(campaignListResponse.tcrBrandId()).contains("BBRAND1")
        assertThat(campaignListResponse.tcrCampaignId()).contains("CCAMP1")
        assertThat(campaignListResponse.termsAndConditions()).contains(true)
        assertThat(campaignListResponse.termsAndConditionsLink()).contains("termsAndConditionsLink")
        assertThat(campaignListResponse.usecase()).contains("usecase")
        assertThat(campaignListResponse.vertical()).contains("vertical")
        assertThat(campaignListResponse.webhookFailoverUrl())
            .contains("https://example.com/failover-webhook")
        assertThat(campaignListResponse.webhookUrl()).contains("https://example.com/webhook")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val campaignListResponse =
            CampaignListResponse.builder()
                .ageGated(true)
                .assignedPhoneNumbersCount(3.0)
                .autoRenewal(true)
                .billedDate("billedDate")
                .brandDisplayName("ABC Mobile")
                .brandId("d2ca9d69-641b-4131-83fa-5d0744f4c8a9")
                .campaignId("823d6b1a-6ed6-41a3-9c50-c8ff41b682ba")
                .campaignStatus(CampaignListResponse.CampaignStatus.TCR_ACCEPTED)
                .createDate("createDate")
                .cspId("cspId")
                .description("description")
                .directLending(true)
                .embeddedLink(true)
                .embeddedLinkSample("embeddedLinkSample")
                .embeddedPhone(true)
                .failureReasons("failureReasons")
                .helpKeywords("helpKeywords")
                .helpMessage("helpMessage")
                .isTMobileNumberPoolingEnabled(true)
                .isTMobileRegistered(true)
                .isTMobileSuspended(true)
                .messageFlow("messageFlow")
                .mock(true)
                .nextRenewalOrExpirationDate("nextRenewalOrExpirationDate")
                .numberPool(true)
                .optinKeywords("optinKeywords")
                .optinMessage("optinMessage")
                .optoutKeywords("optoutKeywords")
                .optoutMessage("optoutMessage")
                .privacyPolicyLink("privacyPolicyLink")
                .referenceId("referenceId")
                .resellerId("resellerId")
                .sample1("sample1")
                .sample2("sample2")
                .sample3("sample3")
                .sample4("sample4")
                .sample5("sample5")
                .status("status")
                .submissionStatus(CampaignListResponse.SubmissionStatus.CREATED)
                .subscriberHelp(true)
                .subscriberOptin(true)
                .subscriberOptout(true)
                .addSubUsecase("string")
                .tcrBrandId("BBRAND1")
                .tcrCampaignId("CCAMP1")
                .termsAndConditions(true)
                .termsAndConditionsLink("termsAndConditionsLink")
                .usecase("usecase")
                .vertical("vertical")
                .webhookFailoverUrl("https://example.com/failover-webhook")
                .webhookUrl("https://example.com/webhook")
                .build()

        val roundtrippedCampaignListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(campaignListResponse),
                jacksonTypeRef<CampaignListResponse>(),
            )

        assertThat(roundtrippedCampaignListResponse).isEqualTo(campaignListResponse)
    }
}
