// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.credentialconnections

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CredentialConnectionRetrieveResponseTest {

    @Test
    fun create() {
        val credentialConnectionRetrieveResponse =
            CredentialConnectionRetrieveResponse.builder()
                .data(
                    CredentialConnection.builder()
                        .id("id")
                        .active(true)
                        .anchorsiteOverride(AnchorsiteOverride.LATENCY)
                        .callCostInWebhooks(false)
                        .connectionName("string")
                        .createdAt("2018-02-02T22:25:27.521Z")
                        .defaultOnHoldComfortNoiseEnabled(true)
                        .dtmfType(DtmfType.RFC_2833)
                        .encodeContactHeaderEnabled(true)
                        .encryptedMedia(EncryptedMedia.SRTP)
                        .inbound(
                            CredentialInbound.builder()
                                .aniNumberFormat(CredentialInbound.AniNumberFormat.PLUS_E_164)
                                .channelLimit(10L)
                                .addCodec("G722")
                                .dnisNumberFormat(CredentialInbound.DnisNumberFormat.PLUS_E164)
                                .generateRingbackTone(true)
                                .isupHeadersEnabled(true)
                                .prackEnabled(true)
                                .shakenStirEnabled(true)
                                .sipCompactHeadersEnabled(true)
                                .timeout1xxSecs(10L)
                                .timeout2xxSecs(15L)
                                .build()
                        )
                        .onnetT38PassthroughEnabled(true)
                        .outbound(
                            CredentialOutbound.builder()
                                .aniOverride("string")
                                .aniOverrideType(CredentialOutbound.AniOverrideType.ALWAYS)
                                .callParkingEnabled(true)
                                .channelLimit(10L)
                                .generateRingbackTone(true)
                                .instantRingbackEnabled(true)
                                .localization("string")
                                .outboundVoiceProfileId("outbound_voice_profile_id")
                                .t38ReinviteSource(CredentialOutbound.T38ReinviteSource.CUSTOMER)
                                .build()
                        )
                        .password("my123secure456password789")
                        .recordType("credential_connection")
                        .rtcpSettings(
                            ConnectionRtcpSettings.builder()
                                .captureEnabled(true)
                                .port(ConnectionRtcpSettings.Port.RTP_1)
                                .reportFrequencySecs(10L)
                                .build()
                        )
                        .sipUriCallingPreference(
                            CredentialConnection.SipUriCallingPreference.DISABLED
                        )
                        .addTag("tag1")
                        .addTag("tag2")
                        .updatedAt("2018-02-02T22:25:27.521Z")
                        .userName("myusername123")
                        .webhookApiVersion(CredentialConnection.WebhookApiVersion.V1)
                        .webhookEventFailoverUrl("https://failover.example.com")
                        .webhookEventUrl("https://example.com")
                        .webhookTimeoutSecs(25L)
                        .build()
                )
                .build()

        assertThat(credentialConnectionRetrieveResponse.data())
            .contains(
                CredentialConnection.builder()
                    .id("id")
                    .active(true)
                    .anchorsiteOverride(AnchorsiteOverride.LATENCY)
                    .callCostInWebhooks(false)
                    .connectionName("string")
                    .createdAt("2018-02-02T22:25:27.521Z")
                    .defaultOnHoldComfortNoiseEnabled(true)
                    .dtmfType(DtmfType.RFC_2833)
                    .encodeContactHeaderEnabled(true)
                    .encryptedMedia(EncryptedMedia.SRTP)
                    .inbound(
                        CredentialInbound.builder()
                            .aniNumberFormat(CredentialInbound.AniNumberFormat.PLUS_E_164)
                            .channelLimit(10L)
                            .addCodec("G722")
                            .dnisNumberFormat(CredentialInbound.DnisNumberFormat.PLUS_E164)
                            .generateRingbackTone(true)
                            .isupHeadersEnabled(true)
                            .prackEnabled(true)
                            .shakenStirEnabled(true)
                            .sipCompactHeadersEnabled(true)
                            .timeout1xxSecs(10L)
                            .timeout2xxSecs(15L)
                            .build()
                    )
                    .onnetT38PassthroughEnabled(true)
                    .outbound(
                        CredentialOutbound.builder()
                            .aniOverride("string")
                            .aniOverrideType(CredentialOutbound.AniOverrideType.ALWAYS)
                            .callParkingEnabled(true)
                            .channelLimit(10L)
                            .generateRingbackTone(true)
                            .instantRingbackEnabled(true)
                            .localization("string")
                            .outboundVoiceProfileId("outbound_voice_profile_id")
                            .t38ReinviteSource(CredentialOutbound.T38ReinviteSource.CUSTOMER)
                            .build()
                    )
                    .password("my123secure456password789")
                    .recordType("credential_connection")
                    .rtcpSettings(
                        ConnectionRtcpSettings.builder()
                            .captureEnabled(true)
                            .port(ConnectionRtcpSettings.Port.RTP_1)
                            .reportFrequencySecs(10L)
                            .build()
                    )
                    .sipUriCallingPreference(CredentialConnection.SipUriCallingPreference.DISABLED)
                    .addTag("tag1")
                    .addTag("tag2")
                    .updatedAt("2018-02-02T22:25:27.521Z")
                    .userName("myusername123")
                    .webhookApiVersion(CredentialConnection.WebhookApiVersion.V1)
                    .webhookEventFailoverUrl("https://failover.example.com")
                    .webhookEventUrl("https://example.com")
                    .webhookTimeoutSecs(25L)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val credentialConnectionRetrieveResponse =
            CredentialConnectionRetrieveResponse.builder()
                .data(
                    CredentialConnection.builder()
                        .id("id")
                        .active(true)
                        .anchorsiteOverride(AnchorsiteOverride.LATENCY)
                        .callCostInWebhooks(false)
                        .connectionName("string")
                        .createdAt("2018-02-02T22:25:27.521Z")
                        .defaultOnHoldComfortNoiseEnabled(true)
                        .dtmfType(DtmfType.RFC_2833)
                        .encodeContactHeaderEnabled(true)
                        .encryptedMedia(EncryptedMedia.SRTP)
                        .inbound(
                            CredentialInbound.builder()
                                .aniNumberFormat(CredentialInbound.AniNumberFormat.PLUS_E_164)
                                .channelLimit(10L)
                                .addCodec("G722")
                                .dnisNumberFormat(CredentialInbound.DnisNumberFormat.PLUS_E164)
                                .generateRingbackTone(true)
                                .isupHeadersEnabled(true)
                                .prackEnabled(true)
                                .shakenStirEnabled(true)
                                .sipCompactHeadersEnabled(true)
                                .timeout1xxSecs(10L)
                                .timeout2xxSecs(15L)
                                .build()
                        )
                        .onnetT38PassthroughEnabled(true)
                        .outbound(
                            CredentialOutbound.builder()
                                .aniOverride("string")
                                .aniOverrideType(CredentialOutbound.AniOverrideType.ALWAYS)
                                .callParkingEnabled(true)
                                .channelLimit(10L)
                                .generateRingbackTone(true)
                                .instantRingbackEnabled(true)
                                .localization("string")
                                .outboundVoiceProfileId("outbound_voice_profile_id")
                                .t38ReinviteSource(CredentialOutbound.T38ReinviteSource.CUSTOMER)
                                .build()
                        )
                        .password("my123secure456password789")
                        .recordType("credential_connection")
                        .rtcpSettings(
                            ConnectionRtcpSettings.builder()
                                .captureEnabled(true)
                                .port(ConnectionRtcpSettings.Port.RTP_1)
                                .reportFrequencySecs(10L)
                                .build()
                        )
                        .sipUriCallingPreference(
                            CredentialConnection.SipUriCallingPreference.DISABLED
                        )
                        .addTag("tag1")
                        .addTag("tag2")
                        .updatedAt("2018-02-02T22:25:27.521Z")
                        .userName("myusername123")
                        .webhookApiVersion(CredentialConnection.WebhookApiVersion.V1)
                        .webhookEventFailoverUrl("https://failover.example.com")
                        .webhookEventUrl("https://example.com")
                        .webhookTimeoutSecs(25L)
                        .build()
                )
                .build()

        val roundtrippedCredentialConnectionRetrieveResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(credentialConnectionRetrieveResponse),
                jacksonTypeRef<CredentialConnectionRetrieveResponse>(),
            )

        assertThat(roundtrippedCredentialConnectionRetrieveResponse)
            .isEqualTo(credentialConnectionRetrieveResponse)
    }
}
