/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.telnyx.sdk.JSON;


/**
 * GetUserTags200ResponseData
 */
@JsonPropertyOrder({
  GetUserTags200ResponseData.JSON_PROPERTY_OUTBOUND_PROFILE_TAGS,
  GetUserTags200ResponseData.JSON_PROPERTY_NUMBER_TAGS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class GetUserTags200ResponseData {
  public static final String JSON_PROPERTY_OUTBOUND_PROFILE_TAGS = "outbound_profile_tags";
  private List<String> outboundProfileTags = null;

  public static final String JSON_PROPERTY_NUMBER_TAGS = "number_tags";
  private List<String> numberTags = null;

  public GetUserTags200ResponseData() { 
  }

  public GetUserTags200ResponseData outboundProfileTags(List<String> outboundProfileTags) {
    this.outboundProfileTags = outboundProfileTags;
    return this;
  }

  public GetUserTags200ResponseData addoutboundProfileTagsItem(String outboundProfileTagsItem) {
    if (this.outboundProfileTags == null) {
      this.outboundProfileTags = new ArrayList<>();
    }
    this.outboundProfileTags.add(outboundProfileTagsItem);
    return this;
  }

   /**
   * A list of your tags on the given resource type. NOTE: The casing of the tags returned will not necessarily match the casing of the tags when they were added to a resource. This is because the tags will have the casing of the first time they were used within the Telnyx system regardless of source.
   * @return outboundProfileTags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of your tags on the given resource type. NOTE: The casing of the tags returned will not necessarily match the casing of the tags when they were added to a resource. This is because the tags will have the casing of the first time they were used within the Telnyx system regardless of source.")
  @JsonProperty(JSON_PROPERTY_OUTBOUND_PROFILE_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getOutboundProfileTags() {
    return outboundProfileTags;
  }


  @JsonProperty(JSON_PROPERTY_OUTBOUND_PROFILE_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOutboundProfileTags(List<String> outboundProfileTags) {
    this.outboundProfileTags = outboundProfileTags;
  }


  public GetUserTags200ResponseData numberTags(List<String> numberTags) {
    this.numberTags = numberTags;
    return this;
  }

  public GetUserTags200ResponseData addnumberTagsItem(String numberTagsItem) {
    if (this.numberTags == null) {
      this.numberTags = new ArrayList<>();
    }
    this.numberTags.add(numberTagsItem);
    return this;
  }

   /**
   * A list of your tags on the given resource type. NOTE: The casing of the tags returned will not necessarily match the casing of the tags when they were added to a resource. This is because the tags will have the casing of the first time they were used within the Telnyx system regardless of source.
   * @return numberTags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of your tags on the given resource type. NOTE: The casing of the tags returned will not necessarily match the casing of the tags when they were added to a resource. This is because the tags will have the casing of the first time they were used within the Telnyx system regardless of source.")
  @JsonProperty(JSON_PROPERTY_NUMBER_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getNumberTags() {
    return numberTags;
  }


  @JsonProperty(JSON_PROPERTY_NUMBER_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumberTags(List<String> numberTags) {
    this.numberTags = numberTags;
  }


  /**
   * Return true if this GetUserTags_200_response_data object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetUserTags200ResponseData getUserTags200ResponseData = (GetUserTags200ResponseData) o;
    return Objects.equals(this.outboundProfileTags, getUserTags200ResponseData.outboundProfileTags) &&
        Objects.equals(this.numberTags, getUserTags200ResponseData.numberTags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(outboundProfileTags, numberTags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetUserTags200ResponseData {\n");
    sb.append("    outboundProfileTags: ").append(toIndentedString(outboundProfileTags)).append("\n");
    sb.append("    numberTags: ").append(toIndentedString(numberTags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

