/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.telnyx.sdk.models.ConferenceEndedBy;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * Conference
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Conference {
  private static final long serialVersionUID = 1L;

  /**
   * Gets or Sets recordType
   */
  @JsonAdapter(RecordTypeEnum.Adapter.class)
  public enum RecordTypeEnum {
    CONFERENCE("conference");

    private String value;

    RecordTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RecordTypeEnum fromValue(String value) {
      for (RecordTypeEnum b : RecordTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<RecordTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RecordTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RecordTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return RecordTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_RECORD_TYPE = "record_type";
  @SerializedName(SERIALIZED_NAME_RECORD_TYPE)
  private RecordTypeEnum recordType;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expires_at";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  private String expiresAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public static final String SERIALIZED_NAME_REGION = "region";
  @SerializedName(SERIALIZED_NAME_REGION)
  private String region;

  /**
   * Status of the conference
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    INIT("init"),
    
    IN_PROGRESS("in_progress"),
    
    COMPLETED("completed");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status;

  /**
   * Reason why the conference ended
   */
  @JsonAdapter(EndReasonEnum.Adapter.class)
  public enum EndReasonEnum {
    ALL_LEFT("all_left"),
    
    ENDED_VIA_API("ended_via_api"),
    
    HOST_LEFT("host_left"),
    
    TIME_EXCEEDED("time_exceeded");

    private String value;

    EndReasonEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static EndReasonEnum fromValue(String value) {
      for (EndReasonEnum b : EndReasonEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<EndReasonEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EndReasonEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EndReasonEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return EndReasonEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_END_REASON = "end_reason";
  @SerializedName(SERIALIZED_NAME_END_REASON)
  private EndReasonEnum endReason;

  public static final String SERIALIZED_NAME_ENDED_BY = "ended_by";
  @SerializedName(SERIALIZED_NAME_ENDED_BY)
  private ConferenceEndedBy endedBy;

  public static final String SERIALIZED_NAME_CONNECTION_ID = "connection_id";
  @SerializedName(SERIALIZED_NAME_CONNECTION_ID)
  private String connectionId;


  public Conference recordType(RecordTypeEnum recordType) {
    
    this.recordType = recordType;
    return this;
  }

   /**
   * Get recordType
   * @return recordType
  **/
  @ApiModelProperty(example = "conference", required = true, value = "")

  public RecordTypeEnum getRecordType() {
    return recordType;
  }


  public void setRecordType(RecordTypeEnum recordType) {
    this.recordType = recordType;
  }


  public Conference id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Uniquely identifies the conference
   * @return id
  **/
  @ApiModelProperty(example = "3fa85f64-5717-4562-b3fc-2c963f66afa6", required = true, value = "Uniquely identifies the conference")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Conference name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the conference
   * @return name
  **/
  @ApiModelProperty(example = "All hands meeting", required = true, value = "Name of the conference")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Conference createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * ISO 8601 formatted date of when the conference was created
   * @return createdAt
  **/
  @ApiModelProperty(example = "2019-01-23T18:10:02.574Z", required = true, value = "ISO 8601 formatted date of when the conference was created")

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public Conference expiresAt(String expiresAt) {
    
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * ISO 8601 formatted date of when the conference will expire
   * @return expiresAt
  **/
  @ApiModelProperty(example = "2019-01-23T18:10:02.574Z", required = true, value = "ISO 8601 formatted date of when the conference will expire")

  public String getExpiresAt() {
    return expiresAt;
  }


  public void setExpiresAt(String expiresAt) {
    this.expiresAt = expiresAt;
  }


  public Conference updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * ISO 8601 formatted date of when the conference was last updated
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2019-01-23T18:10:02.574Z", value = "ISO 8601 formatted date of when the conference was last updated")

  public String getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public Conference region(String region) {
    
    this.region = region;
    return this;
  }

   /**
   * Region where the conference is hosted
   * @return region
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "sv1", value = "Region where the conference is hosted")

  public String getRegion() {
    return region;
  }


  public void setRegion(String region) {
    this.region = region;
  }


  public Conference status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Status of the conference
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "completed", value = "Status of the conference")

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public Conference endReason(EndReasonEnum endReason) {
    
    this.endReason = endReason;
    return this;
  }

   /**
   * Reason why the conference ended
   * @return endReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "all_left", value = "Reason why the conference ended")

  public EndReasonEnum getEndReason() {
    return endReason;
  }


  public void setEndReason(EndReasonEnum endReason) {
    this.endReason = endReason;
  }


  public Conference endedBy(ConferenceEndedBy endedBy) {
    
    this.endedBy = endedBy;
    return this;
  }

   /**
   * Get endedBy
   * @return endedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ConferenceEndedBy getEndedBy() {
    return endedBy;
  }


  public void setEndedBy(ConferenceEndedBy endedBy) {
    this.endedBy = endedBy;
  }


  public Conference connectionId(String connectionId) {
    
    this.connectionId = connectionId;
    return this;
  }

   /**
   * Identifies the connection associated with the conference
   * @return connectionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "3fa85f64-9191-4567-b3fc-2c963f66afa6", value = "Identifies the connection associated with the conference")

  public String getConnectionId() {
    return connectionId;
  }


  public void setConnectionId(String connectionId) {
    this.connectionId = connectionId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Conference conference = (Conference) o;
    return Objects.equals(this.recordType, conference.recordType) &&
        Objects.equals(this.id, conference.id) &&
        Objects.equals(this.name, conference.name) &&
        Objects.equals(this.createdAt, conference.createdAt) &&
        Objects.equals(this.expiresAt, conference.expiresAt) &&
        Objects.equals(this.updatedAt, conference.updatedAt) &&
        Objects.equals(this.region, conference.region) &&
        Objects.equals(this.status, conference.status) &&
        Objects.equals(this.endReason, conference.endReason) &&
        Objects.equals(this.endedBy, conference.endedBy) &&
        Objects.equals(this.connectionId, conference.connectionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recordType, id, name, createdAt, expiresAt, updatedAt, region, status, endReason, endedBy, connectionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Conference {\n");
    sb.append("    recordType: ").append(toIndentedString(recordType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    endReason: ").append(toIndentedString(endReason)).append("\n");
    sb.append("    endedBy: ").append(toIndentedString(endedBy)).append("\n");
    sb.append("    connectionId: ").append(toIndentedString(connectionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

