/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * CostInformation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CostInformation {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_UPFRONT_COST = "upfront_cost";
  @SerializedName(SERIALIZED_NAME_UPFRONT_COST)
  private String upfrontCost;

  public static final String SERIALIZED_NAME_MONTHLY_COST = "monthly_cost";
  @SerializedName(SERIALIZED_NAME_MONTHLY_COST)
  private String monthlyCost;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;


  public CostInformation upfrontCost(String upfrontCost) {
    
    this.upfrontCost = upfrontCost;
    return this;
  }

   /**
   * Get upfrontCost
   * @return upfrontCost
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "3.21", value = "")

  public String getUpfrontCost() {
    return upfrontCost;
  }


  public void setUpfrontCost(String upfrontCost) {
    this.upfrontCost = upfrontCost;
  }


  public CostInformation monthlyCost(String monthlyCost) {
    
    this.monthlyCost = monthlyCost;
    return this;
  }

   /**
   * Get monthlyCost
   * @return monthlyCost
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "6.54", value = "")

  public String getMonthlyCost() {
    return monthlyCost;
  }


  public void setMonthlyCost(String monthlyCost) {
    this.monthlyCost = monthlyCost;
  }


  public CostInformation currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * The ISO 4217 code for the currency.
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "USD", value = "The ISO 4217 code for the currency.")

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CostInformation costInformation = (CostInformation) o;
    return Objects.equals(this.upfrontCost, costInformation.upfrontCost) &&
        Objects.equals(this.monthlyCost, costInformation.monthlyCost) &&
        Objects.equals(this.currency, costInformation.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(upfrontCost, monthlyCost, currency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CostInformation {\n");
    sb.append("    upfrontCost: ").append(toIndentedString(upfrontCost)).append("\n");
    sb.append("    monthlyCost: ").append(toIndentedString(monthlyCost)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

