// File generated from our OpenAPI spec by Stainless.

package com.telnyx.api.models.campaign

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.api.core.jsonMapper
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CampaignListResponseTest {

    @Test
    fun create() {
        val campaignListResponse =
            CampaignListResponse.builder()
                .page(0L)
                .addRecord(
                    CampaignListResponse.Record.builder()
                        .ageGated(true)
                        .assignedPhoneNumbersCount(3.0)
                        .autoRenewal(true)
                        .billedDate("billedDate")
                        .brandDisplayName("ABC Mobile")
                        .brandId("d2ca9d69-641b-4131-83fa-5d0744f4c8a9")
                        .campaignId("823d6b1a-6ed6-41a3-9c50-c8ff41b682ba")
                        .campaignStatus(CampaignListResponse.Record.CampaignStatus.TCR_ACCEPTED)
                        .createDate("createDate")
                        .cspId("cspId")
                        .description("description")
                        .directLending(true)
                        .embeddedLink(true)
                        .embeddedLinkSample("embeddedLinkSample")
                        .embeddedPhone(true)
                        .failureReasons("failureReasons")
                        .helpKeywords("helpKeywords")
                        .helpMessage("helpMessage")
                        .isTMobileNumberPoolingEnabled(true)
                        .isTMobileRegistered(true)
                        .isTMobileSuspended(true)
                        .messageFlow("messageFlow")
                        .mock(true)
                        .nextRenewalOrExpirationDate("nextRenewalOrExpirationDate")
                        .numberPool(true)
                        .optinKeywords("optinKeywords")
                        .optinMessage("optinMessage")
                        .optoutKeywords("optoutKeywords")
                        .optoutMessage("optoutMessage")
                        .privacyPolicyLink("privacyPolicyLink")
                        .referenceId("referenceId")
                        .resellerId("resellerId")
                        .sample1("sample1")
                        .sample2("sample2")
                        .sample3("sample3")
                        .sample4("sample4")
                        .sample5("sample5")
                        .status("status")
                        .submissionStatus(CampaignListResponse.Record.SubmissionStatus.CREATED)
                        .subscriberHelp(true)
                        .subscriberOptin(true)
                        .subscriberOptout(true)
                        .addSubUsecase("string")
                        .tcrBrandId("BBRAND1")
                        .tcrCampaignId("CCAMP1")
                        .termsAndConditions(true)
                        .termsAndConditionsLink("termsAndConditionsLink")
                        .usecase("usecase")
                        .vertical("vertical")
                        .webhookFailoverUrl("https://example.com/failover-webhook")
                        .webhookUrl("https://example.com/webhook")
                        .build()
                )
                .totalRecords(0L)
                .build()

        assertThat(campaignListResponse.page()).contains(0L)
        assertThat(campaignListResponse.records().getOrNull())
            .containsExactly(
                CampaignListResponse.Record.builder()
                    .ageGated(true)
                    .assignedPhoneNumbersCount(3.0)
                    .autoRenewal(true)
                    .billedDate("billedDate")
                    .brandDisplayName("ABC Mobile")
                    .brandId("d2ca9d69-641b-4131-83fa-5d0744f4c8a9")
                    .campaignId("823d6b1a-6ed6-41a3-9c50-c8ff41b682ba")
                    .campaignStatus(CampaignListResponse.Record.CampaignStatus.TCR_ACCEPTED)
                    .createDate("createDate")
                    .cspId("cspId")
                    .description("description")
                    .directLending(true)
                    .embeddedLink(true)
                    .embeddedLinkSample("embeddedLinkSample")
                    .embeddedPhone(true)
                    .failureReasons("failureReasons")
                    .helpKeywords("helpKeywords")
                    .helpMessage("helpMessage")
                    .isTMobileNumberPoolingEnabled(true)
                    .isTMobileRegistered(true)
                    .isTMobileSuspended(true)
                    .messageFlow("messageFlow")
                    .mock(true)
                    .nextRenewalOrExpirationDate("nextRenewalOrExpirationDate")
                    .numberPool(true)
                    .optinKeywords("optinKeywords")
                    .optinMessage("optinMessage")
                    .optoutKeywords("optoutKeywords")
                    .optoutMessage("optoutMessage")
                    .privacyPolicyLink("privacyPolicyLink")
                    .referenceId("referenceId")
                    .resellerId("resellerId")
                    .sample1("sample1")
                    .sample2("sample2")
                    .sample3("sample3")
                    .sample4("sample4")
                    .sample5("sample5")
                    .status("status")
                    .submissionStatus(CampaignListResponse.Record.SubmissionStatus.CREATED)
                    .subscriberHelp(true)
                    .subscriberOptin(true)
                    .subscriberOptout(true)
                    .addSubUsecase("string")
                    .tcrBrandId("BBRAND1")
                    .tcrCampaignId("CCAMP1")
                    .termsAndConditions(true)
                    .termsAndConditionsLink("termsAndConditionsLink")
                    .usecase("usecase")
                    .vertical("vertical")
                    .webhookFailoverUrl("https://example.com/failover-webhook")
                    .webhookUrl("https://example.com/webhook")
                    .build()
            )
        assertThat(campaignListResponse.totalRecords()).contains(0L)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val campaignListResponse =
            CampaignListResponse.builder()
                .page(0L)
                .addRecord(
                    CampaignListResponse.Record.builder()
                        .ageGated(true)
                        .assignedPhoneNumbersCount(3.0)
                        .autoRenewal(true)
                        .billedDate("billedDate")
                        .brandDisplayName("ABC Mobile")
                        .brandId("d2ca9d69-641b-4131-83fa-5d0744f4c8a9")
                        .campaignId("823d6b1a-6ed6-41a3-9c50-c8ff41b682ba")
                        .campaignStatus(CampaignListResponse.Record.CampaignStatus.TCR_ACCEPTED)
                        .createDate("createDate")
                        .cspId("cspId")
                        .description("description")
                        .directLending(true)
                        .embeddedLink(true)
                        .embeddedLinkSample("embeddedLinkSample")
                        .embeddedPhone(true)
                        .failureReasons("failureReasons")
                        .helpKeywords("helpKeywords")
                        .helpMessage("helpMessage")
                        .isTMobileNumberPoolingEnabled(true)
                        .isTMobileRegistered(true)
                        .isTMobileSuspended(true)
                        .messageFlow("messageFlow")
                        .mock(true)
                        .nextRenewalOrExpirationDate("nextRenewalOrExpirationDate")
                        .numberPool(true)
                        .optinKeywords("optinKeywords")
                        .optinMessage("optinMessage")
                        .optoutKeywords("optoutKeywords")
                        .optoutMessage("optoutMessage")
                        .privacyPolicyLink("privacyPolicyLink")
                        .referenceId("referenceId")
                        .resellerId("resellerId")
                        .sample1("sample1")
                        .sample2("sample2")
                        .sample3("sample3")
                        .sample4("sample4")
                        .sample5("sample5")
                        .status("status")
                        .submissionStatus(CampaignListResponse.Record.SubmissionStatus.CREATED)
                        .subscriberHelp(true)
                        .subscriberOptin(true)
                        .subscriberOptout(true)
                        .addSubUsecase("string")
                        .tcrBrandId("BBRAND1")
                        .tcrCampaignId("CCAMP1")
                        .termsAndConditions(true)
                        .termsAndConditionsLink("termsAndConditionsLink")
                        .usecase("usecase")
                        .vertical("vertical")
                        .webhookFailoverUrl("https://example.com/failover-webhook")
                        .webhookUrl("https://example.com/webhook")
                        .build()
                )
                .totalRecords(0L)
                .build()

        val roundtrippedCampaignListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(campaignListResponse),
                jacksonTypeRef<CampaignListResponse>(),
            )

        assertThat(roundtrippedCampaignListResponse).isEqualTo(campaignListResponse)
    }
}
