// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.rcs.agents

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.jsonMapper
import com.telnyx.sdk.models.rcs.agents.testdevices.TestDeviceResponse
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AgentResponseTest {

    @Test
    fun create() {
        val agentResponse =
            AgentResponse.builder()
                .agentId("22222222-2222-4222-8222-222222222222")
                .basicsStatus(AgentSubmissionStatus.SUBMITTED)
                .billingCategory(AgentResponse.BillingCategory.NON_CONVERSATIONAL)
                .brandId("11111111-1111-4111-8111-111111111111")
                .campaignStatus(null)
                .capabilities(
                    CapabilitiesResponse.builder()
                        .brandEntity(true)
                        .brandVerification(true)
                        .campaigns(false)
                        .distinctLaunchPhase(false)
                        .inviteTestDevices(false)
                        .perCarrierApproval(false)
                        .submissionSections(true)
                        .templates(false)
                        .vendorWebhooks(false)
                        .build()
                )
                .addCarrierApproval(
                    CarrierApprovalResponse.builder()
                        .approvalId("33333333-3333-4333-8333-333333333333")
                        .approvedAt(null)
                        .carrier(null)
                        .rejectedReason(null)
                        .scopeType(CarrierApprovalResponse.ScopeType.HUB)
                        .status(CarrierApprovalResponse.Status.SUBMITTED)
                        .submittedAt(OffsetDateTime.parse("2026-08-10T12:00:00Z"))
                        .build()
                )
                .configuration(
                    AgentConfiguration.builder()
                        .basics(
                            AgentConfiguration.Basics.AgentPhoneContactRequirement.builder()
                                .email(
                                    AgentEmailContact.builder()
                                        .address("support@example.com")
                                        .label("Support")
                                        .build()
                                )
                                .brandColor("#123456")
                                .description("Order confirmations and delivery updates")
                                .heroUrl("https://www.example.com/rcs/hero.png")
                                .logoUrl("https://www.example.com/rcs/logo.png")
                                .phoneNumber(
                                    AgentPhoneContact.builder()
                                        .label("x")
                                        .number("+49605132")
                                        .build()
                                )
                                .privacyPolicyUrl("https://www.example.com/privacy")
                                .termsAndConditionsUrl("https://www.example.com/terms")
                                .website(
                                    AgentWebsiteContact.builder()
                                        .label("x")
                                        .url("https://example.com")
                                        .build()
                                )
                                .build()
                        )
                        .campaign(
                            AgentCampaignConfiguration.builder()
                                .companyOverview("x")
                                .additionalInformation("x")
                                .agentOverview("x")
                                .consentSettings(
                                    AgentConsentConfiguration.builder()
                                        .callToAction("x")
                                        .doubleOptIn(true)
                                        .helpResponse("x")
                                        .optInMessage("x")
                                        .addOptInMethod(
                                            AgentConsentConfiguration.OptInMethod.builder()
                                                .methodType(
                                                    AgentConsentConfiguration.OptInMethod.MethodType
                                                        .SMS
                                                )
                                                .description("x")
                                                .build()
                                        )
                                        .optOutResponse("x")
                                        .callToActionMediaUrl("https://example.com")
                                        .callToActionUrl("https://example.com")
                                        .doubleOptInMessage("x")
                                        .build()
                                )
                                .addInteraction(
                                    AgentInteraction.builder()
                                        .interactionType(
                                            AgentInteraction.InteractionType.TRANSACTIONAL_UPDATES
                                        )
                                        .description("x")
                                        .build()
                                )
                                .addMessageExample("x")
                                .build()
                        )
                        .testing(
                            AgentTestingConfiguration.builder()
                                .testUrl("https://example.com")
                                .additionalInformation("x")
                                .messageId("x")
                                .build()
                        )
                        .build()
                )
                .displayName("Acme Order Updates")
                .hostingRegion(null)
                .profileId("40000000-0000-0000-0000-000000000001")
                .status(AgentResponse.Status.SUBMITTED)
                .addTestDevice(
                    TestDeviceResponse.builder()
                        .inviteStatus(TestDeviceResponse.InviteStatus.ACCEPTED)
                        .phoneNumber("+13125550123")
                        .testDeviceId("44444444-4444-4444-8444-444444444444")
                        .build()
                )
                .testingStatus(null)
                .useCase(AgentUseCase.TRANSACTIONAL)
                .build()

        assertThat(agentResponse.agentId()).isEqualTo("22222222-2222-4222-8222-222222222222")
        assertThat(agentResponse.basicsStatus()).contains(AgentSubmissionStatus.SUBMITTED)
        assertThat(agentResponse.billingCategory())
            .contains(AgentResponse.BillingCategory.NON_CONVERSATIONAL)
        assertThat(agentResponse.brandId()).isEqualTo("11111111-1111-4111-8111-111111111111")
        assertThat(agentResponse.campaignStatus()).isEmpty
        assertThat(agentResponse.capabilities())
            .isEqualTo(
                CapabilitiesResponse.builder()
                    .brandEntity(true)
                    .brandVerification(true)
                    .campaigns(false)
                    .distinctLaunchPhase(false)
                    .inviteTestDevices(false)
                    .perCarrierApproval(false)
                    .submissionSections(true)
                    .templates(false)
                    .vendorWebhooks(false)
                    .build()
            )
        assertThat(agentResponse.carrierApprovals())
            .containsExactly(
                CarrierApprovalResponse.builder()
                    .approvalId("33333333-3333-4333-8333-333333333333")
                    .approvedAt(null)
                    .carrier(null)
                    .rejectedReason(null)
                    .scopeType(CarrierApprovalResponse.ScopeType.HUB)
                    .status(CarrierApprovalResponse.Status.SUBMITTED)
                    .submittedAt(OffsetDateTime.parse("2026-08-10T12:00:00Z"))
                    .build()
            )
        assertThat(agentResponse.configuration())
            .isEqualTo(
                AgentConfiguration.builder()
                    .basics(
                        AgentConfiguration.Basics.AgentPhoneContactRequirement.builder()
                            .email(
                                AgentEmailContact.builder()
                                    .address("support@example.com")
                                    .label("Support")
                                    .build()
                            )
                            .brandColor("#123456")
                            .description("Order confirmations and delivery updates")
                            .heroUrl("https://www.example.com/rcs/hero.png")
                            .logoUrl("https://www.example.com/rcs/logo.png")
                            .phoneNumber(
                                AgentPhoneContact.builder().label("x").number("+49605132").build()
                            )
                            .privacyPolicyUrl("https://www.example.com/privacy")
                            .termsAndConditionsUrl("https://www.example.com/terms")
                            .website(
                                AgentWebsiteContact.builder()
                                    .label("x")
                                    .url("https://example.com")
                                    .build()
                            )
                            .build()
                    )
                    .campaign(
                        AgentCampaignConfiguration.builder()
                            .companyOverview("x")
                            .additionalInformation("x")
                            .agentOverview("x")
                            .consentSettings(
                                AgentConsentConfiguration.builder()
                                    .callToAction("x")
                                    .doubleOptIn(true)
                                    .helpResponse("x")
                                    .optInMessage("x")
                                    .addOptInMethod(
                                        AgentConsentConfiguration.OptInMethod.builder()
                                            .methodType(
                                                AgentConsentConfiguration.OptInMethod.MethodType.SMS
                                            )
                                            .description("x")
                                            .build()
                                    )
                                    .optOutResponse("x")
                                    .callToActionMediaUrl("https://example.com")
                                    .callToActionUrl("https://example.com")
                                    .doubleOptInMessage("x")
                                    .build()
                            )
                            .addInteraction(
                                AgentInteraction.builder()
                                    .interactionType(
                                        AgentInteraction.InteractionType.TRANSACTIONAL_UPDATES
                                    )
                                    .description("x")
                                    .build()
                            )
                            .addMessageExample("x")
                            .build()
                    )
                    .testing(
                        AgentTestingConfiguration.builder()
                            .testUrl("https://example.com")
                            .additionalInformation("x")
                            .messageId("x")
                            .build()
                    )
                    .build()
            )
        assertThat(agentResponse.displayName()).isEqualTo("Acme Order Updates")
        assertThat(agentResponse.hostingRegion()).isEmpty
        assertThat(agentResponse.profileId()).contains("40000000-0000-0000-0000-000000000001")
        assertThat(agentResponse.status()).isEqualTo(AgentResponse.Status.SUBMITTED)
        assertThat(agentResponse.testDevices())
            .containsExactly(
                TestDeviceResponse.builder()
                    .inviteStatus(TestDeviceResponse.InviteStatus.ACCEPTED)
                    .phoneNumber("+13125550123")
                    .testDeviceId("44444444-4444-4444-8444-444444444444")
                    .build()
            )
        assertThat(agentResponse.testingStatus()).isEmpty
        assertThat(agentResponse.useCase()).isEqualTo(AgentUseCase.TRANSACTIONAL)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val agentResponse =
            AgentResponse.builder()
                .agentId("22222222-2222-4222-8222-222222222222")
                .basicsStatus(AgentSubmissionStatus.SUBMITTED)
                .billingCategory(AgentResponse.BillingCategory.NON_CONVERSATIONAL)
                .brandId("11111111-1111-4111-8111-111111111111")
                .campaignStatus(null)
                .capabilities(
                    CapabilitiesResponse.builder()
                        .brandEntity(true)
                        .brandVerification(true)
                        .campaigns(false)
                        .distinctLaunchPhase(false)
                        .inviteTestDevices(false)
                        .perCarrierApproval(false)
                        .submissionSections(true)
                        .templates(false)
                        .vendorWebhooks(false)
                        .build()
                )
                .addCarrierApproval(
                    CarrierApprovalResponse.builder()
                        .approvalId("33333333-3333-4333-8333-333333333333")
                        .approvedAt(null)
                        .carrier(null)
                        .rejectedReason(null)
                        .scopeType(CarrierApprovalResponse.ScopeType.HUB)
                        .status(CarrierApprovalResponse.Status.SUBMITTED)
                        .submittedAt(OffsetDateTime.parse("2026-08-10T12:00:00Z"))
                        .build()
                )
                .configuration(
                    AgentConfiguration.builder()
                        .basics(
                            AgentConfiguration.Basics.AgentPhoneContactRequirement.builder()
                                .email(
                                    AgentEmailContact.builder()
                                        .address("support@example.com")
                                        .label("Support")
                                        .build()
                                )
                                .brandColor("#123456")
                                .description("Order confirmations and delivery updates")
                                .heroUrl("https://www.example.com/rcs/hero.png")
                                .logoUrl("https://www.example.com/rcs/logo.png")
                                .phoneNumber(
                                    AgentPhoneContact.builder()
                                        .label("x")
                                        .number("+49605132")
                                        .build()
                                )
                                .privacyPolicyUrl("https://www.example.com/privacy")
                                .termsAndConditionsUrl("https://www.example.com/terms")
                                .website(
                                    AgentWebsiteContact.builder()
                                        .label("x")
                                        .url("https://example.com")
                                        .build()
                                )
                                .build()
                        )
                        .campaign(
                            AgentCampaignConfiguration.builder()
                                .companyOverview("x")
                                .additionalInformation("x")
                                .agentOverview("x")
                                .consentSettings(
                                    AgentConsentConfiguration.builder()
                                        .callToAction("x")
                                        .doubleOptIn(true)
                                        .helpResponse("x")
                                        .optInMessage("x")
                                        .addOptInMethod(
                                            AgentConsentConfiguration.OptInMethod.builder()
                                                .methodType(
                                                    AgentConsentConfiguration.OptInMethod.MethodType
                                                        .SMS
                                                )
                                                .description("x")
                                                .build()
                                        )
                                        .optOutResponse("x")
                                        .callToActionMediaUrl("https://example.com")
                                        .callToActionUrl("https://example.com")
                                        .doubleOptInMessage("x")
                                        .build()
                                )
                                .addInteraction(
                                    AgentInteraction.builder()
                                        .interactionType(
                                            AgentInteraction.InteractionType.TRANSACTIONAL_UPDATES
                                        )
                                        .description("x")
                                        .build()
                                )
                                .addMessageExample("x")
                                .build()
                        )
                        .testing(
                            AgentTestingConfiguration.builder()
                                .testUrl("https://example.com")
                                .additionalInformation("x")
                                .messageId("x")
                                .build()
                        )
                        .build()
                )
                .displayName("Acme Order Updates")
                .hostingRegion(null)
                .profileId("40000000-0000-0000-0000-000000000001")
                .status(AgentResponse.Status.SUBMITTED)
                .addTestDevice(
                    TestDeviceResponse.builder()
                        .inviteStatus(TestDeviceResponse.InviteStatus.ACCEPTED)
                        .phoneNumber("+13125550123")
                        .testDeviceId("44444444-4444-4444-8444-444444444444")
                        .build()
                )
                .testingStatus(null)
                .useCase(AgentUseCase.TRANSACTIONAL)
                .build()

        val roundtrippedAgentResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(agentResponse),
                jacksonTypeRef<AgentResponse>(),
            )

        assertThat(roundtrippedAgentResponse).isEqualTo(agentResponse)
    }
}
