// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.rcs.agents

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AgentConfigurationTest {

    @Test
    fun create() {
        val agentConfiguration =
            AgentConfiguration.builder()
                .basics(
                    AgentConfiguration.Basics.UnionMember0.builder()
                        .phoneNumber(
                            AgentPhoneContact.builder().label("x").number("+49605132").build()
                        )
                        .brandColor("#2FDCd1")
                        .description("x")
                        .email(
                            AgentEmailContact.builder()
                                .address("dev@stainless.com")
                                .label("x")
                                .build()
                        )
                        .heroUrl("https://example.com")
                        .logoUrl("https://example.com")
                        .privacyPolicyUrl("https://example.com")
                        .termsAndConditionsUrl("https://example.com")
                        .website(
                            AgentWebsiteContact.builder()
                                .label("x")
                                .url("https://example.com")
                                .build()
                        )
                        .build()
                )
                .campaign(
                    AgentCampaignConfiguration.builder()
                        .companyOverview("x")
                        .additionalInformation("x")
                        .agentOverview("x")
                        .consentSettings(
                            AgentConsentConfiguration.builder()
                                .callToAction("x")
                                .doubleOptIn(true)
                                .helpResponse("x")
                                .optInMessage("x")
                                .addOptInMethod(
                                    AgentConsentConfiguration.OptInMethod.builder()
                                        .methodType(
                                            AgentConsentConfiguration.OptInMethod.MethodType.SMS
                                        )
                                        .description("x")
                                        .build()
                                )
                                .optOutResponse("x")
                                .callToActionMediaUrl("https://example.com")
                                .callToActionUrl("https://example.com")
                                .doubleOptInMessage("x")
                                .build()
                        )
                        .addInteraction(
                            AgentInteraction.builder()
                                .interactionType(
                                    AgentInteraction.InteractionType.TRANSACTIONAL_UPDATES
                                )
                                .description("x")
                                .build()
                        )
                        .addMessageExample("x")
                        .build()
                )
                .testing(
                    AgentTestingConfiguration.builder()
                        .testUrl("https://example.com")
                        .additionalInformation("x")
                        .messageId("x")
                        .build()
                )
                .build()

        assertThat(agentConfiguration.basics())
            .isEqualTo(
                AgentConfiguration.Basics.ofUnionMember0(
                    AgentConfiguration.Basics.UnionMember0.builder()
                        .phoneNumber(
                            AgentPhoneContact.builder().label("x").number("+49605132").build()
                        )
                        .brandColor("#2FDCd1")
                        .description("x")
                        .email(
                            AgentEmailContact.builder()
                                .address("dev@stainless.com")
                                .label("x")
                                .build()
                        )
                        .heroUrl("https://example.com")
                        .logoUrl("https://example.com")
                        .privacyPolicyUrl("https://example.com")
                        .termsAndConditionsUrl("https://example.com")
                        .website(
                            AgentWebsiteContact.builder()
                                .label("x")
                                .url("https://example.com")
                                .build()
                        )
                        .build()
                )
            )
        assertThat(agentConfiguration.campaign())
            .contains(
                AgentCampaignConfiguration.builder()
                    .companyOverview("x")
                    .additionalInformation("x")
                    .agentOverview("x")
                    .consentSettings(
                        AgentConsentConfiguration.builder()
                            .callToAction("x")
                            .doubleOptIn(true)
                            .helpResponse("x")
                            .optInMessage("x")
                            .addOptInMethod(
                                AgentConsentConfiguration.OptInMethod.builder()
                                    .methodType(
                                        AgentConsentConfiguration.OptInMethod.MethodType.SMS
                                    )
                                    .description("x")
                                    .build()
                            )
                            .optOutResponse("x")
                            .callToActionMediaUrl("https://example.com")
                            .callToActionUrl("https://example.com")
                            .doubleOptInMessage("x")
                            .build()
                    )
                    .addInteraction(
                        AgentInteraction.builder()
                            .interactionType(AgentInteraction.InteractionType.TRANSACTIONAL_UPDATES)
                            .description("x")
                            .build()
                    )
                    .addMessageExample("x")
                    .build()
            )
        assertThat(agentConfiguration.testing())
            .contains(
                AgentTestingConfiguration.builder()
                    .testUrl("https://example.com")
                    .additionalInformation("x")
                    .messageId("x")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val agentConfiguration =
            AgentConfiguration.builder()
                .basics(
                    AgentConfiguration.Basics.UnionMember0.builder()
                        .phoneNumber(
                            AgentPhoneContact.builder().label("x").number("+49605132").build()
                        )
                        .brandColor("#2FDCd1")
                        .description("x")
                        .email(
                            AgentEmailContact.builder()
                                .address("dev@stainless.com")
                                .label("x")
                                .build()
                        )
                        .heroUrl("https://example.com")
                        .logoUrl("https://example.com")
                        .privacyPolicyUrl("https://example.com")
                        .termsAndConditionsUrl("https://example.com")
                        .website(
                            AgentWebsiteContact.builder()
                                .label("x")
                                .url("https://example.com")
                                .build()
                        )
                        .build()
                )
                .campaign(
                    AgentCampaignConfiguration.builder()
                        .companyOverview("x")
                        .additionalInformation("x")
                        .agentOverview("x")
                        .consentSettings(
                            AgentConsentConfiguration.builder()
                                .callToAction("x")
                                .doubleOptIn(true)
                                .helpResponse("x")
                                .optInMessage("x")
                                .addOptInMethod(
                                    AgentConsentConfiguration.OptInMethod.builder()
                                        .methodType(
                                            AgentConsentConfiguration.OptInMethod.MethodType.SMS
                                        )
                                        .description("x")
                                        .build()
                                )
                                .optOutResponse("x")
                                .callToActionMediaUrl("https://example.com")
                                .callToActionUrl("https://example.com")
                                .doubleOptInMessage("x")
                                .build()
                        )
                        .addInteraction(
                            AgentInteraction.builder()
                                .interactionType(
                                    AgentInteraction.InteractionType.TRANSACTIONAL_UPDATES
                                )
                                .description("x")
                                .build()
                        )
                        .addMessageExample("x")
                        .build()
                )
                .testing(
                    AgentTestingConfiguration.builder()
                        .testUrl("https://example.com")
                        .additionalInformation("x")
                        .messageId("x")
                        .build()
                )
                .build()

        val roundtrippedAgentConfiguration =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(agentConfiguration),
                jacksonTypeRef<AgentConfiguration>(),
            )

        assertThat(roundtrippedAgentConfiguration).isEqualTo(agentConfiguration)
    }
}
