// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.uacconnections

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.jsonMapper
import com.telnyx.sdk.models.ConnectionJitterBuffer
import com.telnyx.sdk.models.ConnectionNoiseSuppressionDetails
import com.telnyx.sdk.models.ConnectionsPaginationMeta
import com.telnyx.sdk.models.credentialconnections.AnchorsiteOverride
import com.telnyx.sdk.models.credentialconnections.ConnectionRtcpSettings
import com.telnyx.sdk.models.credentialconnections.DtmfType
import com.telnyx.sdk.models.credentialconnections.EncryptedMedia
import com.telnyx.sdk.models.fqdns.Fqdn
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class UacConnectionListPageResponseTest {

    @Test
    fun create() {
        val uacConnectionListPageResponse =
            UacConnectionListPageResponse.builder()
                .addData(
                    UacConnectionListResponse.builder()
                        .id("6a09cdc3-8948-47f0-aa62-74ac943d6c58")
                        .active(true)
                        .anchorsiteOverride(AnchorsiteOverride.LATENCY)
                        .androidPushCredentialId("06b09dfd-7154-4980-8b75-cebf7a9d4f8e")
                        .authentication(UacConnectionListResponse.Authentication.UAC_AUTHENTICATION)
                        .callCostInWebhooks(false)
                        .connectionName("string")
                        .createdAt("2018-02-02T22:25:27.521Z")
                        .defaultOnHoldComfortNoiseEnabled(true)
                        .dtmfType(DtmfType.RFC_2833)
                        .encodeContactHeaderEnabled(true)
                        .encryptedMedia(EncryptedMedia.SRTP)
                        .externalUacSettings(
                            UacConnectionListResponse.ExternalUacSettings.builder()
                                .authUsername("auth8492")
                                .expirationSec(600L)
                                .fromUser("8492")
                                .outboundProxy("outbound.sip-pbx.acme.example:5061")
                                .password("testtesttest")
                                .proxy("sip-pbx.acme.example")
                                .transport(
                                    UacConnectionListResponse.ExternalUacSettings.Transport.TLS
                                )
                                .username("ext8492")
                                .build()
                        )
                        .fqdn("abc123def456.uac.telnyx.com")
                        .fqdnOutboundAuthentication(
                            UacConnectionListResponse.FqdnOutboundAuthentication
                                .CREDENTIAL_AUTHENTICATION
                        )
                        .addFqdn(
                            Fqdn.builder()
                                .id("1293384261075731499")
                                .connectionId("6a09cdc3-8948-47f0-aa62-74ac943d6c58")
                                .createdAt("2018-02-02T22:25:27.521Z")
                                .dnsRecordType("srv")
                                .fqdn("abc123def456.uac.telnyx.com")
                                .port(5060L)
                                .recordType("fqdn")
                                .updatedAt("2018-02-02T22:25:27.521Z")
                                .build()
                        )
                        .inbound(
                            UacConnectionListResponse.Inbound.builder()
                                .aniNumberFormat(
                                    UacConnectionListResponse.Inbound.AniNumberFormat.PLUS_E_164
                                )
                                .channelLimit(10L)
                                .addCodec("G722")
                                .defaultRoutingMethod(
                                    UacConnectionListResponse.Inbound.DefaultRoutingMethod
                                        .SEQUENTIAL
                                )
                                .dnisNumberFormat(
                                    UacConnectionListResponse.Inbound.DnisNumberFormat.PLUS_E164
                                )
                                .generateRingbackTone(true)
                                .isupHeadersEnabled(true)
                                .prackEnabled(true)
                                .shakenStirEnabled(true)
                                .simultaneousRinging(
                                    UacConnectionListResponse.Inbound.SimultaneousRinging.ENABLED
                                )
                                .sipCompactHeadersEnabled(true)
                                .sipSubdomain("abc123def456")
                                .sipSubdomainReceiveSettings(
                                    UacConnectionListResponse.Inbound.SipSubdomainReceiveSettings
                                        .ONLY_MY_CONNECTIONS
                                )
                                .timeout1xxSecs(10L)
                                .timeout2xxSecs(15L)
                                .build()
                        )
                        .internalUacSettings(
                            UacConnectionListResponse.InternalUacSettings.builder()
                                .destinationUri("14155550123@acme.sip.telnyx.com")
                                .build()
                        )
                        .iosPushCredentialId("ec0c8e5d-439e-4620-a0c1-9d9c8d02a836")
                        .jitterBuffer(
                            ConnectionJitterBuffer.builder()
                                .enableJitterBuffer(true)
                                .jitterbufferMsecMax(200L)
                                .jitterbufferMsecMin(60L)
                                .build()
                        )
                        .noiseSuppression(UacConnectionListResponse.NoiseSuppression.BOTH)
                        .noiseSuppressionDetails(
                            ConnectionNoiseSuppressionDetails.builder()
                                .attenuationLimit(80L)
                                .engine(ConnectionNoiseSuppressionDetails.Engine.DEEP_FILTER_NET)
                                .build()
                        )
                        .onnetT38PassthroughEnabled(true)
                        .outbound(
                            UacConnectionListResponse.Outbound.builder()
                                .aniOverride("string")
                                .aniOverrideType(
                                    UacConnectionListResponse.Outbound.AniOverrideType.ALWAYS
                                )
                                .callParkingEnabled(true)
                                .channelLimit(10L)
                                .generateRingbackTone(true)
                                .instantRingbackEnabled(true)
                                .localization("string")
                                .outboundVoiceProfileId("1293384261075731499")
                                .t38ReinviteSource(
                                    UacConnectionListResponse.Outbound.T38ReinviteSource.CUSTOMER
                                )
                                .build()
                        )
                        .password("my123secure456password789")
                        .recordType("uac_connection")
                        .registrationStatus("Registered")
                        .registrationStatusUpdatedAt("2018-02-02T22:25:27.521Z")
                        .rtcpSettings(
                            ConnectionRtcpSettings.builder()
                                .captureEnabled(true)
                                .port(ConnectionRtcpSettings.Port.RTP_1)
                                .reportFrequencySecs(10L)
                                .build()
                        )
                        .sipUriCallingPreference(
                            UacConnectionListResponse.SipUriCallingPreference.DISABLED
                        )
                        .addTag("tag1")
                        .addTag("tag2")
                        .updatedAt("2018-02-02T22:25:27.521Z")
                        .userName("myusername123")
                        .webhookApiVersion(UacConnectionListResponse.WebhookApiVersion.V1)
                        .webhookEventFailoverUrl("https://failover.example.com")
                        .webhookEventUrl("https://example.com")
                        .webhookTimeoutSecs(25L)
                        .build()
                )
                .meta(
                    ConnectionsPaginationMeta.builder()
                        .pageNumber(2L)
                        .totalPages(3L)
                        .pageSize(25L)
                        .totalResults(55L)
                        .build()
                )
                .build()

        assertThat(uacConnectionListPageResponse.data().getOrNull())
            .containsExactly(
                UacConnectionListResponse.builder()
                    .id("6a09cdc3-8948-47f0-aa62-74ac943d6c58")
                    .active(true)
                    .anchorsiteOverride(AnchorsiteOverride.LATENCY)
                    .androidPushCredentialId("06b09dfd-7154-4980-8b75-cebf7a9d4f8e")
                    .authentication(UacConnectionListResponse.Authentication.UAC_AUTHENTICATION)
                    .callCostInWebhooks(false)
                    .connectionName("string")
                    .createdAt("2018-02-02T22:25:27.521Z")
                    .defaultOnHoldComfortNoiseEnabled(true)
                    .dtmfType(DtmfType.RFC_2833)
                    .encodeContactHeaderEnabled(true)
                    .encryptedMedia(EncryptedMedia.SRTP)
                    .externalUacSettings(
                        UacConnectionListResponse.ExternalUacSettings.builder()
                            .authUsername("auth8492")
                            .expirationSec(600L)
                            .fromUser("8492")
                            .outboundProxy("outbound.sip-pbx.acme.example:5061")
                            .password("testtesttest")
                            .proxy("sip-pbx.acme.example")
                            .transport(UacConnectionListResponse.ExternalUacSettings.Transport.TLS)
                            .username("ext8492")
                            .build()
                    )
                    .fqdn("abc123def456.uac.telnyx.com")
                    .fqdnOutboundAuthentication(
                        UacConnectionListResponse.FqdnOutboundAuthentication
                            .CREDENTIAL_AUTHENTICATION
                    )
                    .addFqdn(
                        Fqdn.builder()
                            .id("1293384261075731499")
                            .connectionId("6a09cdc3-8948-47f0-aa62-74ac943d6c58")
                            .createdAt("2018-02-02T22:25:27.521Z")
                            .dnsRecordType("srv")
                            .fqdn("abc123def456.uac.telnyx.com")
                            .port(5060L)
                            .recordType("fqdn")
                            .updatedAt("2018-02-02T22:25:27.521Z")
                            .build()
                    )
                    .inbound(
                        UacConnectionListResponse.Inbound.builder()
                            .aniNumberFormat(
                                UacConnectionListResponse.Inbound.AniNumberFormat.PLUS_E_164
                            )
                            .channelLimit(10L)
                            .addCodec("G722")
                            .defaultRoutingMethod(
                                UacConnectionListResponse.Inbound.DefaultRoutingMethod.SEQUENTIAL
                            )
                            .dnisNumberFormat(
                                UacConnectionListResponse.Inbound.DnisNumberFormat.PLUS_E164
                            )
                            .generateRingbackTone(true)
                            .isupHeadersEnabled(true)
                            .prackEnabled(true)
                            .shakenStirEnabled(true)
                            .simultaneousRinging(
                                UacConnectionListResponse.Inbound.SimultaneousRinging.ENABLED
                            )
                            .sipCompactHeadersEnabled(true)
                            .sipSubdomain("abc123def456")
                            .sipSubdomainReceiveSettings(
                                UacConnectionListResponse.Inbound.SipSubdomainReceiveSettings
                                    .ONLY_MY_CONNECTIONS
                            )
                            .timeout1xxSecs(10L)
                            .timeout2xxSecs(15L)
                            .build()
                    )
                    .internalUacSettings(
                        UacConnectionListResponse.InternalUacSettings.builder()
                            .destinationUri("14155550123@acme.sip.telnyx.com")
                            .build()
                    )
                    .iosPushCredentialId("ec0c8e5d-439e-4620-a0c1-9d9c8d02a836")
                    .jitterBuffer(
                        ConnectionJitterBuffer.builder()
                            .enableJitterBuffer(true)
                            .jitterbufferMsecMax(200L)
                            .jitterbufferMsecMin(60L)
                            .build()
                    )
                    .noiseSuppression(UacConnectionListResponse.NoiseSuppression.BOTH)
                    .noiseSuppressionDetails(
                        ConnectionNoiseSuppressionDetails.builder()
                            .attenuationLimit(80L)
                            .engine(ConnectionNoiseSuppressionDetails.Engine.DEEP_FILTER_NET)
                            .build()
                    )
                    .onnetT38PassthroughEnabled(true)
                    .outbound(
                        UacConnectionListResponse.Outbound.builder()
                            .aniOverride("string")
                            .aniOverrideType(
                                UacConnectionListResponse.Outbound.AniOverrideType.ALWAYS
                            )
                            .callParkingEnabled(true)
                            .channelLimit(10L)
                            .generateRingbackTone(true)
                            .instantRingbackEnabled(true)
                            .localization("string")
                            .outboundVoiceProfileId("1293384261075731499")
                            .t38ReinviteSource(
                                UacConnectionListResponse.Outbound.T38ReinviteSource.CUSTOMER
                            )
                            .build()
                    )
                    .password("my123secure456password789")
                    .recordType("uac_connection")
                    .registrationStatus("Registered")
                    .registrationStatusUpdatedAt("2018-02-02T22:25:27.521Z")
                    .rtcpSettings(
                        ConnectionRtcpSettings.builder()
                            .captureEnabled(true)
                            .port(ConnectionRtcpSettings.Port.RTP_1)
                            .reportFrequencySecs(10L)
                            .build()
                    )
                    .sipUriCallingPreference(
                        UacConnectionListResponse.SipUriCallingPreference.DISABLED
                    )
                    .addTag("tag1")
                    .addTag("tag2")
                    .updatedAt("2018-02-02T22:25:27.521Z")
                    .userName("myusername123")
                    .webhookApiVersion(UacConnectionListResponse.WebhookApiVersion.V1)
                    .webhookEventFailoverUrl("https://failover.example.com")
                    .webhookEventUrl("https://example.com")
                    .webhookTimeoutSecs(25L)
                    .build()
            )
        assertThat(uacConnectionListPageResponse.meta())
            .contains(
                ConnectionsPaginationMeta.builder()
                    .pageNumber(2L)
                    .totalPages(3L)
                    .pageSize(25L)
                    .totalResults(55L)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val uacConnectionListPageResponse =
            UacConnectionListPageResponse.builder()
                .addData(
                    UacConnectionListResponse.builder()
                        .id("6a09cdc3-8948-47f0-aa62-74ac943d6c58")
                        .active(true)
                        .anchorsiteOverride(AnchorsiteOverride.LATENCY)
                        .androidPushCredentialId("06b09dfd-7154-4980-8b75-cebf7a9d4f8e")
                        .authentication(UacConnectionListResponse.Authentication.UAC_AUTHENTICATION)
                        .callCostInWebhooks(false)
                        .connectionName("string")
                        .createdAt("2018-02-02T22:25:27.521Z")
                        .defaultOnHoldComfortNoiseEnabled(true)
                        .dtmfType(DtmfType.RFC_2833)
                        .encodeContactHeaderEnabled(true)
                        .encryptedMedia(EncryptedMedia.SRTP)
                        .externalUacSettings(
                            UacConnectionListResponse.ExternalUacSettings.builder()
                                .authUsername("auth8492")
                                .expirationSec(600L)
                                .fromUser("8492")
                                .outboundProxy("outbound.sip-pbx.acme.example:5061")
                                .password("testtesttest")
                                .proxy("sip-pbx.acme.example")
                                .transport(
                                    UacConnectionListResponse.ExternalUacSettings.Transport.TLS
                                )
                                .username("ext8492")
                                .build()
                        )
                        .fqdn("abc123def456.uac.telnyx.com")
                        .fqdnOutboundAuthentication(
                            UacConnectionListResponse.FqdnOutboundAuthentication
                                .CREDENTIAL_AUTHENTICATION
                        )
                        .addFqdn(
                            Fqdn.builder()
                                .id("1293384261075731499")
                                .connectionId("6a09cdc3-8948-47f0-aa62-74ac943d6c58")
                                .createdAt("2018-02-02T22:25:27.521Z")
                                .dnsRecordType("srv")
                                .fqdn("abc123def456.uac.telnyx.com")
                                .port(5060L)
                                .recordType("fqdn")
                                .updatedAt("2018-02-02T22:25:27.521Z")
                                .build()
                        )
                        .inbound(
                            UacConnectionListResponse.Inbound.builder()
                                .aniNumberFormat(
                                    UacConnectionListResponse.Inbound.AniNumberFormat.PLUS_E_164
                                )
                                .channelLimit(10L)
                                .addCodec("G722")
                                .defaultRoutingMethod(
                                    UacConnectionListResponse.Inbound.DefaultRoutingMethod
                                        .SEQUENTIAL
                                )
                                .dnisNumberFormat(
                                    UacConnectionListResponse.Inbound.DnisNumberFormat.PLUS_E164
                                )
                                .generateRingbackTone(true)
                                .isupHeadersEnabled(true)
                                .prackEnabled(true)
                                .shakenStirEnabled(true)
                                .simultaneousRinging(
                                    UacConnectionListResponse.Inbound.SimultaneousRinging.ENABLED
                                )
                                .sipCompactHeadersEnabled(true)
                                .sipSubdomain("abc123def456")
                                .sipSubdomainReceiveSettings(
                                    UacConnectionListResponse.Inbound.SipSubdomainReceiveSettings
                                        .ONLY_MY_CONNECTIONS
                                )
                                .timeout1xxSecs(10L)
                                .timeout2xxSecs(15L)
                                .build()
                        )
                        .internalUacSettings(
                            UacConnectionListResponse.InternalUacSettings.builder()
                                .destinationUri("14155550123@acme.sip.telnyx.com")
                                .build()
                        )
                        .iosPushCredentialId("ec0c8e5d-439e-4620-a0c1-9d9c8d02a836")
                        .jitterBuffer(
                            ConnectionJitterBuffer.builder()
                                .enableJitterBuffer(true)
                                .jitterbufferMsecMax(200L)
                                .jitterbufferMsecMin(60L)
                                .build()
                        )
                        .noiseSuppression(UacConnectionListResponse.NoiseSuppression.BOTH)
                        .noiseSuppressionDetails(
                            ConnectionNoiseSuppressionDetails.builder()
                                .attenuationLimit(80L)
                                .engine(ConnectionNoiseSuppressionDetails.Engine.DEEP_FILTER_NET)
                                .build()
                        )
                        .onnetT38PassthroughEnabled(true)
                        .outbound(
                            UacConnectionListResponse.Outbound.builder()
                                .aniOverride("string")
                                .aniOverrideType(
                                    UacConnectionListResponse.Outbound.AniOverrideType.ALWAYS
                                )
                                .callParkingEnabled(true)
                                .channelLimit(10L)
                                .generateRingbackTone(true)
                                .instantRingbackEnabled(true)
                                .localization("string")
                                .outboundVoiceProfileId("1293384261075731499")
                                .t38ReinviteSource(
                                    UacConnectionListResponse.Outbound.T38ReinviteSource.CUSTOMER
                                )
                                .build()
                        )
                        .password("my123secure456password789")
                        .recordType("uac_connection")
                        .registrationStatus("Registered")
                        .registrationStatusUpdatedAt("2018-02-02T22:25:27.521Z")
                        .rtcpSettings(
                            ConnectionRtcpSettings.builder()
                                .captureEnabled(true)
                                .port(ConnectionRtcpSettings.Port.RTP_1)
                                .reportFrequencySecs(10L)
                                .build()
                        )
                        .sipUriCallingPreference(
                            UacConnectionListResponse.SipUriCallingPreference.DISABLED
                        )
                        .addTag("tag1")
                        .addTag("tag2")
                        .updatedAt("2018-02-02T22:25:27.521Z")
                        .userName("myusername123")
                        .webhookApiVersion(UacConnectionListResponse.WebhookApiVersion.V1)
                        .webhookEventFailoverUrl("https://failover.example.com")
                        .webhookEventUrl("https://example.com")
                        .webhookTimeoutSecs(25L)
                        .build()
                )
                .meta(
                    ConnectionsPaginationMeta.builder()
                        .pageNumber(2L)
                        .totalPages(3L)
                        .pageSize(25L)
                        .totalResults(55L)
                        .build()
                )
                .build()

        val roundtrippedUacConnectionListPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(uacConnectionListPageResponse),
                jacksonTypeRef<UacConnectionListPageResponse>(),
            )

        assertThat(roundtrippedUacConnectionListPageResponse)
            .isEqualTo(uacConnectionListPageResponse)
    }
}
