// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.llmtokengateway.usage

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.jsonMapper
import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class UsageRetrieveSummaryResponseTest {

    @Test
    fun create() {
        val usageRetrieveSummaryResponse =
            UsageRetrieveSummaryResponse.builder()
                .data(
                    UsageRetrieveSummaryResponse.Data.builder()
                        .addByDay(
                            UsageRetrieveSummaryResponse.Data.ByDay.builder()
                                .cacheHits(0L)
                                .date(LocalDate.parse("2019-12-27"))
                                .failedRequests(0L)
                                .inputTokens(0L)
                                .outputTokens(0L)
                                .partialRequests(0L)
                                .requests(0L)
                                .reservedSpend(0.0)
                                .spend(0.0)
                                .succeededRequests(0L)
                                .unknownRequests(0L)
                                .build()
                        )
                        .addByModel(
                            UsageRetrieveSummaryResponse.Data.ByModel.builder()
                                .cacheHits(0L)
                                .failedRequests(0L)
                                .inputTokens(0L)
                                .model("model")
                                .outputTokens(0L)
                                .partialRequests(0L)
                                .requests(0L)
                                .reservedSpend(0.0)
                                .spend(0.0)
                                .succeededRequests(0L)
                                .unknownRequests(0L)
                                .build()
                        )
                        .guardrails(
                            UsageRetrieveSummaryResponse.Data.Guardrails.builder()
                                .blockedEvents(0L)
                                .flaggedEvents(0L)
                                .addRecentEvent(
                                    UsageRetrieveSummaryResponse.Data.Guardrails.RecentEvent
                                        .builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .endUserId("end_user_id")
                                        .evaluationInputTokens(0L)
                                        .evaluationOutputTokens(0L)
                                        .addFinding(
                                            UsageRetrieveSummaryResponse.Data.Guardrails.RecentEvent
                                                .Finding
                                                .builder()
                                                .action(
                                                    UsageRetrieveSummaryResponse.Data.Guardrails
                                                        .RecentEvent
                                                        .Finding
                                                        .Action
                                                        .FLAG
                                                )
                                                .code("code")
                                                .count(0L)
                                                .detector(
                                                    UsageRetrieveSummaryResponse.Data.Guardrails
                                                        .RecentEvent
                                                        .Finding
                                                        .Detector
                                                        .SECRETS
                                                )
                                                .build()
                                        )
                                        .model("model")
                                        .outcome(
                                            UsageRetrieveSummaryResponse.Data.Guardrails.RecentEvent
                                                .Outcome
                                                .EVALUATED
                                        )
                                        .requestId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .stage(
                                            UsageRetrieveSummaryResponse.Data.Guardrails.RecentEvent
                                                .Stage
                                                .PROMPT
                                        )
                                        .tokenGroupId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .tokenKeyId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .tokenUserId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .build()
                        )
                        .totals(
                            UsageRetrieveSummaryResponse.Data.Totals.builder()
                                .cacheHits(0L)
                                .failedRequests(0L)
                                .inputTokens(0L)
                                .outputTokens(0L)
                                .partialRequests(0L)
                                .requests(0L)
                                .reservedSpend(0.0)
                                .spend(0.0)
                                .succeededRequests(0L)
                                .unknownRequests(0L)
                                .build()
                        )
                        .build()
                )
                .meta(
                    UsageRetrieveSummaryResponse.Meta.builder()
                        .endDate(LocalDate.parse("2019-12-27"))
                        .startDate(LocalDate.parse("2019-12-27"))
                        .tokenGroupId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .build()

        assertThat(usageRetrieveSummaryResponse.data())
            .isEqualTo(
                UsageRetrieveSummaryResponse.Data.builder()
                    .addByDay(
                        UsageRetrieveSummaryResponse.Data.ByDay.builder()
                            .cacheHits(0L)
                            .date(LocalDate.parse("2019-12-27"))
                            .failedRequests(0L)
                            .inputTokens(0L)
                            .outputTokens(0L)
                            .partialRequests(0L)
                            .requests(0L)
                            .reservedSpend(0.0)
                            .spend(0.0)
                            .succeededRequests(0L)
                            .unknownRequests(0L)
                            .build()
                    )
                    .addByModel(
                        UsageRetrieveSummaryResponse.Data.ByModel.builder()
                            .cacheHits(0L)
                            .failedRequests(0L)
                            .inputTokens(0L)
                            .model("model")
                            .outputTokens(0L)
                            .partialRequests(0L)
                            .requests(0L)
                            .reservedSpend(0.0)
                            .spend(0.0)
                            .succeededRequests(0L)
                            .unknownRequests(0L)
                            .build()
                    )
                    .guardrails(
                        UsageRetrieveSummaryResponse.Data.Guardrails.builder()
                            .blockedEvents(0L)
                            .flaggedEvents(0L)
                            .addRecentEvent(
                                UsageRetrieveSummaryResponse.Data.Guardrails.RecentEvent.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .endUserId("end_user_id")
                                    .evaluationInputTokens(0L)
                                    .evaluationOutputTokens(0L)
                                    .addFinding(
                                        UsageRetrieveSummaryResponse.Data.Guardrails.RecentEvent
                                            .Finding
                                            .builder()
                                            .action(
                                                UsageRetrieveSummaryResponse.Data.Guardrails
                                                    .RecentEvent
                                                    .Finding
                                                    .Action
                                                    .FLAG
                                            )
                                            .code("code")
                                            .count(0L)
                                            .detector(
                                                UsageRetrieveSummaryResponse.Data.Guardrails
                                                    .RecentEvent
                                                    .Finding
                                                    .Detector
                                                    .SECRETS
                                            )
                                            .build()
                                    )
                                    .model("model")
                                    .outcome(
                                        UsageRetrieveSummaryResponse.Data.Guardrails.RecentEvent
                                            .Outcome
                                            .EVALUATED
                                    )
                                    .requestId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .stage(
                                        UsageRetrieveSummaryResponse.Data.Guardrails.RecentEvent
                                            .Stage
                                            .PROMPT
                                    )
                                    .tokenGroupId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .tokenKeyId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .tokenUserId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .build()
                    )
                    .totals(
                        UsageRetrieveSummaryResponse.Data.Totals.builder()
                            .cacheHits(0L)
                            .failedRequests(0L)
                            .inputTokens(0L)
                            .outputTokens(0L)
                            .partialRequests(0L)
                            .requests(0L)
                            .reservedSpend(0.0)
                            .spend(0.0)
                            .succeededRequests(0L)
                            .unknownRequests(0L)
                            .build()
                    )
                    .build()
            )
        assertThat(usageRetrieveSummaryResponse.meta())
            .isEqualTo(
                UsageRetrieveSummaryResponse.Meta.builder()
                    .endDate(LocalDate.parse("2019-12-27"))
                    .startDate(LocalDate.parse("2019-12-27"))
                    .tokenGroupId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val usageRetrieveSummaryResponse =
            UsageRetrieveSummaryResponse.builder()
                .data(
                    UsageRetrieveSummaryResponse.Data.builder()
                        .addByDay(
                            UsageRetrieveSummaryResponse.Data.ByDay.builder()
                                .cacheHits(0L)
                                .date(LocalDate.parse("2019-12-27"))
                                .failedRequests(0L)
                                .inputTokens(0L)
                                .outputTokens(0L)
                                .partialRequests(0L)
                                .requests(0L)
                                .reservedSpend(0.0)
                                .spend(0.0)
                                .succeededRequests(0L)
                                .unknownRequests(0L)
                                .build()
                        )
                        .addByModel(
                            UsageRetrieveSummaryResponse.Data.ByModel.builder()
                                .cacheHits(0L)
                                .failedRequests(0L)
                                .inputTokens(0L)
                                .model("model")
                                .outputTokens(0L)
                                .partialRequests(0L)
                                .requests(0L)
                                .reservedSpend(0.0)
                                .spend(0.0)
                                .succeededRequests(0L)
                                .unknownRequests(0L)
                                .build()
                        )
                        .guardrails(
                            UsageRetrieveSummaryResponse.Data.Guardrails.builder()
                                .blockedEvents(0L)
                                .flaggedEvents(0L)
                                .addRecentEvent(
                                    UsageRetrieveSummaryResponse.Data.Guardrails.RecentEvent
                                        .builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .endUserId("end_user_id")
                                        .evaluationInputTokens(0L)
                                        .evaluationOutputTokens(0L)
                                        .addFinding(
                                            UsageRetrieveSummaryResponse.Data.Guardrails.RecentEvent
                                                .Finding
                                                .builder()
                                                .action(
                                                    UsageRetrieveSummaryResponse.Data.Guardrails
                                                        .RecentEvent
                                                        .Finding
                                                        .Action
                                                        .FLAG
                                                )
                                                .code("code")
                                                .count(0L)
                                                .detector(
                                                    UsageRetrieveSummaryResponse.Data.Guardrails
                                                        .RecentEvent
                                                        .Finding
                                                        .Detector
                                                        .SECRETS
                                                )
                                                .build()
                                        )
                                        .model("model")
                                        .outcome(
                                            UsageRetrieveSummaryResponse.Data.Guardrails.RecentEvent
                                                .Outcome
                                                .EVALUATED
                                        )
                                        .requestId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .stage(
                                            UsageRetrieveSummaryResponse.Data.Guardrails.RecentEvent
                                                .Stage
                                                .PROMPT
                                        )
                                        .tokenGroupId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .tokenKeyId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .tokenUserId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .build()
                        )
                        .totals(
                            UsageRetrieveSummaryResponse.Data.Totals.builder()
                                .cacheHits(0L)
                                .failedRequests(0L)
                                .inputTokens(0L)
                                .outputTokens(0L)
                                .partialRequests(0L)
                                .requests(0L)
                                .reservedSpend(0.0)
                                .spend(0.0)
                                .succeededRequests(0L)
                                .unknownRequests(0L)
                                .build()
                        )
                        .build()
                )
                .meta(
                    UsageRetrieveSummaryResponse.Meta.builder()
                        .endDate(LocalDate.parse("2019-12-27"))
                        .startDate(LocalDate.parse("2019-12-27"))
                        .tokenGroupId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .build()

        val roundtrippedUsageRetrieveSummaryResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(usageRetrieveSummaryResponse),
                jacksonTypeRef<UsageRetrieveSummaryResponse>(),
            )

        assertThat(roundtrippedUsageRetrieveSummaryResponse).isEqualTo(usageRetrieveSummaryResponse)
    }
}
