// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.portingorders

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.jsonMapper
import com.telnyx.sdk.models.PortingOrderStatus
import com.telnyx.sdk.models.PortingOrdersExceptionType
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PortingOrderCreateResponseTest {

    @Test
    fun create() {
        val portingOrderCreateResponse =
            PortingOrderCreateResponse.builder()
                .addData(
                    PortingOrder.builder()
                        .id("b0ea6d6f-de31-4079-a536-992e0c98b037")
                        .activationSettings(
                            PortingOrderActivationSettings.builder()
                                .activationStatus(null)
                                .fastPortEligible(true)
                                .focDatetimeActual(null)
                                .focDatetimeRequested(null)
                                .build()
                        )
                        .addAdditionalStep(PortingOrder.AdditionalStep.ASSOCIATED_PHONE_NUMBERS)
                        .createdAt(OffsetDateTime.parse("2022-03-17T18:01:01Z"))
                        .customerGroupReference(null)
                        .customerReference(null)
                        .description("FP Telnyx")
                        .documents(PortingOrderDocuments.builder().invoice(null).loa(null).build())
                        .endUser(
                            PortingOrderEndUser.builder()
                                .admin(
                                    PortingOrderEndUserAdmin.builder()
                                        .accountNumber(null)
                                        .authPersonName(null)
                                        .billingPhoneNumber(null)
                                        .businessIdentifier(null)
                                        .entityName(null)
                                        .pinPasscode(null)
                                        .taxIdentifier(null)
                                        .build()
                                )
                                .location(
                                    PortingOrderEndUserLocation.builder()
                                        .administrativeArea(null)
                                        .countryCode(null)
                                        .extendedAddress(null)
                                        .locality(null)
                                        .postalCode(null)
                                        .streetAddress(null)
                                        .build()
                                )
                                .build()
                        )
                        .messaging(
                            PortingOrderMessaging.builder()
                                .enableMessaging(false)
                                .messagingCapable(true)
                                .messagingPortCompleted(false)
                                .messagingPortStatus(
                                    PortingOrderMessaging.MessagingPortStatus.NOT_APPLICABLE
                                )
                                .build()
                        )
                        .misc(
                            PortingOrderMisc.builder()
                                .newBillingPhoneNumber("new_billing_phone_number")
                                .remainingNumbersAction(
                                    PortingOrderMisc.RemainingNumbersAction.DISCONNECT
                                )
                                .type(PortingOrderType.FULL)
                                .build()
                        )
                        .oldServiceProviderOcn("Unreal Communications")
                        .parentSupportKey(null)
                        .phoneNumberConfiguration(
                            PortingOrderPhoneNumberConfiguration.builder()
                                .billingGroupId(null)
                                .connectionId(null)
                                .emergencyAddressId(null)
                                .messagingProfileId(null)
                                .addTag("string")
                                .build()
                        )
                        .phoneNumberType(PortingOrder.PhoneNumberType.LOCAL)
                        .portingPhoneNumbersCount(1L)
                        .recordType("porting_order")
                        .addRequirement(
                            PortingOrderRequirement.builder()
                                .fieldType(PortingOrderRequirement.FieldType.DOCUMENT)
                                .fieldValue("9787fb5f-cbe5-4de4-b765-3303774ee9fe")
                                .recordType("porting_requirement")
                                .requirementTypeId("59b0762a-b274-4f76-ac32-4d5cf0272e66")
                                .build()
                        )
                        .requirementsMet(false)
                        .status(
                            PortingOrderStatus.builder()
                                .addDetail(
                                    PortingOrdersExceptionType.builder()
                                        .code(PortingOrdersExceptionType.Code.ENTITY_NAME_MISMATCH)
                                        .description("Entity name does not match that on the CSR")
                                        .build()
                                )
                                .value(PortingOrderStatus.PortingOrderStatusValue.DRAFT)
                                .build()
                        )
                        .supportKey(null)
                        .updatedAt(OffsetDateTime.parse("2022-03-17T18:01:01Z"))
                        .userFeedback(
                            PortingOrderUserFeedback.builder()
                                .userComment(null)
                                .userRating(null)
                                .build()
                        )
                        .userId("40d68ba2-0847-4df2-be9c-b0e0cb673e75")
                        .webhookUrl(null)
                        .build()
                )
                .build()

        assertThat(portingOrderCreateResponse.data().getOrNull())
            .containsExactly(
                PortingOrder.builder()
                    .id("b0ea6d6f-de31-4079-a536-992e0c98b037")
                    .activationSettings(
                        PortingOrderActivationSettings.builder()
                            .activationStatus(null)
                            .fastPortEligible(true)
                            .focDatetimeActual(null)
                            .focDatetimeRequested(null)
                            .build()
                    )
                    .addAdditionalStep(PortingOrder.AdditionalStep.ASSOCIATED_PHONE_NUMBERS)
                    .createdAt(OffsetDateTime.parse("2022-03-17T18:01:01Z"))
                    .customerGroupReference(null)
                    .customerReference(null)
                    .description("FP Telnyx")
                    .documents(PortingOrderDocuments.builder().invoice(null).loa(null).build())
                    .endUser(
                        PortingOrderEndUser.builder()
                            .admin(
                                PortingOrderEndUserAdmin.builder()
                                    .accountNumber(null)
                                    .authPersonName(null)
                                    .billingPhoneNumber(null)
                                    .businessIdentifier(null)
                                    .entityName(null)
                                    .pinPasscode(null)
                                    .taxIdentifier(null)
                                    .build()
                            )
                            .location(
                                PortingOrderEndUserLocation.builder()
                                    .administrativeArea(null)
                                    .countryCode(null)
                                    .extendedAddress(null)
                                    .locality(null)
                                    .postalCode(null)
                                    .streetAddress(null)
                                    .build()
                            )
                            .build()
                    )
                    .messaging(
                        PortingOrderMessaging.builder()
                            .enableMessaging(false)
                            .messagingCapable(true)
                            .messagingPortCompleted(false)
                            .messagingPortStatus(
                                PortingOrderMessaging.MessagingPortStatus.NOT_APPLICABLE
                            )
                            .build()
                    )
                    .misc(
                        PortingOrderMisc.builder()
                            .newBillingPhoneNumber("new_billing_phone_number")
                            .remainingNumbersAction(
                                PortingOrderMisc.RemainingNumbersAction.DISCONNECT
                            )
                            .type(PortingOrderType.FULL)
                            .build()
                    )
                    .oldServiceProviderOcn("Unreal Communications")
                    .parentSupportKey(null)
                    .phoneNumberConfiguration(
                        PortingOrderPhoneNumberConfiguration.builder()
                            .billingGroupId(null)
                            .connectionId(null)
                            .emergencyAddressId(null)
                            .messagingProfileId(null)
                            .addTag("string")
                            .build()
                    )
                    .phoneNumberType(PortingOrder.PhoneNumberType.LOCAL)
                    .portingPhoneNumbersCount(1L)
                    .recordType("porting_order")
                    .addRequirement(
                        PortingOrderRequirement.builder()
                            .fieldType(PortingOrderRequirement.FieldType.DOCUMENT)
                            .fieldValue("9787fb5f-cbe5-4de4-b765-3303774ee9fe")
                            .recordType("porting_requirement")
                            .requirementTypeId("59b0762a-b274-4f76-ac32-4d5cf0272e66")
                            .build()
                    )
                    .requirementsMet(false)
                    .status(
                        PortingOrderStatus.builder()
                            .addDetail(
                                PortingOrdersExceptionType.builder()
                                    .code(PortingOrdersExceptionType.Code.ENTITY_NAME_MISMATCH)
                                    .description("Entity name does not match that on the CSR")
                                    .build()
                            )
                            .value(PortingOrderStatus.PortingOrderStatusValue.DRAFT)
                            .build()
                    )
                    .supportKey(null)
                    .updatedAt(OffsetDateTime.parse("2022-03-17T18:01:01Z"))
                    .userFeedback(
                        PortingOrderUserFeedback.builder()
                            .userComment(null)
                            .userRating(null)
                            .build()
                    )
                    .userId("40d68ba2-0847-4df2-be9c-b0e0cb673e75")
                    .webhookUrl(null)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val portingOrderCreateResponse =
            PortingOrderCreateResponse.builder()
                .addData(
                    PortingOrder.builder()
                        .id("b0ea6d6f-de31-4079-a536-992e0c98b037")
                        .activationSettings(
                            PortingOrderActivationSettings.builder()
                                .activationStatus(null)
                                .fastPortEligible(true)
                                .focDatetimeActual(null)
                                .focDatetimeRequested(null)
                                .build()
                        )
                        .addAdditionalStep(PortingOrder.AdditionalStep.ASSOCIATED_PHONE_NUMBERS)
                        .createdAt(OffsetDateTime.parse("2022-03-17T18:01:01Z"))
                        .customerGroupReference(null)
                        .customerReference(null)
                        .description("FP Telnyx")
                        .documents(PortingOrderDocuments.builder().invoice(null).loa(null).build())
                        .endUser(
                            PortingOrderEndUser.builder()
                                .admin(
                                    PortingOrderEndUserAdmin.builder()
                                        .accountNumber(null)
                                        .authPersonName(null)
                                        .billingPhoneNumber(null)
                                        .businessIdentifier(null)
                                        .entityName(null)
                                        .pinPasscode(null)
                                        .taxIdentifier(null)
                                        .build()
                                )
                                .location(
                                    PortingOrderEndUserLocation.builder()
                                        .administrativeArea(null)
                                        .countryCode(null)
                                        .extendedAddress(null)
                                        .locality(null)
                                        .postalCode(null)
                                        .streetAddress(null)
                                        .build()
                                )
                                .build()
                        )
                        .messaging(
                            PortingOrderMessaging.builder()
                                .enableMessaging(false)
                                .messagingCapable(true)
                                .messagingPortCompleted(false)
                                .messagingPortStatus(
                                    PortingOrderMessaging.MessagingPortStatus.NOT_APPLICABLE
                                )
                                .build()
                        )
                        .misc(
                            PortingOrderMisc.builder()
                                .newBillingPhoneNumber("new_billing_phone_number")
                                .remainingNumbersAction(
                                    PortingOrderMisc.RemainingNumbersAction.DISCONNECT
                                )
                                .type(PortingOrderType.FULL)
                                .build()
                        )
                        .oldServiceProviderOcn("Unreal Communications")
                        .parentSupportKey(null)
                        .phoneNumberConfiguration(
                            PortingOrderPhoneNumberConfiguration.builder()
                                .billingGroupId(null)
                                .connectionId(null)
                                .emergencyAddressId(null)
                                .messagingProfileId(null)
                                .addTag("string")
                                .build()
                        )
                        .phoneNumberType(PortingOrder.PhoneNumberType.LOCAL)
                        .portingPhoneNumbersCount(1L)
                        .recordType("porting_order")
                        .addRequirement(
                            PortingOrderRequirement.builder()
                                .fieldType(PortingOrderRequirement.FieldType.DOCUMENT)
                                .fieldValue("9787fb5f-cbe5-4de4-b765-3303774ee9fe")
                                .recordType("porting_requirement")
                                .requirementTypeId("59b0762a-b274-4f76-ac32-4d5cf0272e66")
                                .build()
                        )
                        .requirementsMet(false)
                        .status(
                            PortingOrderStatus.builder()
                                .addDetail(
                                    PortingOrdersExceptionType.builder()
                                        .code(PortingOrdersExceptionType.Code.ENTITY_NAME_MISMATCH)
                                        .description("Entity name does not match that on the CSR")
                                        .build()
                                )
                                .value(PortingOrderStatus.PortingOrderStatusValue.DRAFT)
                                .build()
                        )
                        .supportKey(null)
                        .updatedAt(OffsetDateTime.parse("2022-03-17T18:01:01Z"))
                        .userFeedback(
                            PortingOrderUserFeedback.builder()
                                .userComment(null)
                                .userRating(null)
                                .build()
                        )
                        .userId("40d68ba2-0847-4df2-be9c-b0e0cb673e75")
                        .webhookUrl(null)
                        .build()
                )
                .build()

        val roundtrippedPortingOrderCreateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(portingOrderCreateResponse),
                jacksonTypeRef<PortingOrderCreateResponse>(),
            )

        assertThat(roundtrippedPortingOrderCreateResponse).isEqualTo(portingOrderCreateResponse)
    }
}
