// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.ipconnections

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.jsonMapper
import com.telnyx.sdk.models.ConnectionJitterBuffer
import com.telnyx.sdk.models.ConnectionNoiseSuppressionDetails
import com.telnyx.sdk.models.credentialconnections.AnchorsiteOverride
import com.telnyx.sdk.models.credentialconnections.ConnectionRtcpSettings
import com.telnyx.sdk.models.credentialconnections.DtmfType
import com.telnyx.sdk.models.credentialconnections.EncryptedMedia
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class IpConnectionTest {

    @Test
    fun create() {
        val ipConnection =
            IpConnection.builder()
                .id("id")
                .active(true)
                .anchorsiteOverride(AnchorsiteOverride.LATENCY)
                .androidPushCredentialId("06b09dfd-7154-4980-8b75-cebf7a9d4f8e")
                .callCostInWebhooks(true)
                .connectionName("string")
                .createdAt("2018-02-02T22:25:27.521Z")
                .defaultOnHoldComfortNoiseEnabled(true)
                .dtmfType(DtmfType.RFC_2833)
                .encodeContactHeaderEnabled(true)
                .encryptedMedia(EncryptedMedia.SRTP)
                .inbound(
                    InboundIp.builder()
                        .aniNumberFormat(InboundIp.AniNumberFormat.PLUS_E_164)
                        .channelLimit(10L)
                        .addCodec("G722")
                        .defaultPrimaryIpId("192.0.2.1")
                        .defaultRoutingMethod(InboundIp.DefaultRoutingMethod.SEQUENTIAL)
                        .defaultSecondaryIpId("198.51.100.1")
                        .defaultTertiaryIpId("203.0.113.1")
                        .dnisNumberFormat(InboundIp.DnisNumberFormat.PLUS_E164)
                        .generateRingbackTone(true)
                        .isupHeadersEnabled(true)
                        .prackEnabled(true)
                        .shakenStirEnabled(true)
                        .sipCompactHeadersEnabled(true)
                        .sipRegion(InboundIp.SipRegion.US)
                        .sipSubdomain("string")
                        .sipSubdomainReceiveSettings(
                            InboundIp.SipSubdomainReceiveSettings.ONLY_MY_CONNECTIONS
                        )
                        .timeout1xxSecs(10L)
                        .timeout2xxSecs(10L)
                        .build()
                )
                .iosPushCredentialId("ec0c8e5d-439e-4620-a0c1-9d9c8d02a836")
                .jitterBuffer(
                    ConnectionJitterBuffer.builder()
                        .enableJitterBuffer(true)
                        .jitterbufferMsecMax(200L)
                        .jitterbufferMsecMin(60L)
                        .build()
                )
                .noiseSuppression(IpConnection.NoiseSuppression.BOTH)
                .noiseSuppressionDetails(
                    ConnectionNoiseSuppressionDetails.builder()
                        .attenuationLimit(80L)
                        .engine(ConnectionNoiseSuppressionDetails.Engine.DEEP_FILTER_NET)
                        .build()
                )
                .onnetT38PassthroughEnabled(true)
                .outbound(
                    OutboundIp.builder()
                        .aniOverride("string")
                        .aniOverrideType(OutboundIp.AniOverrideType.ALWAYS)
                        .callParkingEnabled(true)
                        .channelLimit(10L)
                        .generateRingbackTone(true)
                        .instantRingbackEnabled(true)
                        .ipAuthenticationMethod(OutboundIp.IpAuthenticationMethod.TOKEN)
                        .ipAuthenticationToken("string")
                        .localization("string")
                        .outboundVoiceProfileId("outbound_voice_profile_id")
                        .t38ReinviteSource(OutboundIp.T38ReinviteSource.CUSTOMER)
                        .techPrefix("string")
                        .build()
                )
                .recordType("ip_connection")
                .rtcpSettings(
                    ConnectionRtcpSettings.builder()
                        .captureEnabled(true)
                        .port(ConnectionRtcpSettings.Port.RTCP_MUX)
                        .reportFrequencySecs(10L)
                        .build()
                )
                .addTag("tag1")
                .addTag("tag2")
                .transportProtocol(IpConnection.TransportProtocol.UDP)
                .updatedAt("2018-02-02T22:25:27.521Z")
                .webhookApiVersion(IpConnection.WebhookApiVersion.V1)
                .webhookEventFailoverUrl("https://failover.example.com")
                .webhookEventUrl("https://example.com")
                .webhookTimeoutSecs(25L)
                .build()

        assertThat(ipConnection.id()).contains("id")
        assertThat(ipConnection.active()).contains(true)
        assertThat(ipConnection.anchorsiteOverride()).contains(AnchorsiteOverride.LATENCY)
        assertThat(ipConnection.androidPushCredentialId())
            .contains("06b09dfd-7154-4980-8b75-cebf7a9d4f8e")
        assertThat(ipConnection.callCostInWebhooks()).contains(true)
        assertThat(ipConnection.connectionName()).contains("string")
        assertThat(ipConnection.createdAt()).contains("2018-02-02T22:25:27.521Z")
        assertThat(ipConnection.defaultOnHoldComfortNoiseEnabled()).contains(true)
        assertThat(ipConnection.dtmfType()).contains(DtmfType.RFC_2833)
        assertThat(ipConnection.encodeContactHeaderEnabled()).contains(true)
        assertThat(ipConnection.encryptedMedia()).contains(EncryptedMedia.SRTP)
        assertThat(ipConnection.inbound())
            .contains(
                InboundIp.builder()
                    .aniNumberFormat(InboundIp.AniNumberFormat.PLUS_E_164)
                    .channelLimit(10L)
                    .addCodec("G722")
                    .defaultPrimaryIpId("192.0.2.1")
                    .defaultRoutingMethod(InboundIp.DefaultRoutingMethod.SEQUENTIAL)
                    .defaultSecondaryIpId("198.51.100.1")
                    .defaultTertiaryIpId("203.0.113.1")
                    .dnisNumberFormat(InboundIp.DnisNumberFormat.PLUS_E164)
                    .generateRingbackTone(true)
                    .isupHeadersEnabled(true)
                    .prackEnabled(true)
                    .shakenStirEnabled(true)
                    .sipCompactHeadersEnabled(true)
                    .sipRegion(InboundIp.SipRegion.US)
                    .sipSubdomain("string")
                    .sipSubdomainReceiveSettings(
                        InboundIp.SipSubdomainReceiveSettings.ONLY_MY_CONNECTIONS
                    )
                    .timeout1xxSecs(10L)
                    .timeout2xxSecs(10L)
                    .build()
            )
        assertThat(ipConnection.iosPushCredentialId())
            .contains("ec0c8e5d-439e-4620-a0c1-9d9c8d02a836")
        assertThat(ipConnection.jitterBuffer())
            .contains(
                ConnectionJitterBuffer.builder()
                    .enableJitterBuffer(true)
                    .jitterbufferMsecMax(200L)
                    .jitterbufferMsecMin(60L)
                    .build()
            )
        assertThat(ipConnection.noiseSuppression()).contains(IpConnection.NoiseSuppression.BOTH)
        assertThat(ipConnection.noiseSuppressionDetails())
            .contains(
                ConnectionNoiseSuppressionDetails.builder()
                    .attenuationLimit(80L)
                    .engine(ConnectionNoiseSuppressionDetails.Engine.DEEP_FILTER_NET)
                    .build()
            )
        assertThat(ipConnection.onnetT38PassthroughEnabled()).contains(true)
        assertThat(ipConnection.outbound())
            .contains(
                OutboundIp.builder()
                    .aniOverride("string")
                    .aniOverrideType(OutboundIp.AniOverrideType.ALWAYS)
                    .callParkingEnabled(true)
                    .channelLimit(10L)
                    .generateRingbackTone(true)
                    .instantRingbackEnabled(true)
                    .ipAuthenticationMethod(OutboundIp.IpAuthenticationMethod.TOKEN)
                    .ipAuthenticationToken("string")
                    .localization("string")
                    .outboundVoiceProfileId("outbound_voice_profile_id")
                    .t38ReinviteSource(OutboundIp.T38ReinviteSource.CUSTOMER)
                    .techPrefix("string")
                    .build()
            )
        assertThat(ipConnection.recordType()).contains("ip_connection")
        assertThat(ipConnection.rtcpSettings())
            .contains(
                ConnectionRtcpSettings.builder()
                    .captureEnabled(true)
                    .port(ConnectionRtcpSettings.Port.RTCP_MUX)
                    .reportFrequencySecs(10L)
                    .build()
            )
        assertThat(ipConnection.tags().getOrNull()).containsExactly("tag1", "tag2")
        assertThat(ipConnection.transportProtocol()).contains(IpConnection.TransportProtocol.UDP)
        assertThat(ipConnection.updatedAt()).contains("2018-02-02T22:25:27.521Z")
        assertThat(ipConnection.webhookApiVersion()).contains(IpConnection.WebhookApiVersion.V1)
        assertThat(ipConnection.webhookEventFailoverUrl()).contains("https://failover.example.com")
        assertThat(ipConnection.webhookEventUrl()).contains("https://example.com")
        assertThat(ipConnection.webhookTimeoutSecs()).contains(25L)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val ipConnection =
            IpConnection.builder()
                .id("id")
                .active(true)
                .anchorsiteOverride(AnchorsiteOverride.LATENCY)
                .androidPushCredentialId("06b09dfd-7154-4980-8b75-cebf7a9d4f8e")
                .callCostInWebhooks(true)
                .connectionName("string")
                .createdAt("2018-02-02T22:25:27.521Z")
                .defaultOnHoldComfortNoiseEnabled(true)
                .dtmfType(DtmfType.RFC_2833)
                .encodeContactHeaderEnabled(true)
                .encryptedMedia(EncryptedMedia.SRTP)
                .inbound(
                    InboundIp.builder()
                        .aniNumberFormat(InboundIp.AniNumberFormat.PLUS_E_164)
                        .channelLimit(10L)
                        .addCodec("G722")
                        .defaultPrimaryIpId("192.0.2.1")
                        .defaultRoutingMethod(InboundIp.DefaultRoutingMethod.SEQUENTIAL)
                        .defaultSecondaryIpId("198.51.100.1")
                        .defaultTertiaryIpId("203.0.113.1")
                        .dnisNumberFormat(InboundIp.DnisNumberFormat.PLUS_E164)
                        .generateRingbackTone(true)
                        .isupHeadersEnabled(true)
                        .prackEnabled(true)
                        .shakenStirEnabled(true)
                        .sipCompactHeadersEnabled(true)
                        .sipRegion(InboundIp.SipRegion.US)
                        .sipSubdomain("string")
                        .sipSubdomainReceiveSettings(
                            InboundIp.SipSubdomainReceiveSettings.ONLY_MY_CONNECTIONS
                        )
                        .timeout1xxSecs(10L)
                        .timeout2xxSecs(10L)
                        .build()
                )
                .iosPushCredentialId("ec0c8e5d-439e-4620-a0c1-9d9c8d02a836")
                .jitterBuffer(
                    ConnectionJitterBuffer.builder()
                        .enableJitterBuffer(true)
                        .jitterbufferMsecMax(200L)
                        .jitterbufferMsecMin(60L)
                        .build()
                )
                .noiseSuppression(IpConnection.NoiseSuppression.BOTH)
                .noiseSuppressionDetails(
                    ConnectionNoiseSuppressionDetails.builder()
                        .attenuationLimit(80L)
                        .engine(ConnectionNoiseSuppressionDetails.Engine.DEEP_FILTER_NET)
                        .build()
                )
                .onnetT38PassthroughEnabled(true)
                .outbound(
                    OutboundIp.builder()
                        .aniOverride("string")
                        .aniOverrideType(OutboundIp.AniOverrideType.ALWAYS)
                        .callParkingEnabled(true)
                        .channelLimit(10L)
                        .generateRingbackTone(true)
                        .instantRingbackEnabled(true)
                        .ipAuthenticationMethod(OutboundIp.IpAuthenticationMethod.TOKEN)
                        .ipAuthenticationToken("string")
                        .localization("string")
                        .outboundVoiceProfileId("outbound_voice_profile_id")
                        .t38ReinviteSource(OutboundIp.T38ReinviteSource.CUSTOMER)
                        .techPrefix("string")
                        .build()
                )
                .recordType("ip_connection")
                .rtcpSettings(
                    ConnectionRtcpSettings.builder()
                        .captureEnabled(true)
                        .port(ConnectionRtcpSettings.Port.RTCP_MUX)
                        .reportFrequencySecs(10L)
                        .build()
                )
                .addTag("tag1")
                .addTag("tag2")
                .transportProtocol(IpConnection.TransportProtocol.UDP)
                .updatedAt("2018-02-02T22:25:27.521Z")
                .webhookApiVersion(IpConnection.WebhookApiVersion.V1)
                .webhookEventFailoverUrl("https://failover.example.com")
                .webhookEventUrl("https://example.com")
                .webhookTimeoutSecs(25L)
                .build()

        val roundtrippedIpConnection =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(ipConnection),
                jacksonTypeRef<IpConnection>(),
            )

        assertThat(roundtrippedIpConnection).isEqualTo(ipConnection)
    }
}
