// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.enterprises

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class EnterpriseCreateParamsTest {

    @Test
    fun create() {
        EnterpriseCreateParams.builder()
            .billingAddress(
                BillingAddress.builder()
                    .administrativeArea("IL")
                    .city("Chicago")
                    .country("US")
                    .postalCode("60601")
                    .streetAddress("100 Main St")
                    .extendedAddress("Suite 504")
                    .build()
            )
            .billingContact(
                BillingContact.builder()
                    .email("billing@run065.example.com")
                    .firstName("Alex")
                    .lastName("Bill")
                    .phoneNumber("+13125550001")
                    .build()
            )
            .countryCode("US")
            .doingBusinessAs("Run 065 Debug")
            .fein("12-3456789")
            .industry(EnterpriseCreateParams.Industry.TECHNOLOGY)
            .jurisdictionOfIncorporation("Delaware")
            .legalName("Run 065 Debug Co")
            .numberOfEmployees(EnterpriseCreateParams.NumberOfEmployees.NUMBER_OF_EMPLOYEES_51_200)
            .organizationContact(
                OrganizationContact.builder()
                    .email("org@run065.example.com")
                    .firstName("Sam")
                    .jobTitle("Compliance Lead")
                    .lastName("Org")
                    .phoneNumber("+13125550000")
                    .build()
            )
            .organizationLegalType(EnterpriseCreateParams.OrganizationLegalType.LLC)
            .organizationPhysicalAddress(
                PhysicalAddress.builder()
                    .administrativeArea("IL")
                    .city("Chicago")
                    .country("US")
                    .postalCode("60601")
                    .streetAddress("100 Main St")
                    .extendedAddress("Suite 504")
                    .build()
            )
            .organizationType(EnterpriseCreateParams.OrganizationType.COMMERCIAL)
            .website("https://run065.example.com")
            .corporateRegistrationNumber("corporate_registration_number")
            .customerReference("internal-id-12345")
            .dunBradstreetNumber("dun_bradstreet_number")
            .primaryBusinessDomainSicCode("primary_business_domain_sic_code")
            .professionalLicenseNumber("professional_license_number")
            .roleType(EnterpriseCreateParams.RoleType.ENTERPRISE)
            .build()
    }

    @Test
    fun body() {
        val params =
            EnterpriseCreateParams.builder()
                .billingAddress(
                    BillingAddress.builder()
                        .administrativeArea("IL")
                        .city("Chicago")
                        .country("US")
                        .postalCode("60601")
                        .streetAddress("100 Main St")
                        .extendedAddress("Suite 504")
                        .build()
                )
                .billingContact(
                    BillingContact.builder()
                        .email("billing@run065.example.com")
                        .firstName("Alex")
                        .lastName("Bill")
                        .phoneNumber("+13125550001")
                        .build()
                )
                .countryCode("US")
                .doingBusinessAs("Run 065 Debug")
                .fein("12-3456789")
                .industry(EnterpriseCreateParams.Industry.TECHNOLOGY)
                .jurisdictionOfIncorporation("Delaware")
                .legalName("Run 065 Debug Co")
                .numberOfEmployees(
                    EnterpriseCreateParams.NumberOfEmployees.NUMBER_OF_EMPLOYEES_51_200
                )
                .organizationContact(
                    OrganizationContact.builder()
                        .email("org@run065.example.com")
                        .firstName("Sam")
                        .jobTitle("Compliance Lead")
                        .lastName("Org")
                        .phoneNumber("+13125550000")
                        .build()
                )
                .organizationLegalType(EnterpriseCreateParams.OrganizationLegalType.LLC)
                .organizationPhysicalAddress(
                    PhysicalAddress.builder()
                        .administrativeArea("IL")
                        .city("Chicago")
                        .country("US")
                        .postalCode("60601")
                        .streetAddress("100 Main St")
                        .extendedAddress("Suite 504")
                        .build()
                )
                .organizationType(EnterpriseCreateParams.OrganizationType.COMMERCIAL)
                .website("https://run065.example.com")
                .corporateRegistrationNumber("corporate_registration_number")
                .customerReference("internal-id-12345")
                .dunBradstreetNumber("dun_bradstreet_number")
                .primaryBusinessDomainSicCode("primary_business_domain_sic_code")
                .professionalLicenseNumber("professional_license_number")
                .roleType(EnterpriseCreateParams.RoleType.ENTERPRISE)
                .build()

        val body = params._body()

        assertThat(body.billingAddress())
            .isEqualTo(
                BillingAddress.builder()
                    .administrativeArea("IL")
                    .city("Chicago")
                    .country("US")
                    .postalCode("60601")
                    .streetAddress("100 Main St")
                    .extendedAddress("Suite 504")
                    .build()
            )
        assertThat(body.billingContact())
            .isEqualTo(
                BillingContact.builder()
                    .email("billing@run065.example.com")
                    .firstName("Alex")
                    .lastName("Bill")
                    .phoneNumber("+13125550001")
                    .build()
            )
        assertThat(body.countryCode()).isEqualTo("US")
        assertThat(body.doingBusinessAs()).isEqualTo("Run 065 Debug")
        assertThat(body.fein()).isEqualTo("12-3456789")
        assertThat(body.industry()).isEqualTo(EnterpriseCreateParams.Industry.TECHNOLOGY)
        assertThat(body.jurisdictionOfIncorporation()).isEqualTo("Delaware")
        assertThat(body.legalName()).isEqualTo("Run 065 Debug Co")
        assertThat(body.numberOfEmployees())
            .isEqualTo(EnterpriseCreateParams.NumberOfEmployees.NUMBER_OF_EMPLOYEES_51_200)
        assertThat(body.organizationContact())
            .isEqualTo(
                OrganizationContact.builder()
                    .email("org@run065.example.com")
                    .firstName("Sam")
                    .jobTitle("Compliance Lead")
                    .lastName("Org")
                    .phoneNumber("+13125550000")
                    .build()
            )
        assertThat(body.organizationLegalType())
            .isEqualTo(EnterpriseCreateParams.OrganizationLegalType.LLC)
        assertThat(body.organizationPhysicalAddress())
            .isEqualTo(
                PhysicalAddress.builder()
                    .administrativeArea("IL")
                    .city("Chicago")
                    .country("US")
                    .postalCode("60601")
                    .streetAddress("100 Main St")
                    .extendedAddress("Suite 504")
                    .build()
            )
        assertThat(body.organizationType())
            .isEqualTo(EnterpriseCreateParams.OrganizationType.COMMERCIAL)
        assertThat(body.website()).isEqualTo("https://run065.example.com")
        assertThat(body.corporateRegistrationNumber()).contains("corporate_registration_number")
        assertThat(body.customerReference()).contains("internal-id-12345")
        assertThat(body.dunBradstreetNumber()).contains("dun_bradstreet_number")
        assertThat(body.primaryBusinessDomainSicCode()).contains("primary_business_domain_sic_code")
        assertThat(body.professionalLicenseNumber()).contains("professional_license_number")
        assertThat(body.roleType()).contains(EnterpriseCreateParams.RoleType.ENTERPRISE)
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            EnterpriseCreateParams.builder()
                .billingAddress(
                    BillingAddress.builder()
                        .administrativeArea("IL")
                        .city("Chicago")
                        .country("US")
                        .postalCode("60601")
                        .streetAddress("100 Main St")
                        .build()
                )
                .billingContact(
                    BillingContact.builder()
                        .email("billing@run065.example.com")
                        .firstName("Alex")
                        .lastName("Bill")
                        .phoneNumber("+13125550001")
                        .build()
                )
                .countryCode("US")
                .doingBusinessAs("Run 065 Debug")
                .fein("12-3456789")
                .industry(EnterpriseCreateParams.Industry.TECHNOLOGY)
                .jurisdictionOfIncorporation("Delaware")
                .legalName("Run 065 Debug Co")
                .numberOfEmployees(
                    EnterpriseCreateParams.NumberOfEmployees.NUMBER_OF_EMPLOYEES_51_200
                )
                .organizationContact(
                    OrganizationContact.builder()
                        .email("org@run065.example.com")
                        .firstName("Sam")
                        .jobTitle("Compliance Lead")
                        .lastName("Org")
                        .phoneNumber("+13125550000")
                        .build()
                )
                .organizationLegalType(EnterpriseCreateParams.OrganizationLegalType.LLC)
                .organizationPhysicalAddress(
                    PhysicalAddress.builder()
                        .administrativeArea("IL")
                        .city("Chicago")
                        .country("US")
                        .postalCode("60601")
                        .streetAddress("100 Main St")
                        .build()
                )
                .organizationType(EnterpriseCreateParams.OrganizationType.COMMERCIAL)
                .website("https://run065.example.com")
                .build()

        val body = params._body()

        assertThat(body.billingAddress())
            .isEqualTo(
                BillingAddress.builder()
                    .administrativeArea("IL")
                    .city("Chicago")
                    .country("US")
                    .postalCode("60601")
                    .streetAddress("100 Main St")
                    .build()
            )
        assertThat(body.billingContact())
            .isEqualTo(
                BillingContact.builder()
                    .email("billing@run065.example.com")
                    .firstName("Alex")
                    .lastName("Bill")
                    .phoneNumber("+13125550001")
                    .build()
            )
        assertThat(body.countryCode()).isEqualTo("US")
        assertThat(body.doingBusinessAs()).isEqualTo("Run 065 Debug")
        assertThat(body.fein()).isEqualTo("12-3456789")
        assertThat(body.industry()).isEqualTo(EnterpriseCreateParams.Industry.TECHNOLOGY)
        assertThat(body.jurisdictionOfIncorporation()).isEqualTo("Delaware")
        assertThat(body.legalName()).isEqualTo("Run 065 Debug Co")
        assertThat(body.numberOfEmployees())
            .isEqualTo(EnterpriseCreateParams.NumberOfEmployees.NUMBER_OF_EMPLOYEES_51_200)
        assertThat(body.organizationContact())
            .isEqualTo(
                OrganizationContact.builder()
                    .email("org@run065.example.com")
                    .firstName("Sam")
                    .jobTitle("Compliance Lead")
                    .lastName("Org")
                    .phoneNumber("+13125550000")
                    .build()
            )
        assertThat(body.organizationLegalType())
            .isEqualTo(EnterpriseCreateParams.OrganizationLegalType.LLC)
        assertThat(body.organizationPhysicalAddress())
            .isEqualTo(
                PhysicalAddress.builder()
                    .administrativeArea("IL")
                    .city("Chicago")
                    .country("US")
                    .postalCode("60601")
                    .streetAddress("100 Main St")
                    .build()
            )
        assertThat(body.organizationType())
            .isEqualTo(EnterpriseCreateParams.OrganizationType.COMMERCIAL)
        assertThat(body.website()).isEqualTo("https://run065.example.com")
    }
}
