// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.enterprises

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class EnterpriseListResponseTest {

    @Test
    fun create() {
        val enterpriseListResponse =
            EnterpriseListResponse.builder()
                .id("6a09cdc3-8948-47f0-aa62-74ac943d6c58")
                .billingAddress(
                    EnterpriseListResponse.BillingAddress.builder()
                        .administrativeArea("Illinois")
                        .city("Chicago")
                        .country("United States")
                        .postalCode("60601")
                        .streetAddress("123 Main St")
                        .extendedAddress("Suite 400")
                        .build()
                )
                .billingContact(
                    EnterpriseListResponse.BillingContact.builder()
                        .email("billing@acme.com")
                        .firstName("John")
                        .lastName("Doe")
                        .phoneNumber("15551234568")
                        .build()
                )
                .corporateRegistrationNumber("corporate_registration_number")
                .countryCode("US")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .customerReference("customer_reference")
                .doingBusinessAs("Acme")
                .dunBradstreetNumber("dun_bradstreet_number")
                .fein("fein")
                .industry("industry")
                .legalName("Acme Corp Inc.")
                .numberOfEmployees(EnterpriseListResponse.NumberOfEmployees._1_10)
                .organizationContact(
                    EnterpriseListResponse.OrganizationContact.builder()
                        .email("jane.smith@acme.com")
                        .firstName("Jane")
                        .jobTitle("VP of Engineering")
                        .lastName("Smith")
                        .phone("+16035551234")
                        .build()
                )
                .organizationLegalType(EnterpriseListResponse.OrganizationLegalType.CORPORATION)
                .organizationPhysicalAddress(
                    EnterpriseListResponse.OrganizationPhysicalAddress.builder()
                        .administrativeArea("Illinois")
                        .city("Chicago")
                        .country("United States")
                        .postalCode("60601")
                        .streetAddress("123 Main St")
                        .extendedAddress("Suite 400")
                        .build()
                )
                .organizationType(EnterpriseListResponse.OrganizationType.COMMERCIAL)
                .primaryBusinessDomainSicCode("primary_business_domain_sic_code")
                .professionalLicenseNumber("professional_license_number")
                .roleType(EnterpriseListResponse.RoleType.ENTERPRISE)
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .website("website")
                .build()

        assertThat(enterpriseListResponse.id()).contains("6a09cdc3-8948-47f0-aa62-74ac943d6c58")
        assertThat(enterpriseListResponse.billingAddress())
            .contains(
                EnterpriseListResponse.BillingAddress.builder()
                    .administrativeArea("Illinois")
                    .city("Chicago")
                    .country("United States")
                    .postalCode("60601")
                    .streetAddress("123 Main St")
                    .extendedAddress("Suite 400")
                    .build()
            )
        assertThat(enterpriseListResponse.billingContact())
            .contains(
                EnterpriseListResponse.BillingContact.builder()
                    .email("billing@acme.com")
                    .firstName("John")
                    .lastName("Doe")
                    .phoneNumber("15551234568")
                    .build()
            )
        assertThat(enterpriseListResponse.corporateRegistrationNumber())
            .contains("corporate_registration_number")
        assertThat(enterpriseListResponse.countryCode()).contains("US")
        assertThat(enterpriseListResponse.createdAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(enterpriseListResponse.customerReference()).contains("customer_reference")
        assertThat(enterpriseListResponse.doingBusinessAs()).contains("Acme")
        assertThat(enterpriseListResponse.dunBradstreetNumber()).contains("dun_bradstreet_number")
        assertThat(enterpriseListResponse.fein()).contains("fein")
        assertThat(enterpriseListResponse.industry()).contains("industry")
        assertThat(enterpriseListResponse.legalName()).contains("Acme Corp Inc.")
        assertThat(enterpriseListResponse.numberOfEmployees())
            .contains(EnterpriseListResponse.NumberOfEmployees._1_10)
        assertThat(enterpriseListResponse.organizationContact())
            .contains(
                EnterpriseListResponse.OrganizationContact.builder()
                    .email("jane.smith@acme.com")
                    .firstName("Jane")
                    .jobTitle("VP of Engineering")
                    .lastName("Smith")
                    .phone("+16035551234")
                    .build()
            )
        assertThat(enterpriseListResponse.organizationLegalType())
            .contains(EnterpriseListResponse.OrganizationLegalType.CORPORATION)
        assertThat(enterpriseListResponse.organizationPhysicalAddress())
            .contains(
                EnterpriseListResponse.OrganizationPhysicalAddress.builder()
                    .administrativeArea("Illinois")
                    .city("Chicago")
                    .country("United States")
                    .postalCode("60601")
                    .streetAddress("123 Main St")
                    .extendedAddress("Suite 400")
                    .build()
            )
        assertThat(enterpriseListResponse.organizationType())
            .contains(EnterpriseListResponse.OrganizationType.COMMERCIAL)
        assertThat(enterpriseListResponse.primaryBusinessDomainSicCode())
            .contains("primary_business_domain_sic_code")
        assertThat(enterpriseListResponse.professionalLicenseNumber())
            .contains("professional_license_number")
        assertThat(enterpriseListResponse.roleType())
            .contains(EnterpriseListResponse.RoleType.ENTERPRISE)
        assertThat(enterpriseListResponse.updatedAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(enterpriseListResponse.website()).contains("website")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val enterpriseListResponse =
            EnterpriseListResponse.builder()
                .id("6a09cdc3-8948-47f0-aa62-74ac943d6c58")
                .billingAddress(
                    EnterpriseListResponse.BillingAddress.builder()
                        .administrativeArea("Illinois")
                        .city("Chicago")
                        .country("United States")
                        .postalCode("60601")
                        .streetAddress("123 Main St")
                        .extendedAddress("Suite 400")
                        .build()
                )
                .billingContact(
                    EnterpriseListResponse.BillingContact.builder()
                        .email("billing@acme.com")
                        .firstName("John")
                        .lastName("Doe")
                        .phoneNumber("15551234568")
                        .build()
                )
                .corporateRegistrationNumber("corporate_registration_number")
                .countryCode("US")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .customerReference("customer_reference")
                .doingBusinessAs("Acme")
                .dunBradstreetNumber("dun_bradstreet_number")
                .fein("fein")
                .industry("industry")
                .legalName("Acme Corp Inc.")
                .numberOfEmployees(EnterpriseListResponse.NumberOfEmployees._1_10)
                .organizationContact(
                    EnterpriseListResponse.OrganizationContact.builder()
                        .email("jane.smith@acme.com")
                        .firstName("Jane")
                        .jobTitle("VP of Engineering")
                        .lastName("Smith")
                        .phone("+16035551234")
                        .build()
                )
                .organizationLegalType(EnterpriseListResponse.OrganizationLegalType.CORPORATION)
                .organizationPhysicalAddress(
                    EnterpriseListResponse.OrganizationPhysicalAddress.builder()
                        .administrativeArea("Illinois")
                        .city("Chicago")
                        .country("United States")
                        .postalCode("60601")
                        .streetAddress("123 Main St")
                        .extendedAddress("Suite 400")
                        .build()
                )
                .organizationType(EnterpriseListResponse.OrganizationType.COMMERCIAL)
                .primaryBusinessDomainSicCode("primary_business_domain_sic_code")
                .professionalLicenseNumber("professional_license_number")
                .roleType(EnterpriseListResponse.RoleType.ENTERPRISE)
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .website("website")
                .build()

        val roundtrippedEnterpriseListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(enterpriseListResponse),
                jacksonTypeRef<EnterpriseListResponse>(),
            )

        assertThat(roundtrippedEnterpriseListResponse).isEqualTo(enterpriseListResponse)
    }
}
