// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.enterprises

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class EnterpriseCreateParamsTest {

    @Test
    fun create() {
        EnterpriseCreateParams.builder()
            .billingAddress(
                BillingAddress.builder()
                    .administrativeArea("Illinois")
                    .city("Chicago")
                    .country("United States")
                    .postalCode("60601")
                    .streetAddress("123 Main St")
                    .extendedAddress("Suite 400")
                    .build()
            )
            .billingContact(
                BillingContact.builder()
                    .email("billing@acme.com")
                    .firstName("John")
                    .lastName("Doe")
                    .phoneNumber("15551234568")
                    .build()
            )
            .countryCode("US")
            .doingBusinessAs("Acme")
            .fein("12-3456789")
            .industry("technology")
            .legalName("Acme Corp Inc.")
            .numberOfEmployees(EnterpriseCreateParams.NumberOfEmployees.NUMBER_OF_EMPLOYEES_51_200)
            .organizationContact(
                OrganizationContact.builder()
                    .email("jane.smith@acme.com")
                    .firstName("Jane")
                    .jobTitle("VP of Engineering")
                    .lastName("Smith")
                    .phone("+16035551234")
                    .build()
            )
            .organizationLegalType(EnterpriseCreateParams.OrganizationLegalType.CORPORATION)
            .organizationPhysicalAddress(
                PhysicalAddress.builder()
                    .administrativeArea("Illinois")
                    .city("Chicago")
                    .country("United States")
                    .postalCode("60601")
                    .streetAddress("123 Main St")
                    .extendedAddress("Suite 400")
                    .build()
            )
            .organizationType(EnterpriseCreateParams.OrganizationType.COMMERCIAL)
            .website("https://acme.com")
            .corporateRegistrationNumber("corporate_registration_number")
            .customerReference("customer_reference")
            .dunBradstreetNumber("dun_bradstreet_number")
            .primaryBusinessDomainSicCode("7372")
            .professionalLicenseNumber("professional_license_number")
            .roleType(EnterpriseCreateParams.RoleType.ENTERPRISE)
            .build()
    }

    @Test
    fun body() {
        val params =
            EnterpriseCreateParams.builder()
                .billingAddress(
                    BillingAddress.builder()
                        .administrativeArea("Illinois")
                        .city("Chicago")
                        .country("United States")
                        .postalCode("60601")
                        .streetAddress("123 Main St")
                        .extendedAddress("Suite 400")
                        .build()
                )
                .billingContact(
                    BillingContact.builder()
                        .email("billing@acme.com")
                        .firstName("John")
                        .lastName("Doe")
                        .phoneNumber("15551234568")
                        .build()
                )
                .countryCode("US")
                .doingBusinessAs("Acme")
                .fein("12-3456789")
                .industry("technology")
                .legalName("Acme Corp Inc.")
                .numberOfEmployees(
                    EnterpriseCreateParams.NumberOfEmployees.NUMBER_OF_EMPLOYEES_51_200
                )
                .organizationContact(
                    OrganizationContact.builder()
                        .email("jane.smith@acme.com")
                        .firstName("Jane")
                        .jobTitle("VP of Engineering")
                        .lastName("Smith")
                        .phone("+16035551234")
                        .build()
                )
                .organizationLegalType(EnterpriseCreateParams.OrganizationLegalType.CORPORATION)
                .organizationPhysicalAddress(
                    PhysicalAddress.builder()
                        .administrativeArea("Illinois")
                        .city("Chicago")
                        .country("United States")
                        .postalCode("60601")
                        .streetAddress("123 Main St")
                        .extendedAddress("Suite 400")
                        .build()
                )
                .organizationType(EnterpriseCreateParams.OrganizationType.COMMERCIAL)
                .website("https://acme.com")
                .corporateRegistrationNumber("corporate_registration_number")
                .customerReference("customer_reference")
                .dunBradstreetNumber("dun_bradstreet_number")
                .primaryBusinessDomainSicCode("7372")
                .professionalLicenseNumber("professional_license_number")
                .roleType(EnterpriseCreateParams.RoleType.ENTERPRISE)
                .build()

        val body = params._body()

        assertThat(body.billingAddress())
            .isEqualTo(
                BillingAddress.builder()
                    .administrativeArea("Illinois")
                    .city("Chicago")
                    .country("United States")
                    .postalCode("60601")
                    .streetAddress("123 Main St")
                    .extendedAddress("Suite 400")
                    .build()
            )
        assertThat(body.billingContact())
            .isEqualTo(
                BillingContact.builder()
                    .email("billing@acme.com")
                    .firstName("John")
                    .lastName("Doe")
                    .phoneNumber("15551234568")
                    .build()
            )
        assertThat(body.countryCode()).isEqualTo("US")
        assertThat(body.doingBusinessAs()).isEqualTo("Acme")
        assertThat(body.fein()).isEqualTo("12-3456789")
        assertThat(body.industry()).isEqualTo("technology")
        assertThat(body.legalName()).isEqualTo("Acme Corp Inc.")
        assertThat(body.numberOfEmployees())
            .isEqualTo(EnterpriseCreateParams.NumberOfEmployees.NUMBER_OF_EMPLOYEES_51_200)
        assertThat(body.organizationContact())
            .isEqualTo(
                OrganizationContact.builder()
                    .email("jane.smith@acme.com")
                    .firstName("Jane")
                    .jobTitle("VP of Engineering")
                    .lastName("Smith")
                    .phone("+16035551234")
                    .build()
            )
        assertThat(body.organizationLegalType())
            .isEqualTo(EnterpriseCreateParams.OrganizationLegalType.CORPORATION)
        assertThat(body.organizationPhysicalAddress())
            .isEqualTo(
                PhysicalAddress.builder()
                    .administrativeArea("Illinois")
                    .city("Chicago")
                    .country("United States")
                    .postalCode("60601")
                    .streetAddress("123 Main St")
                    .extendedAddress("Suite 400")
                    .build()
            )
        assertThat(body.organizationType())
            .isEqualTo(EnterpriseCreateParams.OrganizationType.COMMERCIAL)
        assertThat(body.website()).isEqualTo("https://acme.com")
        assertThat(body.corporateRegistrationNumber()).contains("corporate_registration_number")
        assertThat(body.customerReference()).contains("customer_reference")
        assertThat(body.dunBradstreetNumber()).contains("dun_bradstreet_number")
        assertThat(body.primaryBusinessDomainSicCode()).contains("7372")
        assertThat(body.professionalLicenseNumber()).contains("professional_license_number")
        assertThat(body.roleType()).contains(EnterpriseCreateParams.RoleType.ENTERPRISE)
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            EnterpriseCreateParams.builder()
                .billingAddress(
                    BillingAddress.builder()
                        .administrativeArea("Illinois")
                        .city("Chicago")
                        .country("United States")
                        .postalCode("60601")
                        .streetAddress("123 Main St")
                        .build()
                )
                .billingContact(
                    BillingContact.builder()
                        .email("billing@acme.com")
                        .firstName("John")
                        .lastName("Doe")
                        .phoneNumber("15551234568")
                        .build()
                )
                .countryCode("US")
                .doingBusinessAs("Acme")
                .fein("12-3456789")
                .industry("technology")
                .legalName("Acme Corp Inc.")
                .numberOfEmployees(
                    EnterpriseCreateParams.NumberOfEmployees.NUMBER_OF_EMPLOYEES_51_200
                )
                .organizationContact(
                    OrganizationContact.builder()
                        .email("jane.smith@acme.com")
                        .firstName("Jane")
                        .jobTitle("VP of Engineering")
                        .lastName("Smith")
                        .phone("+16035551234")
                        .build()
                )
                .organizationLegalType(EnterpriseCreateParams.OrganizationLegalType.CORPORATION)
                .organizationPhysicalAddress(
                    PhysicalAddress.builder()
                        .administrativeArea("Illinois")
                        .city("Chicago")
                        .country("United States")
                        .postalCode("60601")
                        .streetAddress("123 Main St")
                        .build()
                )
                .organizationType(EnterpriseCreateParams.OrganizationType.COMMERCIAL)
                .website("https://acme.com")
                .build()

        val body = params._body()

        assertThat(body.billingAddress())
            .isEqualTo(
                BillingAddress.builder()
                    .administrativeArea("Illinois")
                    .city("Chicago")
                    .country("United States")
                    .postalCode("60601")
                    .streetAddress("123 Main St")
                    .build()
            )
        assertThat(body.billingContact())
            .isEqualTo(
                BillingContact.builder()
                    .email("billing@acme.com")
                    .firstName("John")
                    .lastName("Doe")
                    .phoneNumber("15551234568")
                    .build()
            )
        assertThat(body.countryCode()).isEqualTo("US")
        assertThat(body.doingBusinessAs()).isEqualTo("Acme")
        assertThat(body.fein()).isEqualTo("12-3456789")
        assertThat(body.industry()).isEqualTo("technology")
        assertThat(body.legalName()).isEqualTo("Acme Corp Inc.")
        assertThat(body.numberOfEmployees())
            .isEqualTo(EnterpriseCreateParams.NumberOfEmployees.NUMBER_OF_EMPLOYEES_51_200)
        assertThat(body.organizationContact())
            .isEqualTo(
                OrganizationContact.builder()
                    .email("jane.smith@acme.com")
                    .firstName("Jane")
                    .jobTitle("VP of Engineering")
                    .lastName("Smith")
                    .phone("+16035551234")
                    .build()
            )
        assertThat(body.organizationLegalType())
            .isEqualTo(EnterpriseCreateParams.OrganizationLegalType.CORPORATION)
        assertThat(body.organizationPhysicalAddress())
            .isEqualTo(
                PhysicalAddress.builder()
                    .administrativeArea("Illinois")
                    .city("Chicago")
                    .country("United States")
                    .postalCode("60601")
                    .streetAddress("123 Main St")
                    .build()
            )
        assertThat(body.organizationType())
            .isEqualTo(EnterpriseCreateParams.OrganizationType.COMMERCIAL)
        assertThat(body.website()).isEqualTo("https://acme.com")
    }
}
