// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.services.blocking

import com.telnyx.sdk.TestServerExtension
import com.telnyx.sdk.client.okhttp.TelnyxOkHttpClient
import com.telnyx.sdk.core.JsonValue
import com.telnyx.sdk.models.messsages.MesssageRcsParams
import com.telnyx.sdk.models.messsages.MesssageWhatsappParams
import com.telnyx.sdk.models.messsages.RcsAgentMessage
import com.telnyx.sdk.models.messsages.RcsCardContent
import com.telnyx.sdk.models.messsages.RcsContentInfo
import com.telnyx.sdk.models.messsages.RcsSuggestion
import com.telnyx.sdk.models.messsages.WhatsappMedia
import java.time.OffsetDateTime
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith

@ExtendWith(TestServerExtension::class)
internal class MesssageServiceTest {

    @Disabled("Prism tests are disabled")
    @Test
    fun rcs() {
        val client =
            TelnyxOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .apiKey("My API Key")
                .build()
        val messsageService = client.messsages()

        val response =
            messsageService.rcs(
                MesssageRcsParams.builder()
                    .agentId("Agent007")
                    .agentMessage(
                        RcsAgentMessage.builder()
                            .contentMessage(
                                RcsAgentMessage.ContentMessage.builder()
                                    .contentInfo(
                                        RcsContentInfo.builder()
                                            .fileUrl("https://example.com/elephant.jpg")
                                            .forceRefresh(true)
                                            .thumbnailUrl("thumbnail_url")
                                            .build()
                                    )
                                    .richCard(
                                        RcsAgentMessage.ContentMessage.RichCard.builder()
                                            .carouselCard(
                                                RcsAgentMessage.ContentMessage.RichCard.CarouselCard
                                                    .builder()
                                                    .addCardContent(
                                                        RcsCardContent.builder()
                                                            .description("description")
                                                            .media(
                                                                RcsCardContent.Media.builder()
                                                                    .contentInfo(
                                                                        RcsContentInfo.builder()
                                                                            .fileUrl(
                                                                                "https://example.com/elephant.jpg"
                                                                            )
                                                                            .forceRefresh(true)
                                                                            .thumbnailUrl(
                                                                                "thumbnail_url"
                                                                            )
                                                                            .build()
                                                                    )
                                                                    .height(
                                                                        RcsCardContent.Media.Height
                                                                            .MEDIUM
                                                                    )
                                                                    .build()
                                                            )
                                                            .addSuggestion(
                                                                RcsSuggestion.builder()
                                                                    .action(
                                                                        RcsSuggestion.Action
                                                                            .builder()
                                                                            .createCalendarEventAction(
                                                                                RcsSuggestion.Action
                                                                                    .CreateCalendarEventAction
                                                                                    .builder()
                                                                                    .description(
                                                                                        "description"
                                                                                    )
                                                                                    .endTime(
                                                                                        OffsetDateTime
                                                                                            .parse(
                                                                                                "2024-10-02T15:02:31Z"
                                                                                            )
                                                                                    )
                                                                                    .startTime(
                                                                                        OffsetDateTime
                                                                                            .parse(
                                                                                                "2024-10-02T15:01:23Z"
                                                                                            )
                                                                                    )
                                                                                    .title("title")
                                                                                    .build()
                                                                            )
                                                                            .dialAction(
                                                                                RcsSuggestion.Action
                                                                                    .DialAction
                                                                                    .builder()
                                                                                    .phoneNumber(
                                                                                        "+13125551234"
                                                                                    )
                                                                                    .build()
                                                                            )
                                                                            .fallbackUrl(
                                                                                "fallback_url"
                                                                            )
                                                                            .openUrlAction(
                                                                                RcsSuggestion.Action
                                                                                    .OpenUrlAction
                                                                                    .builder()
                                                                                    .application(
                                                                                        RcsSuggestion
                                                                                            .Action
                                                                                            .OpenUrlAction
                                                                                            .Application
                                                                                            .BROWSER
                                                                                    )
                                                                                    .url(
                                                                                        "http://example.com"
                                                                                    )
                                                                                    .webviewViewMode(
                                                                                        RcsSuggestion
                                                                                            .Action
                                                                                            .OpenUrlAction
                                                                                            .WebviewViewMode
                                                                                            .HALF
                                                                                    )
                                                                                    .description(
                                                                                        "description"
                                                                                    )
                                                                                    .build()
                                                                            )
                                                                            .postbackData(
                                                                                "postback_data"
                                                                            )
                                                                            .shareLocationAction(
                                                                                RcsSuggestion.Action
                                                                                    .ShareLocationAction
                                                                                    .builder()
                                                                                    .putAdditionalProperty(
                                                                                        "foo",
                                                                                        JsonValue
                                                                                            .from(
                                                                                                "bar"
                                                                                            ),
                                                                                    )
                                                                                    .build()
                                                                            )
                                                                            .text("Hello world")
                                                                            .viewLocationAction(
                                                                                RcsSuggestion.Action
                                                                                    .ViewLocationAction
                                                                                    .builder()
                                                                                    .label("label")
                                                                                    .latLong(
                                                                                        RcsSuggestion
                                                                                            .Action
                                                                                            .ViewLocationAction
                                                                                            .LatLong
                                                                                            .builder()
                                                                                            .latitude(
                                                                                                41.8
                                                                                            )
                                                                                            .longitude(
                                                                                                -87.6
                                                                                            )
                                                                                            .build()
                                                                                    )
                                                                                    .query("query")
                                                                                    .build()
                                                                            )
                                                                            .build()
                                                                    )
                                                                    .reply(
                                                                        RcsSuggestion.Reply
                                                                            .builder()
                                                                            .postbackData(
                                                                                "postback_data"
                                                                            )
                                                                            .text("text")
                                                                            .build()
                                                                    )
                                                                    .build()
                                                            )
                                                            .title("Elephant")
                                                            .build()
                                                    )
                                                    .cardWidth(
                                                        RcsAgentMessage.ContentMessage.RichCard
                                                            .CarouselCard
                                                            .CardWidth
                                                            .SMALL
                                                    )
                                                    .build()
                                            )
                                            .standaloneCard(
                                                RcsAgentMessage.ContentMessage.RichCard
                                                    .StandaloneCard
                                                    .builder()
                                                    .cardContent(
                                                        RcsCardContent.builder()
                                                            .description("description")
                                                            .media(
                                                                RcsCardContent.Media.builder()
                                                                    .contentInfo(
                                                                        RcsContentInfo.builder()
                                                                            .fileUrl(
                                                                                "https://example.com/elephant.jpg"
                                                                            )
                                                                            .forceRefresh(true)
                                                                            .thumbnailUrl(
                                                                                "thumbnail_url"
                                                                            )
                                                                            .build()
                                                                    )
                                                                    .height(
                                                                        RcsCardContent.Media.Height
                                                                            .MEDIUM
                                                                    )
                                                                    .build()
                                                            )
                                                            .addSuggestion(
                                                                RcsSuggestion.builder()
                                                                    .action(
                                                                        RcsSuggestion.Action
                                                                            .builder()
                                                                            .createCalendarEventAction(
                                                                                RcsSuggestion.Action
                                                                                    .CreateCalendarEventAction
                                                                                    .builder()
                                                                                    .description(
                                                                                        "description"
                                                                                    )
                                                                                    .endTime(
                                                                                        OffsetDateTime
                                                                                            .parse(
                                                                                                "2024-10-02T15:02:31Z"
                                                                                            )
                                                                                    )
                                                                                    .startTime(
                                                                                        OffsetDateTime
                                                                                            .parse(
                                                                                                "2024-10-02T15:01:23Z"
                                                                                            )
                                                                                    )
                                                                                    .title("title")
                                                                                    .build()
                                                                            )
                                                                            .dialAction(
                                                                                RcsSuggestion.Action
                                                                                    .DialAction
                                                                                    .builder()
                                                                                    .phoneNumber(
                                                                                        "+13125551234"
                                                                                    )
                                                                                    .build()
                                                                            )
                                                                            .fallbackUrl(
                                                                                "fallback_url"
                                                                            )
                                                                            .openUrlAction(
                                                                                RcsSuggestion.Action
                                                                                    .OpenUrlAction
                                                                                    .builder()
                                                                                    .application(
                                                                                        RcsSuggestion
                                                                                            .Action
                                                                                            .OpenUrlAction
                                                                                            .Application
                                                                                            .BROWSER
                                                                                    )
                                                                                    .url(
                                                                                        "http://example.com"
                                                                                    )
                                                                                    .webviewViewMode(
                                                                                        RcsSuggestion
                                                                                            .Action
                                                                                            .OpenUrlAction
                                                                                            .WebviewViewMode
                                                                                            .HALF
                                                                                    )
                                                                                    .description(
                                                                                        "description"
                                                                                    )
                                                                                    .build()
                                                                            )
                                                                            .postbackData(
                                                                                "postback_data"
                                                                            )
                                                                            .shareLocationAction(
                                                                                RcsSuggestion.Action
                                                                                    .ShareLocationAction
                                                                                    .builder()
                                                                                    .putAdditionalProperty(
                                                                                        "foo",
                                                                                        JsonValue
                                                                                            .from(
                                                                                                "bar"
                                                                                            ),
                                                                                    )
                                                                                    .build()
                                                                            )
                                                                            .text("Hello world")
                                                                            .viewLocationAction(
                                                                                RcsSuggestion.Action
                                                                                    .ViewLocationAction
                                                                                    .builder()
                                                                                    .label("label")
                                                                                    .latLong(
                                                                                        RcsSuggestion
                                                                                            .Action
                                                                                            .ViewLocationAction
                                                                                            .LatLong
                                                                                            .builder()
                                                                                            .latitude(
                                                                                                41.8
                                                                                            )
                                                                                            .longitude(
                                                                                                -87.6
                                                                                            )
                                                                                            .build()
                                                                                    )
                                                                                    .query("query")
                                                                                    .build()
                                                                            )
                                                                            .build()
                                                                    )
                                                                    .reply(
                                                                        RcsSuggestion.Reply
                                                                            .builder()
                                                                            .postbackData(
                                                                                "postback_data"
                                                                            )
                                                                            .text("text")
                                                                            .build()
                                                                    )
                                                                    .build()
                                                            )
                                                            .title("Elephant")
                                                            .build()
                                                    )
                                                    .cardOrientation(
                                                        RcsAgentMessage.ContentMessage.RichCard
                                                            .StandaloneCard
                                                            .CardOrientation
                                                            .HORIZONTAL
                                                    )
                                                    .thumbnailImageAlignment(
                                                        RcsAgentMessage.ContentMessage.RichCard
                                                            .StandaloneCard
                                                            .ThumbnailImageAlignment
                                                            .LEFT
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .addSuggestion(
                                        RcsSuggestion.builder()
                                            .action(
                                                RcsSuggestion.Action.builder()
                                                    .createCalendarEventAction(
                                                        RcsSuggestion.Action
                                                            .CreateCalendarEventAction
                                                            .builder()
                                                            .description("description")
                                                            .endTime(
                                                                OffsetDateTime.parse(
                                                                    "2024-10-02T15:02:31Z"
                                                                )
                                                            )
                                                            .startTime(
                                                                OffsetDateTime.parse(
                                                                    "2024-10-02T15:01:23Z"
                                                                )
                                                            )
                                                            .title("title")
                                                            .build()
                                                    )
                                                    .dialAction(
                                                        RcsSuggestion.Action.DialAction.builder()
                                                            .phoneNumber("+13125551234")
                                                            .build()
                                                    )
                                                    .fallbackUrl("fallback_url")
                                                    .openUrlAction(
                                                        RcsSuggestion.Action.OpenUrlAction.builder()
                                                            .application(
                                                                RcsSuggestion.Action.OpenUrlAction
                                                                    .Application
                                                                    .BROWSER
                                                            )
                                                            .url("http://example.com")
                                                            .webviewViewMode(
                                                                RcsSuggestion.Action.OpenUrlAction
                                                                    .WebviewViewMode
                                                                    .HALF
                                                            )
                                                            .description("description")
                                                            .build()
                                                    )
                                                    .postbackData("postback_data")
                                                    .shareLocationAction(
                                                        RcsSuggestion.Action.ShareLocationAction
                                                            .builder()
                                                            .putAdditionalProperty(
                                                                "foo",
                                                                JsonValue.from("bar"),
                                                            )
                                                            .build()
                                                    )
                                                    .text("Hello world")
                                                    .viewLocationAction(
                                                        RcsSuggestion.Action.ViewLocationAction
                                                            .builder()
                                                            .label("label")
                                                            .latLong(
                                                                RcsSuggestion.Action
                                                                    .ViewLocationAction
                                                                    .LatLong
                                                                    .builder()
                                                                    .latitude(41.8)
                                                                    .longitude(-87.6)
                                                                    .build()
                                                            )
                                                            .query("query")
                                                            .build()
                                                    )
                                                    .build()
                                            )
                                            .reply(
                                                RcsSuggestion.Reply.builder()
                                                    .postbackData("postback_data")
                                                    .text("text")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .text("Hello world!")
                                    .build()
                            )
                            .event(
                                RcsAgentMessage.Event.builder()
                                    .eventType(RcsAgentMessage.Event.EventType.IS_TYPING)
                                    .build()
                            )
                            .expireTime(OffsetDateTime.parse("2024-10-02T15:01:23Z"))
                            .ttl("10.5s")
                            .build()
                    )
                    .messagingProfileId("messaging_profile_id")
                    .to("+13125551234")
                    .mmsFallback(
                        MesssageRcsParams.MmsFallback.builder()
                            .from("+13125551234")
                            .addMediaUrl("string")
                            .subject("Test Message")
                            .text("Hello world!")
                            .build()
                    )
                    .smsFallback(
                        MesssageRcsParams.SmsFallback.builder()
                            .from("+13125551234")
                            .text("Hello world!")
                            .build()
                    )
                    .type(MesssageRcsParams.Type.RCS)
                    .webhookUrl("webhook_url")
                    .build()
            )

        response.validate()
    }

    @Disabled("Prism tests are disabled")
    @Test
    fun whatsapp() {
        val client =
            TelnyxOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .apiKey("My API Key")
                .build()
        val messsageService = client.messsages()

        val response =
            messsageService.whatsapp(
                MesssageWhatsappParams.builder()
                    .from("+13125551234")
                    .to("+13125551234")
                    .whatsappMessage(
                        MesssageWhatsappParams.WhatsappMessage.builder()
                            .audio(
                                WhatsappMedia.builder()
                                    .caption("caption")
                                    .filename("filename")
                                    .link("http://example.com/media.jpg")
                                    .voice(true)
                                    .build()
                            )
                            .bizOpaqueCallbackData("biz_opaque_callback_data")
                            .addContact(
                                MesssageWhatsappParams.WhatsappMessage.Contact.builder()
                                    .addAddress(
                                        MesssageWhatsappParams.WhatsappMessage.Contact.Address
                                            .builder()
                                            .city("city")
                                            .country("country")
                                            .countryCode("country_code")
                                            .state("state")
                                            .street("street")
                                            .type("type")
                                            .zip("zip")
                                            .build()
                                    )
                                    .birthday("birthday")
                                    .addEmail(
                                        MesssageWhatsappParams.WhatsappMessage.Contact.Email
                                            .builder()
                                            .email("email")
                                            .type("type")
                                            .build()
                                    )
                                    .name("name")
                                    .org(
                                        MesssageWhatsappParams.WhatsappMessage.Contact.Org.builder()
                                            .company("company")
                                            .department("department")
                                            .title("title")
                                            .build()
                                    )
                                    .addPhone(
                                        MesssageWhatsappParams.WhatsappMessage.Contact.Phone
                                            .builder()
                                            .phone("phone")
                                            .type("type")
                                            .waId("wa_id")
                                            .build()
                                    )
                                    .addUrl(
                                        MesssageWhatsappParams.WhatsappMessage.Contact.Url.builder()
                                            .type("type")
                                            .url("url")
                                            .build()
                                    )
                                    .build()
                            )
                            .document(
                                WhatsappMedia.builder()
                                    .caption("caption")
                                    .filename("filename")
                                    .link("http://example.com/media.jpg")
                                    .voice(true)
                                    .build()
                            )
                            .image(
                                WhatsappMedia.builder()
                                    .caption("caption")
                                    .filename("filename")
                                    .link("http://example.com/media.jpg")
                                    .voice(true)
                                    .build()
                            )
                            .interactive(
                                MesssageWhatsappParams.WhatsappMessage.Interactive.builder()
                                    .action(
                                        MesssageWhatsappParams.WhatsappMessage.Interactive.Action
                                            .builder()
                                            .button("button")
                                            .addButton(
                                                MesssageWhatsappParams.WhatsappMessage.Interactive
                                                    .Action
                                                    .Button
                                                    .builder()
                                                    .reply(
                                                        MesssageWhatsappParams.WhatsappMessage
                                                            .Interactive
                                                            .Action
                                                            .Button
                                                            .Reply
                                                            .builder()
                                                            .id("id")
                                                            .title("title")
                                                            .build()
                                                    )
                                                    .type(
                                                        MesssageWhatsappParams.WhatsappMessage
                                                            .Interactive
                                                            .Action
                                                            .Button
                                                            .Type
                                                            .REPLY
                                                    )
                                                    .build()
                                            )
                                            .addCard(
                                                MesssageWhatsappParams.WhatsappMessage.Interactive
                                                    .Action
                                                    .Card
                                                    .builder()
                                                    .action(
                                                        MesssageWhatsappParams.WhatsappMessage
                                                            .Interactive
                                                            .Action
                                                            .Card
                                                            .CardAction
                                                            .builder()
                                                            .catalogId("catalog_id")
                                                            .productRetailerId(
                                                                "product_retailer_id"
                                                            )
                                                            .build()
                                                    )
                                                    .body(
                                                        MesssageWhatsappParams.WhatsappMessage
                                                            .Interactive
                                                            .Action
                                                            .Card
                                                            .CardBody
                                                            .builder()
                                                            .text("text")
                                                            .build()
                                                    )
                                                    .cardIndex(0L)
                                                    .header(
                                                        MesssageWhatsappParams.WhatsappMessage
                                                            .Interactive
                                                            .Action
                                                            .Card
                                                            .Header
                                                            .builder()
                                                            .image(
                                                                WhatsappMedia.builder()
                                                                    .caption("caption")
                                                                    .filename("filename")
                                                                    .link(
                                                                        "http://example.com/media.jpg"
                                                                    )
                                                                    .voice(true)
                                                                    .build()
                                                            )
                                                            .type(
                                                                MesssageWhatsappParams
                                                                    .WhatsappMessage
                                                                    .Interactive
                                                                    .Action
                                                                    .Card
                                                                    .Header
                                                                    .Type
                                                                    .IMAGE
                                                            )
                                                            .video(
                                                                WhatsappMedia.builder()
                                                                    .caption("caption")
                                                                    .filename("filename")
                                                                    .link(
                                                                        "http://example.com/media.jpg"
                                                                    )
                                                                    .voice(true)
                                                                    .build()
                                                            )
                                                            .build()
                                                    )
                                                    .type(
                                                        MesssageWhatsappParams.WhatsappMessage
                                                            .Interactive
                                                            .Action
                                                            .Card
                                                            .Type
                                                            .CTA_URL
                                                    )
                                                    .build()
                                            )
                                            .catalogId("catalog_id")
                                            .mode("mode")
                                            .name("name")
                                            .parameters(
                                                MesssageWhatsappParams.WhatsappMessage.Interactive
                                                    .Action
                                                    .Parameters
                                                    .builder()
                                                    .displayText("display_text")
                                                    .url("url")
                                                    .build()
                                            )
                                            .productRetailerId("product_retailer_id")
                                            .addSection(
                                                MesssageWhatsappParams.WhatsappMessage.Interactive
                                                    .Action
                                                    .Section
                                                    .builder()
                                                    .addProductItem(
                                                        MesssageWhatsappParams.WhatsappMessage
                                                            .Interactive
                                                            .Action
                                                            .Section
                                                            .ProductItem
                                                            .builder()
                                                            .productRetailerId(
                                                                "product_retailer_id"
                                                            )
                                                            .build()
                                                    )
                                                    .addRow(
                                                        MesssageWhatsappParams.WhatsappMessage
                                                            .Interactive
                                                            .Action
                                                            .Section
                                                            .Row
                                                            .builder()
                                                            .id("id")
                                                            .description("description")
                                                            .title("title")
                                                            .build()
                                                    )
                                                    .title("title")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .body(
                                        MesssageWhatsappParams.WhatsappMessage.Interactive
                                            .InteractiveBody
                                            .builder()
                                            .text("text")
                                            .build()
                                    )
                                    .footer(
                                        MesssageWhatsappParams.WhatsappMessage.Interactive.Footer
                                            .builder()
                                            .text("text")
                                            .build()
                                    )
                                    .header(
                                        MesssageWhatsappParams.WhatsappMessage.Interactive.Header
                                            .builder()
                                            .document(
                                                WhatsappMedia.builder()
                                                    .caption("caption")
                                                    .filename("filename")
                                                    .link("http://example.com/media.jpg")
                                                    .voice(true)
                                                    .build()
                                            )
                                            .image(
                                                WhatsappMedia.builder()
                                                    .caption("caption")
                                                    .filename("filename")
                                                    .link("http://example.com/media.jpg")
                                                    .voice(true)
                                                    .build()
                                            )
                                            .subText("sub_text")
                                            .text("text")
                                            .video(
                                                WhatsappMedia.builder()
                                                    .caption("caption")
                                                    .filename("filename")
                                                    .link("http://example.com/media.jpg")
                                                    .voice(true)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .type(
                                        MesssageWhatsappParams.WhatsappMessage.Interactive.Type
                                            .CTA_URL
                                    )
                                    .build()
                            )
                            .location(
                                MesssageWhatsappParams.WhatsappMessage.Location.builder()
                                    .address("address")
                                    .latitude("latitude")
                                    .longitude("longitude")
                                    .name("name")
                                    .build()
                            )
                            .reaction(
                                MesssageWhatsappParams.WhatsappMessage.Reaction.builder()
                                    .empji("empji")
                                    .messageId("message_id")
                                    .build()
                            )
                            .sticker(
                                WhatsappMedia.builder()
                                    .caption("caption")
                                    .filename("filename")
                                    .link("http://example.com/media.jpg")
                                    .voice(true)
                                    .build()
                            )
                            .type(MesssageWhatsappParams.WhatsappMessage.Type.AUDIO)
                            .video(
                                WhatsappMedia.builder()
                                    .caption("caption")
                                    .filename("filename")
                                    .link("http://example.com/media.jpg")
                                    .voice(true)
                                    .build()
                            )
                            .build()
                    )
                    .type(MesssageWhatsappParams.Type.WHATSAPP)
                    .webhookUrl("webhook_url")
                    .build()
            )

        response.validate()
    }
}
