/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.telnyx.sdk.model.MessagingProfileMessageTypeMetrics;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.telnyx.sdk.JSON;


/**
 * MessagingProfileDetailedMetric
 */
@JsonPropertyOrder({
  MessagingProfileDetailedMetric.JSON_PROPERTY_TIMESTAMP,
  MessagingProfileDetailedMetric.JSON_PROPERTY_METRICS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class MessagingProfileDetailedMetric {
  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  private String timestamp;

  public static final String JSON_PROPERTY_METRICS = "metrics";
  private List<MessagingProfileMessageTypeMetrics> metrics = null;

  public MessagingProfileDetailedMetric() { 
  }

  @JsonCreator
  public MessagingProfileDetailedMetric(
    @JsonProperty(JSON_PROPERTY_TIMESTAMP) String timestamp
  ) {
    this();
    this.timestamp = timestamp;
  }

   /**
   * The timestamp of the aggregated data.
   * @return timestamp
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(example = "2019-01-23T18:10:02.574Z", value = "The timestamp of the aggregated data.")
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimestamp() {
    return timestamp;
  }




  public MessagingProfileDetailedMetric metrics(List<MessagingProfileMessageTypeMetrics> metrics) {
    this.metrics = metrics;
    return this;
  }

  public MessagingProfileDetailedMetric addMetricsItem(MessagingProfileMessageTypeMetrics metricsItem) {
    if (this.metrics == null) {
      this.metrics = new ArrayList<>();
    }
    this.metrics.add(metricsItem);
    return this;
  }

   /**
   * Get metrics
   * @return metrics
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_METRICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MessagingProfileMessageTypeMetrics> getMetrics() {
    return metrics;
  }


  @JsonProperty(JSON_PROPERTY_METRICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetrics(List<MessagingProfileMessageTypeMetrics> metrics) {
    this.metrics = metrics;
  }


  /**
   * Return true if this MessagingProfileDetailedMetric object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessagingProfileDetailedMetric messagingProfileDetailedMetric = (MessagingProfileDetailedMetric) o;
    return Objects.equals(this.timestamp, messagingProfileDetailedMetric.timestamp) &&
        Objects.equals(this.metrics, messagingProfileDetailedMetric.metrics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, metrics);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessagingProfileDetailedMetric {\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

