/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.telnyx.sdk.JSON;


/**
 * ReadCommentAllOf
 */
@JsonPropertyOrder({
  ReadCommentAllOf.JSON_PROPERTY_READ_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ReadCommentAllOf {
  public static final String JSON_PROPERTY_READ_AT = "read_at";
  private String readAt;

  public ReadCommentAllOf() { 
  }

  @JsonCreator
  public ReadCommentAllOf(
    @JsonProperty(JSON_PROPERTY_READ_AT) String readAt
  ) {
    this();
    this.readAt = readAt;
  }

   /**
   * An ISO 8901 datetime string for when the comment was read.
   * @return readAt
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(example = "2018-01-01T00:00:00.000000Z", value = "An ISO 8901 datetime string for when the comment was read.")
  @JsonProperty(JSON_PROPERTY_READ_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReadAt() {
    return readAt;
  }




  /**
   * Return true if this ReadComment_allOf object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReadCommentAllOf readCommentAllOf = (ReadCommentAllOf) o;
    return Objects.equals(this.readAt, readCommentAllOf.readAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(readAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReadCommentAllOf {\n");
    sb.append("    readAt: ").append(toIndentedString(readAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

