// File generated from our OpenAPI spec by Stainless.

package com.telnyx.api.models.globaliplatency

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class GlobalIpLatencyRetrieveResponseTest {

    @Test
    fun create() {
        val globalIpLatencyRetrieveResponse =
            GlobalIpLatencyRetrieveResponse.builder()
                .addData(
                    GlobalIpLatencyRetrieveResponse.Data.builder()
                        .globalIp(
                            GlobalIpLatencyRetrieveResponse.Data.GlobalIp.builder()
                                .id("a836125b-20b6-452e-9c03-2653f09c7ed7")
                                .ipAddress("ip_address")
                                .build()
                        )
                        .meanLatency(
                            GlobalIpLatencyRetrieveResponse.Data.MeanLatency.builder()
                                .amount(100.0)
                                .unit("ms")
                                .build()
                        )
                        .percentileLatency(
                            GlobalIpLatencyRetrieveResponse.Data.PercentileLatency.builder()
                                .p0(
                                    GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._0
                                        .builder()
                                        .amount(100.0)
                                        .unit("ms")
                                        .build()
                                )
                                .p25(
                                    GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._25
                                        .builder()
                                        .amount(100.0)
                                        .unit("ms")
                                        .build()
                                )
                                .p50(
                                    GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._50
                                        .builder()
                                        .amount(100.0)
                                        .unit("ms")
                                        .build()
                                )
                                .p75(
                                    GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._75
                                        .builder()
                                        .amount(100.0)
                                        .unit("ms")
                                        .build()
                                )
                                .p90(
                                    GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._90
                                        .builder()
                                        .amount(100.0)
                                        .unit("ms")
                                        .build()
                                )
                                .p99(
                                    GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._99
                                        .builder()
                                        .amount(100.0)
                                        .unit("ms")
                                        .build()
                                )
                                .p100(
                                    GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._100
                                        .builder()
                                        .amount(100.0)
                                        .unit("ms")
                                        .build()
                                )
                                .build()
                        )
                        .proberLocation(
                            GlobalIpLatencyRetrieveResponse.Data.ProberLocation.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .lat(52.370216)
                                .lon(4.895168)
                                .name("Amsterdam")
                                .build()
                        )
                        .timestamp(OffsetDateTime.parse("2020-01-01T00:00:00.000Z"))
                        .build()
                )
                .build()

        assertThat(globalIpLatencyRetrieveResponse.data().getOrNull())
            .containsExactly(
                GlobalIpLatencyRetrieveResponse.Data.builder()
                    .globalIp(
                        GlobalIpLatencyRetrieveResponse.Data.GlobalIp.builder()
                            .id("a836125b-20b6-452e-9c03-2653f09c7ed7")
                            .ipAddress("ip_address")
                            .build()
                    )
                    .meanLatency(
                        GlobalIpLatencyRetrieveResponse.Data.MeanLatency.builder()
                            .amount(100.0)
                            .unit("ms")
                            .build()
                    )
                    .percentileLatency(
                        GlobalIpLatencyRetrieveResponse.Data.PercentileLatency.builder()
                            .p0(
                                GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._0
                                    .builder()
                                    .amount(100.0)
                                    .unit("ms")
                                    .build()
                            )
                            .p25(
                                GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._25
                                    .builder()
                                    .amount(100.0)
                                    .unit("ms")
                                    .build()
                            )
                            .p50(
                                GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._50
                                    .builder()
                                    .amount(100.0)
                                    .unit("ms")
                                    .build()
                            )
                            .p75(
                                GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._75
                                    .builder()
                                    .amount(100.0)
                                    .unit("ms")
                                    .build()
                            )
                            .p90(
                                GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._90
                                    .builder()
                                    .amount(100.0)
                                    .unit("ms")
                                    .build()
                            )
                            .p99(
                                GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._99
                                    .builder()
                                    .amount(100.0)
                                    .unit("ms")
                                    .build()
                            )
                            .p100(
                                GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._100
                                    .builder()
                                    .amount(100.0)
                                    .unit("ms")
                                    .build()
                            )
                            .build()
                    )
                    .proberLocation(
                        GlobalIpLatencyRetrieveResponse.Data.ProberLocation.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .lat(52.370216)
                            .lon(4.895168)
                            .name("Amsterdam")
                            .build()
                    )
                    .timestamp(OffsetDateTime.parse("2020-01-01T00:00:00.000Z"))
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val globalIpLatencyRetrieveResponse =
            GlobalIpLatencyRetrieveResponse.builder()
                .addData(
                    GlobalIpLatencyRetrieveResponse.Data.builder()
                        .globalIp(
                            GlobalIpLatencyRetrieveResponse.Data.GlobalIp.builder()
                                .id("a836125b-20b6-452e-9c03-2653f09c7ed7")
                                .ipAddress("ip_address")
                                .build()
                        )
                        .meanLatency(
                            GlobalIpLatencyRetrieveResponse.Data.MeanLatency.builder()
                                .amount(100.0)
                                .unit("ms")
                                .build()
                        )
                        .percentileLatency(
                            GlobalIpLatencyRetrieveResponse.Data.PercentileLatency.builder()
                                .p0(
                                    GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._0
                                        .builder()
                                        .amount(100.0)
                                        .unit("ms")
                                        .build()
                                )
                                .p25(
                                    GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._25
                                        .builder()
                                        .amount(100.0)
                                        .unit("ms")
                                        .build()
                                )
                                .p50(
                                    GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._50
                                        .builder()
                                        .amount(100.0)
                                        .unit("ms")
                                        .build()
                                )
                                .p75(
                                    GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._75
                                        .builder()
                                        .amount(100.0)
                                        .unit("ms")
                                        .build()
                                )
                                .p90(
                                    GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._90
                                        .builder()
                                        .amount(100.0)
                                        .unit("ms")
                                        .build()
                                )
                                .p99(
                                    GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._99
                                        .builder()
                                        .amount(100.0)
                                        .unit("ms")
                                        .build()
                                )
                                .p100(
                                    GlobalIpLatencyRetrieveResponse.Data.PercentileLatency._100
                                        .builder()
                                        .amount(100.0)
                                        .unit("ms")
                                        .build()
                                )
                                .build()
                        )
                        .proberLocation(
                            GlobalIpLatencyRetrieveResponse.Data.ProberLocation.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .lat(52.370216)
                                .lon(4.895168)
                                .name("Amsterdam")
                                .build()
                        )
                        .timestamp(OffsetDateTime.parse("2020-01-01T00:00:00.000Z"))
                        .build()
                )
                .build()

        val roundtrippedGlobalIpLatencyRetrieveResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(globalIpLatencyRetrieveResponse),
                jacksonTypeRef<GlobalIpLatencyRetrieveResponse>(),
            )

        assertThat(roundtrippedGlobalIpLatencyRetrieveResponse)
            .isEqualTo(globalIpLatencyRetrieveResponse)
    }
}
