// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.ai.assistants.versions

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.JsonValue
import com.telnyx.sdk.core.jsonMapper
import com.telnyx.sdk.models.ai.assistants.AssistantTool
import com.telnyx.sdk.models.ai.assistants.EnabledFeatures
import com.telnyx.sdk.models.ai.assistants.InferenceEmbeddingWebhookToolParams
import com.telnyx.sdk.models.ai.assistants.InsightSettings
import com.telnyx.sdk.models.ai.assistants.MessagingSettings
import com.telnyx.sdk.models.ai.assistants.PrivacySettings
import com.telnyx.sdk.models.ai.assistants.TelephonySettings
import com.telnyx.sdk.models.ai.assistants.TranscriptionSettings
import com.telnyx.sdk.models.ai.assistants.TranscriptionSettingsConfig
import com.telnyx.sdk.models.ai.assistants.VoiceSettings
import com.telnyx.sdk.models.ai.assistants.WebhookTool
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class UpdateAssistantTest {

    @Test
    fun create() {
        val updateAssistant =
            UpdateAssistant.builder()
                .description("description")
                .dynamicVariables(
                    UpdateAssistant.DynamicVariables.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .dynamicVariablesWebhookUrl("dynamic_variables_webhook_url")
                .addEnabledFeature(EnabledFeatures.TELEPHONY)
                .greeting("greeting")
                .insightSettings(
                    InsightSettings.builder().insightGroupId("insight_group_id").build()
                )
                .instructions("instructions")
                .llmApiKeyRef("llm_api_key_ref")
                .messagingSettings(
                    MessagingSettings.builder()
                        .defaultMessagingProfileId("default_messaging_profile_id")
                        .deliveryStatusWebhookUrl("delivery_status_webhook_url")
                        .build()
                )
                .model("model")
                .name("name")
                .privacySettings(PrivacySettings.builder().dataRetention(true).build())
                .telephonySettings(
                    TelephonySettings.builder()
                        .defaultTexmlAppId("default_texml_app_id")
                        .noiseSuppression(TelephonySettings.NoiseSuppression.DEEPFILTERNET)
                        .noiseSuppressionConfig(
                            TelephonySettings.NoiseSuppressionConfig.builder()
                                .attenuationLimit(0L)
                                .mode(TelephonySettings.NoiseSuppressionConfig.Mode.ADVANCED)
                                .build()
                        )
                        .supportsUnauthenticatedWebCalls(true)
                        .timeLimitSecs(30L)
                        .build()
                )
                .addWebhookTool(
                    InferenceEmbeddingWebhookToolParams.builder()
                        .description("description")
                        .name("name")
                        .url("https://example.com/api/v1/function")
                        .bodyParameters(
                            InferenceEmbeddingWebhookToolParams.BodyParameters.builder()
                                .properties(
                                    InferenceEmbeddingWebhookToolParams.BodyParameters.Properties
                                        .builder()
                                        .putAdditionalProperty("age", JsonValue.from("bar"))
                                        .putAdditionalProperty("location", JsonValue.from("bar"))
                                        .build()
                                )
                                .addRequired("age")
                                .addRequired("location")
                                .type(
                                    InferenceEmbeddingWebhookToolParams.BodyParameters.Type.OBJECT
                                )
                                .build()
                        )
                        .addHeader(
                            InferenceEmbeddingWebhookToolParams.Header.builder()
                                .name("name")
                                .value("value")
                                .build()
                        )
                        .method(InferenceEmbeddingWebhookToolParams.Method.GET)
                        .pathParameters(
                            InferenceEmbeddingWebhookToolParams.PathParameters.builder()
                                .properties(
                                    InferenceEmbeddingWebhookToolParams.PathParameters.Properties
                                        .builder()
                                        .putAdditionalProperty("id", JsonValue.from("bar"))
                                        .build()
                                )
                                .addRequired("id")
                                .type(
                                    InferenceEmbeddingWebhookToolParams.PathParameters.Type.OBJECT
                                )
                                .build()
                        )
                        .queryParameters(
                            InferenceEmbeddingWebhookToolParams.QueryParameters.builder()
                                .properties(
                                    InferenceEmbeddingWebhookToolParams.QueryParameters.Properties
                                        .builder()
                                        .putAdditionalProperty("page", JsonValue.from("bar"))
                                        .build()
                                )
                                .addRequired("page")
                                .type(
                                    InferenceEmbeddingWebhookToolParams.QueryParameters.Type.OBJECT
                                )
                                .build()
                        )
                        .build()
                )
                .transcription(
                    TranscriptionSettings.builder()
                        .language("language")
                        .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                        .region("region")
                        .settings(
                            TranscriptionSettingsConfig.builder()
                                .eagerEotThreshold(0.3)
                                .eotThreshold(0.0)
                                .eotTimeoutMs(0L)
                                .numerals(true)
                                .smartFormat(true)
                                .build()
                        )
                        .build()
                )
                .voiceSettings(
                    VoiceSettings.builder()
                        .voice("voice")
                        .apiKeyRef("api_key_ref")
                        .predefinedMediaBackgroundAudio(
                            VoiceSettings.BackgroundAudio.PredefinedMedia.PredefinedMediaValue
                                .SILENCE
                        )
                        .similarityBoost(0.0)
                        .speed(0.0)
                        .style(0.0)
                        .temperature(0.0)
                        .useSpeakerBoost(true)
                        .voiceSpeed(0.0)
                        .build()
                )
                .widgetSettings(
                    UpdateAssistant.WidgetSettings.builder()
                        .agentThinkingText("agent_thinking_text")
                        .audioVisualizerConfig(
                            UpdateAssistant.WidgetSettings.AudioVisualizerConfig.builder()
                                .color(
                                    UpdateAssistant.WidgetSettings.AudioVisualizerConfig.Color
                                        .VERDANT
                                )
                                .preset("preset")
                                .build()
                        )
                        .defaultState(UpdateAssistant.WidgetSettings.DefaultState.EXPANDED)
                        .giveFeedbackUrl("give_feedback_url")
                        .logoIconUrl("logo_icon_url")
                        .position(UpdateAssistant.WidgetSettings.Position.FIXED)
                        .reportIssueUrl("report_issue_url")
                        .speakToInterruptText("speak_to_interrupt_text")
                        .startCallText("start_call_text")
                        .theme(UpdateAssistant.WidgetSettings.Theme.LIGHT)
                        .viewHistoryUrl("view_history_url")
                        .build()
                )
                .build()

        assertThat(updateAssistant.description()).contains("description")
        assertThat(updateAssistant.dynamicVariables())
            .contains(
                UpdateAssistant.DynamicVariables.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(updateAssistant.dynamicVariablesWebhookUrl())
            .contains("dynamic_variables_webhook_url")
        assertThat(updateAssistant.enabledFeatures().getOrNull())
            .containsExactly(EnabledFeatures.TELEPHONY)
        assertThat(updateAssistant.greeting()).contains("greeting")
        assertThat(updateAssistant.insightSettings())
            .contains(InsightSettings.builder().insightGroupId("insight_group_id").build())
        assertThat(updateAssistant.instructions()).contains("instructions")
        assertThat(updateAssistant.llmApiKeyRef()).contains("llm_api_key_ref")
        assertThat(updateAssistant.messagingSettings())
            .contains(
                MessagingSettings.builder()
                    .defaultMessagingProfileId("default_messaging_profile_id")
                    .deliveryStatusWebhookUrl("delivery_status_webhook_url")
                    .build()
            )
        assertThat(updateAssistant.model()).contains("model")
        assertThat(updateAssistant.name()).contains("name")
        assertThat(updateAssistant.privacySettings())
            .contains(PrivacySettings.builder().dataRetention(true).build())
        assertThat(updateAssistant.telephonySettings())
            .contains(
                TelephonySettings.builder()
                    .defaultTexmlAppId("default_texml_app_id")
                    .noiseSuppression(TelephonySettings.NoiseSuppression.DEEPFILTERNET)
                    .noiseSuppressionConfig(
                        TelephonySettings.NoiseSuppressionConfig.builder()
                            .attenuationLimit(0L)
                            .mode(TelephonySettings.NoiseSuppressionConfig.Mode.ADVANCED)
                            .build()
                    )
                    .supportsUnauthenticatedWebCalls(true)
                    .timeLimitSecs(30L)
                    .build()
            )
        assertThat(updateAssistant.tools().getOrNull())
            .containsExactly(
                AssistantTool.ofWebhook(
                    WebhookTool.builder()
                        .type(WebhookTool.Type.WEBHOOK)
                        .webhook(
                            InferenceEmbeddingWebhookToolParams.builder()
                                .description("description")
                                .name("name")
                                .url("https://example.com/api/v1/function")
                                .bodyParameters(
                                    InferenceEmbeddingWebhookToolParams.BodyParameters.builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.BodyParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty("age", JsonValue.from("bar"))
                                                .putAdditionalProperty(
                                                    "location",
                                                    JsonValue.from("bar"),
                                                )
                                                .build()
                                        )
                                        .addRequired("age")
                                        .addRequired("location")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.BodyParameters.Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .addHeader(
                                    InferenceEmbeddingWebhookToolParams.Header.builder()
                                        .name("name")
                                        .value("value")
                                        .build()
                                )
                                .method(InferenceEmbeddingWebhookToolParams.Method.GET)
                                .pathParameters(
                                    InferenceEmbeddingWebhookToolParams.PathParameters.builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.PathParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty("id", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .addRequired("id")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.PathParameters.Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .queryParameters(
                                    InferenceEmbeddingWebhookToolParams.QueryParameters.builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.QueryParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty(
                                                    "page",
                                                    JsonValue.from("bar"),
                                                )
                                                .build()
                                        )
                                        .addRequired("page")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.QueryParameters.Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
            )
        assertThat(updateAssistant.transcription())
            .contains(
                TranscriptionSettings.builder()
                    .language("language")
                    .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                    .region("region")
                    .settings(
                        TranscriptionSettingsConfig.builder()
                            .eagerEotThreshold(0.3)
                            .eotThreshold(0.0)
                            .eotTimeoutMs(0L)
                            .numerals(true)
                            .smartFormat(true)
                            .build()
                    )
                    .build()
            )
        assertThat(updateAssistant.voiceSettings())
            .contains(
                VoiceSettings.builder()
                    .voice("voice")
                    .apiKeyRef("api_key_ref")
                    .predefinedMediaBackgroundAudio(
                        VoiceSettings.BackgroundAudio.PredefinedMedia.PredefinedMediaValue.SILENCE
                    )
                    .similarityBoost(0.0)
                    .speed(0.0)
                    .style(0.0)
                    .temperature(0.0)
                    .useSpeakerBoost(true)
                    .voiceSpeed(0.0)
                    .build()
            )
        assertThat(updateAssistant.widgetSettings())
            .contains(
                UpdateAssistant.WidgetSettings.builder()
                    .agentThinkingText("agent_thinking_text")
                    .audioVisualizerConfig(
                        UpdateAssistant.WidgetSettings.AudioVisualizerConfig.builder()
                            .color(
                                UpdateAssistant.WidgetSettings.AudioVisualizerConfig.Color.VERDANT
                            )
                            .preset("preset")
                            .build()
                    )
                    .defaultState(UpdateAssistant.WidgetSettings.DefaultState.EXPANDED)
                    .giveFeedbackUrl("give_feedback_url")
                    .logoIconUrl("logo_icon_url")
                    .position(UpdateAssistant.WidgetSettings.Position.FIXED)
                    .reportIssueUrl("report_issue_url")
                    .speakToInterruptText("speak_to_interrupt_text")
                    .startCallText("start_call_text")
                    .theme(UpdateAssistant.WidgetSettings.Theme.LIGHT)
                    .viewHistoryUrl("view_history_url")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val updateAssistant =
            UpdateAssistant.builder()
                .description("description")
                .dynamicVariables(
                    UpdateAssistant.DynamicVariables.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .dynamicVariablesWebhookUrl("dynamic_variables_webhook_url")
                .addEnabledFeature(EnabledFeatures.TELEPHONY)
                .greeting("greeting")
                .insightSettings(
                    InsightSettings.builder().insightGroupId("insight_group_id").build()
                )
                .instructions("instructions")
                .llmApiKeyRef("llm_api_key_ref")
                .messagingSettings(
                    MessagingSettings.builder()
                        .defaultMessagingProfileId("default_messaging_profile_id")
                        .deliveryStatusWebhookUrl("delivery_status_webhook_url")
                        .build()
                )
                .model("model")
                .name("name")
                .privacySettings(PrivacySettings.builder().dataRetention(true).build())
                .telephonySettings(
                    TelephonySettings.builder()
                        .defaultTexmlAppId("default_texml_app_id")
                        .noiseSuppression(TelephonySettings.NoiseSuppression.DEEPFILTERNET)
                        .noiseSuppressionConfig(
                            TelephonySettings.NoiseSuppressionConfig.builder()
                                .attenuationLimit(0L)
                                .mode(TelephonySettings.NoiseSuppressionConfig.Mode.ADVANCED)
                                .build()
                        )
                        .supportsUnauthenticatedWebCalls(true)
                        .timeLimitSecs(30L)
                        .build()
                )
                .addWebhookTool(
                    InferenceEmbeddingWebhookToolParams.builder()
                        .description("description")
                        .name("name")
                        .url("https://example.com/api/v1/function")
                        .bodyParameters(
                            InferenceEmbeddingWebhookToolParams.BodyParameters.builder()
                                .properties(
                                    InferenceEmbeddingWebhookToolParams.BodyParameters.Properties
                                        .builder()
                                        .putAdditionalProperty("age", JsonValue.from("bar"))
                                        .putAdditionalProperty("location", JsonValue.from("bar"))
                                        .build()
                                )
                                .addRequired("age")
                                .addRequired("location")
                                .type(
                                    InferenceEmbeddingWebhookToolParams.BodyParameters.Type.OBJECT
                                )
                                .build()
                        )
                        .addHeader(
                            InferenceEmbeddingWebhookToolParams.Header.builder()
                                .name("name")
                                .value("value")
                                .build()
                        )
                        .method(InferenceEmbeddingWebhookToolParams.Method.GET)
                        .pathParameters(
                            InferenceEmbeddingWebhookToolParams.PathParameters.builder()
                                .properties(
                                    InferenceEmbeddingWebhookToolParams.PathParameters.Properties
                                        .builder()
                                        .putAdditionalProperty("id", JsonValue.from("bar"))
                                        .build()
                                )
                                .addRequired("id")
                                .type(
                                    InferenceEmbeddingWebhookToolParams.PathParameters.Type.OBJECT
                                )
                                .build()
                        )
                        .queryParameters(
                            InferenceEmbeddingWebhookToolParams.QueryParameters.builder()
                                .properties(
                                    InferenceEmbeddingWebhookToolParams.QueryParameters.Properties
                                        .builder()
                                        .putAdditionalProperty("page", JsonValue.from("bar"))
                                        .build()
                                )
                                .addRequired("page")
                                .type(
                                    InferenceEmbeddingWebhookToolParams.QueryParameters.Type.OBJECT
                                )
                                .build()
                        )
                        .build()
                )
                .transcription(
                    TranscriptionSettings.builder()
                        .language("language")
                        .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                        .region("region")
                        .settings(
                            TranscriptionSettingsConfig.builder()
                                .eagerEotThreshold(0.3)
                                .eotThreshold(0.0)
                                .eotTimeoutMs(0L)
                                .numerals(true)
                                .smartFormat(true)
                                .build()
                        )
                        .build()
                )
                .voiceSettings(
                    VoiceSettings.builder()
                        .voice("voice")
                        .apiKeyRef("api_key_ref")
                        .predefinedMediaBackgroundAudio(
                            VoiceSettings.BackgroundAudio.PredefinedMedia.PredefinedMediaValue
                                .SILENCE
                        )
                        .similarityBoost(0.0)
                        .speed(0.0)
                        .style(0.0)
                        .temperature(0.0)
                        .useSpeakerBoost(true)
                        .voiceSpeed(0.0)
                        .build()
                )
                .widgetSettings(
                    UpdateAssistant.WidgetSettings.builder()
                        .agentThinkingText("agent_thinking_text")
                        .audioVisualizerConfig(
                            UpdateAssistant.WidgetSettings.AudioVisualizerConfig.builder()
                                .color(
                                    UpdateAssistant.WidgetSettings.AudioVisualizerConfig.Color
                                        .VERDANT
                                )
                                .preset("preset")
                                .build()
                        )
                        .defaultState(UpdateAssistant.WidgetSettings.DefaultState.EXPANDED)
                        .giveFeedbackUrl("give_feedback_url")
                        .logoIconUrl("logo_icon_url")
                        .position(UpdateAssistant.WidgetSettings.Position.FIXED)
                        .reportIssueUrl("report_issue_url")
                        .speakToInterruptText("speak_to_interrupt_text")
                        .startCallText("start_call_text")
                        .theme(UpdateAssistant.WidgetSettings.Theme.LIGHT)
                        .viewHistoryUrl("view_history_url")
                        .build()
                )
                .build()

        val roundtrippedUpdateAssistant =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(updateAssistant),
                jacksonTypeRef<UpdateAssistant>(),
            )

        assertThat(roundtrippedUpdateAssistant).isEqualTo(updateAssistant)
    }
}
