/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.model;

import com.fasterxml.jackson.annotation.JsonTypeName;
import java.math.BigDecimal;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuditEventChangesInnerFrom
 */
public class AuditEventChangesInnerFromTest {
    private final AuditEventChangesInnerFrom model = new AuditEventChangesInnerFrom();

    /**
     * Model tests for AuditEventChangesInnerFrom
     */
    @Test
    public void testAuditEventChangesInnerFrom() {
        // TODO: test AuditEventChangesInnerFrom
    }

}
