/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.telnyx.sdk.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.Test;

/**
 * Model tests for ConferenceDetailRecord
 */
public class ConferenceDetailRecordTest {

    private final ConferenceDetailRecord model = new ConferenceDetailRecord();

    /**
     * Model tests for ConferenceDetailRecord
     */
    @Test
    public void testConferenceDetailRecord() {
        // TODO: test ConferenceDetailRecord
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'startedAt'
     */
    @Test
    public void startedAtTest() {
        // TODO: test startedAt
    }

    /**
     * Test the property 'endedAt'
     */
    @Test
    public void endedAtTest() {
        // TODO: test endedAt
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'callLegId'
     */
    @Test
    public void callLegIdTest() {
        // TODO: test callLegId
    }

    /**
     * Test the property 'callSessionId'
     */
    @Test
    public void callSessionIdTest() {
        // TODO: test callSessionId
    }

    /**
     * Test the property 'connectionId'
     */
    @Test
    public void connectionIdTest() {
        // TODO: test connectionId
    }

    /**
     * Test the property 'callSec'
     */
    @Test
    public void callSecTest() {
        // TODO: test callSec
    }

    /**
     * Test the property 'participantCount'
     */
    @Test
    public void participantCountTest() {
        // TODO: test participantCount
    }

    /**
     * Test the property 'participantCallSec'
     */
    @Test
    public void participantCallSecTest() {
        // TODO: test participantCallSec
    }

    /**
     * Test the property 'isTelnyxBillable'
     */
    @Test
    public void isTelnyxBillableTest() {
        // TODO: test isTelnyxBillable
    }

    /**
     * Test the property 'recordType'
     */
    @Test
    public void recordTypeTest() {
        // TODO: test recordType
    }
}
