/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.telnyx.sdk.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateConferenceRequest
 */
public class CreateConferenceRequestTest {

    private final CreateConferenceRequest model = new CreateConferenceRequest();

    /**
     * Model tests for CreateConferenceRequest
     */
    @Test
    public void testCreateConferenceRequest() {
        // TODO: test CreateConferenceRequest
    }

    /**
     * Test the property 'callControlId'
     */
    @Test
    public void callControlIdTest() {
        // TODO: test callControlId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'beepEnabled'
     */
    @Test
    public void beepEnabledTest() {
        // TODO: test beepEnabled
    }

    /**
     * Test the property 'clientState'
     */
    @Test
    public void clientStateTest() {
        // TODO: test clientState
    }

    /**
     * Test the property 'comfortNoise'
     */
    @Test
    public void comfortNoiseTest() {
        // TODO: test comfortNoise
    }

    /**
     * Test the property 'commandId'
     */
    @Test
    public void commandIdTest() {
        // TODO: test commandId
    }

    /**
     * Test the property 'durationMinutes'
     */
    @Test
    public void durationMinutesTest() {
        // TODO: test durationMinutes
    }

    /**
     * Test the property 'holdAudioUrl'
     */
    @Test
    public void holdAudioUrlTest() {
        // TODO: test holdAudioUrl
    }

    /**
     * Test the property 'holdMediaName'
     */
    @Test
    public void holdMediaNameTest() {
        // TODO: test holdMediaName
    }

    /**
     * Test the property 'maxParticipants'
     */
    @Test
    public void maxParticipantsTest() {
        // TODO: test maxParticipants
    }

    /**
     * Test the property 'startConferenceOnCreate'
     */
    @Test
    public void startConferenceOnCreateTest() {
        // TODO: test startConferenceOnCreate
    }
}
