/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.telnyx.sdk.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Test;

/**
 * Model tests for DialogflowConfig
 */
public class DialogflowConfigTest {

    private final DialogflowConfig model = new DialogflowConfig();

    /**
     * Model tests for DialogflowConfig
     */
    @Test
    public void testDialogflowConfig() {
        // TODO: test DialogflowConfig
    }

    /**
     * Test the property 'analyzeSentiment'
     */
    @Test
    public void analyzeSentimentTest() {
        // TODO: test analyzeSentiment
    }

    /**
     * Test the property 'partialAutomatedAgentReply'
     */
    @Test
    public void partialAutomatedAgentReplyTest() {
        // TODO: test partialAutomatedAgentReply
    }
}
