/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.telnyx.sdk.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetUploadsStatusResponseData
 */
public class GetUploadsStatusResponseDataTest {

    private final GetUploadsStatusResponseData model =
        new GetUploadsStatusResponseData();

    /**
     * Model tests for GetUploadsStatusResponseData
     */
    @Test
    public void testGetUploadsStatusResponseData() {
        // TODO: test GetUploadsStatusResponseData
    }

    /**
     * Test the property 'pendingNumbersCount'
     */
    @Test
    public void pendingNumbersCountTest() {
        // TODO: test pendingNumbersCount
    }

    /**
     * Test the property 'pendingOrdersCount'
     */
    @Test
    public void pendingOrdersCountTest() {
        // TODO: test pendingOrdersCount
    }
}
