/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.telnyx.sdk.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.telnyx.sdk.model.LogMessage;
import com.telnyx.sdk.model.PaginationMeta;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListLogMessagesResponse
 */
public class ListLogMessagesResponseTest {

    private final ListLogMessagesResponse model = new ListLogMessagesResponse();

    /**
     * Model tests for ListLogMessagesResponse
     */
    @Test
    public void testListLogMessagesResponse() {
        // TODO: test ListLogMessagesResponse
    }

    /**
     * Test the property 'logMessages'
     */
    @Test
    public void logMessagesTest() {
        // TODO: test logMessages
    }

    /**
     * Test the property 'meta'
     */
    @Test
    public void metaTest() {
        // TODO: test meta
    }
}
