/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.telnyx.sdk.model.PortingOrderType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PortingOrderMisc
 */
public class PortingOrderMiscTest {
    private final PortingOrderMisc model = new PortingOrderMisc();

    /**
     * Model tests for PortingOrderMisc
     */
    @Test
    public void testPortingOrderMisc() {
        // TODO: test PortingOrderMisc
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'remainingNumbersAction'
     */
    @Test
    public void remainingNumbersActionTest() {
        // TODO: test remainingNumbersAction
    }

    /**
     * Test the property 'newBillingPhoneNumber'
     */
    @Test
    public void newBillingPhoneNumberTest() {
        // TODO: test newBillingPhoneNumber
    }

}
