/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.telnyx.sdk.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RecordingResponseDataDownloadUrls
 */
public class RecordingResponseDataDownloadUrlsTest {

    private final RecordingResponseDataDownloadUrls model =
        new RecordingResponseDataDownloadUrls();

    /**
     * Model tests for RecordingResponseDataDownloadUrls
     */
    @Test
    public void testRecordingResponseDataDownloadUrls() {
        // TODO: test RecordingResponseDataDownloadUrls
    }

    /**
     * Test the property 'mp3'
     */
    @Test
    public void mp3Test() {
        // TODO: test mp3
    }

    /**
     * Test the property 'wav'
     */
    @Test
    public void wavTest() {
        // TODO: test wav
    }
}
