/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import org.junit.Test;

/**
 * Model tests for UpdatePhoneNumberRequest
 */
public class UpdatePhoneNumberRequestTest {
    private final UpdatePhoneNumberRequest model = new UpdatePhoneNumberRequest();

    /**
     * Model tests for UpdatePhoneNumberRequest
     */
    @Test
    public void testUpdatePhoneNumberRequest() {
        // TODO: test UpdatePhoneNumberRequest
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'externalPin'
     */
    @Test
    public void externalPinTest() {
        // TODO: test externalPin
    }

    /**
     * Test the property 'connectionId'
     */
    @Test
    public void connectionIdTest() {
        // TODO: test connectionId
    }

    /**
     * Test the property 'billingGroupId'
     */
    @Test
    public void billingGroupIdTest() {
        // TODO: test billingGroupId
    }

}
