/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.telnyx.sdk.model.PortingOrderDocuments;
import com.telnyx.sdk.model.PortingOrderEndUser;
import com.telnyx.sdk.model.PortingOrderMisc;
import com.telnyx.sdk.model.PortingOrderPhoneNumberConfiguration;
import com.telnyx.sdk.model.PortingOrderUserFeedback;
import com.telnyx.sdk.model.UpdatePortingOrderActivationSettings;
import com.telnyx.sdk.model.UpdatePortingOrderRequirement;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import org.junit.Test;

/**
 * Model tests for UpdatePortingOrder
 */
public class UpdatePortingOrderTest {
    private final UpdatePortingOrder model = new UpdatePortingOrder();

    /**
     * Model tests for UpdatePortingOrder
     */
    @Test
    public void testUpdatePortingOrder() {
        // TODO: test UpdatePortingOrder
    }

    /**
     * Test the property 'misc'
     */
    @Test
    public void miscTest() {
        // TODO: test misc
    }

    /**
     * Test the property 'endUser'
     */
    @Test
    public void endUserTest() {
        // TODO: test endUser
    }

    /**
     * Test the property 'documents'
     */
    @Test
    public void documentsTest() {
        // TODO: test documents
    }

    /**
     * Test the property 'activationSettings'
     */
    @Test
    public void activationSettingsTest() {
        // TODO: test activationSettings
    }

    /**
     * Test the property 'phoneNumberConfiguration'
     */
    @Test
    public void phoneNumberConfigurationTest() {
        // TODO: test phoneNumberConfiguration
    }

    /**
     * Test the property 'requirements'
     */
    @Test
    public void requirementsTest() {
        // TODO: test requirements
    }

    /**
     * Test the property 'userFeedback'
     */
    @Test
    public void userFeedbackTest() {
        // TODO: test userFeedback
    }

    /**
     * Test the property 'webhookUrl'
     */
    @Test
    public void webhookUrlTest() {
        // TODO: test webhookUrl
    }

    /**
     * Test the property 'customerReference'
     */
    @Test
    public void customerReferenceTest() {
        // TODO: test customerReference
    }

}
