/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VerifiedCallsDisplayProfileCallReasons
 */
public class VerifiedCallsDisplayProfileCallReasonsTest {
    private final VerifiedCallsDisplayProfileCallReasons model = new VerifiedCallsDisplayProfileCallReasons();

    /**
     * Model tests for VerifiedCallsDisplayProfileCallReasons
     */
    @Test
    public void testVerifiedCallsDisplayProfileCallReasons() {
        // TODO: test VerifiedCallsDisplayProfileCallReasons
    }

    /**
     * Test the property 'recordType'
     */
    @Test
    public void recordTypeTest() {
        // TODO: test recordType
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'googleVerificationStatus'
     */
    @Test
    public void googleVerificationStatusTest() {
        // TODO: test googleVerificationStatus
    }

    /**
     * Test the property 'googleApprovalInfo'
     */
    @Test
    public void googleApprovalInfoTest() {
        // TODO: test googleApprovalInfo
    }

    /**
     * Test the property 'displayProfileId'
     */
    @Test
    public void displayProfileIdTest() {
        // TODO: test displayProfileId
    }

    /**
     * Test the property 'delete'
     */
    @Test
    public void deleteTest() {
        // TODO: test delete
    }

}
