/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VirtualCrossConnect1
 */
public class VirtualCrossConnect1Test {
    private final VirtualCrossConnect1 model = new VirtualCrossConnect1();

    /**
     * Model tests for VirtualCrossConnect1
     */
    @Test
    public void testVirtualCrossConnect1() {
        // TODO: test VirtualCrossConnect1
    }

    /**
     * Test the property 'recordType'
     */
    @Test
    public void recordTypeTest() {
        // TODO: test recordType
    }

    /**
     * Test the property 'cloudProvider'
     */
    @Test
    public void cloudProviderTest() {
        // TODO: test cloudProvider
    }

    /**
     * Test the property 'cloudRegion'
     */
    @Test
    public void cloudRegionTest() {
        // TODO: test cloudRegion
    }

    /**
     * Test the property 'bgpAsn'
     */
    @Test
    public void bgpAsnTest() {
        // TODO: test bgpAsn
    }

    /**
     * Test the property 'bandwidthMbps'
     */
    @Test
    public void bandwidthMbpsTest() {
        // TODO: test bandwidthMbps
    }

    /**
     * Test the property 'primaryEnabled'
     */
    @Test
    public void primaryEnabledTest() {
        // TODO: test primaryEnabled
    }

    /**
     * Test the property 'primaryCloudAccountId'
     */
    @Test
    public void primaryCloudAccountIdTest() {
        // TODO: test primaryCloudAccountId
    }

    /**
     * Test the property 'primaryTelnyxIp'
     */
    @Test
    public void primaryTelnyxIpTest() {
        // TODO: test primaryTelnyxIp
    }

    /**
     * Test the property 'primaryCloudIp'
     */
    @Test
    public void primaryCloudIpTest() {
        // TODO: test primaryCloudIp
    }

    /**
     * Test the property 'primaryBgpKey'
     */
    @Test
    public void primaryBgpKeyTest() {
        // TODO: test primaryBgpKey
    }

    /**
     * Test the property 'secondaryEnabled'
     */
    @Test
    public void secondaryEnabledTest() {
        // TODO: test secondaryEnabled
    }

    /**
     * Test the property 'secondaryCloudAccountId'
     */
    @Test
    public void secondaryCloudAccountIdTest() {
        // TODO: test secondaryCloudAccountId
    }

    /**
     * Test the property 'secondaryTelnyxIp'
     */
    @Test
    public void secondaryTelnyxIpTest() {
        // TODO: test secondaryTelnyxIp
    }

    /**
     * Test the property 'secondaryCloudIp'
     */
    @Test
    public void secondaryCloudIpTest() {
        // TODO: test secondaryCloudIp
    }

    /**
     * Test the property 'secondaryBgpKey'
     */
    @Test
    public void secondaryBgpKeyTest() {
        // TODO: test secondaryBgpKey
    }

}
