// File generated from our OpenAPI spec by Stainless.

package com.telnyx.api.models.campaignbuilder

import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CampaignBuilderCreateParamsTest {

    @Test
    fun create() {
        CampaignBuilderCreateParams.builder()
            .brandId("brandId")
            .description("description")
            .usecase("usecase")
            .ageGated(true)
            .autoRenewal(true)
            .directLending(true)
            .embeddedLink(true)
            .embeddedLinkSample("embeddedLinkSample")
            .embeddedPhone(true)
            .helpKeywords("helpKeywords")
            .helpMessage("helpMessage")
            .messageFlow("messageFlow")
            .addMnoId(0L)
            .numberPool(true)
            .optinKeywords("optinKeywords")
            .optinMessage("optinMessage")
            .optoutKeywords("optoutKeywords")
            .optoutMessage("optoutMessage")
            .privacyPolicyLink("privacyPolicyLink")
            .referenceId("referenceId")
            .resellerId("resellerId")
            .sample1("sample1")
            .sample2("sample2")
            .sample3("sample3")
            .sample4("sample4")
            .sample5("sample5")
            .subscriberHelp(true)
            .subscriberOptin(true)
            .subscriberOptout(true)
            .addSubUsecase("string")
            .addTag("string")
            .termsAndConditions(true)
            .termsAndConditionsLink("termsAndConditionsLink")
            .webhookFailoverUrl("https://webhook.com/93711262-23e5-4048-a966-c0b2a16d5963")
            .webhookUrl("https://webhook.com/67ea78a8-9f32-4d04-b62d-f9502e8e5f93")
            .build()
    }

    @Test
    fun body() {
        val params =
            CampaignBuilderCreateParams.builder()
                .brandId("brandId")
                .description("description")
                .usecase("usecase")
                .ageGated(true)
                .autoRenewal(true)
                .directLending(true)
                .embeddedLink(true)
                .embeddedLinkSample("embeddedLinkSample")
                .embeddedPhone(true)
                .helpKeywords("helpKeywords")
                .helpMessage("helpMessage")
                .messageFlow("messageFlow")
                .addMnoId(0L)
                .numberPool(true)
                .optinKeywords("optinKeywords")
                .optinMessage("optinMessage")
                .optoutKeywords("optoutKeywords")
                .optoutMessage("optoutMessage")
                .privacyPolicyLink("privacyPolicyLink")
                .referenceId("referenceId")
                .resellerId("resellerId")
                .sample1("sample1")
                .sample2("sample2")
                .sample3("sample3")
                .sample4("sample4")
                .sample5("sample5")
                .subscriberHelp(true)
                .subscriberOptin(true)
                .subscriberOptout(true)
                .addSubUsecase("string")
                .addTag("string")
                .termsAndConditions(true)
                .termsAndConditionsLink("termsAndConditionsLink")
                .webhookFailoverUrl("https://webhook.com/93711262-23e5-4048-a966-c0b2a16d5963")
                .webhookUrl("https://webhook.com/67ea78a8-9f32-4d04-b62d-f9502e8e5f93")
                .build()

        val body = params._body()

        assertThat(body.brandId()).isEqualTo("brandId")
        assertThat(body.description()).isEqualTo("description")
        assertThat(body.usecase()).isEqualTo("usecase")
        assertThat(body.ageGated()).contains(true)
        assertThat(body.autoRenewal()).contains(true)
        assertThat(body.directLending()).contains(true)
        assertThat(body.embeddedLink()).contains(true)
        assertThat(body.embeddedLinkSample()).contains("embeddedLinkSample")
        assertThat(body.embeddedPhone()).contains(true)
        assertThat(body.helpKeywords()).contains("helpKeywords")
        assertThat(body.helpMessage()).contains("helpMessage")
        assertThat(body.messageFlow()).contains("messageFlow")
        assertThat(body.mnoIds().getOrNull()).containsExactly(0L)
        assertThat(body.numberPool()).contains(true)
        assertThat(body.optinKeywords()).contains("optinKeywords")
        assertThat(body.optinMessage()).contains("optinMessage")
        assertThat(body.optoutKeywords()).contains("optoutKeywords")
        assertThat(body.optoutMessage()).contains("optoutMessage")
        assertThat(body.privacyPolicyLink()).contains("privacyPolicyLink")
        assertThat(body.referenceId()).contains("referenceId")
        assertThat(body.resellerId()).contains("resellerId")
        assertThat(body.sample1()).contains("sample1")
        assertThat(body.sample2()).contains("sample2")
        assertThat(body.sample3()).contains("sample3")
        assertThat(body.sample4()).contains("sample4")
        assertThat(body.sample5()).contains("sample5")
        assertThat(body.subscriberHelp()).contains(true)
        assertThat(body.subscriberOptin()).contains(true)
        assertThat(body.subscriberOptout()).contains(true)
        assertThat(body.subUsecases().getOrNull()).containsExactly("string")
        assertThat(body.tag().getOrNull()).containsExactly("string")
        assertThat(body.termsAndConditions()).contains(true)
        assertThat(body.termsAndConditionsLink()).contains("termsAndConditionsLink")
        assertThat(body.webhookFailoverUrl())
            .contains("https://webhook.com/93711262-23e5-4048-a966-c0b2a16d5963")
        assertThat(body.webhookUrl())
            .contains("https://webhook.com/67ea78a8-9f32-4d04-b62d-f9502e8e5f93")
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            CampaignBuilderCreateParams.builder()
                .brandId("brandId")
                .description("description")
                .usecase("usecase")
                .build()

        val body = params._body()

        assertThat(body.brandId()).isEqualTo("brandId")
        assertThat(body.description()).isEqualTo("description")
        assertThat(body.usecase()).isEqualTo("usecase")
    }
}
