/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.api;

import com.telnyx.sdk.*;
import com.telnyx.sdk.auth.*;
import com.telnyx.sdk.model.Errors;
import com.telnyx.sdk.model.InventoryCoverageResponse;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InventoryLevelApi
 */
public class InventoryLevelApiTest {

    private final InventoryLevelApi api = new InventoryLevelApi();

    /**
     * Create an inventory coverage request
     *
     * Creates an inventory coverage request. If locality, npa or national_destination_code is used in groupBy, and no region or locality filters are used, the whole paginated set is returned.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createInventoryCoverageRequestTest() throws ApiException {
        //String filterGroupBy = null;
        //Integer filterNpa = null;
        //Integer filterNxx = null;
        //String filterAdministrativeArea = null;
        //String filterPhoneNumberType = null;
        //String filterCountryCode = null;
        //Boolean filterCount = null;
        //InventoryCoverageResponse response = api.createInventoryCoverageRequest(filterGroupBy, filterNpa, filterNxx, filterAdministrativeArea, filterPhoneNumberType, filterCountryCode, filterCount);
        // TODO: test validations
    }

}
