/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.telnyx.sdk.api;

import com.telnyx.sdk.*;
import com.telnyx.sdk.auth.*;
import com.telnyx.sdk.model.Errors;
import com.telnyx.sdk.model.SiprecConnector;
import com.telnyx.sdk.model.SiprecConnectorResponse;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for SiprecConnectorApi
 */
public class SiprecConnectorApiTest {

    private final SiprecConnectorApi api = new SiprecConnectorApi();

    /**
     * Creates a siprec connector
     *
     * Saves a siprec connector configuration.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSiprecConnectorTest() throws ApiException {
        //SiprecConnector siprecConnector = null;
        //SiprecConnectorResponse response = api.createSiprecConnector(siprecConnector);
        // TODO: test validations
    }

    /**
     * Delete stored Siprec Connection
     *
     * Deletes a stored Siprec Connection.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSiprecConnectionTest() throws ApiException {
        //String siprecConnectorName = null;
        //api.deleteSiprecConnection(siprecConnectorName);
        // TODO: test validations
    }

    /**
     * Retrieve stored Siprec Connection
     *
     * Return details of the Siprec connection.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSiprecConnectionTest() throws ApiException {
        //String siprecConnectorName = null;
        //SiprecConnectorResponse response = api.getSiprecConnection(siprecConnectorName);
        // TODO: test validations
    }

    /**
     * Update stored SIPREC connector
     *
     * Updates a stored SIPREC connector
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSiprecConnectorTest() throws ApiException {
        //String siprecConnectorName = null;
        //SiprecConnector siprecConnector = null;
        //SiprecConnectorResponse response = api.updateSiprecConnector(siprecConnectorName, siprecConnector);
        // TODO: test validations
    }
}
