// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.mobilephonenumbers

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class MobilePhoneNumberUpdateResponseTest {

    @Test
    fun create() {
        val mobilePhoneNumberUpdateResponse =
            MobilePhoneNumberUpdateResponse.builder()
                .data(
                    MobilePhoneNumberUpdateResponse.Data.builder()
                        .id("id")
                        .callForwarding(
                            MobilePhoneNumberUpdateResponse.Data.CallForwarding.builder()
                                .callForwardingEnabled(true)
                                .forwardingType(
                                    MobilePhoneNumberUpdateResponse.Data.CallForwarding
                                        .ForwardingType
                                        .ALWAYS
                                )
                                .forwardsTo("forwards_to")
                                .build()
                        )
                        .callRecording(
                            MobilePhoneNumberUpdateResponse.Data.CallRecording.builder()
                                .inboundCallRecordingChannels(
                                    MobilePhoneNumberUpdateResponse.Data.CallRecording
                                        .InboundCallRecordingChannels
                                        .SINGLE
                                )
                                .inboundCallRecordingEnabled(true)
                                .inboundCallRecordingFormat(
                                    MobilePhoneNumberUpdateResponse.Data.CallRecording
                                        .InboundCallRecordingFormat
                                        .WAV
                                )
                                .build()
                        )
                        .callerIdNameEnabled(true)
                        .cnamListing(
                            MobilePhoneNumberUpdateResponse.Data.CnamListing.builder()
                                .cnamListingDetails("cnam_listing_details")
                                .cnamListingEnabled(true)
                                .build()
                        )
                        .connectionId("connection_id")
                        .connectionName("connection_name")
                        .connectionType("connection_type")
                        .countryIsoAlpha2("country_iso_alpha2")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .customerReference("customer_reference")
                        .inbound(
                            MobilePhoneNumberUpdateResponse.Data.Inbound.builder()
                                .interceptionAppId("interception_app_id")
                                .interceptionAppName("interception_app_name")
                                .build()
                        )
                        .inboundCallScreening(
                            MobilePhoneNumberUpdateResponse.Data.InboundCallScreening.DISABLED
                        )
                        .mobileVoiceEnabled(true)
                        .noiseSuppression(
                            MobilePhoneNumberUpdateResponse.Data.NoiseSuppression.INBOUND
                        )
                        .outbound(
                            MobilePhoneNumberUpdateResponse.Data.Outbound.builder()
                                .interceptionAppId("interception_app_id")
                                .interceptionAppName("interception_app_name")
                                .build()
                        )
                        .phoneNumber("phone_number")
                        .recordType("mobile_phone_number")
                        .simCardId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .status("status")
                        .addTag("string")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .build()

        assertThat(mobilePhoneNumberUpdateResponse.data())
            .contains(
                MobilePhoneNumberUpdateResponse.Data.builder()
                    .id("id")
                    .callForwarding(
                        MobilePhoneNumberUpdateResponse.Data.CallForwarding.builder()
                            .callForwardingEnabled(true)
                            .forwardingType(
                                MobilePhoneNumberUpdateResponse.Data.CallForwarding.ForwardingType
                                    .ALWAYS
                            )
                            .forwardsTo("forwards_to")
                            .build()
                    )
                    .callRecording(
                        MobilePhoneNumberUpdateResponse.Data.CallRecording.builder()
                            .inboundCallRecordingChannels(
                                MobilePhoneNumberUpdateResponse.Data.CallRecording
                                    .InboundCallRecordingChannels
                                    .SINGLE
                            )
                            .inboundCallRecordingEnabled(true)
                            .inboundCallRecordingFormat(
                                MobilePhoneNumberUpdateResponse.Data.CallRecording
                                    .InboundCallRecordingFormat
                                    .WAV
                            )
                            .build()
                    )
                    .callerIdNameEnabled(true)
                    .cnamListing(
                        MobilePhoneNumberUpdateResponse.Data.CnamListing.builder()
                            .cnamListingDetails("cnam_listing_details")
                            .cnamListingEnabled(true)
                            .build()
                    )
                    .connectionId("connection_id")
                    .connectionName("connection_name")
                    .connectionType("connection_type")
                    .countryIsoAlpha2("country_iso_alpha2")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .customerReference("customer_reference")
                    .inbound(
                        MobilePhoneNumberUpdateResponse.Data.Inbound.builder()
                            .interceptionAppId("interception_app_id")
                            .interceptionAppName("interception_app_name")
                            .build()
                    )
                    .inboundCallScreening(
                        MobilePhoneNumberUpdateResponse.Data.InboundCallScreening.DISABLED
                    )
                    .mobileVoiceEnabled(true)
                    .noiseSuppression(MobilePhoneNumberUpdateResponse.Data.NoiseSuppression.INBOUND)
                    .outbound(
                        MobilePhoneNumberUpdateResponse.Data.Outbound.builder()
                            .interceptionAppId("interception_app_id")
                            .interceptionAppName("interception_app_name")
                            .build()
                    )
                    .phoneNumber("phone_number")
                    .recordType("mobile_phone_number")
                    .simCardId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .status("status")
                    .addTag("string")
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val mobilePhoneNumberUpdateResponse =
            MobilePhoneNumberUpdateResponse.builder()
                .data(
                    MobilePhoneNumberUpdateResponse.Data.builder()
                        .id("id")
                        .callForwarding(
                            MobilePhoneNumberUpdateResponse.Data.CallForwarding.builder()
                                .callForwardingEnabled(true)
                                .forwardingType(
                                    MobilePhoneNumberUpdateResponse.Data.CallForwarding
                                        .ForwardingType
                                        .ALWAYS
                                )
                                .forwardsTo("forwards_to")
                                .build()
                        )
                        .callRecording(
                            MobilePhoneNumberUpdateResponse.Data.CallRecording.builder()
                                .inboundCallRecordingChannels(
                                    MobilePhoneNumberUpdateResponse.Data.CallRecording
                                        .InboundCallRecordingChannels
                                        .SINGLE
                                )
                                .inboundCallRecordingEnabled(true)
                                .inboundCallRecordingFormat(
                                    MobilePhoneNumberUpdateResponse.Data.CallRecording
                                        .InboundCallRecordingFormat
                                        .WAV
                                )
                                .build()
                        )
                        .callerIdNameEnabled(true)
                        .cnamListing(
                            MobilePhoneNumberUpdateResponse.Data.CnamListing.builder()
                                .cnamListingDetails("cnam_listing_details")
                                .cnamListingEnabled(true)
                                .build()
                        )
                        .connectionId("connection_id")
                        .connectionName("connection_name")
                        .connectionType("connection_type")
                        .countryIsoAlpha2("country_iso_alpha2")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .customerReference("customer_reference")
                        .inbound(
                            MobilePhoneNumberUpdateResponse.Data.Inbound.builder()
                                .interceptionAppId("interception_app_id")
                                .interceptionAppName("interception_app_name")
                                .build()
                        )
                        .inboundCallScreening(
                            MobilePhoneNumberUpdateResponse.Data.InboundCallScreening.DISABLED
                        )
                        .mobileVoiceEnabled(true)
                        .noiseSuppression(
                            MobilePhoneNumberUpdateResponse.Data.NoiseSuppression.INBOUND
                        )
                        .outbound(
                            MobilePhoneNumberUpdateResponse.Data.Outbound.builder()
                                .interceptionAppId("interception_app_id")
                                .interceptionAppName("interception_app_name")
                                .build()
                        )
                        .phoneNumber("phone_number")
                        .recordType("mobile_phone_number")
                        .simCardId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .status("status")
                        .addTag("string")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .build()

        val roundtrippedMobilePhoneNumberUpdateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(mobilePhoneNumberUpdateResponse),
                jacksonTypeRef<MobilePhoneNumberUpdateResponse>(),
            )

        assertThat(roundtrippedMobilePhoneNumberUpdateResponse)
            .isEqualTo(mobilePhoneNumberUpdateResponse)
    }
}
