// File generated from our OpenAPI spec by Stainless.

package com.telnyx.api.models.portingorders

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.api.core.jsonMapper
import com.telnyx.api.models.PortingOrderStatus
import com.telnyx.api.models.PortingOrdersExceptionType
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PortingOrderCreateResponseTest {

    @Test
    fun create() {
        val portingOrderCreateResponse =
            PortingOrderCreateResponse.builder()
                .addData(
                    PortingOrder.builder()
                        .id("b0ea6d6f-de31-4079-a536-992e0c98b037")
                        .activationSettings(
                            PortingOrderActivationSettings.builder()
                                .activationStatus(
                                    PortingOrderActivationSettings.ActivationStatus.NEW
                                )
                                .fastPortEligible(true)
                                .focDatetimeActual(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .focDatetimeRequested(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .build()
                        )
                        .addAdditionalStep(PortingOrder.AdditionalStep.ASSOCIATED_PHONE_NUMBERS)
                        .createdAt(OffsetDateTime.parse("2022-03-17T18:01:01Z"))
                        .customerGroupReference("customer_group_reference")
                        .customerReference("customer_reference")
                        .description("FP Telnyx")
                        .documents(
                            PortingOrderDocuments.builder()
                                .invoice("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .loa("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .endUser(
                            PortingOrderEndUser.builder()
                                .admin(
                                    PortingOrderEndUserAdmin.builder()
                                        .accountNumber("account_number")
                                        .authPersonName("auth_person_name")
                                        .billingPhoneNumber("billing_phone_number")
                                        .businessIdentifier("business_identifier")
                                        .entityName("entity_name")
                                        .pinPasscode("pin_passcode")
                                        .taxIdentifier("tax_identifier")
                                        .build()
                                )
                                .location(
                                    PortingOrderEndUserLocation.builder()
                                        .administrativeArea("administrative_area")
                                        .countryCode("country_code")
                                        .extendedAddress("extended_address")
                                        .locality("locality")
                                        .postalCode("postal_code")
                                        .streetAddress("street_address")
                                        .build()
                                )
                                .build()
                        )
                        .messaging(
                            PortingOrderMessaging.builder()
                                .enableMessaging(false)
                                .messagingCapable(true)
                                .messagingPortCompleted(false)
                                .messagingPortStatus(
                                    PortingOrderMessaging.MessagingPortStatus.NOT_APPLICABLE
                                )
                                .build()
                        )
                        .misc(
                            PortingOrderMisc.builder()
                                .newBillingPhoneNumber("new_billing_phone_number")
                                .remainingNumbersAction(
                                    PortingOrderMisc.RemainingNumbersAction.DISCONNECT
                                )
                                .type(PortingOrderType.FULL)
                                .build()
                        )
                        .oldServiceProviderOcn("Unreal Communications")
                        .parentSupportKey("parent_support_key")
                        .phoneNumberConfiguration(
                            PortingOrderPhoneNumberConfiguration.builder()
                                .billingGroupId("billing_group_id")
                                .connectionId("connection_id")
                                .emergencyAddressId("emergency_address_id")
                                .messagingProfileId("messaging_profile_id")
                                .addTag("string")
                                .build()
                        )
                        .phoneNumberType(PortingOrder.PhoneNumberType.LOCAL)
                        .portingPhoneNumbersCount(1L)
                        .recordType("porting_order")
                        .addRequirement(
                            PortingOrderRequirement.builder()
                                .fieldType(PortingOrderRequirement.FieldType.DOCUMENT)
                                .fieldValue("9787fb5f-cbe5-4de4-b765-3303774ee9fe")
                                .recordType("porting_requirement")
                                .requirementTypeId("59b0762a-b274-4f76-ac32-4d5cf0272e66")
                                .build()
                        )
                        .requirementsMet(false)
                        .status(
                            PortingOrderStatus.builder()
                                .addDetail(
                                    PortingOrdersExceptionType.builder()
                                        .code(PortingOrdersExceptionType.Code.ENTITY_NAME_MISMATCH)
                                        .description("Entity name does not match that on the CSR")
                                        .build()
                                )
                                .value(PortingOrderStatus.Value.DRAFT)
                                .build()
                        )
                        .supportKey("support_key")
                        .updatedAt(OffsetDateTime.parse("2022-03-17T18:01:01Z"))
                        .userFeedback(
                            PortingOrderUserFeedback.builder()
                                .userComment("user_comment")
                                .userRating(0L)
                                .build()
                        )
                        .userId("40d68ba2-0847-4df2-be9c-b0e0cb673e75")
                        .webhookUrl("https://example.com")
                        .build()
                )
                .build()

        assertThat(portingOrderCreateResponse.data().getOrNull())
            .containsExactly(
                PortingOrder.builder()
                    .id("b0ea6d6f-de31-4079-a536-992e0c98b037")
                    .activationSettings(
                        PortingOrderActivationSettings.builder()
                            .activationStatus(PortingOrderActivationSettings.ActivationStatus.NEW)
                            .fastPortEligible(true)
                            .focDatetimeActual(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .focDatetimeRequested(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .addAdditionalStep(PortingOrder.AdditionalStep.ASSOCIATED_PHONE_NUMBERS)
                    .createdAt(OffsetDateTime.parse("2022-03-17T18:01:01Z"))
                    .customerGroupReference("customer_group_reference")
                    .customerReference("customer_reference")
                    .description("FP Telnyx")
                    .documents(
                        PortingOrderDocuments.builder()
                            .invoice("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .loa("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .build()
                    )
                    .endUser(
                        PortingOrderEndUser.builder()
                            .admin(
                                PortingOrderEndUserAdmin.builder()
                                    .accountNumber("account_number")
                                    .authPersonName("auth_person_name")
                                    .billingPhoneNumber("billing_phone_number")
                                    .businessIdentifier("business_identifier")
                                    .entityName("entity_name")
                                    .pinPasscode("pin_passcode")
                                    .taxIdentifier("tax_identifier")
                                    .build()
                            )
                            .location(
                                PortingOrderEndUserLocation.builder()
                                    .administrativeArea("administrative_area")
                                    .countryCode("country_code")
                                    .extendedAddress("extended_address")
                                    .locality("locality")
                                    .postalCode("postal_code")
                                    .streetAddress("street_address")
                                    .build()
                            )
                            .build()
                    )
                    .messaging(
                        PortingOrderMessaging.builder()
                            .enableMessaging(false)
                            .messagingCapable(true)
                            .messagingPortCompleted(false)
                            .messagingPortStatus(
                                PortingOrderMessaging.MessagingPortStatus.NOT_APPLICABLE
                            )
                            .build()
                    )
                    .misc(
                        PortingOrderMisc.builder()
                            .newBillingPhoneNumber("new_billing_phone_number")
                            .remainingNumbersAction(
                                PortingOrderMisc.RemainingNumbersAction.DISCONNECT
                            )
                            .type(PortingOrderType.FULL)
                            .build()
                    )
                    .oldServiceProviderOcn("Unreal Communications")
                    .parentSupportKey("parent_support_key")
                    .phoneNumberConfiguration(
                        PortingOrderPhoneNumberConfiguration.builder()
                            .billingGroupId("billing_group_id")
                            .connectionId("connection_id")
                            .emergencyAddressId("emergency_address_id")
                            .messagingProfileId("messaging_profile_id")
                            .addTag("string")
                            .build()
                    )
                    .phoneNumberType(PortingOrder.PhoneNumberType.LOCAL)
                    .portingPhoneNumbersCount(1L)
                    .recordType("porting_order")
                    .addRequirement(
                        PortingOrderRequirement.builder()
                            .fieldType(PortingOrderRequirement.FieldType.DOCUMENT)
                            .fieldValue("9787fb5f-cbe5-4de4-b765-3303774ee9fe")
                            .recordType("porting_requirement")
                            .requirementTypeId("59b0762a-b274-4f76-ac32-4d5cf0272e66")
                            .build()
                    )
                    .requirementsMet(false)
                    .status(
                        PortingOrderStatus.builder()
                            .addDetail(
                                PortingOrdersExceptionType.builder()
                                    .code(PortingOrdersExceptionType.Code.ENTITY_NAME_MISMATCH)
                                    .description("Entity name does not match that on the CSR")
                                    .build()
                            )
                            .value(PortingOrderStatus.Value.DRAFT)
                            .build()
                    )
                    .supportKey("support_key")
                    .updatedAt(OffsetDateTime.parse("2022-03-17T18:01:01Z"))
                    .userFeedback(
                        PortingOrderUserFeedback.builder()
                            .userComment("user_comment")
                            .userRating(0L)
                            .build()
                    )
                    .userId("40d68ba2-0847-4df2-be9c-b0e0cb673e75")
                    .webhookUrl("https://example.com")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val portingOrderCreateResponse =
            PortingOrderCreateResponse.builder()
                .addData(
                    PortingOrder.builder()
                        .id("b0ea6d6f-de31-4079-a536-992e0c98b037")
                        .activationSettings(
                            PortingOrderActivationSettings.builder()
                                .activationStatus(
                                    PortingOrderActivationSettings.ActivationStatus.NEW
                                )
                                .fastPortEligible(true)
                                .focDatetimeActual(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .focDatetimeRequested(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .build()
                        )
                        .addAdditionalStep(PortingOrder.AdditionalStep.ASSOCIATED_PHONE_NUMBERS)
                        .createdAt(OffsetDateTime.parse("2022-03-17T18:01:01Z"))
                        .customerGroupReference("customer_group_reference")
                        .customerReference("customer_reference")
                        .description("FP Telnyx")
                        .documents(
                            PortingOrderDocuments.builder()
                                .invoice("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .loa("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .endUser(
                            PortingOrderEndUser.builder()
                                .admin(
                                    PortingOrderEndUserAdmin.builder()
                                        .accountNumber("account_number")
                                        .authPersonName("auth_person_name")
                                        .billingPhoneNumber("billing_phone_number")
                                        .businessIdentifier("business_identifier")
                                        .entityName("entity_name")
                                        .pinPasscode("pin_passcode")
                                        .taxIdentifier("tax_identifier")
                                        .build()
                                )
                                .location(
                                    PortingOrderEndUserLocation.builder()
                                        .administrativeArea("administrative_area")
                                        .countryCode("country_code")
                                        .extendedAddress("extended_address")
                                        .locality("locality")
                                        .postalCode("postal_code")
                                        .streetAddress("street_address")
                                        .build()
                                )
                                .build()
                        )
                        .messaging(
                            PortingOrderMessaging.builder()
                                .enableMessaging(false)
                                .messagingCapable(true)
                                .messagingPortCompleted(false)
                                .messagingPortStatus(
                                    PortingOrderMessaging.MessagingPortStatus.NOT_APPLICABLE
                                )
                                .build()
                        )
                        .misc(
                            PortingOrderMisc.builder()
                                .newBillingPhoneNumber("new_billing_phone_number")
                                .remainingNumbersAction(
                                    PortingOrderMisc.RemainingNumbersAction.DISCONNECT
                                )
                                .type(PortingOrderType.FULL)
                                .build()
                        )
                        .oldServiceProviderOcn("Unreal Communications")
                        .parentSupportKey("parent_support_key")
                        .phoneNumberConfiguration(
                            PortingOrderPhoneNumberConfiguration.builder()
                                .billingGroupId("billing_group_id")
                                .connectionId("connection_id")
                                .emergencyAddressId("emergency_address_id")
                                .messagingProfileId("messaging_profile_id")
                                .addTag("string")
                                .build()
                        )
                        .phoneNumberType(PortingOrder.PhoneNumberType.LOCAL)
                        .portingPhoneNumbersCount(1L)
                        .recordType("porting_order")
                        .addRequirement(
                            PortingOrderRequirement.builder()
                                .fieldType(PortingOrderRequirement.FieldType.DOCUMENT)
                                .fieldValue("9787fb5f-cbe5-4de4-b765-3303774ee9fe")
                                .recordType("porting_requirement")
                                .requirementTypeId("59b0762a-b274-4f76-ac32-4d5cf0272e66")
                                .build()
                        )
                        .requirementsMet(false)
                        .status(
                            PortingOrderStatus.builder()
                                .addDetail(
                                    PortingOrdersExceptionType.builder()
                                        .code(PortingOrdersExceptionType.Code.ENTITY_NAME_MISMATCH)
                                        .description("Entity name does not match that on the CSR")
                                        .build()
                                )
                                .value(PortingOrderStatus.Value.DRAFT)
                                .build()
                        )
                        .supportKey("support_key")
                        .updatedAt(OffsetDateTime.parse("2022-03-17T18:01:01Z"))
                        .userFeedback(
                            PortingOrderUserFeedback.builder()
                                .userComment("user_comment")
                                .userRating(0L)
                                .build()
                        )
                        .userId("40d68ba2-0847-4df2-be9c-b0e0cb673e75")
                        .webhookUrl("https://example.com")
                        .build()
                )
                .build()

        val roundtrippedPortingOrderCreateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(portingOrderCreateResponse),
                jacksonTypeRef<PortingOrderCreateResponse>(),
            )

        assertThat(roundtrippedPortingOrderCreateResponse).isEqualTo(portingOrderCreateResponse)
    }
}
