// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.webhooks

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.JsonValue
import com.telnyx.sdk.core.jsonMapper
import com.telnyx.sdk.models.messages.MessagingError0b38e7044b
import com.telnyx.sdk.models.messages.MessagingInboundMessagePayload
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class MessagingInboundMessageTest {

    @Test
    fun create() {
        val messagingInboundMessage =
            MessagingInboundMessage.builder()
                .id("bf6307bd-884d-4c1f-b6ea-c62b8c495d3c")
                .eventType(MessagingInboundMessage.EventType.MESSAGE_RECEIVED)
                .occurredAt(OffsetDateTime.parse("2019-01-23T18:10:02.574Z"))
                .payload(
                    MessagingInboundMessagePayload.builder()
                        .id("7ee4241c-f127-47e5-9c34-3aac291f8058")
                        .body(
                            MessagingInboundMessagePayload.Body.builder()
                                .id("id")
                                .edit(
                                    MessagingInboundMessagePayload.Body.Edit.builder()
                                        .message(
                                            MessagingInboundMessagePayload.Body.Edit.Message
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .originalMessageId("original_message_id")
                                        .build()
                                )
                                .foreignId("foreign_id")
                                .from("from")
                                .location(
                                    MessagingInboundMessagePayload.Body.Location.builder()
                                        .latitude(0.0)
                                        .longitude(0.0)
                                        .build()
                                )
                                .revoke(
                                    MessagingInboundMessagePayload.Body.Revoke.builder()
                                        .originalMessageId("original_message_id")
                                        .build()
                                )
                                .suggestionResponse(
                                    MessagingInboundMessagePayload.Body.SuggestionResponse.builder()
                                        .postbackData("postback_data")
                                        .text("text")
                                        .build()
                                )
                                .text("string")
                                .timestamp("timestamp")
                                .type("edit")
                                .userFile(
                                    MessagingInboundMessagePayload.Body.UserFile.builder()
                                        .payload(
                                            MessagingInboundMessagePayload.Body.UserFile.Payload
                                                .builder()
                                                .fileName("file_name")
                                                .fileSizeBytes(0L)
                                                .fileUri("file_uri")
                                                .mimeType("mime_type")
                                                .build()
                                        )
                                        .thumbnail(
                                            MessagingInboundMessagePayload.Body.UserFile.Thumbnail
                                                .builder()
                                                .fileName("file_name")
                                                .fileSizeBytes(0L)
                                                .fileUri("file_uri")
                                                .mimeType("mime_type")
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .addCc(
                            MessagingInboundMessagePayload.Cc.builder()
                                .carrier("carrier")
                                .lineType(MessagingInboundMessagePayload.Cc.LineType.WIRELINE)
                                .phoneNumber("phone_number")
                                .status(MessagingInboundMessagePayload.Cc.Status.QUEUED)
                                .build()
                        )
                        .completedAt(null)
                        .cost(
                            MessagingInboundMessagePayload.Cost.builder()
                                .amount("0.0051")
                                .currency("USD")
                                .build()
                        )
                        .costBreakdown(
                            MessagingInboundMessagePayload.CostBreakdown.builder()
                                .carrierFee(
                                    MessagingInboundMessagePayload.CostBreakdown.CarrierFee
                                        .builder()
                                        .amount("0.00305")
                                        .currency("USD")
                                        .build()
                                )
                                .rate(
                                    MessagingInboundMessagePayload.CostBreakdown.Rate.builder()
                                        .amount("0.00205")
                                        .currency("USD")
                                        .build()
                                )
                                .build()
                        )
                        .direction(MessagingInboundMessagePayload.Direction.INBOUND)
                        .encoding("GSM-7")
                        .addError(
                            MessagingError0b38e7044b.builder()
                                .code("code")
                                .title("title")
                                .detail("detail")
                                .meta(
                                    MessagingError0b38e7044b.Meta.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .source(
                                    MessagingError0b38e7044b.Source.builder()
                                        .parameter("parameter")
                                        .pointer("pointer")
                                        .build()
                                )
                                .build()
                        )
                        .from(
                            MessagingInboundMessagePayload.From.builder()
                                .carrier("T-MOBILE USA, INC.")
                                .lineType(MessagingInboundMessagePayload.From.LineType.WIRELESS)
                                .phoneNumber("+18665550001")
                                .status(MessagingInboundMessagePayload.From.Status.RECEIVED)
                                .build()
                        )
                        .addMedia(
                            MessagingInboundMessagePayload.Media.builder()
                                .contentType("content_type")
                                .hashSha256("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
                                .size(0L)
                                .url("url")
                                .build()
                        )
                        .messagingProfileId("0f512bda-ae1e-4597-8e11-e5f5686b97d3")
                        .numChars(13L)
                        .organizationId("b448f9cc-a842-4784-98e9-03c1a5872950")
                        .parts(1L)
                        .receivedAt(OffsetDateTime.parse("2019-01-23T18:10:02.574Z"))
                        .recordType(MessagingInboundMessagePayload.RecordType.MESSAGE)
                        .sentAt(null)
                        .subject("From Telnyx!")
                        .addTag("Greetings")
                        .tcrCampaignBillable(true)
                        .tcrCampaignId("TCPA3X7")
                        .tcrCampaignRegistered("REGISTERED")
                        .text("Hello, World!")
                        .toOfUnnamedSchemaWithArrayParent0s(
                            listOf(
                                MessagingInboundMessagePayload.To.UnnamedSchemaWithArrayParent0
                                    .builder()
                                    .agentId("agent_id")
                                    .agentName("agent_name")
                                    .carrier("TELNYX LLC")
                                    .lineType(
                                        MessagingInboundMessagePayload.To
                                            .UnnamedSchemaWithArrayParent0
                                            .LineType
                                            .VO_IP
                                    )
                                    .phoneNumber("+18445550001")
                                    .status(
                                        MessagingInboundMessagePayload.To
                                            .UnnamedSchemaWithArrayParent0
                                            .Status
                                            .DELIVERED
                                    )
                                    .build()
                            )
                        )
                        .type(MessagingInboundMessagePayload.Type.SMS)
                        .validUntil(null)
                        .webhookFailoverUrl("https://backup.example.com/hooks")
                        .webhookUrl("https://www.example.com/hooks")
                        .build()
                )
                .recordType(MessagingInboundMessage.RecordType.EVENT)
                .build()

        assertThat(messagingInboundMessage.id()).contains("bf6307bd-884d-4c1f-b6ea-c62b8c495d3c")
        assertThat(messagingInboundMessage.eventType())
            .contains(MessagingInboundMessage.EventType.MESSAGE_RECEIVED)
        assertThat(messagingInboundMessage.occurredAt())
            .contains(OffsetDateTime.parse("2019-01-23T18:10:02.574Z"))
        assertThat(messagingInboundMessage.payload())
            .contains(
                MessagingInboundMessagePayload.builder()
                    .id("7ee4241c-f127-47e5-9c34-3aac291f8058")
                    .body(
                        MessagingInboundMessagePayload.Body.builder()
                            .id("id")
                            .edit(
                                MessagingInboundMessagePayload.Body.Edit.builder()
                                    .message(
                                        MessagingInboundMessagePayload.Body.Edit.Message.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                                            .build()
                                    )
                                    .originalMessageId("original_message_id")
                                    .build()
                            )
                            .foreignId("foreign_id")
                            .from("from")
                            .location(
                                MessagingInboundMessagePayload.Body.Location.builder()
                                    .latitude(0.0)
                                    .longitude(0.0)
                                    .build()
                            )
                            .revoke(
                                MessagingInboundMessagePayload.Body.Revoke.builder()
                                    .originalMessageId("original_message_id")
                                    .build()
                            )
                            .suggestionResponse(
                                MessagingInboundMessagePayload.Body.SuggestionResponse.builder()
                                    .postbackData("postback_data")
                                    .text("text")
                                    .build()
                            )
                            .text("string")
                            .timestamp("timestamp")
                            .type("edit")
                            .userFile(
                                MessagingInboundMessagePayload.Body.UserFile.builder()
                                    .payload(
                                        MessagingInboundMessagePayload.Body.UserFile.Payload
                                            .builder()
                                            .fileName("file_name")
                                            .fileSizeBytes(0L)
                                            .fileUri("file_uri")
                                            .mimeType("mime_type")
                                            .build()
                                    )
                                    .thumbnail(
                                        MessagingInboundMessagePayload.Body.UserFile.Thumbnail
                                            .builder()
                                            .fileName("file_name")
                                            .fileSizeBytes(0L)
                                            .fileUri("file_uri")
                                            .mimeType("mime_type")
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .addCc(
                        MessagingInboundMessagePayload.Cc.builder()
                            .carrier("carrier")
                            .lineType(MessagingInboundMessagePayload.Cc.LineType.WIRELINE)
                            .phoneNumber("phone_number")
                            .status(MessagingInboundMessagePayload.Cc.Status.QUEUED)
                            .build()
                    )
                    .completedAt(null)
                    .cost(
                        MessagingInboundMessagePayload.Cost.builder()
                            .amount("0.0051")
                            .currency("USD")
                            .build()
                    )
                    .costBreakdown(
                        MessagingInboundMessagePayload.CostBreakdown.builder()
                            .carrierFee(
                                MessagingInboundMessagePayload.CostBreakdown.CarrierFee.builder()
                                    .amount("0.00305")
                                    .currency("USD")
                                    .build()
                            )
                            .rate(
                                MessagingInboundMessagePayload.CostBreakdown.Rate.builder()
                                    .amount("0.00205")
                                    .currency("USD")
                                    .build()
                            )
                            .build()
                    )
                    .direction(MessagingInboundMessagePayload.Direction.INBOUND)
                    .encoding("GSM-7")
                    .addError(
                        MessagingError0b38e7044b.builder()
                            .code("code")
                            .title("title")
                            .detail("detail")
                            .meta(
                                MessagingError0b38e7044b.Meta.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .build()
                            )
                            .source(
                                MessagingError0b38e7044b.Source.builder()
                                    .parameter("parameter")
                                    .pointer("pointer")
                                    .build()
                            )
                            .build()
                    )
                    .from(
                        MessagingInboundMessagePayload.From.builder()
                            .carrier("T-MOBILE USA, INC.")
                            .lineType(MessagingInboundMessagePayload.From.LineType.WIRELESS)
                            .phoneNumber("+18665550001")
                            .status(MessagingInboundMessagePayload.From.Status.RECEIVED)
                            .build()
                    )
                    .addMedia(
                        MessagingInboundMessagePayload.Media.builder()
                            .contentType("content_type")
                            .hashSha256("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
                            .size(0L)
                            .url("url")
                            .build()
                    )
                    .messagingProfileId("0f512bda-ae1e-4597-8e11-e5f5686b97d3")
                    .numChars(13L)
                    .organizationId("b448f9cc-a842-4784-98e9-03c1a5872950")
                    .parts(1L)
                    .receivedAt(OffsetDateTime.parse("2019-01-23T18:10:02.574Z"))
                    .recordType(MessagingInboundMessagePayload.RecordType.MESSAGE)
                    .sentAt(null)
                    .subject("From Telnyx!")
                    .addTag("Greetings")
                    .tcrCampaignBillable(true)
                    .tcrCampaignId("TCPA3X7")
                    .tcrCampaignRegistered("REGISTERED")
                    .text("Hello, World!")
                    .toOfUnnamedSchemaWithArrayParent0s(
                        listOf(
                            MessagingInboundMessagePayload.To.UnnamedSchemaWithArrayParent0
                                .builder()
                                .agentId("agent_id")
                                .agentName("agent_name")
                                .carrier("TELNYX LLC")
                                .lineType(
                                    MessagingInboundMessagePayload.To.UnnamedSchemaWithArrayParent0
                                        .LineType
                                        .VO_IP
                                )
                                .phoneNumber("+18445550001")
                                .status(
                                    MessagingInboundMessagePayload.To.UnnamedSchemaWithArrayParent0
                                        .Status
                                        .DELIVERED
                                )
                                .build()
                        )
                    )
                    .type(MessagingInboundMessagePayload.Type.SMS)
                    .validUntil(null)
                    .webhookFailoverUrl("https://backup.example.com/hooks")
                    .webhookUrl("https://www.example.com/hooks")
                    .build()
            )
        assertThat(messagingInboundMessage.recordType())
            .contains(MessagingInboundMessage.RecordType.EVENT)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val messagingInboundMessage =
            MessagingInboundMessage.builder()
                .id("bf6307bd-884d-4c1f-b6ea-c62b8c495d3c")
                .eventType(MessagingInboundMessage.EventType.MESSAGE_RECEIVED)
                .occurredAt(OffsetDateTime.parse("2019-01-23T18:10:02.574Z"))
                .payload(
                    MessagingInboundMessagePayload.builder()
                        .id("7ee4241c-f127-47e5-9c34-3aac291f8058")
                        .body(
                            MessagingInboundMessagePayload.Body.builder()
                                .id("id")
                                .edit(
                                    MessagingInboundMessagePayload.Body.Edit.builder()
                                        .message(
                                            MessagingInboundMessagePayload.Body.Edit.Message
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .originalMessageId("original_message_id")
                                        .build()
                                )
                                .foreignId("foreign_id")
                                .from("from")
                                .location(
                                    MessagingInboundMessagePayload.Body.Location.builder()
                                        .latitude(0.0)
                                        .longitude(0.0)
                                        .build()
                                )
                                .revoke(
                                    MessagingInboundMessagePayload.Body.Revoke.builder()
                                        .originalMessageId("original_message_id")
                                        .build()
                                )
                                .suggestionResponse(
                                    MessagingInboundMessagePayload.Body.SuggestionResponse.builder()
                                        .postbackData("postback_data")
                                        .text("text")
                                        .build()
                                )
                                .text("string")
                                .timestamp("timestamp")
                                .type("edit")
                                .userFile(
                                    MessagingInboundMessagePayload.Body.UserFile.builder()
                                        .payload(
                                            MessagingInboundMessagePayload.Body.UserFile.Payload
                                                .builder()
                                                .fileName("file_name")
                                                .fileSizeBytes(0L)
                                                .fileUri("file_uri")
                                                .mimeType("mime_type")
                                                .build()
                                        )
                                        .thumbnail(
                                            MessagingInboundMessagePayload.Body.UserFile.Thumbnail
                                                .builder()
                                                .fileName("file_name")
                                                .fileSizeBytes(0L)
                                                .fileUri("file_uri")
                                                .mimeType("mime_type")
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .addCc(
                            MessagingInboundMessagePayload.Cc.builder()
                                .carrier("carrier")
                                .lineType(MessagingInboundMessagePayload.Cc.LineType.WIRELINE)
                                .phoneNumber("phone_number")
                                .status(MessagingInboundMessagePayload.Cc.Status.QUEUED)
                                .build()
                        )
                        .completedAt(null)
                        .cost(
                            MessagingInboundMessagePayload.Cost.builder()
                                .amount("0.0051")
                                .currency("USD")
                                .build()
                        )
                        .costBreakdown(
                            MessagingInboundMessagePayload.CostBreakdown.builder()
                                .carrierFee(
                                    MessagingInboundMessagePayload.CostBreakdown.CarrierFee
                                        .builder()
                                        .amount("0.00305")
                                        .currency("USD")
                                        .build()
                                )
                                .rate(
                                    MessagingInboundMessagePayload.CostBreakdown.Rate.builder()
                                        .amount("0.00205")
                                        .currency("USD")
                                        .build()
                                )
                                .build()
                        )
                        .direction(MessagingInboundMessagePayload.Direction.INBOUND)
                        .encoding("GSM-7")
                        .addError(
                            MessagingError0b38e7044b.builder()
                                .code("code")
                                .title("title")
                                .detail("detail")
                                .meta(
                                    MessagingError0b38e7044b.Meta.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .source(
                                    MessagingError0b38e7044b.Source.builder()
                                        .parameter("parameter")
                                        .pointer("pointer")
                                        .build()
                                )
                                .build()
                        )
                        .from(
                            MessagingInboundMessagePayload.From.builder()
                                .carrier("T-MOBILE USA, INC.")
                                .lineType(MessagingInboundMessagePayload.From.LineType.WIRELESS)
                                .phoneNumber("+18665550001")
                                .status(MessagingInboundMessagePayload.From.Status.RECEIVED)
                                .build()
                        )
                        .addMedia(
                            MessagingInboundMessagePayload.Media.builder()
                                .contentType("content_type")
                                .hashSha256("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
                                .size(0L)
                                .url("url")
                                .build()
                        )
                        .messagingProfileId("0f512bda-ae1e-4597-8e11-e5f5686b97d3")
                        .numChars(13L)
                        .organizationId("b448f9cc-a842-4784-98e9-03c1a5872950")
                        .parts(1L)
                        .receivedAt(OffsetDateTime.parse("2019-01-23T18:10:02.574Z"))
                        .recordType(MessagingInboundMessagePayload.RecordType.MESSAGE)
                        .sentAt(null)
                        .subject("From Telnyx!")
                        .addTag("Greetings")
                        .tcrCampaignBillable(true)
                        .tcrCampaignId("TCPA3X7")
                        .tcrCampaignRegistered("REGISTERED")
                        .text("Hello, World!")
                        .toOfUnnamedSchemaWithArrayParent0s(
                            listOf(
                                MessagingInboundMessagePayload.To.UnnamedSchemaWithArrayParent0
                                    .builder()
                                    .agentId("agent_id")
                                    .agentName("agent_name")
                                    .carrier("TELNYX LLC")
                                    .lineType(
                                        MessagingInboundMessagePayload.To
                                            .UnnamedSchemaWithArrayParent0
                                            .LineType
                                            .VO_IP
                                    )
                                    .phoneNumber("+18445550001")
                                    .status(
                                        MessagingInboundMessagePayload.To
                                            .UnnamedSchemaWithArrayParent0
                                            .Status
                                            .DELIVERED
                                    )
                                    .build()
                            )
                        )
                        .type(MessagingInboundMessagePayload.Type.SMS)
                        .validUntil(null)
                        .webhookFailoverUrl("https://backup.example.com/hooks")
                        .webhookUrl("https://www.example.com/hooks")
                        .build()
                )
                .recordType(MessagingInboundMessage.RecordType.EVENT)
                .build()

        val roundtrippedMessagingInboundMessage =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(messagingInboundMessage),
                jacksonTypeRef<MessagingInboundMessage>(),
            )

        assertThat(roundtrippedMessagingInboundMessage).isEqualTo(messagingInboundMessage)
    }
}
