// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.ai.assistants

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.JsonValue
import com.telnyx.sdk.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AssistantsListTest {

    @Test
    fun create() {
        val assistantsList =
            AssistantsList.builder()
                .addData(
                    InferenceEmbedding.builder()
                        .id("id")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .instructions("instructions")
                        .model("model")
                        .name("name")
                        .description("description")
                        .dynamicVariables(
                            InferenceEmbedding.DynamicVariables.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .dynamicVariablesWebhookUrl("dynamic_variables_webhook_url")
                        .addEnabledFeature(EnabledFeatures.TELEPHONY)
                        .greeting("greeting")
                        .importMetadata(
                            ImportMetadata.builder()
                                .importId("import_id")
                                .importProvider(ImportMetadata.ImportProvider.ELEVENLABS)
                                .build()
                        )
                        .insightSettings(
                            InsightSettings.builder().insightGroupId("insight_group_id").build()
                        )
                        .llmApiKeyRef("llm_api_key_ref")
                        .messagingSettings(
                            MessagingSettings.builder()
                                .defaultMessagingProfileId("default_messaging_profile_id")
                                .deliveryStatusWebhookUrl("delivery_status_webhook_url")
                                .build()
                        )
                        .privacySettings(PrivacySettings.builder().dataRetention(true).build())
                        .telephonySettings(
                            TelephonySettings.builder()
                                .defaultTexmlAppId("default_texml_app_id")
                                .supportsUnauthenticatedWebCalls(true)
                                .build()
                        )
                        .addTool(
                            WebhookTool.builder()
                                .type(WebhookTool.Type.WEBHOOK)
                                .webhook(
                                    InferenceEmbeddingWebhookToolParams.builder()
                                        .description("description")
                                        .name("name")
                                        .url("https://example.com/api/v1/function")
                                        .bodyParameters(
                                            InferenceEmbeddingWebhookToolParams.BodyParameters
                                                .builder()
                                                .properties(
                                                    InferenceEmbeddingWebhookToolParams
                                                        .BodyParameters
                                                        .Properties
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "age",
                                                            JsonValue.from("bar"),
                                                        )
                                                        .putAdditionalProperty(
                                                            "location",
                                                            JsonValue.from("bar"),
                                                        )
                                                        .build()
                                                )
                                                .addRequired("age")
                                                .addRequired("location")
                                                .type(
                                                    InferenceEmbeddingWebhookToolParams
                                                        .BodyParameters
                                                        .Type
                                                        .OBJECT
                                                )
                                                .build()
                                        )
                                        .addHeader(
                                            InferenceEmbeddingWebhookToolParams.Header.builder()
                                                .name("name")
                                                .value("value")
                                                .build()
                                        )
                                        .method(InferenceEmbeddingWebhookToolParams.Method.GET)
                                        .pathParameters(
                                            InferenceEmbeddingWebhookToolParams.PathParameters
                                                .builder()
                                                .properties(
                                                    InferenceEmbeddingWebhookToolParams
                                                        .PathParameters
                                                        .Properties
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "id",
                                                            JsonValue.from("bar"),
                                                        )
                                                        .build()
                                                )
                                                .addRequired("id")
                                                .type(
                                                    InferenceEmbeddingWebhookToolParams
                                                        .PathParameters
                                                        .Type
                                                        .OBJECT
                                                )
                                                .build()
                                        )
                                        .queryParameters(
                                            InferenceEmbeddingWebhookToolParams.QueryParameters
                                                .builder()
                                                .properties(
                                                    InferenceEmbeddingWebhookToolParams
                                                        .QueryParameters
                                                        .Properties
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "page",
                                                            JsonValue.from("bar"),
                                                        )
                                                        .build()
                                                )
                                                .addRequired("page")
                                                .type(
                                                    InferenceEmbeddingWebhookToolParams
                                                        .QueryParameters
                                                        .Type
                                                        .OBJECT
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .transcription(
                            TranscriptionSettings.builder()
                                .language("language")
                                .model("model")
                                .build()
                        )
                        .voiceSettings(
                            VoiceSettings.builder()
                                .voice("voice")
                                .apiKeyRef("api_key_ref")
                                .backgroundAudio(
                                    VoiceSettings.BackgroundAudio.UnionMember0.builder()
                                        .type(
                                            VoiceSettings.BackgroundAudio.UnionMember0.Type
                                                .PREDEFINED_MEDIA
                                        )
                                        .value(
                                            VoiceSettings.BackgroundAudio.UnionMember0.Value_
                                                .SILENCE
                                        )
                                        .build()
                                )
                                .voiceSpeed(0.0)
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(assistantsList.data())
            .containsExactly(
                InferenceEmbedding.builder()
                    .id("id")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .instructions("instructions")
                    .model("model")
                    .name("name")
                    .description("description")
                    .dynamicVariables(
                        InferenceEmbedding.DynamicVariables.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .dynamicVariablesWebhookUrl("dynamic_variables_webhook_url")
                    .addEnabledFeature(EnabledFeatures.TELEPHONY)
                    .greeting("greeting")
                    .importMetadata(
                        ImportMetadata.builder()
                            .importId("import_id")
                            .importProvider(ImportMetadata.ImportProvider.ELEVENLABS)
                            .build()
                    )
                    .insightSettings(
                        InsightSettings.builder().insightGroupId("insight_group_id").build()
                    )
                    .llmApiKeyRef("llm_api_key_ref")
                    .messagingSettings(
                        MessagingSettings.builder()
                            .defaultMessagingProfileId("default_messaging_profile_id")
                            .deliveryStatusWebhookUrl("delivery_status_webhook_url")
                            .build()
                    )
                    .privacySettings(PrivacySettings.builder().dataRetention(true).build())
                    .telephonySettings(
                        TelephonySettings.builder()
                            .defaultTexmlAppId("default_texml_app_id")
                            .supportsUnauthenticatedWebCalls(true)
                            .build()
                    )
                    .addTool(
                        WebhookTool.builder()
                            .type(WebhookTool.Type.WEBHOOK)
                            .webhook(
                                InferenceEmbeddingWebhookToolParams.builder()
                                    .description("description")
                                    .name("name")
                                    .url("https://example.com/api/v1/function")
                                    .bodyParameters(
                                        InferenceEmbeddingWebhookToolParams.BodyParameters.builder()
                                            .properties(
                                                InferenceEmbeddingWebhookToolParams.BodyParameters
                                                    .Properties
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "age",
                                                        JsonValue.from("bar"),
                                                    )
                                                    .putAdditionalProperty(
                                                        "location",
                                                        JsonValue.from("bar"),
                                                    )
                                                    .build()
                                            )
                                            .addRequired("age")
                                            .addRequired("location")
                                            .type(
                                                InferenceEmbeddingWebhookToolParams.BodyParameters
                                                    .Type
                                                    .OBJECT
                                            )
                                            .build()
                                    )
                                    .addHeader(
                                        InferenceEmbeddingWebhookToolParams.Header.builder()
                                            .name("name")
                                            .value("value")
                                            .build()
                                    )
                                    .method(InferenceEmbeddingWebhookToolParams.Method.GET)
                                    .pathParameters(
                                        InferenceEmbeddingWebhookToolParams.PathParameters.builder()
                                            .properties(
                                                InferenceEmbeddingWebhookToolParams.PathParameters
                                                    .Properties
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "id",
                                                        JsonValue.from("bar"),
                                                    )
                                                    .build()
                                            )
                                            .addRequired("id")
                                            .type(
                                                InferenceEmbeddingWebhookToolParams.PathParameters
                                                    .Type
                                                    .OBJECT
                                            )
                                            .build()
                                    )
                                    .queryParameters(
                                        InferenceEmbeddingWebhookToolParams.QueryParameters
                                            .builder()
                                            .properties(
                                                InferenceEmbeddingWebhookToolParams.QueryParameters
                                                    .Properties
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "page",
                                                        JsonValue.from("bar"),
                                                    )
                                                    .build()
                                            )
                                            .addRequired("page")
                                            .type(
                                                InferenceEmbeddingWebhookToolParams.QueryParameters
                                                    .Type
                                                    .OBJECT
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .transcription(
                        TranscriptionSettings.builder().language("language").model("model").build()
                    )
                    .voiceSettings(
                        VoiceSettings.builder()
                            .voice("voice")
                            .apiKeyRef("api_key_ref")
                            .backgroundAudio(
                                VoiceSettings.BackgroundAudio.UnionMember0.builder()
                                    .type(
                                        VoiceSettings.BackgroundAudio.UnionMember0.Type
                                            .PREDEFINED_MEDIA
                                    )
                                    .value(
                                        VoiceSettings.BackgroundAudio.UnionMember0.Value_.SILENCE
                                    )
                                    .build()
                            )
                            .voiceSpeed(0.0)
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val assistantsList =
            AssistantsList.builder()
                .addData(
                    InferenceEmbedding.builder()
                        .id("id")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .instructions("instructions")
                        .model("model")
                        .name("name")
                        .description("description")
                        .dynamicVariables(
                            InferenceEmbedding.DynamicVariables.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .dynamicVariablesWebhookUrl("dynamic_variables_webhook_url")
                        .addEnabledFeature(EnabledFeatures.TELEPHONY)
                        .greeting("greeting")
                        .importMetadata(
                            ImportMetadata.builder()
                                .importId("import_id")
                                .importProvider(ImportMetadata.ImportProvider.ELEVENLABS)
                                .build()
                        )
                        .insightSettings(
                            InsightSettings.builder().insightGroupId("insight_group_id").build()
                        )
                        .llmApiKeyRef("llm_api_key_ref")
                        .messagingSettings(
                            MessagingSettings.builder()
                                .defaultMessagingProfileId("default_messaging_profile_id")
                                .deliveryStatusWebhookUrl("delivery_status_webhook_url")
                                .build()
                        )
                        .privacySettings(PrivacySettings.builder().dataRetention(true).build())
                        .telephonySettings(
                            TelephonySettings.builder()
                                .defaultTexmlAppId("default_texml_app_id")
                                .supportsUnauthenticatedWebCalls(true)
                                .build()
                        )
                        .addTool(
                            WebhookTool.builder()
                                .type(WebhookTool.Type.WEBHOOK)
                                .webhook(
                                    InferenceEmbeddingWebhookToolParams.builder()
                                        .description("description")
                                        .name("name")
                                        .url("https://example.com/api/v1/function")
                                        .bodyParameters(
                                            InferenceEmbeddingWebhookToolParams.BodyParameters
                                                .builder()
                                                .properties(
                                                    InferenceEmbeddingWebhookToolParams
                                                        .BodyParameters
                                                        .Properties
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "age",
                                                            JsonValue.from("bar"),
                                                        )
                                                        .putAdditionalProperty(
                                                            "location",
                                                            JsonValue.from("bar"),
                                                        )
                                                        .build()
                                                )
                                                .addRequired("age")
                                                .addRequired("location")
                                                .type(
                                                    InferenceEmbeddingWebhookToolParams
                                                        .BodyParameters
                                                        .Type
                                                        .OBJECT
                                                )
                                                .build()
                                        )
                                        .addHeader(
                                            InferenceEmbeddingWebhookToolParams.Header.builder()
                                                .name("name")
                                                .value("value")
                                                .build()
                                        )
                                        .method(InferenceEmbeddingWebhookToolParams.Method.GET)
                                        .pathParameters(
                                            InferenceEmbeddingWebhookToolParams.PathParameters
                                                .builder()
                                                .properties(
                                                    InferenceEmbeddingWebhookToolParams
                                                        .PathParameters
                                                        .Properties
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "id",
                                                            JsonValue.from("bar"),
                                                        )
                                                        .build()
                                                )
                                                .addRequired("id")
                                                .type(
                                                    InferenceEmbeddingWebhookToolParams
                                                        .PathParameters
                                                        .Type
                                                        .OBJECT
                                                )
                                                .build()
                                        )
                                        .queryParameters(
                                            InferenceEmbeddingWebhookToolParams.QueryParameters
                                                .builder()
                                                .properties(
                                                    InferenceEmbeddingWebhookToolParams
                                                        .QueryParameters
                                                        .Properties
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "page",
                                                            JsonValue.from("bar"),
                                                        )
                                                        .build()
                                                )
                                                .addRequired("page")
                                                .type(
                                                    InferenceEmbeddingWebhookToolParams
                                                        .QueryParameters
                                                        .Type
                                                        .OBJECT
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .transcription(
                            TranscriptionSettings.builder()
                                .language("language")
                                .model("model")
                                .build()
                        )
                        .voiceSettings(
                            VoiceSettings.builder()
                                .voice("voice")
                                .apiKeyRef("api_key_ref")
                                .backgroundAudio(
                                    VoiceSettings.BackgroundAudio.UnionMember0.builder()
                                        .type(
                                            VoiceSettings.BackgroundAudio.UnionMember0.Type
                                                .PREDEFINED_MEDIA
                                        )
                                        .value(
                                            VoiceSettings.BackgroundAudio.UnionMember0.Value_
                                                .SILENCE
                                        )
                                        .build()
                                )
                                .voiceSpeed(0.0)
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedAssistantsList =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(assistantsList),
                jacksonTypeRef<AssistantsList>(),
            )

        assertThat(roundtrippedAssistantsList).isEqualTo(assistantsList)
    }
}
