// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.ai.assistants

import com.telnyx.sdk.core.JsonValue
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AssistantCreateParamsTest {

    @Test
    fun create() {
        AssistantCreateParams.builder()
            .instructions("instructions")
            .name("name")
            .description("description")
            .dynamicVariables(
                AssistantCreateParams.DynamicVariables.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
            .dynamicVariablesWebhookTimeoutMs(1L)
            .dynamicVariablesWebhookUrl("dynamic_variables_webhook_url")
            .addEnabledFeature(EnabledFeatures.TELEPHONY)
            .externalLlm(
                ExternalLlmReq.builder()
                    .baseUrl("base_url")
                    .model("model")
                    .authenticationMethod(ExternalLlmReq.AuthenticationMethod.TOKEN)
                    .certificateRef("certificate_ref")
                    .forwardMetadata(true)
                    .llmApiKeyRef("llm_api_key_ref")
                    .tokenRetrievalUrl("token_retrieval_url")
                    .build()
            )
            .fallbackConfig(
                FallbackConfigReq.builder()
                    .externalLlm(
                        ExternalLlmReq.builder()
                            .baseUrl("base_url")
                            .model("model")
                            .authenticationMethod(ExternalLlmReq.AuthenticationMethod.TOKEN)
                            .certificateRef("certificate_ref")
                            .forwardMetadata(true)
                            .llmApiKeyRef("llm_api_key_ref")
                            .tokenRetrievalUrl("token_retrieval_url")
                            .build()
                    )
                    .llmApiKeyRef("llm_api_key_ref")
                    .model("model")
                    .build()
            )
            .greeting("greeting")
            .insightSettings(InsightSettings.builder().insightGroupId("insight_group_id").build())
            .addIntegration(
                AssistantCreateParams.Integration.builder()
                    .integrationId("integration_id")
                    .addAllowedList("string")
                    .build()
            )
            .interruptionSettings(
                AssistantCreateParams.InterruptionSettings.builder()
                    .disableGreetingInterruption(true)
                    .enable(true)
                    .startSpeakingPlan(
                        AssistantCreateParams.InterruptionSettings.StartSpeakingPlan.builder()
                            .transcriptionEndpointingPlan(
                                AssistantCreateParams.InterruptionSettings.StartSpeakingPlan
                                    .TranscriptionEndpointingPlan
                                    .builder()
                                    .onNoPunctuationSeconds(0.0f)
                                    .onNumberSeconds(0.0f)
                                    .onPunctuationSeconds(0.0f)
                                    .build()
                            )
                            .waitSeconds(0.0f)
                            .build()
                    )
                    .build()
            )
            .llmApiKeyRef("llm_api_key_ref")
            .addMcpServer(
                AssistantCreateParams.McpServer.builder().id("id").addAllowedTool("string").build()
            )
            .messagingSettings(
                MessagingSettings.builder()
                    .conversationInactivityMinutes(1L)
                    .defaultMessagingProfileId("default_messaging_profile_id")
                    .deliveryStatusWebhookUrl("delivery_status_webhook_url")
                    .build()
            )
            .model("model")
            .observabilitySettings(
                ObservabilityReq.builder()
                    .host("host")
                    .promptLabel("prompt_label")
                    .promptName("prompt_name")
                    .promptSync(ObservabilityReq.PromptSync.ENABLED)
                    .promptVersion(1L)
                    .publicKeyRef("public_key_ref")
                    .secretKeyRef("secret_key_ref")
                    .status(ObservabilityReq.Status.ENABLED)
                    .build()
            )
            .postConversationSettings(PostConversationSettingsReq.builder().enabled(true).build())
            .privacySettings(PrivacySettings.builder().dataRetention(true).build())
            .addTag("string")
            .telephonySettings(
                TelephonySettings.builder()
                    .defaultTexmlAppId("default_texml_app_id")
                    .noiseSuppression(TelephonySettings.NoiseSuppression.KRISP)
                    .noiseSuppressionConfig(
                        TelephonySettings.NoiseSuppressionConfig.builder()
                            .attenuationLimit(0L)
                            .mode(TelephonySettings.NoiseSuppressionConfig.Mode.ADVANCED)
                            .build()
                    )
                    .recordingSettings(
                        TelephonySettings.RecordingSettings.builder()
                            .channels(TelephonySettings.RecordingSettings.Channels.SINGLE)
                            .enabled(true)
                            .format(TelephonySettings.RecordingSettings.Format.WAV)
                            .stopOnConversationEnd(true)
                            .build()
                    )
                    .supportsUnauthenticatedWebCalls(true)
                    .timeLimitSecs(30L)
                    .userIdleReplySecs(0L)
                    .userIdleTimeoutSecs(10L)
                    .voicemailDetection(
                        TelephonySettings.VoicemailDetection.builder()
                            .onVoicemailDetected(
                                TelephonySettings.VoicemailDetection.OnVoicemailDetected.builder()
                                    .action(
                                        TelephonySettings.VoicemailDetection.OnVoicemailDetected
                                            .Action
                                            .STOP_ASSISTANT
                                    )
                                    .voicemailMessage(
                                        TelephonySettings.VoicemailDetection.OnVoicemailDetected
                                            .VoicemailMessage
                                            .builder()
                                            .message("message")
                                            .prompt("prompt")
                                            .type(
                                                TelephonySettings.VoicemailDetection
                                                    .OnVoicemailDetected
                                                    .VoicemailMessage
                                                    .Type
                                                    .PROMPT
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
            .addToolId("string")
            .addWebhookTool(
                InferenceEmbeddingWebhookToolParams.Webhook.builder()
                    .description("description")
                    .name("name")
                    .url("https://example.com/api/v1/function")
                    .async(true)
                    .asyncTimeoutMs(1L)
                    .bodyParameters(
                        InferenceEmbeddingWebhookToolParams.Webhook.BodyParameters.builder()
                            .properties(
                                InferenceEmbeddingWebhookToolParams.Webhook.BodyParameters
                                    .Properties
                                    .builder()
                                    .putAdditionalProperty("age", JsonValue.from("bar"))
                                    .putAdditionalProperty("location", JsonValue.from("bar"))
                                    .build()
                            )
                            .addRequired("age")
                            .addRequired("location")
                            .type(
                                InferenceEmbeddingWebhookToolParams.Webhook.BodyParameters.Type
                                    .OBJECT
                            )
                            .build()
                    )
                    .addHeader(
                        InferenceEmbeddingWebhookToolParams.Webhook.Header.builder()
                            .name("name")
                            .value("value")
                            .build()
                    )
                    .method(InferenceEmbeddingWebhookToolParams.Webhook.Method.GET)
                    .pathParameters(
                        InferenceEmbeddingWebhookToolParams.Webhook.PathParameters.builder()
                            .properties(
                                InferenceEmbeddingWebhookToolParams.Webhook.PathParameters
                                    .Properties
                                    .builder()
                                    .putAdditionalProperty("id", JsonValue.from("bar"))
                                    .build()
                            )
                            .addRequired("id")
                            .type(
                                InferenceEmbeddingWebhookToolParams.Webhook.PathParameters.Type
                                    .OBJECT
                            )
                            .build()
                    )
                    .queryParameters(
                        InferenceEmbeddingWebhookToolParams.Webhook.QueryParameters.builder()
                            .properties(
                                InferenceEmbeddingWebhookToolParams.Webhook.QueryParameters
                                    .Properties
                                    .builder()
                                    .putAdditionalProperty("page", JsonValue.from("bar"))
                                    .build()
                            )
                            .addRequired("page")
                            .type(
                                InferenceEmbeddingWebhookToolParams.Webhook.QueryParameters.Type
                                    .OBJECT
                            )
                            .build()
                    )
                    .addStoreFieldsAsVariable(
                        InferenceEmbeddingWebhookToolParams.Webhook.StoreFieldsAsVariable.builder()
                            .name("x")
                            .valuePath("x")
                            .build()
                    )
                    .timeoutMs(500L)
                    .build()
            )
            .transcription(
                TranscriptionSettings.builder()
                    .apiKeyRef("api_key_ref")
                    .language("language")
                    .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                    .region("region")
                    .settings(
                        TranscriptionSettingsConfig.builder()
                            .eagerEotThreshold(0.3)
                            .enableEndpointDetection(true)
                            .endOfTurnConfidenceThreshold(0.0)
                            .eotThreshold(0.5)
                            .eotTimeoutMs(500L)
                            .interimResults(true)
                            .keyterm("keyterm")
                            .maxEndpointDelayMs(500L)
                            .maxTurnSilence(100L)
                            .minTurnSilence(100L)
                            .numerals(true)
                            .smartFormat(true)
                            .build()
                    )
                    .build()
            )
            .voiceSettings(
                VoiceSettings.builder()
                    .voice("voice")
                    .apiKeyRef("api_key_ref")
                    .backgroundAudio(
                        VoiceSettings.BackgroundAudio.PredefinedMedia.builder()
                            .value(
                                VoiceSettings.BackgroundAudio.PredefinedMedia.PredefinedMediaValue
                                    .SILENCE
                            )
                            .volume(0.1)
                            .build()
                    )
                    .expressiveMode(true)
                    .languageBoost(VoiceSettings.LanguageBoost.AUTO)
                    .similarityBoost(0.0)
                    .speed(0.0)
                    .style(0.0)
                    .temperature(0.0)
                    .useSpeakerBoost(true)
                    .voiceSpeed(0.0)
                    .build()
            )
            .widgetSettings(
                WidgetSettings.builder()
                    .agentThinkingText("agent_thinking_text")
                    .audioVisualizerConfig(
                        AudioVisualizerConfig.builder()
                            .color(AudioVisualizerConfig.Color.VERDANT)
                            .preset("preset")
                            .build()
                    )
                    .defaultState(WidgetSettings.DefaultState.EXPANDED)
                    .giveFeedbackUrl("give_feedback_url")
                    .logoIconUrl("logo_icon_url")
                    .position(WidgetSettings.Position.FIXED)
                    .reportIssueUrl("report_issue_url")
                    .speakToInterruptText("speak_to_interrupt_text")
                    .startCallText("start_call_text")
                    .theme(WidgetSettings.Theme.LIGHT)
                    .viewHistoryUrl("view_history_url")
                    .build()
            )
            .build()
    }

    @Test
    fun body() {
        val params =
            AssistantCreateParams.builder()
                .instructions("instructions")
                .name("name")
                .description("description")
                .dynamicVariables(
                    AssistantCreateParams.DynamicVariables.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .dynamicVariablesWebhookTimeoutMs(1L)
                .dynamicVariablesWebhookUrl("dynamic_variables_webhook_url")
                .addEnabledFeature(EnabledFeatures.TELEPHONY)
                .externalLlm(
                    ExternalLlmReq.builder()
                        .baseUrl("base_url")
                        .model("model")
                        .authenticationMethod(ExternalLlmReq.AuthenticationMethod.TOKEN)
                        .certificateRef("certificate_ref")
                        .forwardMetadata(true)
                        .llmApiKeyRef("llm_api_key_ref")
                        .tokenRetrievalUrl("token_retrieval_url")
                        .build()
                )
                .fallbackConfig(
                    FallbackConfigReq.builder()
                        .externalLlm(
                            ExternalLlmReq.builder()
                                .baseUrl("base_url")
                                .model("model")
                                .authenticationMethod(ExternalLlmReq.AuthenticationMethod.TOKEN)
                                .certificateRef("certificate_ref")
                                .forwardMetadata(true)
                                .llmApiKeyRef("llm_api_key_ref")
                                .tokenRetrievalUrl("token_retrieval_url")
                                .build()
                        )
                        .llmApiKeyRef("llm_api_key_ref")
                        .model("model")
                        .build()
                )
                .greeting("greeting")
                .insightSettings(
                    InsightSettings.builder().insightGroupId("insight_group_id").build()
                )
                .addIntegration(
                    AssistantCreateParams.Integration.builder()
                        .integrationId("integration_id")
                        .addAllowedList("string")
                        .build()
                )
                .interruptionSettings(
                    AssistantCreateParams.InterruptionSettings.builder()
                        .disableGreetingInterruption(true)
                        .enable(true)
                        .startSpeakingPlan(
                            AssistantCreateParams.InterruptionSettings.StartSpeakingPlan.builder()
                                .transcriptionEndpointingPlan(
                                    AssistantCreateParams.InterruptionSettings.StartSpeakingPlan
                                        .TranscriptionEndpointingPlan
                                        .builder()
                                        .onNoPunctuationSeconds(0.0f)
                                        .onNumberSeconds(0.0f)
                                        .onPunctuationSeconds(0.0f)
                                        .build()
                                )
                                .waitSeconds(0.0f)
                                .build()
                        )
                        .build()
                )
                .llmApiKeyRef("llm_api_key_ref")
                .addMcpServer(
                    AssistantCreateParams.McpServer.builder()
                        .id("id")
                        .addAllowedTool("string")
                        .build()
                )
                .messagingSettings(
                    MessagingSettings.builder()
                        .conversationInactivityMinutes(1L)
                        .defaultMessagingProfileId("default_messaging_profile_id")
                        .deliveryStatusWebhookUrl("delivery_status_webhook_url")
                        .build()
                )
                .model("model")
                .observabilitySettings(
                    ObservabilityReq.builder()
                        .host("host")
                        .promptLabel("prompt_label")
                        .promptName("prompt_name")
                        .promptSync(ObservabilityReq.PromptSync.ENABLED)
                        .promptVersion(1L)
                        .publicKeyRef("public_key_ref")
                        .secretKeyRef("secret_key_ref")
                        .status(ObservabilityReq.Status.ENABLED)
                        .build()
                )
                .postConversationSettings(
                    PostConversationSettingsReq.builder().enabled(true).build()
                )
                .privacySettings(PrivacySettings.builder().dataRetention(true).build())
                .addTag("string")
                .telephonySettings(
                    TelephonySettings.builder()
                        .defaultTexmlAppId("default_texml_app_id")
                        .noiseSuppression(TelephonySettings.NoiseSuppression.KRISP)
                        .noiseSuppressionConfig(
                            TelephonySettings.NoiseSuppressionConfig.builder()
                                .attenuationLimit(0L)
                                .mode(TelephonySettings.NoiseSuppressionConfig.Mode.ADVANCED)
                                .build()
                        )
                        .recordingSettings(
                            TelephonySettings.RecordingSettings.builder()
                                .channels(TelephonySettings.RecordingSettings.Channels.SINGLE)
                                .enabled(true)
                                .format(TelephonySettings.RecordingSettings.Format.WAV)
                                .stopOnConversationEnd(true)
                                .build()
                        )
                        .supportsUnauthenticatedWebCalls(true)
                        .timeLimitSecs(30L)
                        .userIdleReplySecs(0L)
                        .userIdleTimeoutSecs(10L)
                        .voicemailDetection(
                            TelephonySettings.VoicemailDetection.builder()
                                .onVoicemailDetected(
                                    TelephonySettings.VoicemailDetection.OnVoicemailDetected
                                        .builder()
                                        .action(
                                            TelephonySettings.VoicemailDetection.OnVoicemailDetected
                                                .Action
                                                .STOP_ASSISTANT
                                        )
                                        .voicemailMessage(
                                            TelephonySettings.VoicemailDetection.OnVoicemailDetected
                                                .VoicemailMessage
                                                .builder()
                                                .message("message")
                                                .prompt("prompt")
                                                .type(
                                                    TelephonySettings.VoicemailDetection
                                                        .OnVoicemailDetected
                                                        .VoicemailMessage
                                                        .Type
                                                        .PROMPT
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .addToolId("string")
                .addWebhookTool(
                    InferenceEmbeddingWebhookToolParams.Webhook.builder()
                        .description("description")
                        .name("name")
                        .url("https://example.com/api/v1/function")
                        .async(true)
                        .asyncTimeoutMs(1L)
                        .bodyParameters(
                            InferenceEmbeddingWebhookToolParams.Webhook.BodyParameters.builder()
                                .properties(
                                    InferenceEmbeddingWebhookToolParams.Webhook.BodyParameters
                                        .Properties
                                        .builder()
                                        .putAdditionalProperty("age", JsonValue.from("bar"))
                                        .putAdditionalProperty("location", JsonValue.from("bar"))
                                        .build()
                                )
                                .addRequired("age")
                                .addRequired("location")
                                .type(
                                    InferenceEmbeddingWebhookToolParams.Webhook.BodyParameters.Type
                                        .OBJECT
                                )
                                .build()
                        )
                        .addHeader(
                            InferenceEmbeddingWebhookToolParams.Webhook.Header.builder()
                                .name("name")
                                .value("value")
                                .build()
                        )
                        .method(InferenceEmbeddingWebhookToolParams.Webhook.Method.GET)
                        .pathParameters(
                            InferenceEmbeddingWebhookToolParams.Webhook.PathParameters.builder()
                                .properties(
                                    InferenceEmbeddingWebhookToolParams.Webhook.PathParameters
                                        .Properties
                                        .builder()
                                        .putAdditionalProperty("id", JsonValue.from("bar"))
                                        .build()
                                )
                                .addRequired("id")
                                .type(
                                    InferenceEmbeddingWebhookToolParams.Webhook.PathParameters.Type
                                        .OBJECT
                                )
                                .build()
                        )
                        .queryParameters(
                            InferenceEmbeddingWebhookToolParams.Webhook.QueryParameters.builder()
                                .properties(
                                    InferenceEmbeddingWebhookToolParams.Webhook.QueryParameters
                                        .Properties
                                        .builder()
                                        .putAdditionalProperty("page", JsonValue.from("bar"))
                                        .build()
                                )
                                .addRequired("page")
                                .type(
                                    InferenceEmbeddingWebhookToolParams.Webhook.QueryParameters.Type
                                        .OBJECT
                                )
                                .build()
                        )
                        .addStoreFieldsAsVariable(
                            InferenceEmbeddingWebhookToolParams.Webhook.StoreFieldsAsVariable
                                .builder()
                                .name("x")
                                .valuePath("x")
                                .build()
                        )
                        .timeoutMs(500L)
                        .build()
                )
                .transcription(
                    TranscriptionSettings.builder()
                        .apiKeyRef("api_key_ref")
                        .language("language")
                        .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                        .region("region")
                        .settings(
                            TranscriptionSettingsConfig.builder()
                                .eagerEotThreshold(0.3)
                                .enableEndpointDetection(true)
                                .endOfTurnConfidenceThreshold(0.0)
                                .eotThreshold(0.5)
                                .eotTimeoutMs(500L)
                                .interimResults(true)
                                .keyterm("keyterm")
                                .maxEndpointDelayMs(500L)
                                .maxTurnSilence(100L)
                                .minTurnSilence(100L)
                                .numerals(true)
                                .smartFormat(true)
                                .build()
                        )
                        .build()
                )
                .voiceSettings(
                    VoiceSettings.builder()
                        .voice("voice")
                        .apiKeyRef("api_key_ref")
                        .backgroundAudio(
                            VoiceSettings.BackgroundAudio.PredefinedMedia.builder()
                                .value(
                                    VoiceSettings.BackgroundAudio.PredefinedMedia
                                        .PredefinedMediaValue
                                        .SILENCE
                                )
                                .volume(0.1)
                                .build()
                        )
                        .expressiveMode(true)
                        .languageBoost(VoiceSettings.LanguageBoost.AUTO)
                        .similarityBoost(0.0)
                        .speed(0.0)
                        .style(0.0)
                        .temperature(0.0)
                        .useSpeakerBoost(true)
                        .voiceSpeed(0.0)
                        .build()
                )
                .widgetSettings(
                    WidgetSettings.builder()
                        .agentThinkingText("agent_thinking_text")
                        .audioVisualizerConfig(
                            AudioVisualizerConfig.builder()
                                .color(AudioVisualizerConfig.Color.VERDANT)
                                .preset("preset")
                                .build()
                        )
                        .defaultState(WidgetSettings.DefaultState.EXPANDED)
                        .giveFeedbackUrl("give_feedback_url")
                        .logoIconUrl("logo_icon_url")
                        .position(WidgetSettings.Position.FIXED)
                        .reportIssueUrl("report_issue_url")
                        .speakToInterruptText("speak_to_interrupt_text")
                        .startCallText("start_call_text")
                        .theme(WidgetSettings.Theme.LIGHT)
                        .viewHistoryUrl("view_history_url")
                        .build()
                )
                .build()

        val body = params._body()

        assertThat(body.instructions()).isEqualTo("instructions")
        assertThat(body.name()).isEqualTo("name")
        assertThat(body.description()).contains("description")
        assertThat(body.dynamicVariables())
            .contains(
                AssistantCreateParams.DynamicVariables.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(body.dynamicVariablesWebhookTimeoutMs()).contains(1L)
        assertThat(body.dynamicVariablesWebhookUrl()).contains("dynamic_variables_webhook_url")
        assertThat(body.enabledFeatures().getOrNull()).containsExactly(EnabledFeatures.TELEPHONY)
        assertThat(body.externalLlm())
            .contains(
                ExternalLlmReq.builder()
                    .baseUrl("base_url")
                    .model("model")
                    .authenticationMethod(ExternalLlmReq.AuthenticationMethod.TOKEN)
                    .certificateRef("certificate_ref")
                    .forwardMetadata(true)
                    .llmApiKeyRef("llm_api_key_ref")
                    .tokenRetrievalUrl("token_retrieval_url")
                    .build()
            )
        assertThat(body.fallbackConfig())
            .contains(
                FallbackConfigReq.builder()
                    .externalLlm(
                        ExternalLlmReq.builder()
                            .baseUrl("base_url")
                            .model("model")
                            .authenticationMethod(ExternalLlmReq.AuthenticationMethod.TOKEN)
                            .certificateRef("certificate_ref")
                            .forwardMetadata(true)
                            .llmApiKeyRef("llm_api_key_ref")
                            .tokenRetrievalUrl("token_retrieval_url")
                            .build()
                    )
                    .llmApiKeyRef("llm_api_key_ref")
                    .model("model")
                    .build()
            )
        assertThat(body.greeting()).contains("greeting")
        assertThat(body.insightSettings())
            .contains(InsightSettings.builder().insightGroupId("insight_group_id").build())
        assertThat(body.integrations().getOrNull())
            .containsExactly(
                AssistantCreateParams.Integration.builder()
                    .integrationId("integration_id")
                    .addAllowedList("string")
                    .build()
            )
        assertThat(body.interruptionSettings())
            .contains(
                AssistantCreateParams.InterruptionSettings.builder()
                    .disableGreetingInterruption(true)
                    .enable(true)
                    .startSpeakingPlan(
                        AssistantCreateParams.InterruptionSettings.StartSpeakingPlan.builder()
                            .transcriptionEndpointingPlan(
                                AssistantCreateParams.InterruptionSettings.StartSpeakingPlan
                                    .TranscriptionEndpointingPlan
                                    .builder()
                                    .onNoPunctuationSeconds(0.0f)
                                    .onNumberSeconds(0.0f)
                                    .onPunctuationSeconds(0.0f)
                                    .build()
                            )
                            .waitSeconds(0.0f)
                            .build()
                    )
                    .build()
            )
        assertThat(body.llmApiKeyRef()).contains("llm_api_key_ref")
        assertThat(body.mcpServers().getOrNull())
            .containsExactly(
                AssistantCreateParams.McpServer.builder().id("id").addAllowedTool("string").build()
            )
        assertThat(body.messagingSettings())
            .contains(
                MessagingSettings.builder()
                    .conversationInactivityMinutes(1L)
                    .defaultMessagingProfileId("default_messaging_profile_id")
                    .deliveryStatusWebhookUrl("delivery_status_webhook_url")
                    .build()
            )
        assertThat(body.model()).contains("model")
        assertThat(body.observabilitySettings())
            .contains(
                ObservabilityReq.builder()
                    .host("host")
                    .promptLabel("prompt_label")
                    .promptName("prompt_name")
                    .promptSync(ObservabilityReq.PromptSync.ENABLED)
                    .promptVersion(1L)
                    .publicKeyRef("public_key_ref")
                    .secretKeyRef("secret_key_ref")
                    .status(ObservabilityReq.Status.ENABLED)
                    .build()
            )
        assertThat(body.postConversationSettings())
            .contains(PostConversationSettingsReq.builder().enabled(true).build())
        assertThat(body.privacySettings())
            .contains(PrivacySettings.builder().dataRetention(true).build())
        assertThat(body.tags().getOrNull()).containsExactly("string")
        assertThat(body.telephonySettings())
            .contains(
                TelephonySettings.builder()
                    .defaultTexmlAppId("default_texml_app_id")
                    .noiseSuppression(TelephonySettings.NoiseSuppression.KRISP)
                    .noiseSuppressionConfig(
                        TelephonySettings.NoiseSuppressionConfig.builder()
                            .attenuationLimit(0L)
                            .mode(TelephonySettings.NoiseSuppressionConfig.Mode.ADVANCED)
                            .build()
                    )
                    .recordingSettings(
                        TelephonySettings.RecordingSettings.builder()
                            .channels(TelephonySettings.RecordingSettings.Channels.SINGLE)
                            .enabled(true)
                            .format(TelephonySettings.RecordingSettings.Format.WAV)
                            .stopOnConversationEnd(true)
                            .build()
                    )
                    .supportsUnauthenticatedWebCalls(true)
                    .timeLimitSecs(30L)
                    .userIdleReplySecs(0L)
                    .userIdleTimeoutSecs(10L)
                    .voicemailDetection(
                        TelephonySettings.VoicemailDetection.builder()
                            .onVoicemailDetected(
                                TelephonySettings.VoicemailDetection.OnVoicemailDetected.builder()
                                    .action(
                                        TelephonySettings.VoicemailDetection.OnVoicemailDetected
                                            .Action
                                            .STOP_ASSISTANT
                                    )
                                    .voicemailMessage(
                                        TelephonySettings.VoicemailDetection.OnVoicemailDetected
                                            .VoicemailMessage
                                            .builder()
                                            .message("message")
                                            .prompt("prompt")
                                            .type(
                                                TelephonySettings.VoicemailDetection
                                                    .OnVoicemailDetected
                                                    .VoicemailMessage
                                                    .Type
                                                    .PROMPT
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(body.toolIds().getOrNull()).containsExactly("string")
        assertThat(body.tools().getOrNull())
            .containsExactly(
                AssistantTool.ofWebhook(
                    InferenceEmbeddingWebhookToolParams.builder()
                        .type(InferenceEmbeddingWebhookToolParams.Type.WEBHOOK)
                        .webhook(
                            InferenceEmbeddingWebhookToolParams.Webhook.builder()
                                .description("description")
                                .name("name")
                                .url("https://example.com/api/v1/function")
                                .async(true)
                                .asyncTimeoutMs(1L)
                                .bodyParameters(
                                    InferenceEmbeddingWebhookToolParams.Webhook.BodyParameters
                                        .builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .BodyParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty("age", JsonValue.from("bar"))
                                                .putAdditionalProperty(
                                                    "location",
                                                    JsonValue.from("bar"),
                                                )
                                                .build()
                                        )
                                        .addRequired("age")
                                        .addRequired("location")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .BodyParameters
                                                .Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .addHeader(
                                    InferenceEmbeddingWebhookToolParams.Webhook.Header.builder()
                                        .name("name")
                                        .value("value")
                                        .build()
                                )
                                .method(InferenceEmbeddingWebhookToolParams.Webhook.Method.GET)
                                .pathParameters(
                                    InferenceEmbeddingWebhookToolParams.Webhook.PathParameters
                                        .builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .PathParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty("id", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .addRequired("id")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .PathParameters
                                                .Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .queryParameters(
                                    InferenceEmbeddingWebhookToolParams.Webhook.QueryParameters
                                        .builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .QueryParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty(
                                                    "page",
                                                    JsonValue.from("bar"),
                                                )
                                                .build()
                                        )
                                        .addRequired("page")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .QueryParameters
                                                .Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .addStoreFieldsAsVariable(
                                    InferenceEmbeddingWebhookToolParams.Webhook
                                        .StoreFieldsAsVariable
                                        .builder()
                                        .name("x")
                                        .valuePath("x")
                                        .build()
                                )
                                .timeoutMs(500L)
                                .build()
                        )
                        .build()
                )
            )
        assertThat(body.transcription())
            .contains(
                TranscriptionSettings.builder()
                    .apiKeyRef("api_key_ref")
                    .language("language")
                    .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                    .region("region")
                    .settings(
                        TranscriptionSettingsConfig.builder()
                            .eagerEotThreshold(0.3)
                            .enableEndpointDetection(true)
                            .endOfTurnConfidenceThreshold(0.0)
                            .eotThreshold(0.5)
                            .eotTimeoutMs(500L)
                            .interimResults(true)
                            .keyterm("keyterm")
                            .maxEndpointDelayMs(500L)
                            .maxTurnSilence(100L)
                            .minTurnSilence(100L)
                            .numerals(true)
                            .smartFormat(true)
                            .build()
                    )
                    .build()
            )
        assertThat(body.voiceSettings())
            .contains(
                VoiceSettings.builder()
                    .voice("voice")
                    .apiKeyRef("api_key_ref")
                    .backgroundAudio(
                        VoiceSettings.BackgroundAudio.PredefinedMedia.builder()
                            .value(
                                VoiceSettings.BackgroundAudio.PredefinedMedia.PredefinedMediaValue
                                    .SILENCE
                            )
                            .volume(0.1)
                            .build()
                    )
                    .expressiveMode(true)
                    .languageBoost(VoiceSettings.LanguageBoost.AUTO)
                    .similarityBoost(0.0)
                    .speed(0.0)
                    .style(0.0)
                    .temperature(0.0)
                    .useSpeakerBoost(true)
                    .voiceSpeed(0.0)
                    .build()
            )
        assertThat(body.widgetSettings())
            .contains(
                WidgetSettings.builder()
                    .agentThinkingText("agent_thinking_text")
                    .audioVisualizerConfig(
                        AudioVisualizerConfig.builder()
                            .color(AudioVisualizerConfig.Color.VERDANT)
                            .preset("preset")
                            .build()
                    )
                    .defaultState(WidgetSettings.DefaultState.EXPANDED)
                    .giveFeedbackUrl("give_feedback_url")
                    .logoIconUrl("logo_icon_url")
                    .position(WidgetSettings.Position.FIXED)
                    .reportIssueUrl("report_issue_url")
                    .speakToInterruptText("speak_to_interrupt_text")
                    .startCallText("start_call_text")
                    .theme(WidgetSettings.Theme.LIGHT)
                    .viewHistoryUrl("view_history_url")
                    .build()
            )
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            AssistantCreateParams.builder().instructions("instructions").name("name").build()

        val body = params._body()

        assertThat(body.instructions()).isEqualTo("instructions")
        assertThat(body.name()).isEqualTo("name")
    }
}
