// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.ai.assistants

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.JsonValue
import com.telnyx.sdk.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AssistantsListTest {

    @Test
    fun create() {
        val assistantsList =
            AssistantsList.builder()
                .addData(
                    InferenceEmbedding.builder()
                        .id("id")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .instructions("instructions")
                        .model("model")
                        .name("name")
                        .description("description")
                        .dynamicVariables(
                            InferenceEmbedding.DynamicVariables.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .dynamicVariablesWebhookTimeoutMs(1L)
                        .dynamicVariablesWebhookUrl("dynamic_variables_webhook_url")
                        .addEnabledFeature(EnabledFeatures.TELEPHONY)
                        .externalLlm(
                            ExternalLlm.builder()
                                .baseUrl("base_url")
                                .model("model")
                                .authenticationMethod(ExternalLlm.AuthenticationMethod.TOKEN)
                                .certificateRef("certificate_ref")
                                .forwardMetadata(true)
                                .llmApiKeyRef("llm_api_key_ref")
                                .tokenRetrievalUrl("token_retrieval_url")
                                .build()
                        )
                        .fallbackConfig(
                            FallbackConfig.builder()
                                .externalLlm(
                                    ExternalLlm.builder()
                                        .baseUrl("base_url")
                                        .model("model")
                                        .authenticationMethod(
                                            ExternalLlm.AuthenticationMethod.TOKEN
                                        )
                                        .certificateRef("certificate_ref")
                                        .forwardMetadata(true)
                                        .llmApiKeyRef("llm_api_key_ref")
                                        .tokenRetrievalUrl("token_retrieval_url")
                                        .build()
                                )
                                .llmApiKeyRef("llm_api_key_ref")
                                .model("model")
                                .build()
                        )
                        .greeting("greeting")
                        .importMetadata(
                            ImportMetadata.builder()
                                .importId("import_id")
                                .importProvider(ImportMetadata.ImportProvider.ELEVENLABS)
                                .build()
                        )
                        .insightSettings(
                            InsightSettings.builder().insightGroupId("insight_group_id").build()
                        )
                        .addIntegration(
                            InferenceEmbedding.Integration.builder()
                                .integrationId("integration_id")
                                .addAllowedList("string")
                                .build()
                        )
                        .interruptionSettings(
                            InferenceEmbedding.InterruptionSettings.builder()
                                .disableGreetingInterruption(true)
                                .enable(true)
                                .startSpeakingPlan(
                                    InferenceEmbedding.InterruptionSettings.StartSpeakingPlan
                                        .builder()
                                        .transcriptionEndpointingPlan(
                                            InferenceEmbedding.InterruptionSettings
                                                .StartSpeakingPlan
                                                .TranscriptionEndpointingPlan
                                                .builder()
                                                .onNoPunctuationSeconds(0.0f)
                                                .onNumberSeconds(0.0f)
                                                .onPunctuationSeconds(0.0f)
                                                .build()
                                        )
                                        .waitSeconds(0.0f)
                                        .build()
                                )
                                .build()
                        )
                        .llmApiKeyRef("llm_api_key_ref")
                        .addMcpServer(
                            InferenceEmbedding.McpServer.builder()
                                .id("id")
                                .addAllowedTool("string")
                                .build()
                        )
                        .messagingSettings(
                            MessagingSettings.builder()
                                .conversationInactivityMinutes(1L)
                                .defaultMessagingProfileId("default_messaging_profile_id")
                                .deliveryStatusWebhookUrl("delivery_status_webhook_url")
                                .build()
                        )
                        .observabilitySettings(
                            Observability.builder()
                                .host("host")
                                .promptLabel("prompt_label")
                                .promptName("prompt_name")
                                .promptSync(Observability.PromptSync.ENABLED)
                                .promptVersion(1L)
                                .publicKeyRef("public_key_ref")
                                .secretKeyRef("secret_key_ref")
                                .status(Observability.Status.ENABLED)
                                .build()
                        )
                        .postConversationSettings(
                            PostConversationSettings.builder().enabled(true).build()
                        )
                        .privacySettings(PrivacySettings.builder().dataRetention(true).build())
                        .addRelatedMissionId("string")
                        .addTag("string")
                        .telephonySettings(
                            TelephonySettings.builder()
                                .defaultTexmlAppId("default_texml_app_id")
                                .noiseSuppression(TelephonySettings.NoiseSuppression.KRISP)
                                .noiseSuppressionConfig(
                                    TelephonySettings.NoiseSuppressionConfig.builder()
                                        .attenuationLimit(0L)
                                        .mode(
                                            TelephonySettings.NoiseSuppressionConfig.Mode.ADVANCED
                                        )
                                        .build()
                                )
                                .recordingSettings(
                                    TelephonySettings.RecordingSettings.builder()
                                        .channels(
                                            TelephonySettings.RecordingSettings.Channels.SINGLE
                                        )
                                        .enabled(true)
                                        .format(TelephonySettings.RecordingSettings.Format.WAV)
                                        .build()
                                )
                                .supportsUnauthenticatedWebCalls(true)
                                .timeLimitSecs(30L)
                                .userIdleReplySecs(0L)
                                .userIdleTimeoutSecs(10L)
                                .voicemailDetection(
                                    TelephonySettings.VoicemailDetection.builder()
                                        .onVoicemailDetected(
                                            TelephonySettings.VoicemailDetection.OnVoicemailDetected
                                                .builder()
                                                .action(
                                                    TelephonySettings.VoicemailDetection
                                                        .OnVoicemailDetected
                                                        .Action
                                                        .STOP_ASSISTANT
                                                )
                                                .voicemailMessage(
                                                    TelephonySettings.VoicemailDetection
                                                        .OnVoicemailDetected
                                                        .VoicemailMessage
                                                        .builder()
                                                        .message("message")
                                                        .prompt("prompt")
                                                        .type(
                                                            TelephonySettings.VoicemailDetection
                                                                .OnVoicemailDetected
                                                                .VoicemailMessage
                                                                .Type
                                                                .PROMPT
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .addWebhookTool(
                            InferenceEmbeddingWebhookToolParams.Webhook.builder()
                                .description("description")
                                .name("name")
                                .url("https://example.com/api/v1/function")
                                .async(true)
                                .bodyParameters(
                                    InferenceEmbeddingWebhookToolParams.Webhook.BodyParameters
                                        .builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .BodyParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty("age", JsonValue.from("bar"))
                                                .putAdditionalProperty(
                                                    "location",
                                                    JsonValue.from("bar"),
                                                )
                                                .build()
                                        )
                                        .addRequired("age")
                                        .addRequired("location")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .BodyParameters
                                                .Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .addHeader(
                                    InferenceEmbeddingWebhookToolParams.Webhook.Header.builder()
                                        .name("name")
                                        .value("value")
                                        .build()
                                )
                                .method(InferenceEmbeddingWebhookToolParams.Webhook.Method.GET)
                                .pathParameters(
                                    InferenceEmbeddingWebhookToolParams.Webhook.PathParameters
                                        .builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .PathParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty("id", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .addRequired("id")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .PathParameters
                                                .Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .queryParameters(
                                    InferenceEmbeddingWebhookToolParams.Webhook.QueryParameters
                                        .builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .QueryParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty(
                                                    "page",
                                                    JsonValue.from("bar"),
                                                )
                                                .build()
                                        )
                                        .addRequired("page")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .QueryParameters
                                                .Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .addStoreFieldsAsVariable(
                                    InferenceEmbeddingWebhookToolParams.Webhook
                                        .StoreFieldsAsVariable
                                        .builder()
                                        .name("x")
                                        .valuePath("x")
                                        .build()
                                )
                                .timeoutMs(500L)
                                .build()
                        )
                        .transcription(
                            TranscriptionSettings.builder()
                                .apiKeyRef("api_key_ref")
                                .language("language")
                                .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                                .region("region")
                                .settings(
                                    TranscriptionSettingsConfig.builder()
                                        .eagerEotThreshold(0.3)
                                        .endOfTurnConfidenceThreshold(0.0)
                                        .eotThreshold(0.5)
                                        .eotTimeoutMs(500L)
                                        .keyterm("keyterm")
                                        .maxTurnSilence(100L)
                                        .minTurnSilence(100L)
                                        .numerals(true)
                                        .smartFormat(true)
                                        .build()
                                )
                                .build()
                        )
                        .versionCreatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .versionId("version_id")
                        .versionName("version_name")
                        .voiceSettings(
                            VoiceSettings.builder()
                                .voice("voice")
                                .apiKeyRef("api_key_ref")
                                .predefinedMediaBackgroundAudio(
                                    VoiceSettings.BackgroundAudio.PredefinedMedia
                                        .PredefinedMediaValue
                                        .SILENCE
                                )
                                .expressiveMode(true)
                                .languageBoost(VoiceSettings.LanguageBoost.AUTO)
                                .similarityBoost(0.0)
                                .speed(0.0)
                                .style(0.0)
                                .temperature(0.0)
                                .useSpeakerBoost(true)
                                .voiceSpeed(0.0)
                                .build()
                        )
                        .widgetSettings(
                            WidgetSettings.builder()
                                .agentThinkingText("agent_thinking_text")
                                .audioVisualizerConfig(
                                    AudioVisualizerConfig.builder()
                                        .color(AudioVisualizerConfig.Color.VERDANT)
                                        .preset("preset")
                                        .build()
                                )
                                .defaultState(WidgetSettings.DefaultState.EXPANDED)
                                .giveFeedbackUrl("give_feedback_url")
                                .logoIconUrl("logo_icon_url")
                                .position(WidgetSettings.Position.FIXED)
                                .reportIssueUrl("report_issue_url")
                                .speakToInterruptText("speak_to_interrupt_text")
                                .startCallText("start_call_text")
                                .theme(WidgetSettings.Theme.LIGHT)
                                .viewHistoryUrl("view_history_url")
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(assistantsList.data())
            .containsExactly(
                InferenceEmbedding.builder()
                    .id("id")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .instructions("instructions")
                    .model("model")
                    .name("name")
                    .description("description")
                    .dynamicVariables(
                        InferenceEmbedding.DynamicVariables.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .dynamicVariablesWebhookTimeoutMs(1L)
                    .dynamicVariablesWebhookUrl("dynamic_variables_webhook_url")
                    .addEnabledFeature(EnabledFeatures.TELEPHONY)
                    .externalLlm(
                        ExternalLlm.builder()
                            .baseUrl("base_url")
                            .model("model")
                            .authenticationMethod(ExternalLlm.AuthenticationMethod.TOKEN)
                            .certificateRef("certificate_ref")
                            .forwardMetadata(true)
                            .llmApiKeyRef("llm_api_key_ref")
                            .tokenRetrievalUrl("token_retrieval_url")
                            .build()
                    )
                    .fallbackConfig(
                        FallbackConfig.builder()
                            .externalLlm(
                                ExternalLlm.builder()
                                    .baseUrl("base_url")
                                    .model("model")
                                    .authenticationMethod(ExternalLlm.AuthenticationMethod.TOKEN)
                                    .certificateRef("certificate_ref")
                                    .forwardMetadata(true)
                                    .llmApiKeyRef("llm_api_key_ref")
                                    .tokenRetrievalUrl("token_retrieval_url")
                                    .build()
                            )
                            .llmApiKeyRef("llm_api_key_ref")
                            .model("model")
                            .build()
                    )
                    .greeting("greeting")
                    .importMetadata(
                        ImportMetadata.builder()
                            .importId("import_id")
                            .importProvider(ImportMetadata.ImportProvider.ELEVENLABS)
                            .build()
                    )
                    .insightSettings(
                        InsightSettings.builder().insightGroupId("insight_group_id").build()
                    )
                    .addIntegration(
                        InferenceEmbedding.Integration.builder()
                            .integrationId("integration_id")
                            .addAllowedList("string")
                            .build()
                    )
                    .interruptionSettings(
                        InferenceEmbedding.InterruptionSettings.builder()
                            .disableGreetingInterruption(true)
                            .enable(true)
                            .startSpeakingPlan(
                                InferenceEmbedding.InterruptionSettings.StartSpeakingPlan.builder()
                                    .transcriptionEndpointingPlan(
                                        InferenceEmbedding.InterruptionSettings.StartSpeakingPlan
                                            .TranscriptionEndpointingPlan
                                            .builder()
                                            .onNoPunctuationSeconds(0.0f)
                                            .onNumberSeconds(0.0f)
                                            .onPunctuationSeconds(0.0f)
                                            .build()
                                    )
                                    .waitSeconds(0.0f)
                                    .build()
                            )
                            .build()
                    )
                    .llmApiKeyRef("llm_api_key_ref")
                    .addMcpServer(
                        InferenceEmbedding.McpServer.builder()
                            .id("id")
                            .addAllowedTool("string")
                            .build()
                    )
                    .messagingSettings(
                        MessagingSettings.builder()
                            .conversationInactivityMinutes(1L)
                            .defaultMessagingProfileId("default_messaging_profile_id")
                            .deliveryStatusWebhookUrl("delivery_status_webhook_url")
                            .build()
                    )
                    .observabilitySettings(
                        Observability.builder()
                            .host("host")
                            .promptLabel("prompt_label")
                            .promptName("prompt_name")
                            .promptSync(Observability.PromptSync.ENABLED)
                            .promptVersion(1L)
                            .publicKeyRef("public_key_ref")
                            .secretKeyRef("secret_key_ref")
                            .status(Observability.Status.ENABLED)
                            .build()
                    )
                    .postConversationSettings(
                        PostConversationSettings.builder().enabled(true).build()
                    )
                    .privacySettings(PrivacySettings.builder().dataRetention(true).build())
                    .addRelatedMissionId("string")
                    .addTag("string")
                    .telephonySettings(
                        TelephonySettings.builder()
                            .defaultTexmlAppId("default_texml_app_id")
                            .noiseSuppression(TelephonySettings.NoiseSuppression.KRISP)
                            .noiseSuppressionConfig(
                                TelephonySettings.NoiseSuppressionConfig.builder()
                                    .attenuationLimit(0L)
                                    .mode(TelephonySettings.NoiseSuppressionConfig.Mode.ADVANCED)
                                    .build()
                            )
                            .recordingSettings(
                                TelephonySettings.RecordingSettings.builder()
                                    .channels(TelephonySettings.RecordingSettings.Channels.SINGLE)
                                    .enabled(true)
                                    .format(TelephonySettings.RecordingSettings.Format.WAV)
                                    .build()
                            )
                            .supportsUnauthenticatedWebCalls(true)
                            .timeLimitSecs(30L)
                            .userIdleReplySecs(0L)
                            .userIdleTimeoutSecs(10L)
                            .voicemailDetection(
                                TelephonySettings.VoicemailDetection.builder()
                                    .onVoicemailDetected(
                                        TelephonySettings.VoicemailDetection.OnVoicemailDetected
                                            .builder()
                                            .action(
                                                TelephonySettings.VoicemailDetection
                                                    .OnVoicemailDetected
                                                    .Action
                                                    .STOP_ASSISTANT
                                            )
                                            .voicemailMessage(
                                                TelephonySettings.VoicemailDetection
                                                    .OnVoicemailDetected
                                                    .VoicemailMessage
                                                    .builder()
                                                    .message("message")
                                                    .prompt("prompt")
                                                    .type(
                                                        TelephonySettings.VoicemailDetection
                                                            .OnVoicemailDetected
                                                            .VoicemailMessage
                                                            .Type
                                                            .PROMPT
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .addWebhookTool(
                        InferenceEmbeddingWebhookToolParams.Webhook.builder()
                            .description("description")
                            .name("name")
                            .url("https://example.com/api/v1/function")
                            .async(true)
                            .bodyParameters(
                                InferenceEmbeddingWebhookToolParams.Webhook.BodyParameters.builder()
                                    .properties(
                                        InferenceEmbeddingWebhookToolParams.Webhook.BodyParameters
                                            .Properties
                                            .builder()
                                            .putAdditionalProperty("age", JsonValue.from("bar"))
                                            .putAdditionalProperty(
                                                "location",
                                                JsonValue.from("bar"),
                                            )
                                            .build()
                                    )
                                    .addRequired("age")
                                    .addRequired("location")
                                    .type(
                                        InferenceEmbeddingWebhookToolParams.Webhook.BodyParameters
                                            .Type
                                            .OBJECT
                                    )
                                    .build()
                            )
                            .addHeader(
                                InferenceEmbeddingWebhookToolParams.Webhook.Header.builder()
                                    .name("name")
                                    .value("value")
                                    .build()
                            )
                            .method(InferenceEmbeddingWebhookToolParams.Webhook.Method.GET)
                            .pathParameters(
                                InferenceEmbeddingWebhookToolParams.Webhook.PathParameters.builder()
                                    .properties(
                                        InferenceEmbeddingWebhookToolParams.Webhook.PathParameters
                                            .Properties
                                            .builder()
                                            .putAdditionalProperty("id", JsonValue.from("bar"))
                                            .build()
                                    )
                                    .addRequired("id")
                                    .type(
                                        InferenceEmbeddingWebhookToolParams.Webhook.PathParameters
                                            .Type
                                            .OBJECT
                                    )
                                    .build()
                            )
                            .queryParameters(
                                InferenceEmbeddingWebhookToolParams.Webhook.QueryParameters
                                    .builder()
                                    .properties(
                                        InferenceEmbeddingWebhookToolParams.Webhook.QueryParameters
                                            .Properties
                                            .builder()
                                            .putAdditionalProperty("page", JsonValue.from("bar"))
                                            .build()
                                    )
                                    .addRequired("page")
                                    .type(
                                        InferenceEmbeddingWebhookToolParams.Webhook.QueryParameters
                                            .Type
                                            .OBJECT
                                    )
                                    .build()
                            )
                            .addStoreFieldsAsVariable(
                                InferenceEmbeddingWebhookToolParams.Webhook.StoreFieldsAsVariable
                                    .builder()
                                    .name("x")
                                    .valuePath("x")
                                    .build()
                            )
                            .timeoutMs(500L)
                            .build()
                    )
                    .transcription(
                        TranscriptionSettings.builder()
                            .apiKeyRef("api_key_ref")
                            .language("language")
                            .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                            .region("region")
                            .settings(
                                TranscriptionSettingsConfig.builder()
                                    .eagerEotThreshold(0.3)
                                    .endOfTurnConfidenceThreshold(0.0)
                                    .eotThreshold(0.5)
                                    .eotTimeoutMs(500L)
                                    .keyterm("keyterm")
                                    .maxTurnSilence(100L)
                                    .minTurnSilence(100L)
                                    .numerals(true)
                                    .smartFormat(true)
                                    .build()
                            )
                            .build()
                    )
                    .versionCreatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .versionId("version_id")
                    .versionName("version_name")
                    .voiceSettings(
                        VoiceSettings.builder()
                            .voice("voice")
                            .apiKeyRef("api_key_ref")
                            .predefinedMediaBackgroundAudio(
                                VoiceSettings.BackgroundAudio.PredefinedMedia.PredefinedMediaValue
                                    .SILENCE
                            )
                            .expressiveMode(true)
                            .languageBoost(VoiceSettings.LanguageBoost.AUTO)
                            .similarityBoost(0.0)
                            .speed(0.0)
                            .style(0.0)
                            .temperature(0.0)
                            .useSpeakerBoost(true)
                            .voiceSpeed(0.0)
                            .build()
                    )
                    .widgetSettings(
                        WidgetSettings.builder()
                            .agentThinkingText("agent_thinking_text")
                            .audioVisualizerConfig(
                                AudioVisualizerConfig.builder()
                                    .color(AudioVisualizerConfig.Color.VERDANT)
                                    .preset("preset")
                                    .build()
                            )
                            .defaultState(WidgetSettings.DefaultState.EXPANDED)
                            .giveFeedbackUrl("give_feedback_url")
                            .logoIconUrl("logo_icon_url")
                            .position(WidgetSettings.Position.FIXED)
                            .reportIssueUrl("report_issue_url")
                            .speakToInterruptText("speak_to_interrupt_text")
                            .startCallText("start_call_text")
                            .theme(WidgetSettings.Theme.LIGHT)
                            .viewHistoryUrl("view_history_url")
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val assistantsList =
            AssistantsList.builder()
                .addData(
                    InferenceEmbedding.builder()
                        .id("id")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .instructions("instructions")
                        .model("model")
                        .name("name")
                        .description("description")
                        .dynamicVariables(
                            InferenceEmbedding.DynamicVariables.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .dynamicVariablesWebhookTimeoutMs(1L)
                        .dynamicVariablesWebhookUrl("dynamic_variables_webhook_url")
                        .addEnabledFeature(EnabledFeatures.TELEPHONY)
                        .externalLlm(
                            ExternalLlm.builder()
                                .baseUrl("base_url")
                                .model("model")
                                .authenticationMethod(ExternalLlm.AuthenticationMethod.TOKEN)
                                .certificateRef("certificate_ref")
                                .forwardMetadata(true)
                                .llmApiKeyRef("llm_api_key_ref")
                                .tokenRetrievalUrl("token_retrieval_url")
                                .build()
                        )
                        .fallbackConfig(
                            FallbackConfig.builder()
                                .externalLlm(
                                    ExternalLlm.builder()
                                        .baseUrl("base_url")
                                        .model("model")
                                        .authenticationMethod(
                                            ExternalLlm.AuthenticationMethod.TOKEN
                                        )
                                        .certificateRef("certificate_ref")
                                        .forwardMetadata(true)
                                        .llmApiKeyRef("llm_api_key_ref")
                                        .tokenRetrievalUrl("token_retrieval_url")
                                        .build()
                                )
                                .llmApiKeyRef("llm_api_key_ref")
                                .model("model")
                                .build()
                        )
                        .greeting("greeting")
                        .importMetadata(
                            ImportMetadata.builder()
                                .importId("import_id")
                                .importProvider(ImportMetadata.ImportProvider.ELEVENLABS)
                                .build()
                        )
                        .insightSettings(
                            InsightSettings.builder().insightGroupId("insight_group_id").build()
                        )
                        .addIntegration(
                            InferenceEmbedding.Integration.builder()
                                .integrationId("integration_id")
                                .addAllowedList("string")
                                .build()
                        )
                        .interruptionSettings(
                            InferenceEmbedding.InterruptionSettings.builder()
                                .disableGreetingInterruption(true)
                                .enable(true)
                                .startSpeakingPlan(
                                    InferenceEmbedding.InterruptionSettings.StartSpeakingPlan
                                        .builder()
                                        .transcriptionEndpointingPlan(
                                            InferenceEmbedding.InterruptionSettings
                                                .StartSpeakingPlan
                                                .TranscriptionEndpointingPlan
                                                .builder()
                                                .onNoPunctuationSeconds(0.0f)
                                                .onNumberSeconds(0.0f)
                                                .onPunctuationSeconds(0.0f)
                                                .build()
                                        )
                                        .waitSeconds(0.0f)
                                        .build()
                                )
                                .build()
                        )
                        .llmApiKeyRef("llm_api_key_ref")
                        .addMcpServer(
                            InferenceEmbedding.McpServer.builder()
                                .id("id")
                                .addAllowedTool("string")
                                .build()
                        )
                        .messagingSettings(
                            MessagingSettings.builder()
                                .conversationInactivityMinutes(1L)
                                .defaultMessagingProfileId("default_messaging_profile_id")
                                .deliveryStatusWebhookUrl("delivery_status_webhook_url")
                                .build()
                        )
                        .observabilitySettings(
                            Observability.builder()
                                .host("host")
                                .promptLabel("prompt_label")
                                .promptName("prompt_name")
                                .promptSync(Observability.PromptSync.ENABLED)
                                .promptVersion(1L)
                                .publicKeyRef("public_key_ref")
                                .secretKeyRef("secret_key_ref")
                                .status(Observability.Status.ENABLED)
                                .build()
                        )
                        .postConversationSettings(
                            PostConversationSettings.builder().enabled(true).build()
                        )
                        .privacySettings(PrivacySettings.builder().dataRetention(true).build())
                        .addRelatedMissionId("string")
                        .addTag("string")
                        .telephonySettings(
                            TelephonySettings.builder()
                                .defaultTexmlAppId("default_texml_app_id")
                                .noiseSuppression(TelephonySettings.NoiseSuppression.KRISP)
                                .noiseSuppressionConfig(
                                    TelephonySettings.NoiseSuppressionConfig.builder()
                                        .attenuationLimit(0L)
                                        .mode(
                                            TelephonySettings.NoiseSuppressionConfig.Mode.ADVANCED
                                        )
                                        .build()
                                )
                                .recordingSettings(
                                    TelephonySettings.RecordingSettings.builder()
                                        .channels(
                                            TelephonySettings.RecordingSettings.Channels.SINGLE
                                        )
                                        .enabled(true)
                                        .format(TelephonySettings.RecordingSettings.Format.WAV)
                                        .build()
                                )
                                .supportsUnauthenticatedWebCalls(true)
                                .timeLimitSecs(30L)
                                .userIdleReplySecs(0L)
                                .userIdleTimeoutSecs(10L)
                                .voicemailDetection(
                                    TelephonySettings.VoicemailDetection.builder()
                                        .onVoicemailDetected(
                                            TelephonySettings.VoicemailDetection.OnVoicemailDetected
                                                .builder()
                                                .action(
                                                    TelephonySettings.VoicemailDetection
                                                        .OnVoicemailDetected
                                                        .Action
                                                        .STOP_ASSISTANT
                                                )
                                                .voicemailMessage(
                                                    TelephonySettings.VoicemailDetection
                                                        .OnVoicemailDetected
                                                        .VoicemailMessage
                                                        .builder()
                                                        .message("message")
                                                        .prompt("prompt")
                                                        .type(
                                                            TelephonySettings.VoicemailDetection
                                                                .OnVoicemailDetected
                                                                .VoicemailMessage
                                                                .Type
                                                                .PROMPT
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .addWebhookTool(
                            InferenceEmbeddingWebhookToolParams.Webhook.builder()
                                .description("description")
                                .name("name")
                                .url("https://example.com/api/v1/function")
                                .async(true)
                                .bodyParameters(
                                    InferenceEmbeddingWebhookToolParams.Webhook.BodyParameters
                                        .builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .BodyParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty("age", JsonValue.from("bar"))
                                                .putAdditionalProperty(
                                                    "location",
                                                    JsonValue.from("bar"),
                                                )
                                                .build()
                                        )
                                        .addRequired("age")
                                        .addRequired("location")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .BodyParameters
                                                .Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .addHeader(
                                    InferenceEmbeddingWebhookToolParams.Webhook.Header.builder()
                                        .name("name")
                                        .value("value")
                                        .build()
                                )
                                .method(InferenceEmbeddingWebhookToolParams.Webhook.Method.GET)
                                .pathParameters(
                                    InferenceEmbeddingWebhookToolParams.Webhook.PathParameters
                                        .builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .PathParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty("id", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .addRequired("id")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .PathParameters
                                                .Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .queryParameters(
                                    InferenceEmbeddingWebhookToolParams.Webhook.QueryParameters
                                        .builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .QueryParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty(
                                                    "page",
                                                    JsonValue.from("bar"),
                                                )
                                                .build()
                                        )
                                        .addRequired("page")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .QueryParameters
                                                .Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .addStoreFieldsAsVariable(
                                    InferenceEmbeddingWebhookToolParams.Webhook
                                        .StoreFieldsAsVariable
                                        .builder()
                                        .name("x")
                                        .valuePath("x")
                                        .build()
                                )
                                .timeoutMs(500L)
                                .build()
                        )
                        .transcription(
                            TranscriptionSettings.builder()
                                .apiKeyRef("api_key_ref")
                                .language("language")
                                .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                                .region("region")
                                .settings(
                                    TranscriptionSettingsConfig.builder()
                                        .eagerEotThreshold(0.3)
                                        .endOfTurnConfidenceThreshold(0.0)
                                        .eotThreshold(0.5)
                                        .eotTimeoutMs(500L)
                                        .keyterm("keyterm")
                                        .maxTurnSilence(100L)
                                        .minTurnSilence(100L)
                                        .numerals(true)
                                        .smartFormat(true)
                                        .build()
                                )
                                .build()
                        )
                        .versionCreatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .versionId("version_id")
                        .versionName("version_name")
                        .voiceSettings(
                            VoiceSettings.builder()
                                .voice("voice")
                                .apiKeyRef("api_key_ref")
                                .predefinedMediaBackgroundAudio(
                                    VoiceSettings.BackgroundAudio.PredefinedMedia
                                        .PredefinedMediaValue
                                        .SILENCE
                                )
                                .expressiveMode(true)
                                .languageBoost(VoiceSettings.LanguageBoost.AUTO)
                                .similarityBoost(0.0)
                                .speed(0.0)
                                .style(0.0)
                                .temperature(0.0)
                                .useSpeakerBoost(true)
                                .voiceSpeed(0.0)
                                .build()
                        )
                        .widgetSettings(
                            WidgetSettings.builder()
                                .agentThinkingText("agent_thinking_text")
                                .audioVisualizerConfig(
                                    AudioVisualizerConfig.builder()
                                        .color(AudioVisualizerConfig.Color.VERDANT)
                                        .preset("preset")
                                        .build()
                                )
                                .defaultState(WidgetSettings.DefaultState.EXPANDED)
                                .giveFeedbackUrl("give_feedback_url")
                                .logoIconUrl("logo_icon_url")
                                .position(WidgetSettings.Position.FIXED)
                                .reportIssueUrl("report_issue_url")
                                .speakToInterruptText("speak_to_interrupt_text")
                                .startCallText("start_call_text")
                                .theme(WidgetSettings.Theme.LIGHT)
                                .viewHistoryUrl("view_history_url")
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedAssistantsList =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(assistantsList),
                jacksonTypeRef<AssistantsList>(),
            )

        assertThat(roundtrippedAssistantsList).isEqualTo(assistantsList)
    }
}
