// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.ai.assistants

import com.telnyx.sdk.core.JsonValue
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AssistantCreateParamsTest {

    @Test
    fun create() {
        AssistantCreateParams.builder()
            .instructions("instructions")
            .model("model")
            .name("name")
            .description("description")
            .dynamicVariables(
                AssistantCreateParams.DynamicVariables.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
            .dynamicVariablesWebhookUrl("dynamic_variables_webhook_url")
            .addEnabledFeature(EnabledFeatures.TELEPHONY)
            .greeting("greeting")
            .insightSettings(InsightSettings.builder().insightGroupId("insight_group_id").build())
            .llmApiKeyRef("llm_api_key_ref")
            .messagingSettings(
                MessagingSettings.builder()
                    .conversationInactivityMinutes(1L)
                    .defaultMessagingProfileId("default_messaging_profile_id")
                    .deliveryStatusWebhookUrl("delivery_status_webhook_url")
                    .build()
            )
            .privacySettings(PrivacySettings.builder().dataRetention(true).build())
            .telephonySettings(
                TelephonySettings.builder()
                    .defaultTexmlAppId("default_texml_app_id")
                    .noiseSuppression(TelephonySettings.NoiseSuppression.KRISP)
                    .noiseSuppressionConfig(
                        TelephonySettings.NoiseSuppressionConfig.builder()
                            .attenuationLimit(0L)
                            .mode(TelephonySettings.NoiseSuppressionConfig.Mode.ADVANCED)
                            .build()
                    )
                    .supportsUnauthenticatedWebCalls(true)
                    .timeLimitSecs(30L)
                    .userIdleTimeoutSecs(30L)
                    .voicemailDetection(
                        TelephonySettings.VoicemailDetection.builder()
                            .onVoicemailDetected(
                                TelephonySettings.VoicemailDetection.OnVoicemailDetected.builder()
                                    .action(
                                        TelephonySettings.VoicemailDetection.OnVoicemailDetected
                                            .Action
                                            .STOP_ASSISTANT
                                    )
                                    .voicemailMessage(
                                        TelephonySettings.VoicemailDetection.OnVoicemailDetected
                                            .VoicemailMessage
                                            .builder()
                                            .message("message")
                                            .prompt("prompt")
                                            .type(
                                                TelephonySettings.VoicemailDetection
                                                    .OnVoicemailDetected
                                                    .VoicemailMessage
                                                    .Type
                                                    .PROMPT
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
            .addWebhookTool(
                InferenceEmbeddingWebhookToolParams.builder()
                    .description("description")
                    .name("name")
                    .url("https://example.com/api/v1/function")
                    .async(true)
                    .bodyParameters(
                        InferenceEmbeddingWebhookToolParams.BodyParameters.builder()
                            .properties(
                                InferenceEmbeddingWebhookToolParams.BodyParameters.Properties
                                    .builder()
                                    .putAdditionalProperty("age", JsonValue.from("bar"))
                                    .putAdditionalProperty("location", JsonValue.from("bar"))
                                    .build()
                            )
                            .addRequired("age")
                            .addRequired("location")
                            .type(InferenceEmbeddingWebhookToolParams.BodyParameters.Type.OBJECT)
                            .build()
                    )
                    .addHeader(
                        InferenceEmbeddingWebhookToolParams.Header.builder()
                            .name("name")
                            .value("value")
                            .build()
                    )
                    .method(InferenceEmbeddingWebhookToolParams.Method.GET)
                    .pathParameters(
                        InferenceEmbeddingWebhookToolParams.PathParameters.builder()
                            .properties(
                                InferenceEmbeddingWebhookToolParams.PathParameters.Properties
                                    .builder()
                                    .putAdditionalProperty("id", JsonValue.from("bar"))
                                    .build()
                            )
                            .addRequired("id")
                            .type(InferenceEmbeddingWebhookToolParams.PathParameters.Type.OBJECT)
                            .build()
                    )
                    .queryParameters(
                        InferenceEmbeddingWebhookToolParams.QueryParameters.builder()
                            .properties(
                                InferenceEmbeddingWebhookToolParams.QueryParameters.Properties
                                    .builder()
                                    .putAdditionalProperty("page", JsonValue.from("bar"))
                                    .build()
                            )
                            .addRequired("page")
                            .type(InferenceEmbeddingWebhookToolParams.QueryParameters.Type.OBJECT)
                            .build()
                    )
                    .timeoutMs(500L)
                    .build()
            )
            .transcription(
                TranscriptionSettings.builder()
                    .language("language")
                    .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                    .region("region")
                    .settings(
                        TranscriptionSettingsConfig.builder()
                            .eagerEotThreshold(0.3)
                            .eotThreshold(0.0)
                            .eotTimeoutMs(0L)
                            .numerals(true)
                            .smartFormat(true)
                            .build()
                    )
                    .build()
            )
            .voiceSettings(
                VoiceSettings.builder()
                    .voice("voice")
                    .apiKeyRef("api_key_ref")
                    .predefinedMediaBackgroundAudio(
                        VoiceSettings.BackgroundAudio.PredefinedMedia.PredefinedMediaValue.SILENCE
                    )
                    .similarityBoost(0.0)
                    .speed(0.0)
                    .style(0.0)
                    .temperature(0.0)
                    .useSpeakerBoost(true)
                    .voiceSpeed(0.0)
                    .build()
            )
            .widgetSettings(
                AssistantCreateParams.WidgetSettings.builder()
                    .agentThinkingText("agent_thinking_text")
                    .audioVisualizerConfig(
                        AssistantCreateParams.WidgetSettings.AudioVisualizerConfig.builder()
                            .color(
                                AssistantCreateParams.WidgetSettings.AudioVisualizerConfig.Color
                                    .VERDANT
                            )
                            .preset("preset")
                            .build()
                    )
                    .defaultState(AssistantCreateParams.WidgetSettings.DefaultState.EXPANDED)
                    .giveFeedbackUrl("give_feedback_url")
                    .logoIconUrl("logo_icon_url")
                    .position(AssistantCreateParams.WidgetSettings.Position.FIXED)
                    .reportIssueUrl("report_issue_url")
                    .speakToInterruptText("speak_to_interrupt_text")
                    .startCallText("start_call_text")
                    .theme(AssistantCreateParams.WidgetSettings.Theme.LIGHT)
                    .viewHistoryUrl("view_history_url")
                    .build()
            )
            .build()
    }

    @Test
    fun body() {
        val params =
            AssistantCreateParams.builder()
                .instructions("instructions")
                .model("model")
                .name("name")
                .description("description")
                .dynamicVariables(
                    AssistantCreateParams.DynamicVariables.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .dynamicVariablesWebhookUrl("dynamic_variables_webhook_url")
                .addEnabledFeature(EnabledFeatures.TELEPHONY)
                .greeting("greeting")
                .insightSettings(
                    InsightSettings.builder().insightGroupId("insight_group_id").build()
                )
                .llmApiKeyRef("llm_api_key_ref")
                .messagingSettings(
                    MessagingSettings.builder()
                        .conversationInactivityMinutes(1L)
                        .defaultMessagingProfileId("default_messaging_profile_id")
                        .deliveryStatusWebhookUrl("delivery_status_webhook_url")
                        .build()
                )
                .privacySettings(PrivacySettings.builder().dataRetention(true).build())
                .telephonySettings(
                    TelephonySettings.builder()
                        .defaultTexmlAppId("default_texml_app_id")
                        .noiseSuppression(TelephonySettings.NoiseSuppression.KRISP)
                        .noiseSuppressionConfig(
                            TelephonySettings.NoiseSuppressionConfig.builder()
                                .attenuationLimit(0L)
                                .mode(TelephonySettings.NoiseSuppressionConfig.Mode.ADVANCED)
                                .build()
                        )
                        .supportsUnauthenticatedWebCalls(true)
                        .timeLimitSecs(30L)
                        .userIdleTimeoutSecs(30L)
                        .voicemailDetection(
                            TelephonySettings.VoicemailDetection.builder()
                                .onVoicemailDetected(
                                    TelephonySettings.VoicemailDetection.OnVoicemailDetected
                                        .builder()
                                        .action(
                                            TelephonySettings.VoicemailDetection.OnVoicemailDetected
                                                .Action
                                                .STOP_ASSISTANT
                                        )
                                        .voicemailMessage(
                                            TelephonySettings.VoicemailDetection.OnVoicemailDetected
                                                .VoicemailMessage
                                                .builder()
                                                .message("message")
                                                .prompt("prompt")
                                                .type(
                                                    TelephonySettings.VoicemailDetection
                                                        .OnVoicemailDetected
                                                        .VoicemailMessage
                                                        .Type
                                                        .PROMPT
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .addWebhookTool(
                    InferenceEmbeddingWebhookToolParams.builder()
                        .description("description")
                        .name("name")
                        .url("https://example.com/api/v1/function")
                        .async(true)
                        .bodyParameters(
                            InferenceEmbeddingWebhookToolParams.BodyParameters.builder()
                                .properties(
                                    InferenceEmbeddingWebhookToolParams.BodyParameters.Properties
                                        .builder()
                                        .putAdditionalProperty("age", JsonValue.from("bar"))
                                        .putAdditionalProperty("location", JsonValue.from("bar"))
                                        .build()
                                )
                                .addRequired("age")
                                .addRequired("location")
                                .type(
                                    InferenceEmbeddingWebhookToolParams.BodyParameters.Type.OBJECT
                                )
                                .build()
                        )
                        .addHeader(
                            InferenceEmbeddingWebhookToolParams.Header.builder()
                                .name("name")
                                .value("value")
                                .build()
                        )
                        .method(InferenceEmbeddingWebhookToolParams.Method.GET)
                        .pathParameters(
                            InferenceEmbeddingWebhookToolParams.PathParameters.builder()
                                .properties(
                                    InferenceEmbeddingWebhookToolParams.PathParameters.Properties
                                        .builder()
                                        .putAdditionalProperty("id", JsonValue.from("bar"))
                                        .build()
                                )
                                .addRequired("id")
                                .type(
                                    InferenceEmbeddingWebhookToolParams.PathParameters.Type.OBJECT
                                )
                                .build()
                        )
                        .queryParameters(
                            InferenceEmbeddingWebhookToolParams.QueryParameters.builder()
                                .properties(
                                    InferenceEmbeddingWebhookToolParams.QueryParameters.Properties
                                        .builder()
                                        .putAdditionalProperty("page", JsonValue.from("bar"))
                                        .build()
                                )
                                .addRequired("page")
                                .type(
                                    InferenceEmbeddingWebhookToolParams.QueryParameters.Type.OBJECT
                                )
                                .build()
                        )
                        .timeoutMs(500L)
                        .build()
                )
                .transcription(
                    TranscriptionSettings.builder()
                        .language("language")
                        .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                        .region("region")
                        .settings(
                            TranscriptionSettingsConfig.builder()
                                .eagerEotThreshold(0.3)
                                .eotThreshold(0.0)
                                .eotTimeoutMs(0L)
                                .numerals(true)
                                .smartFormat(true)
                                .build()
                        )
                        .build()
                )
                .voiceSettings(
                    VoiceSettings.builder()
                        .voice("voice")
                        .apiKeyRef("api_key_ref")
                        .predefinedMediaBackgroundAudio(
                            VoiceSettings.BackgroundAudio.PredefinedMedia.PredefinedMediaValue
                                .SILENCE
                        )
                        .similarityBoost(0.0)
                        .speed(0.0)
                        .style(0.0)
                        .temperature(0.0)
                        .useSpeakerBoost(true)
                        .voiceSpeed(0.0)
                        .build()
                )
                .widgetSettings(
                    AssistantCreateParams.WidgetSettings.builder()
                        .agentThinkingText("agent_thinking_text")
                        .audioVisualizerConfig(
                            AssistantCreateParams.WidgetSettings.AudioVisualizerConfig.builder()
                                .color(
                                    AssistantCreateParams.WidgetSettings.AudioVisualizerConfig.Color
                                        .VERDANT
                                )
                                .preset("preset")
                                .build()
                        )
                        .defaultState(AssistantCreateParams.WidgetSettings.DefaultState.EXPANDED)
                        .giveFeedbackUrl("give_feedback_url")
                        .logoIconUrl("logo_icon_url")
                        .position(AssistantCreateParams.WidgetSettings.Position.FIXED)
                        .reportIssueUrl("report_issue_url")
                        .speakToInterruptText("speak_to_interrupt_text")
                        .startCallText("start_call_text")
                        .theme(AssistantCreateParams.WidgetSettings.Theme.LIGHT)
                        .viewHistoryUrl("view_history_url")
                        .build()
                )
                .build()

        val body = params._body()

        assertThat(body.instructions()).isEqualTo("instructions")
        assertThat(body.model()).isEqualTo("model")
        assertThat(body.name()).isEqualTo("name")
        assertThat(body.description()).contains("description")
        assertThat(body.dynamicVariables())
            .contains(
                AssistantCreateParams.DynamicVariables.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(body.dynamicVariablesWebhookUrl()).contains("dynamic_variables_webhook_url")
        assertThat(body.enabledFeatures().getOrNull()).containsExactly(EnabledFeatures.TELEPHONY)
        assertThat(body.greeting()).contains("greeting")
        assertThat(body.insightSettings())
            .contains(InsightSettings.builder().insightGroupId("insight_group_id").build())
        assertThat(body.llmApiKeyRef()).contains("llm_api_key_ref")
        assertThat(body.messagingSettings())
            .contains(
                MessagingSettings.builder()
                    .conversationInactivityMinutes(1L)
                    .defaultMessagingProfileId("default_messaging_profile_id")
                    .deliveryStatusWebhookUrl("delivery_status_webhook_url")
                    .build()
            )
        assertThat(body.privacySettings())
            .contains(PrivacySettings.builder().dataRetention(true).build())
        assertThat(body.telephonySettings())
            .contains(
                TelephonySettings.builder()
                    .defaultTexmlAppId("default_texml_app_id")
                    .noiseSuppression(TelephonySettings.NoiseSuppression.KRISP)
                    .noiseSuppressionConfig(
                        TelephonySettings.NoiseSuppressionConfig.builder()
                            .attenuationLimit(0L)
                            .mode(TelephonySettings.NoiseSuppressionConfig.Mode.ADVANCED)
                            .build()
                    )
                    .supportsUnauthenticatedWebCalls(true)
                    .timeLimitSecs(30L)
                    .userIdleTimeoutSecs(30L)
                    .voicemailDetection(
                        TelephonySettings.VoicemailDetection.builder()
                            .onVoicemailDetected(
                                TelephonySettings.VoicemailDetection.OnVoicemailDetected.builder()
                                    .action(
                                        TelephonySettings.VoicemailDetection.OnVoicemailDetected
                                            .Action
                                            .STOP_ASSISTANT
                                    )
                                    .voicemailMessage(
                                        TelephonySettings.VoicemailDetection.OnVoicemailDetected
                                            .VoicemailMessage
                                            .builder()
                                            .message("message")
                                            .prompt("prompt")
                                            .type(
                                                TelephonySettings.VoicemailDetection
                                                    .OnVoicemailDetected
                                                    .VoicemailMessage
                                                    .Type
                                                    .PROMPT
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(body.tools().getOrNull())
            .containsExactly(
                AssistantTool.ofWebhook(
                    WebhookTool.builder()
                        .type(WebhookTool.Type.WEBHOOK)
                        .webhook(
                            InferenceEmbeddingWebhookToolParams.builder()
                                .description("description")
                                .name("name")
                                .url("https://example.com/api/v1/function")
                                .async(true)
                                .bodyParameters(
                                    InferenceEmbeddingWebhookToolParams.BodyParameters.builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.BodyParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty("age", JsonValue.from("bar"))
                                                .putAdditionalProperty(
                                                    "location",
                                                    JsonValue.from("bar"),
                                                )
                                                .build()
                                        )
                                        .addRequired("age")
                                        .addRequired("location")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.BodyParameters.Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .addHeader(
                                    InferenceEmbeddingWebhookToolParams.Header.builder()
                                        .name("name")
                                        .value("value")
                                        .build()
                                )
                                .method(InferenceEmbeddingWebhookToolParams.Method.GET)
                                .pathParameters(
                                    InferenceEmbeddingWebhookToolParams.PathParameters.builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.PathParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty("id", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .addRequired("id")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.PathParameters.Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .queryParameters(
                                    InferenceEmbeddingWebhookToolParams.QueryParameters.builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.QueryParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty(
                                                    "page",
                                                    JsonValue.from("bar"),
                                                )
                                                .build()
                                        )
                                        .addRequired("page")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.QueryParameters.Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .timeoutMs(500L)
                                .build()
                        )
                        .build()
                )
            )
        assertThat(body.transcription())
            .contains(
                TranscriptionSettings.builder()
                    .language("language")
                    .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                    .region("region")
                    .settings(
                        TranscriptionSettingsConfig.builder()
                            .eagerEotThreshold(0.3)
                            .eotThreshold(0.0)
                            .eotTimeoutMs(0L)
                            .numerals(true)
                            .smartFormat(true)
                            .build()
                    )
                    .build()
            )
        assertThat(body.voiceSettings())
            .contains(
                VoiceSettings.builder()
                    .voice("voice")
                    .apiKeyRef("api_key_ref")
                    .predefinedMediaBackgroundAudio(
                        VoiceSettings.BackgroundAudio.PredefinedMedia.PredefinedMediaValue.SILENCE
                    )
                    .similarityBoost(0.0)
                    .speed(0.0)
                    .style(0.0)
                    .temperature(0.0)
                    .useSpeakerBoost(true)
                    .voiceSpeed(0.0)
                    .build()
            )
        assertThat(body.widgetSettings())
            .contains(
                AssistantCreateParams.WidgetSettings.builder()
                    .agentThinkingText("agent_thinking_text")
                    .audioVisualizerConfig(
                        AssistantCreateParams.WidgetSettings.AudioVisualizerConfig.builder()
                            .color(
                                AssistantCreateParams.WidgetSettings.AudioVisualizerConfig.Color
                                    .VERDANT
                            )
                            .preset("preset")
                            .build()
                    )
                    .defaultState(AssistantCreateParams.WidgetSettings.DefaultState.EXPANDED)
                    .giveFeedbackUrl("give_feedback_url")
                    .logoIconUrl("logo_icon_url")
                    .position(AssistantCreateParams.WidgetSettings.Position.FIXED)
                    .reportIssueUrl("report_issue_url")
                    .speakToInterruptText("speak_to_interrupt_text")
                    .startCallText("start_call_text")
                    .theme(AssistantCreateParams.WidgetSettings.Theme.LIGHT)
                    .viewHistoryUrl("view_history_url")
                    .build()
            )
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            AssistantCreateParams.builder()
                .instructions("instructions")
                .model("model")
                .name("name")
                .build()

        val body = params._body()

        assertThat(body.instructions()).isEqualTo("instructions")
        assertThat(body.model()).isEqualTo("model")
        assertThat(body.name()).isEqualTo("name")
    }
}
