// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.ai.assistants

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.JsonValue
import com.telnyx.sdk.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AssistantsListTest {

    @Test
    fun create() {
        val assistantsList =
            AssistantsList.builder()
                .addData(
                    InferenceEmbedding.builder()
                        .id("id")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .instructions("instructions")
                        .model("model")
                        .name("name")
                        .description("description")
                        .dynamicVariables(
                            InferenceEmbedding.DynamicVariables.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .dynamicVariablesWebhookUrl("dynamic_variables_webhook_url")
                        .addEnabledFeature(EnabledFeatures.TELEPHONY)
                        .greeting("greeting")
                        .importMetadata(
                            ImportMetadata.builder()
                                .importId("import_id")
                                .importProvider(ImportMetadata.ImportProvider.ELEVENLABS)
                                .build()
                        )
                        .insightSettings(
                            InsightSettings.builder().insightGroupId("insight_group_id").build()
                        )
                        .llmApiKeyRef("llm_api_key_ref")
                        .messagingSettings(
                            MessagingSettings.builder()
                                .defaultMessagingProfileId("default_messaging_profile_id")
                                .deliveryStatusWebhookUrl("delivery_status_webhook_url")
                                .build()
                        )
                        .privacySettings(PrivacySettings.builder().dataRetention(true).build())
                        .telephonySettings(
                            TelephonySettings.builder()
                                .defaultTexmlAppId("default_texml_app_id")
                                .noiseSuppression(TelephonySettings.NoiseSuppression.DEEPFILTERNET)
                                .noiseSuppressionConfig(
                                    TelephonySettings.NoiseSuppressionConfig.builder()
                                        .attenuationLimit(0L)
                                        .mode(
                                            TelephonySettings.NoiseSuppressionConfig.Mode.ADVANCED
                                        )
                                        .build()
                                )
                                .supportsUnauthenticatedWebCalls(true)
                                .timeLimitSecs(30L)
                                .build()
                        )
                        .addWebhookTool(
                            InferenceEmbeddingWebhookToolParams.builder()
                                .description("description")
                                .name("name")
                                .url("https://example.com/api/v1/function")
                                .bodyParameters(
                                    InferenceEmbeddingWebhookToolParams.BodyParameters.builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.BodyParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty("age", JsonValue.from("bar"))
                                                .putAdditionalProperty(
                                                    "location",
                                                    JsonValue.from("bar"),
                                                )
                                                .build()
                                        )
                                        .addRequired("age")
                                        .addRequired("location")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.BodyParameters.Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .addHeader(
                                    InferenceEmbeddingWebhookToolParams.Header.builder()
                                        .name("name")
                                        .value("value")
                                        .build()
                                )
                                .method(InferenceEmbeddingWebhookToolParams.Method.GET)
                                .pathParameters(
                                    InferenceEmbeddingWebhookToolParams.PathParameters.builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.PathParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty("id", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .addRequired("id")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.PathParameters.Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .queryParameters(
                                    InferenceEmbeddingWebhookToolParams.QueryParameters.builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.QueryParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty(
                                                    "page",
                                                    JsonValue.from("bar"),
                                                )
                                                .build()
                                        )
                                        .addRequired("page")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.QueryParameters.Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .transcription(
                            TranscriptionSettings.builder()
                                .language("language")
                                .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                                .region("region")
                                .settings(
                                    TranscriptionSettingsConfig.builder()
                                        .eagerEotThreshold(0.3)
                                        .eotThreshold(0.0)
                                        .eotTimeoutMs(0L)
                                        .numerals(true)
                                        .smartFormat(true)
                                        .build()
                                )
                                .build()
                        )
                        .voiceSettings(
                            VoiceSettings.builder()
                                .voice("voice")
                                .apiKeyRef("api_key_ref")
                                .predefinedMediaBackgroundAudio(
                                    VoiceSettings.BackgroundAudio.PredefinedMedia
                                        .PredefinedMediaValue
                                        .SILENCE
                                )
                                .similarityBoost(0.0)
                                .speed(0.0)
                                .style(0.0)
                                .temperature(0.0)
                                .useSpeakerBoost(true)
                                .voiceSpeed(0.0)
                                .build()
                        )
                        .widgetSettings(
                            InferenceEmbedding.WidgetSettings.builder()
                                .agentThinkingText("agent_thinking_text")
                                .audioVisualizerConfig(
                                    InferenceEmbedding.WidgetSettings.AudioVisualizerConfig
                                        .builder()
                                        .color(
                                            InferenceEmbedding.WidgetSettings.AudioVisualizerConfig
                                                .Color
                                                .VERDANT
                                        )
                                        .preset("preset")
                                        .build()
                                )
                                .defaultState(
                                    InferenceEmbedding.WidgetSettings.DefaultState.EXPANDED
                                )
                                .giveFeedbackUrl("give_feedback_url")
                                .logoIconUrl("logo_icon_url")
                                .position(InferenceEmbedding.WidgetSettings.Position.FIXED)
                                .reportIssueUrl("report_issue_url")
                                .speakToInterruptText("speak_to_interrupt_text")
                                .startCallText("start_call_text")
                                .theme(InferenceEmbedding.WidgetSettings.Theme.LIGHT)
                                .viewHistoryUrl("view_history_url")
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(assistantsList.data())
            .containsExactly(
                InferenceEmbedding.builder()
                    .id("id")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .instructions("instructions")
                    .model("model")
                    .name("name")
                    .description("description")
                    .dynamicVariables(
                        InferenceEmbedding.DynamicVariables.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .dynamicVariablesWebhookUrl("dynamic_variables_webhook_url")
                    .addEnabledFeature(EnabledFeatures.TELEPHONY)
                    .greeting("greeting")
                    .importMetadata(
                        ImportMetadata.builder()
                            .importId("import_id")
                            .importProvider(ImportMetadata.ImportProvider.ELEVENLABS)
                            .build()
                    )
                    .insightSettings(
                        InsightSettings.builder().insightGroupId("insight_group_id").build()
                    )
                    .llmApiKeyRef("llm_api_key_ref")
                    .messagingSettings(
                        MessagingSettings.builder()
                            .defaultMessagingProfileId("default_messaging_profile_id")
                            .deliveryStatusWebhookUrl("delivery_status_webhook_url")
                            .build()
                    )
                    .privacySettings(PrivacySettings.builder().dataRetention(true).build())
                    .telephonySettings(
                        TelephonySettings.builder()
                            .defaultTexmlAppId("default_texml_app_id")
                            .noiseSuppression(TelephonySettings.NoiseSuppression.DEEPFILTERNET)
                            .noiseSuppressionConfig(
                                TelephonySettings.NoiseSuppressionConfig.builder()
                                    .attenuationLimit(0L)
                                    .mode(TelephonySettings.NoiseSuppressionConfig.Mode.ADVANCED)
                                    .build()
                            )
                            .supportsUnauthenticatedWebCalls(true)
                            .timeLimitSecs(30L)
                            .build()
                    )
                    .addWebhookTool(
                        InferenceEmbeddingWebhookToolParams.builder()
                            .description("description")
                            .name("name")
                            .url("https://example.com/api/v1/function")
                            .bodyParameters(
                                InferenceEmbeddingWebhookToolParams.BodyParameters.builder()
                                    .properties(
                                        InferenceEmbeddingWebhookToolParams.BodyParameters
                                            .Properties
                                            .builder()
                                            .putAdditionalProperty("age", JsonValue.from("bar"))
                                            .putAdditionalProperty(
                                                "location",
                                                JsonValue.from("bar"),
                                            )
                                            .build()
                                    )
                                    .addRequired("age")
                                    .addRequired("location")
                                    .type(
                                        InferenceEmbeddingWebhookToolParams.BodyParameters.Type
                                            .OBJECT
                                    )
                                    .build()
                            )
                            .addHeader(
                                InferenceEmbeddingWebhookToolParams.Header.builder()
                                    .name("name")
                                    .value("value")
                                    .build()
                            )
                            .method(InferenceEmbeddingWebhookToolParams.Method.GET)
                            .pathParameters(
                                InferenceEmbeddingWebhookToolParams.PathParameters.builder()
                                    .properties(
                                        InferenceEmbeddingWebhookToolParams.PathParameters
                                            .Properties
                                            .builder()
                                            .putAdditionalProperty("id", JsonValue.from("bar"))
                                            .build()
                                    )
                                    .addRequired("id")
                                    .type(
                                        InferenceEmbeddingWebhookToolParams.PathParameters.Type
                                            .OBJECT
                                    )
                                    .build()
                            )
                            .queryParameters(
                                InferenceEmbeddingWebhookToolParams.QueryParameters.builder()
                                    .properties(
                                        InferenceEmbeddingWebhookToolParams.QueryParameters
                                            .Properties
                                            .builder()
                                            .putAdditionalProperty("page", JsonValue.from("bar"))
                                            .build()
                                    )
                                    .addRequired("page")
                                    .type(
                                        InferenceEmbeddingWebhookToolParams.QueryParameters.Type
                                            .OBJECT
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .transcription(
                        TranscriptionSettings.builder()
                            .language("language")
                            .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                            .region("region")
                            .settings(
                                TranscriptionSettingsConfig.builder()
                                    .eagerEotThreshold(0.3)
                                    .eotThreshold(0.0)
                                    .eotTimeoutMs(0L)
                                    .numerals(true)
                                    .smartFormat(true)
                                    .build()
                            )
                            .build()
                    )
                    .voiceSettings(
                        VoiceSettings.builder()
                            .voice("voice")
                            .apiKeyRef("api_key_ref")
                            .predefinedMediaBackgroundAudio(
                                VoiceSettings.BackgroundAudio.PredefinedMedia.PredefinedMediaValue
                                    .SILENCE
                            )
                            .similarityBoost(0.0)
                            .speed(0.0)
                            .style(0.0)
                            .temperature(0.0)
                            .useSpeakerBoost(true)
                            .voiceSpeed(0.0)
                            .build()
                    )
                    .widgetSettings(
                        InferenceEmbedding.WidgetSettings.builder()
                            .agentThinkingText("agent_thinking_text")
                            .audioVisualizerConfig(
                                InferenceEmbedding.WidgetSettings.AudioVisualizerConfig.builder()
                                    .color(
                                        InferenceEmbedding.WidgetSettings.AudioVisualizerConfig
                                            .Color
                                            .VERDANT
                                    )
                                    .preset("preset")
                                    .build()
                            )
                            .defaultState(InferenceEmbedding.WidgetSettings.DefaultState.EXPANDED)
                            .giveFeedbackUrl("give_feedback_url")
                            .logoIconUrl("logo_icon_url")
                            .position(InferenceEmbedding.WidgetSettings.Position.FIXED)
                            .reportIssueUrl("report_issue_url")
                            .speakToInterruptText("speak_to_interrupt_text")
                            .startCallText("start_call_text")
                            .theme(InferenceEmbedding.WidgetSettings.Theme.LIGHT)
                            .viewHistoryUrl("view_history_url")
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val assistantsList =
            AssistantsList.builder()
                .addData(
                    InferenceEmbedding.builder()
                        .id("id")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .instructions("instructions")
                        .model("model")
                        .name("name")
                        .description("description")
                        .dynamicVariables(
                            InferenceEmbedding.DynamicVariables.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .dynamicVariablesWebhookUrl("dynamic_variables_webhook_url")
                        .addEnabledFeature(EnabledFeatures.TELEPHONY)
                        .greeting("greeting")
                        .importMetadata(
                            ImportMetadata.builder()
                                .importId("import_id")
                                .importProvider(ImportMetadata.ImportProvider.ELEVENLABS)
                                .build()
                        )
                        .insightSettings(
                            InsightSettings.builder().insightGroupId("insight_group_id").build()
                        )
                        .llmApiKeyRef("llm_api_key_ref")
                        .messagingSettings(
                            MessagingSettings.builder()
                                .defaultMessagingProfileId("default_messaging_profile_id")
                                .deliveryStatusWebhookUrl("delivery_status_webhook_url")
                                .build()
                        )
                        .privacySettings(PrivacySettings.builder().dataRetention(true).build())
                        .telephonySettings(
                            TelephonySettings.builder()
                                .defaultTexmlAppId("default_texml_app_id")
                                .noiseSuppression(TelephonySettings.NoiseSuppression.DEEPFILTERNET)
                                .noiseSuppressionConfig(
                                    TelephonySettings.NoiseSuppressionConfig.builder()
                                        .attenuationLimit(0L)
                                        .mode(
                                            TelephonySettings.NoiseSuppressionConfig.Mode.ADVANCED
                                        )
                                        .build()
                                )
                                .supportsUnauthenticatedWebCalls(true)
                                .timeLimitSecs(30L)
                                .build()
                        )
                        .addWebhookTool(
                            InferenceEmbeddingWebhookToolParams.builder()
                                .description("description")
                                .name("name")
                                .url("https://example.com/api/v1/function")
                                .bodyParameters(
                                    InferenceEmbeddingWebhookToolParams.BodyParameters.builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.BodyParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty("age", JsonValue.from("bar"))
                                                .putAdditionalProperty(
                                                    "location",
                                                    JsonValue.from("bar"),
                                                )
                                                .build()
                                        )
                                        .addRequired("age")
                                        .addRequired("location")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.BodyParameters.Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .addHeader(
                                    InferenceEmbeddingWebhookToolParams.Header.builder()
                                        .name("name")
                                        .value("value")
                                        .build()
                                )
                                .method(InferenceEmbeddingWebhookToolParams.Method.GET)
                                .pathParameters(
                                    InferenceEmbeddingWebhookToolParams.PathParameters.builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.PathParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty("id", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .addRequired("id")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.PathParameters.Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .queryParameters(
                                    InferenceEmbeddingWebhookToolParams.QueryParameters.builder()
                                        .properties(
                                            InferenceEmbeddingWebhookToolParams.QueryParameters
                                                .Properties
                                                .builder()
                                                .putAdditionalProperty(
                                                    "page",
                                                    JsonValue.from("bar"),
                                                )
                                                .build()
                                        )
                                        .addRequired("page")
                                        .type(
                                            InferenceEmbeddingWebhookToolParams.QueryParameters.Type
                                                .OBJECT
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .transcription(
                            TranscriptionSettings.builder()
                                .language("language")
                                .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                                .region("region")
                                .settings(
                                    TranscriptionSettingsConfig.builder()
                                        .eagerEotThreshold(0.3)
                                        .eotThreshold(0.0)
                                        .eotTimeoutMs(0L)
                                        .numerals(true)
                                        .smartFormat(true)
                                        .build()
                                )
                                .build()
                        )
                        .voiceSettings(
                            VoiceSettings.builder()
                                .voice("voice")
                                .apiKeyRef("api_key_ref")
                                .predefinedMediaBackgroundAudio(
                                    VoiceSettings.BackgroundAudio.PredefinedMedia
                                        .PredefinedMediaValue
                                        .SILENCE
                                )
                                .similarityBoost(0.0)
                                .speed(0.0)
                                .style(0.0)
                                .temperature(0.0)
                                .useSpeakerBoost(true)
                                .voiceSpeed(0.0)
                                .build()
                        )
                        .widgetSettings(
                            InferenceEmbedding.WidgetSettings.builder()
                                .agentThinkingText("agent_thinking_text")
                                .audioVisualizerConfig(
                                    InferenceEmbedding.WidgetSettings.AudioVisualizerConfig
                                        .builder()
                                        .color(
                                            InferenceEmbedding.WidgetSettings.AudioVisualizerConfig
                                                .Color
                                                .VERDANT
                                        )
                                        .preset("preset")
                                        .build()
                                )
                                .defaultState(
                                    InferenceEmbedding.WidgetSettings.DefaultState.EXPANDED
                                )
                                .giveFeedbackUrl("give_feedback_url")
                                .logoIconUrl("logo_icon_url")
                                .position(InferenceEmbedding.WidgetSettings.Position.FIXED)
                                .reportIssueUrl("report_issue_url")
                                .speakToInterruptText("speak_to_interrupt_text")
                                .startCallText("start_call_text")
                                .theme(InferenceEmbedding.WidgetSettings.Theme.LIGHT)
                                .viewHistoryUrl("view_history_url")
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedAssistantsList =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(assistantsList),
                jacksonTypeRef<AssistantsList>(),
            )

        assertThat(roundtrippedAssistantsList).isEqualTo(assistantsList)
    }
}
