// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.ai.assistants

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.JsonValue
import com.telnyx.sdk.core.jsonMapper
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ConversationFlowTest {

    @Test
    fun create() {
        val conversationFlow =
            ConversationFlow.builder()
                .addNode(
                    FlowNode.builder()
                        .id("n_intake")
                        .instructions("Greet the caller and ask what they're calling about.")
                        .externalLlm(
                            ExternalLlm.builder()
                                .baseUrl("base_url")
                                .model("model")
                                .authenticationMethod(AuthenticationMethod.TOKEN)
                                .certificateRef("certificate_ref")
                                .forwardMetadata(true)
                                .llmApiKeyRef("llm_api_key_ref")
                                .tokenRetrievalUrl("token_retrieval_url")
                                .build()
                        )
                        .instructionsMode(FlowNode.InstructionsMode.REPLACE)
                        .llmApiKeyRef("llm_api_key_ref")
                        .model("model")
                        .name("Intake")
                        .position(NodePosition.builder().x(120.0).y(80.0).build())
                        .addSharedToolId("tool-faq-kb")
                        .addTool(
                            listOf(
                                AssistantTool.ofWebhook(
                                    InferenceEmbeddingWebhookToolParams.builder()
                                        .type(InferenceEmbeddingWebhookToolParams.Type.WEBHOOK)
                                        .webhook(
                                            InferenceEmbeddingWebhookToolParams.Webhook.builder()
                                                .description("description")
                                                .name("name")
                                                .url("https://example.com/api/v1/function")
                                                .async(true)
                                                .asyncTimeoutMs(1L)
                                                .bodyParameters(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .BodyParameters
                                                        .builder()
                                                        .properties(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .BodyParameters
                                                                .Properties
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "age",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .putAdditionalProperty(
                                                                    "location",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .build()
                                                        )
                                                        .addRequired("age")
                                                        .addRequired("location")
                                                        .type(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .BodyParameters
                                                                .Type
                                                                .OBJECT
                                                        )
                                                        .build()
                                                )
                                                .addHeader(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Header
                                                        .builder()
                                                        .name("name")
                                                        .value("value")
                                                        .build()
                                                )
                                                .addMessage(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Message
                                                        .WebhookToolRequestStartMessage
                                                        .builder()
                                                        .content("Let me look that up for you.")
                                                        .timingMs(100L)
                                                        .build()
                                                )
                                                .addMessage(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Message
                                                        .WebhookToolRequestResponseDelayedMessage
                                                        .builder()
                                                        .content("Still working on that.")
                                                        .timingMs(5000L)
                                                        .build()
                                                )
                                                .method(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Method
                                                        .GET
                                                )
                                                .pathParameters(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .PathParameters
                                                        .builder()
                                                        .properties(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .PathParameters
                                                                .Properties
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "id",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .build()
                                                        )
                                                        .addRequired("id")
                                                        .type(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .PathParameters
                                                                .Type
                                                                .OBJECT
                                                        )
                                                        .build()
                                                )
                                                .queryParameters(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .QueryParameters
                                                        .builder()
                                                        .properties(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .QueryParameters
                                                                .Properties
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "page",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .build()
                                                        )
                                                        .addRequired("page")
                                                        .type(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .QueryParameters
                                                                .Type
                                                                .OBJECT
                                                        )
                                                        .build()
                                                )
                                                .addStoreFieldsAsVariable(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .StoreFieldsAsVariable
                                                        .builder()
                                                        .name("x")
                                                        .valuePath("x")
                                                        .build()
                                                )
                                                .timeoutMs(500L)
                                                .build()
                                        )
                                        .build()
                                )
                            )
                        )
                        .toolsMode(FlowNode.ToolsMode.REPLACE)
                        .transcription(
                            TranscriptionSettings.builder()
                                .apiKeyRef("api_key_ref")
                                .language("language")
                                .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                                .region("region")
                                .settings(
                                    TranscriptionSettingsConfig.builder()
                                        .eagerEotThreshold(0.3)
                                        .enableEndpointDetection(true)
                                        .endOfTurnConfidenceThreshold(0.0)
                                        .eotThreshold(0.5)
                                        .eotTimeoutMs(500L)
                                        .interimResults(true)
                                        .keyterm("keyterm")
                                        .maxEndpointDelayMs(500L)
                                        .maxTurnSilence(100L)
                                        .minTurnSilence(100L)
                                        .numerals(true)
                                        .smartFormat(true)
                                        .build()
                                )
                                .build()
                        )
                        .type(FlowNode.Type.PROMPT)
                        .voiceSettings(
                            VoiceSettings.builder()
                                .voice("voice")
                                .apiKeyRef("api_key_ref")
                                .backgroundAudio(
                                    VoiceSettings.BackgroundAudio.PredefinedMedia.builder()
                                        .value(
                                            VoiceSettings.BackgroundAudio.PredefinedMedia
                                                .PredefinedMediaValue
                                                .SILENCE
                                        )
                                        .volume(0.1)
                                        .build()
                                )
                                .expressiveMode(true)
                                .languageBoost(VoiceSettings.LanguageBoost.AUTO)
                                .similarityBoost(0.0)
                                .speed(0.0)
                                .style(0.0)
                                .temperature(0.0)
                                .useSpeakerBoost(true)
                                .voiceSpeed(0.0)
                                .build()
                        )
                        .build()
                )
                .addNode(
                    FlowNode.builder()
                        .id("n_billing")
                        .instructions(
                            "Focus on billing questions. Look up the caller's latest invoice with the billing tool before answering."
                        )
                        .externalLlm(
                            ExternalLlm.builder()
                                .baseUrl("base_url")
                                .model("model")
                                .authenticationMethod(AuthenticationMethod.TOKEN)
                                .certificateRef("certificate_ref")
                                .forwardMetadata(true)
                                .llmApiKeyRef("llm_api_key_ref")
                                .tokenRetrievalUrl("token_retrieval_url")
                                .build()
                        )
                        .instructionsMode(FlowNode.InstructionsMode.APPEND)
                        .llmApiKeyRef("llm_api_key_ref")
                        .model("moonshotai/Kimi-K2.6")
                        .name("Billing")
                        .position(NodePosition.builder().x(420.0).y(80.0).build())
                        .addSharedToolId("tool-billing-lookup")
                        .addTool(
                            listOf(
                                AssistantTool.ofWebhook(
                                    InferenceEmbeddingWebhookToolParams.builder()
                                        .type(InferenceEmbeddingWebhookToolParams.Type.WEBHOOK)
                                        .webhook(
                                            InferenceEmbeddingWebhookToolParams.Webhook.builder()
                                                .description("description")
                                                .name("name")
                                                .url("https://example.com/api/v1/function")
                                                .async(true)
                                                .asyncTimeoutMs(1L)
                                                .bodyParameters(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .BodyParameters
                                                        .builder()
                                                        .properties(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .BodyParameters
                                                                .Properties
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "age",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .putAdditionalProperty(
                                                                    "location",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .build()
                                                        )
                                                        .addRequired("age")
                                                        .addRequired("location")
                                                        .type(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .BodyParameters
                                                                .Type
                                                                .OBJECT
                                                        )
                                                        .build()
                                                )
                                                .addHeader(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Header
                                                        .builder()
                                                        .name("name")
                                                        .value("value")
                                                        .build()
                                                )
                                                .addMessage(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Message
                                                        .WebhookToolRequestStartMessage
                                                        .builder()
                                                        .content("Let me look that up for you.")
                                                        .timingMs(100L)
                                                        .build()
                                                )
                                                .addMessage(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Message
                                                        .WebhookToolRequestResponseDelayedMessage
                                                        .builder()
                                                        .content("Still working on that.")
                                                        .timingMs(5000L)
                                                        .build()
                                                )
                                                .method(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Method
                                                        .GET
                                                )
                                                .pathParameters(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .PathParameters
                                                        .builder()
                                                        .properties(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .PathParameters
                                                                .Properties
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "id",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .build()
                                                        )
                                                        .addRequired("id")
                                                        .type(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .PathParameters
                                                                .Type
                                                                .OBJECT
                                                        )
                                                        .build()
                                                )
                                                .queryParameters(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .QueryParameters
                                                        .builder()
                                                        .properties(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .QueryParameters
                                                                .Properties
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "page",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .build()
                                                        )
                                                        .addRequired("page")
                                                        .type(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .QueryParameters
                                                                .Type
                                                                .OBJECT
                                                        )
                                                        .build()
                                                )
                                                .addStoreFieldsAsVariable(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .StoreFieldsAsVariable
                                                        .builder()
                                                        .name("x")
                                                        .valuePath("x")
                                                        .build()
                                                )
                                                .timeoutMs(500L)
                                                .build()
                                        )
                                        .build()
                                )
                            )
                        )
                        .toolsMode(FlowNode.ToolsMode.APPEND)
                        .transcription(
                            TranscriptionSettings.builder()
                                .apiKeyRef("api_key_ref")
                                .language("language")
                                .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                                .region("region")
                                .settings(
                                    TranscriptionSettingsConfig.builder()
                                        .eagerEotThreshold(0.3)
                                        .enableEndpointDetection(true)
                                        .endOfTurnConfidenceThreshold(0.0)
                                        .eotThreshold(0.5)
                                        .eotTimeoutMs(500L)
                                        .interimResults(true)
                                        .keyterm("keyterm")
                                        .maxEndpointDelayMs(500L)
                                        .maxTurnSilence(100L)
                                        .minTurnSilence(100L)
                                        .numerals(true)
                                        .smartFormat(true)
                                        .build()
                                )
                                .build()
                        )
                        .type(FlowNode.Type.PROMPT)
                        .voiceSettings(
                            VoiceSettings.builder()
                                .voice("voice")
                                .apiKeyRef("api_key_ref")
                                .backgroundAudio(
                                    VoiceSettings.BackgroundAudio.PredefinedMedia.builder()
                                        .value(
                                            VoiceSettings.BackgroundAudio.PredefinedMedia
                                                .PredefinedMediaValue
                                                .SILENCE
                                        )
                                        .volume(0.1)
                                        .build()
                                )
                                .expressiveMode(true)
                                .languageBoost(VoiceSettings.LanguageBoost.AUTO)
                                .similarityBoost(0.0)
                                .speed(0.0)
                                .style(0.0)
                                .temperature(0.0)
                                .useSpeakerBoost(true)
                                .voiceSpeed(0.0)
                                .build()
                        )
                        .build()
                )
                .startNodeId("n_intake")
                .addEdge(
                    FlowEdge.builder()
                        .id("e_intake_to_billing")
                        .llmCondition("The caller is asking about a bill or charge.")
                        .startNodeId("n_intake")
                        .nodeTarget("n_billing")
                        .build()
                )
                .addEdge(
                    FlowEdge.builder()
                        .id("e_intake_to_escalation_assistant")
                        .llmCondition("The caller has explicitly asked for a human.")
                        .startNodeId("n_intake")
                        .target(
                            FlowEdge.Target.Assistant.builder()
                                .assistantId("assistant-human-handoff")
                                .position(NodePosition.builder().x(600.0).y(80.0).build())
                                .voiceMode(FlowEdge.Target.Assistant.VoiceMode.DISTINCT)
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(conversationFlow.nodes())
            .containsExactly(
                ConversationFlow.Node.ofPrompt(
                    FlowNode.builder()
                        .id("n_intake")
                        .instructions("Greet the caller and ask what they're calling about.")
                        .externalLlm(
                            ExternalLlm.builder()
                                .baseUrl("base_url")
                                .model("model")
                                .authenticationMethod(AuthenticationMethod.TOKEN)
                                .certificateRef("certificate_ref")
                                .forwardMetadata(true)
                                .llmApiKeyRef("llm_api_key_ref")
                                .tokenRetrievalUrl("token_retrieval_url")
                                .build()
                        )
                        .instructionsMode(FlowNode.InstructionsMode.REPLACE)
                        .llmApiKeyRef("llm_api_key_ref")
                        .model("model")
                        .name("Intake")
                        .position(NodePosition.builder().x(120.0).y(80.0).build())
                        .addSharedToolId("tool-faq-kb")
                        .addTool(
                            listOf(
                                AssistantTool.ofWebhook(
                                    InferenceEmbeddingWebhookToolParams.builder()
                                        .type(InferenceEmbeddingWebhookToolParams.Type.WEBHOOK)
                                        .webhook(
                                            InferenceEmbeddingWebhookToolParams.Webhook.builder()
                                                .description("description")
                                                .name("name")
                                                .url("https://example.com/api/v1/function")
                                                .async(true)
                                                .asyncTimeoutMs(1L)
                                                .bodyParameters(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .BodyParameters
                                                        .builder()
                                                        .properties(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .BodyParameters
                                                                .Properties
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "age",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .putAdditionalProperty(
                                                                    "location",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .build()
                                                        )
                                                        .addRequired("age")
                                                        .addRequired("location")
                                                        .type(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .BodyParameters
                                                                .Type
                                                                .OBJECT
                                                        )
                                                        .build()
                                                )
                                                .addHeader(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Header
                                                        .builder()
                                                        .name("name")
                                                        .value("value")
                                                        .build()
                                                )
                                                .addMessage(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Message
                                                        .WebhookToolRequestStartMessage
                                                        .builder()
                                                        .content("Let me look that up for you.")
                                                        .timingMs(100L)
                                                        .build()
                                                )
                                                .addMessage(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Message
                                                        .WebhookToolRequestResponseDelayedMessage
                                                        .builder()
                                                        .content("Still working on that.")
                                                        .timingMs(5000L)
                                                        .build()
                                                )
                                                .method(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Method
                                                        .GET
                                                )
                                                .pathParameters(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .PathParameters
                                                        .builder()
                                                        .properties(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .PathParameters
                                                                .Properties
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "id",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .build()
                                                        )
                                                        .addRequired("id")
                                                        .type(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .PathParameters
                                                                .Type
                                                                .OBJECT
                                                        )
                                                        .build()
                                                )
                                                .queryParameters(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .QueryParameters
                                                        .builder()
                                                        .properties(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .QueryParameters
                                                                .Properties
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "page",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .build()
                                                        )
                                                        .addRequired("page")
                                                        .type(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .QueryParameters
                                                                .Type
                                                                .OBJECT
                                                        )
                                                        .build()
                                                )
                                                .addStoreFieldsAsVariable(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .StoreFieldsAsVariable
                                                        .builder()
                                                        .name("x")
                                                        .valuePath("x")
                                                        .build()
                                                )
                                                .timeoutMs(500L)
                                                .build()
                                        )
                                        .build()
                                )
                            )
                        )
                        .toolsMode(FlowNode.ToolsMode.REPLACE)
                        .transcription(
                            TranscriptionSettings.builder()
                                .apiKeyRef("api_key_ref")
                                .language("language")
                                .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                                .region("region")
                                .settings(
                                    TranscriptionSettingsConfig.builder()
                                        .eagerEotThreshold(0.3)
                                        .enableEndpointDetection(true)
                                        .endOfTurnConfidenceThreshold(0.0)
                                        .eotThreshold(0.5)
                                        .eotTimeoutMs(500L)
                                        .interimResults(true)
                                        .keyterm("keyterm")
                                        .maxEndpointDelayMs(500L)
                                        .maxTurnSilence(100L)
                                        .minTurnSilence(100L)
                                        .numerals(true)
                                        .smartFormat(true)
                                        .build()
                                )
                                .build()
                        )
                        .type(FlowNode.Type.PROMPT)
                        .voiceSettings(
                            VoiceSettings.builder()
                                .voice("voice")
                                .apiKeyRef("api_key_ref")
                                .backgroundAudio(
                                    VoiceSettings.BackgroundAudio.PredefinedMedia.builder()
                                        .value(
                                            VoiceSettings.BackgroundAudio.PredefinedMedia
                                                .PredefinedMediaValue
                                                .SILENCE
                                        )
                                        .volume(0.1)
                                        .build()
                                )
                                .expressiveMode(true)
                                .languageBoost(VoiceSettings.LanguageBoost.AUTO)
                                .similarityBoost(0.0)
                                .speed(0.0)
                                .style(0.0)
                                .temperature(0.0)
                                .useSpeakerBoost(true)
                                .voiceSpeed(0.0)
                                .build()
                        )
                        .build()
                ),
                ConversationFlow.Node.ofPrompt(
                    FlowNode.builder()
                        .id("n_billing")
                        .instructions(
                            "Focus on billing questions. Look up the caller's latest invoice with the billing tool before answering."
                        )
                        .externalLlm(
                            ExternalLlm.builder()
                                .baseUrl("base_url")
                                .model("model")
                                .authenticationMethod(AuthenticationMethod.TOKEN)
                                .certificateRef("certificate_ref")
                                .forwardMetadata(true)
                                .llmApiKeyRef("llm_api_key_ref")
                                .tokenRetrievalUrl("token_retrieval_url")
                                .build()
                        )
                        .instructionsMode(FlowNode.InstructionsMode.APPEND)
                        .llmApiKeyRef("llm_api_key_ref")
                        .model("moonshotai/Kimi-K2.6")
                        .name("Billing")
                        .position(NodePosition.builder().x(420.0).y(80.0).build())
                        .addSharedToolId("tool-billing-lookup")
                        .addTool(
                            listOf(
                                AssistantTool.ofWebhook(
                                    InferenceEmbeddingWebhookToolParams.builder()
                                        .type(InferenceEmbeddingWebhookToolParams.Type.WEBHOOK)
                                        .webhook(
                                            InferenceEmbeddingWebhookToolParams.Webhook.builder()
                                                .description("description")
                                                .name("name")
                                                .url("https://example.com/api/v1/function")
                                                .async(true)
                                                .asyncTimeoutMs(1L)
                                                .bodyParameters(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .BodyParameters
                                                        .builder()
                                                        .properties(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .BodyParameters
                                                                .Properties
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "age",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .putAdditionalProperty(
                                                                    "location",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .build()
                                                        )
                                                        .addRequired("age")
                                                        .addRequired("location")
                                                        .type(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .BodyParameters
                                                                .Type
                                                                .OBJECT
                                                        )
                                                        .build()
                                                )
                                                .addHeader(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Header
                                                        .builder()
                                                        .name("name")
                                                        .value("value")
                                                        .build()
                                                )
                                                .addMessage(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Message
                                                        .WebhookToolRequestStartMessage
                                                        .builder()
                                                        .content("Let me look that up for you.")
                                                        .timingMs(100L)
                                                        .build()
                                                )
                                                .addMessage(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Message
                                                        .WebhookToolRequestResponseDelayedMessage
                                                        .builder()
                                                        .content("Still working on that.")
                                                        .timingMs(5000L)
                                                        .build()
                                                )
                                                .method(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Method
                                                        .GET
                                                )
                                                .pathParameters(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .PathParameters
                                                        .builder()
                                                        .properties(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .PathParameters
                                                                .Properties
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "id",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .build()
                                                        )
                                                        .addRequired("id")
                                                        .type(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .PathParameters
                                                                .Type
                                                                .OBJECT
                                                        )
                                                        .build()
                                                )
                                                .queryParameters(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .QueryParameters
                                                        .builder()
                                                        .properties(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .QueryParameters
                                                                .Properties
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "page",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .build()
                                                        )
                                                        .addRequired("page")
                                                        .type(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .QueryParameters
                                                                .Type
                                                                .OBJECT
                                                        )
                                                        .build()
                                                )
                                                .addStoreFieldsAsVariable(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .StoreFieldsAsVariable
                                                        .builder()
                                                        .name("x")
                                                        .valuePath("x")
                                                        .build()
                                                )
                                                .timeoutMs(500L)
                                                .build()
                                        )
                                        .build()
                                )
                            )
                        )
                        .toolsMode(FlowNode.ToolsMode.APPEND)
                        .transcription(
                            TranscriptionSettings.builder()
                                .apiKeyRef("api_key_ref")
                                .language("language")
                                .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                                .region("region")
                                .settings(
                                    TranscriptionSettingsConfig.builder()
                                        .eagerEotThreshold(0.3)
                                        .enableEndpointDetection(true)
                                        .endOfTurnConfidenceThreshold(0.0)
                                        .eotThreshold(0.5)
                                        .eotTimeoutMs(500L)
                                        .interimResults(true)
                                        .keyterm("keyterm")
                                        .maxEndpointDelayMs(500L)
                                        .maxTurnSilence(100L)
                                        .minTurnSilence(100L)
                                        .numerals(true)
                                        .smartFormat(true)
                                        .build()
                                )
                                .build()
                        )
                        .type(FlowNode.Type.PROMPT)
                        .voiceSettings(
                            VoiceSettings.builder()
                                .voice("voice")
                                .apiKeyRef("api_key_ref")
                                .backgroundAudio(
                                    VoiceSettings.BackgroundAudio.PredefinedMedia.builder()
                                        .value(
                                            VoiceSettings.BackgroundAudio.PredefinedMedia
                                                .PredefinedMediaValue
                                                .SILENCE
                                        )
                                        .volume(0.1)
                                        .build()
                                )
                                .expressiveMode(true)
                                .languageBoost(VoiceSettings.LanguageBoost.AUTO)
                                .similarityBoost(0.0)
                                .speed(0.0)
                                .style(0.0)
                                .temperature(0.0)
                                .useSpeakerBoost(true)
                                .voiceSpeed(0.0)
                                .build()
                        )
                        .build()
                ),
            )
        assertThat(conversationFlow.startNodeId()).isEqualTo("n_intake")
        assertThat(conversationFlow.edges().getOrNull())
            .containsExactly(
                FlowEdge.builder()
                    .id("e_intake_to_billing")
                    .llmCondition("The caller is asking about a bill or charge.")
                    .startNodeId("n_intake")
                    .nodeTarget("n_billing")
                    .build(),
                FlowEdge.builder()
                    .id("e_intake_to_escalation_assistant")
                    .llmCondition("The caller has explicitly asked for a human.")
                    .startNodeId("n_intake")
                    .target(
                        FlowEdge.Target.Assistant.builder()
                            .assistantId("assistant-human-handoff")
                            .position(NodePosition.builder().x(600.0).y(80.0).build())
                            .voiceMode(FlowEdge.Target.Assistant.VoiceMode.DISTINCT)
                            .build()
                    )
                    .build(),
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val conversationFlow =
            ConversationFlow.builder()
                .addNode(
                    FlowNode.builder()
                        .id("n_intake")
                        .instructions("Greet the caller and ask what they're calling about.")
                        .externalLlm(
                            ExternalLlm.builder()
                                .baseUrl("base_url")
                                .model("model")
                                .authenticationMethod(AuthenticationMethod.TOKEN)
                                .certificateRef("certificate_ref")
                                .forwardMetadata(true)
                                .llmApiKeyRef("llm_api_key_ref")
                                .tokenRetrievalUrl("token_retrieval_url")
                                .build()
                        )
                        .instructionsMode(FlowNode.InstructionsMode.REPLACE)
                        .llmApiKeyRef("llm_api_key_ref")
                        .model("model")
                        .name("Intake")
                        .position(NodePosition.builder().x(120.0).y(80.0).build())
                        .addSharedToolId("tool-faq-kb")
                        .addTool(
                            listOf(
                                AssistantTool.ofWebhook(
                                    InferenceEmbeddingWebhookToolParams.builder()
                                        .type(InferenceEmbeddingWebhookToolParams.Type.WEBHOOK)
                                        .webhook(
                                            InferenceEmbeddingWebhookToolParams.Webhook.builder()
                                                .description("description")
                                                .name("name")
                                                .url("https://example.com/api/v1/function")
                                                .async(true)
                                                .asyncTimeoutMs(1L)
                                                .bodyParameters(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .BodyParameters
                                                        .builder()
                                                        .properties(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .BodyParameters
                                                                .Properties
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "age",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .putAdditionalProperty(
                                                                    "location",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .build()
                                                        )
                                                        .addRequired("age")
                                                        .addRequired("location")
                                                        .type(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .BodyParameters
                                                                .Type
                                                                .OBJECT
                                                        )
                                                        .build()
                                                )
                                                .addHeader(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Header
                                                        .builder()
                                                        .name("name")
                                                        .value("value")
                                                        .build()
                                                )
                                                .addMessage(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Message
                                                        .WebhookToolRequestStartMessage
                                                        .builder()
                                                        .content("Let me look that up for you.")
                                                        .timingMs(100L)
                                                        .build()
                                                )
                                                .addMessage(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Message
                                                        .WebhookToolRequestResponseDelayedMessage
                                                        .builder()
                                                        .content("Still working on that.")
                                                        .timingMs(5000L)
                                                        .build()
                                                )
                                                .method(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Method
                                                        .GET
                                                )
                                                .pathParameters(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .PathParameters
                                                        .builder()
                                                        .properties(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .PathParameters
                                                                .Properties
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "id",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .build()
                                                        )
                                                        .addRequired("id")
                                                        .type(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .PathParameters
                                                                .Type
                                                                .OBJECT
                                                        )
                                                        .build()
                                                )
                                                .queryParameters(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .QueryParameters
                                                        .builder()
                                                        .properties(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .QueryParameters
                                                                .Properties
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "page",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .build()
                                                        )
                                                        .addRequired("page")
                                                        .type(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .QueryParameters
                                                                .Type
                                                                .OBJECT
                                                        )
                                                        .build()
                                                )
                                                .addStoreFieldsAsVariable(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .StoreFieldsAsVariable
                                                        .builder()
                                                        .name("x")
                                                        .valuePath("x")
                                                        .build()
                                                )
                                                .timeoutMs(500L)
                                                .build()
                                        )
                                        .build()
                                )
                            )
                        )
                        .toolsMode(FlowNode.ToolsMode.REPLACE)
                        .transcription(
                            TranscriptionSettings.builder()
                                .apiKeyRef("api_key_ref")
                                .language("language")
                                .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                                .region("region")
                                .settings(
                                    TranscriptionSettingsConfig.builder()
                                        .eagerEotThreshold(0.3)
                                        .enableEndpointDetection(true)
                                        .endOfTurnConfidenceThreshold(0.0)
                                        .eotThreshold(0.5)
                                        .eotTimeoutMs(500L)
                                        .interimResults(true)
                                        .keyterm("keyterm")
                                        .maxEndpointDelayMs(500L)
                                        .maxTurnSilence(100L)
                                        .minTurnSilence(100L)
                                        .numerals(true)
                                        .smartFormat(true)
                                        .build()
                                )
                                .build()
                        )
                        .type(FlowNode.Type.PROMPT)
                        .voiceSettings(
                            VoiceSettings.builder()
                                .voice("voice")
                                .apiKeyRef("api_key_ref")
                                .backgroundAudio(
                                    VoiceSettings.BackgroundAudio.PredefinedMedia.builder()
                                        .value(
                                            VoiceSettings.BackgroundAudio.PredefinedMedia
                                                .PredefinedMediaValue
                                                .SILENCE
                                        )
                                        .volume(0.1)
                                        .build()
                                )
                                .expressiveMode(true)
                                .languageBoost(VoiceSettings.LanguageBoost.AUTO)
                                .similarityBoost(0.0)
                                .speed(0.0)
                                .style(0.0)
                                .temperature(0.0)
                                .useSpeakerBoost(true)
                                .voiceSpeed(0.0)
                                .build()
                        )
                        .build()
                )
                .addNode(
                    FlowNode.builder()
                        .id("n_billing")
                        .instructions(
                            "Focus on billing questions. Look up the caller's latest invoice with the billing tool before answering."
                        )
                        .externalLlm(
                            ExternalLlm.builder()
                                .baseUrl("base_url")
                                .model("model")
                                .authenticationMethod(AuthenticationMethod.TOKEN)
                                .certificateRef("certificate_ref")
                                .forwardMetadata(true)
                                .llmApiKeyRef("llm_api_key_ref")
                                .tokenRetrievalUrl("token_retrieval_url")
                                .build()
                        )
                        .instructionsMode(FlowNode.InstructionsMode.APPEND)
                        .llmApiKeyRef("llm_api_key_ref")
                        .model("moonshotai/Kimi-K2.6")
                        .name("Billing")
                        .position(NodePosition.builder().x(420.0).y(80.0).build())
                        .addSharedToolId("tool-billing-lookup")
                        .addTool(
                            listOf(
                                AssistantTool.ofWebhook(
                                    InferenceEmbeddingWebhookToolParams.builder()
                                        .type(InferenceEmbeddingWebhookToolParams.Type.WEBHOOK)
                                        .webhook(
                                            InferenceEmbeddingWebhookToolParams.Webhook.builder()
                                                .description("description")
                                                .name("name")
                                                .url("https://example.com/api/v1/function")
                                                .async(true)
                                                .asyncTimeoutMs(1L)
                                                .bodyParameters(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .BodyParameters
                                                        .builder()
                                                        .properties(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .BodyParameters
                                                                .Properties
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "age",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .putAdditionalProperty(
                                                                    "location",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .build()
                                                        )
                                                        .addRequired("age")
                                                        .addRequired("location")
                                                        .type(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .BodyParameters
                                                                .Type
                                                                .OBJECT
                                                        )
                                                        .build()
                                                )
                                                .addHeader(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Header
                                                        .builder()
                                                        .name("name")
                                                        .value("value")
                                                        .build()
                                                )
                                                .addMessage(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Message
                                                        .WebhookToolRequestStartMessage
                                                        .builder()
                                                        .content("Let me look that up for you.")
                                                        .timingMs(100L)
                                                        .build()
                                                )
                                                .addMessage(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Message
                                                        .WebhookToolRequestResponseDelayedMessage
                                                        .builder()
                                                        .content("Still working on that.")
                                                        .timingMs(5000L)
                                                        .build()
                                                )
                                                .method(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .Method
                                                        .GET
                                                )
                                                .pathParameters(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .PathParameters
                                                        .builder()
                                                        .properties(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .PathParameters
                                                                .Properties
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "id",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .build()
                                                        )
                                                        .addRequired("id")
                                                        .type(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .PathParameters
                                                                .Type
                                                                .OBJECT
                                                        )
                                                        .build()
                                                )
                                                .queryParameters(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .QueryParameters
                                                        .builder()
                                                        .properties(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .QueryParameters
                                                                .Properties
                                                                .builder()
                                                                .putAdditionalProperty(
                                                                    "page",
                                                                    JsonValue.from("bar"),
                                                                )
                                                                .build()
                                                        )
                                                        .addRequired("page")
                                                        .type(
                                                            InferenceEmbeddingWebhookToolParams
                                                                .Webhook
                                                                .QueryParameters
                                                                .Type
                                                                .OBJECT
                                                        )
                                                        .build()
                                                )
                                                .addStoreFieldsAsVariable(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .StoreFieldsAsVariable
                                                        .builder()
                                                        .name("x")
                                                        .valuePath("x")
                                                        .build()
                                                )
                                                .timeoutMs(500L)
                                                .build()
                                        )
                                        .build()
                                )
                            )
                        )
                        .toolsMode(FlowNode.ToolsMode.APPEND)
                        .transcription(
                            TranscriptionSettings.builder()
                                .apiKeyRef("api_key_ref")
                                .language("language")
                                .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                                .region("region")
                                .settings(
                                    TranscriptionSettingsConfig.builder()
                                        .eagerEotThreshold(0.3)
                                        .enableEndpointDetection(true)
                                        .endOfTurnConfidenceThreshold(0.0)
                                        .eotThreshold(0.5)
                                        .eotTimeoutMs(500L)
                                        .interimResults(true)
                                        .keyterm("keyterm")
                                        .maxEndpointDelayMs(500L)
                                        .maxTurnSilence(100L)
                                        .minTurnSilence(100L)
                                        .numerals(true)
                                        .smartFormat(true)
                                        .build()
                                )
                                .build()
                        )
                        .type(FlowNode.Type.PROMPT)
                        .voiceSettings(
                            VoiceSettings.builder()
                                .voice("voice")
                                .apiKeyRef("api_key_ref")
                                .backgroundAudio(
                                    VoiceSettings.BackgroundAudio.PredefinedMedia.builder()
                                        .value(
                                            VoiceSettings.BackgroundAudio.PredefinedMedia
                                                .PredefinedMediaValue
                                                .SILENCE
                                        )
                                        .volume(0.1)
                                        .build()
                                )
                                .expressiveMode(true)
                                .languageBoost(VoiceSettings.LanguageBoost.AUTO)
                                .similarityBoost(0.0)
                                .speed(0.0)
                                .style(0.0)
                                .temperature(0.0)
                                .useSpeakerBoost(true)
                                .voiceSpeed(0.0)
                                .build()
                        )
                        .build()
                )
                .startNodeId("n_intake")
                .addEdge(
                    FlowEdge.builder()
                        .id("e_intake_to_billing")
                        .llmCondition("The caller is asking about a bill or charge.")
                        .startNodeId("n_intake")
                        .nodeTarget("n_billing")
                        .build()
                )
                .addEdge(
                    FlowEdge.builder()
                        .id("e_intake_to_escalation_assistant")
                        .llmCondition("The caller has explicitly asked for a human.")
                        .startNodeId("n_intake")
                        .target(
                            FlowEdge.Target.Assistant.builder()
                                .assistantId("assistant-human-handoff")
                                .position(NodePosition.builder().x(600.0).y(80.0).build())
                                .voiceMode(FlowEdge.Target.Assistant.VoiceMode.DISTINCT)
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedConversationFlow =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(conversationFlow),
                jacksonTypeRef<ConversationFlow>(),
            )

        assertThat(roundtrippedConversationFlow).isEqualTo(conversationFlow)
    }
}
