// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.ai.assistants

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.JsonValue
import com.telnyx.sdk.core.jsonMapper
import com.telnyx.sdk.models.ai.openai.chat.FunctionDefinition
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class FlowNodeTest {

    @Test
    fun create() {
        val flowNode =
            FlowNode.builder()
                .id("id")
                .instructions("instructions")
                .externalLlm(
                    ExternalLlm.builder()
                        .baseUrl("base_url")
                        .model("model")
                        .authenticationMethod(AuthenticationMethod.TOKEN)
                        .certificateRef("certificate_ref")
                        .forwardMetadata(true)
                        .llmApiKeyRef("llm_api_key_ref")
                        .tokenRetrievalUrl("token_retrieval_url")
                        .build()
                )
                .instructionsMode(FlowNode.InstructionsMode.REPLACE)
                .llmApiKeyRef("llm_api_key_ref")
                .model("model")
                .name("name")
                .position(NodePosition.builder().x(0.0).y(0.0).build())
                .addSharedToolId("string")
                .addTool(
                    listOf(
                        AssistantTool.ofFunction(
                            AssistantTool.Function.builder()
                                .function(
                                    FunctionDefinition.builder()
                                        .name("name")
                                        .description("description")
                                        .parameters(
                                            FunctionDefinition.Parameters.builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .build()
                                )
                                .shared(true)
                                .build()
                        )
                    )
                )
                .toolsMode(FlowNode.ToolsMode.REPLACE)
                .transcription(
                    TranscriptionSettings.builder()
                        .apiKeyRef("api_key_ref")
                        .language("language")
                        .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                        .region("region")
                        .settings(
                            TranscriptionSettingsConfig.builder()
                                .context("context")
                                .eagerEotThreshold(0.3)
                                .enableEndpointDetection(true)
                                .endOfTurnConfidenceThreshold(0.0)
                                .eotThreshold(0.5)
                                .eotTimeoutMs(500L)
                                .interimResults(true)
                                .keyterm("keyterm")
                                .addLanguageHint("string")
                                .maxEndpointDelayMs(500L)
                                .maxTurnSilence(100L)
                                .minTurnSilence(100L)
                                .numerals(true)
                                .smartFormat(true)
                                .build()
                        )
                        .build()
                )
                .type(FlowNode.Type.PROMPT)
                .voiceSettings(
                    InferenceEmbeddingVoiceSettings.builder()
                        .voice("voice")
                        .apiKeyRef("api_key_ref")
                        .backgroundAudio(
                            InferenceEmbeddingVoiceSettings.BackgroundAudio.UnionMember0.builder()
                                .type(
                                    InferenceEmbeddingVoiceSettings.BackgroundAudio.UnionMember0
                                        .Type
                                        .PREDEFINED_MEDIA
                                )
                                .value(
                                    InferenceEmbeddingVoiceSettings.BackgroundAudio.UnionMember0
                                        .Value_
                                        .SILENCE
                                )
                                .volume(0.1)
                                .build()
                        )
                        .expressiveMode(true)
                        .languageBoost(InferenceEmbeddingVoiceSettings.LanguageBoost.AUTO)
                        .similarityBoost(0.0)
                        .speed(0.0)
                        .style(0.0)
                        .temperature(0.0)
                        .useSpeakerBoost(true)
                        .voiceSpeed(0.0)
                        .build()
                )
                .build()

        assertThat(flowNode.id()).isEqualTo("id")
        assertThat(flowNode.instructions()).isEqualTo("instructions")
        assertThat(flowNode.externalLlm())
            .contains(
                ExternalLlm.builder()
                    .baseUrl("base_url")
                    .model("model")
                    .authenticationMethod(AuthenticationMethod.TOKEN)
                    .certificateRef("certificate_ref")
                    .forwardMetadata(true)
                    .llmApiKeyRef("llm_api_key_ref")
                    .tokenRetrievalUrl("token_retrieval_url")
                    .build()
            )
        assertThat(flowNode.instructionsMode()).contains(FlowNode.InstructionsMode.REPLACE)
        assertThat(flowNode.llmApiKeyRef()).contains("llm_api_key_ref")
        assertThat(flowNode.model()).contains("model")
        assertThat(flowNode.name()).contains("name")
        assertThat(flowNode.position()).contains(NodePosition.builder().x(0.0).y(0.0).build())
        assertThat(flowNode.sharedToolIds().getOrNull()).containsExactly("string")
        assertThat(flowNode.tools().getOrNull())
            .containsExactly(
                listOf(
                    AssistantTool.ofFunction(
                        AssistantTool.Function.builder()
                            .function(
                                FunctionDefinition.builder()
                                    .name("name")
                                    .description("description")
                                    .parameters(
                                        FunctionDefinition.Parameters.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                                            .build()
                                    )
                                    .build()
                            )
                            .shared(true)
                            .build()
                    )
                )
            )
        assertThat(flowNode.toolsMode()).contains(FlowNode.ToolsMode.REPLACE)
        assertThat(flowNode.transcription())
            .contains(
                TranscriptionSettings.builder()
                    .apiKeyRef("api_key_ref")
                    .language("language")
                    .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                    .region("region")
                    .settings(
                        TranscriptionSettingsConfig.builder()
                            .context("context")
                            .eagerEotThreshold(0.3)
                            .enableEndpointDetection(true)
                            .endOfTurnConfidenceThreshold(0.0)
                            .eotThreshold(0.5)
                            .eotTimeoutMs(500L)
                            .interimResults(true)
                            .keyterm("keyterm")
                            .addLanguageHint("string")
                            .maxEndpointDelayMs(500L)
                            .maxTurnSilence(100L)
                            .minTurnSilence(100L)
                            .numerals(true)
                            .smartFormat(true)
                            .build()
                    )
                    .build()
            )
        assertThat(flowNode.type()).contains(FlowNode.Type.PROMPT)
        assertThat(flowNode.voiceSettings())
            .contains(
                InferenceEmbeddingVoiceSettings.builder()
                    .voice("voice")
                    .apiKeyRef("api_key_ref")
                    .backgroundAudio(
                        InferenceEmbeddingVoiceSettings.BackgroundAudio.UnionMember0.builder()
                            .type(
                                InferenceEmbeddingVoiceSettings.BackgroundAudio.UnionMember0.Type
                                    .PREDEFINED_MEDIA
                            )
                            .value(
                                InferenceEmbeddingVoiceSettings.BackgroundAudio.UnionMember0.Value_
                                    .SILENCE
                            )
                            .volume(0.1)
                            .build()
                    )
                    .expressiveMode(true)
                    .languageBoost(InferenceEmbeddingVoiceSettings.LanguageBoost.AUTO)
                    .similarityBoost(0.0)
                    .speed(0.0)
                    .style(0.0)
                    .temperature(0.0)
                    .useSpeakerBoost(true)
                    .voiceSpeed(0.0)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val flowNode =
            FlowNode.builder()
                .id("id")
                .instructions("instructions")
                .externalLlm(
                    ExternalLlm.builder()
                        .baseUrl("base_url")
                        .model("model")
                        .authenticationMethod(AuthenticationMethod.TOKEN)
                        .certificateRef("certificate_ref")
                        .forwardMetadata(true)
                        .llmApiKeyRef("llm_api_key_ref")
                        .tokenRetrievalUrl("token_retrieval_url")
                        .build()
                )
                .instructionsMode(FlowNode.InstructionsMode.REPLACE)
                .llmApiKeyRef("llm_api_key_ref")
                .model("model")
                .name("name")
                .position(NodePosition.builder().x(0.0).y(0.0).build())
                .addSharedToolId("string")
                .addTool(
                    listOf(
                        AssistantTool.ofFunction(
                            AssistantTool.Function.builder()
                                .function(
                                    FunctionDefinition.builder()
                                        .name("name")
                                        .description("description")
                                        .parameters(
                                            FunctionDefinition.Parameters.builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .build()
                                )
                                .shared(true)
                                .build()
                        )
                    )
                )
                .toolsMode(FlowNode.ToolsMode.REPLACE)
                .transcription(
                    TranscriptionSettings.builder()
                        .apiKeyRef("api_key_ref")
                        .language("language")
                        .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                        .region("region")
                        .settings(
                            TranscriptionSettingsConfig.builder()
                                .context("context")
                                .eagerEotThreshold(0.3)
                                .enableEndpointDetection(true)
                                .endOfTurnConfidenceThreshold(0.0)
                                .eotThreshold(0.5)
                                .eotTimeoutMs(500L)
                                .interimResults(true)
                                .keyterm("keyterm")
                                .addLanguageHint("string")
                                .maxEndpointDelayMs(500L)
                                .maxTurnSilence(100L)
                                .minTurnSilence(100L)
                                .numerals(true)
                                .smartFormat(true)
                                .build()
                        )
                        .build()
                )
                .type(FlowNode.Type.PROMPT)
                .voiceSettings(
                    InferenceEmbeddingVoiceSettings.builder()
                        .voice("voice")
                        .apiKeyRef("api_key_ref")
                        .backgroundAudio(
                            InferenceEmbeddingVoiceSettings.BackgroundAudio.UnionMember0.builder()
                                .type(
                                    InferenceEmbeddingVoiceSettings.BackgroundAudio.UnionMember0
                                        .Type
                                        .PREDEFINED_MEDIA
                                )
                                .value(
                                    InferenceEmbeddingVoiceSettings.BackgroundAudio.UnionMember0
                                        .Value_
                                        .SILENCE
                                )
                                .volume(0.1)
                                .build()
                        )
                        .expressiveMode(true)
                        .languageBoost(InferenceEmbeddingVoiceSettings.LanguageBoost.AUTO)
                        .similarityBoost(0.0)
                        .speed(0.0)
                        .style(0.0)
                        .temperature(0.0)
                        .useSpeakerBoost(true)
                        .voiceSpeed(0.0)
                        .build()
                )
                .build()

        val roundtrippedFlowNode =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(flowNode),
                jacksonTypeRef<FlowNode>(),
            )

        assertThat(roundtrippedFlowNode).isEqualTo(flowNode)
    }
}
