// File generated from our OpenAPI spec by Stainless.

package com.telnyx.sdk.models.ai.assistants

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.telnyx.sdk.core.JsonValue
import com.telnyx.sdk.core.jsonMapper
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class FlowNodeTest {

    @Test
    fun create() {
        val flowNode =
            FlowNode.builder()
                .id("id")
                .instructions("instructions")
                .externalLlm(
                    ExternalLlm.builder()
                        .baseUrl("base_url")
                        .model("model")
                        .authenticationMethod(AuthenticationMethod.TOKEN)
                        .certificateRef("certificate_ref")
                        .forwardMetadata(true)
                        .llmApiKeyRef("llm_api_key_ref")
                        .tokenRetrievalUrl("token_retrieval_url")
                        .build()
                )
                .instructionsMode(FlowNode.InstructionsMode.REPLACE)
                .llmApiKeyRef("llm_api_key_ref")
                .model("model")
                .name("name")
                .position(NodePosition.builder().x(0.0).y(0.0).build())
                .addSharedToolId("string")
                .addTool(
                    listOf(
                        AssistantTool.ofWebhook(
                            InferenceEmbeddingWebhookToolParams.builder()
                                .type(InferenceEmbeddingWebhookToolParams.Type.WEBHOOK)
                                .webhook(
                                    InferenceEmbeddingWebhookToolParams.Webhook.builder()
                                        .description("description")
                                        .name("name")
                                        .url("https://example.com/api/v1/function")
                                        .async(true)
                                        .asyncTimeoutMs(1L)
                                        .bodyParameters(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .BodyParameters
                                                .builder()
                                                .properties(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .BodyParameters
                                                        .Properties
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "age",
                                                            JsonValue.from("bar"),
                                                        )
                                                        .putAdditionalProperty(
                                                            "location",
                                                            JsonValue.from("bar"),
                                                        )
                                                        .build()
                                                )
                                                .addRequired("age")
                                                .addRequired("location")
                                                .type(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .BodyParameters
                                                        .Type
                                                        .OBJECT
                                                )
                                                .build()
                                        )
                                        .addHeader(
                                            InferenceEmbeddingWebhookToolParams.Webhook.Header
                                                .builder()
                                                .name("name")
                                                .value("value")
                                                .build()
                                        )
                                        .addMessage(
                                            InferenceEmbeddingWebhookToolParams.Webhook.Message
                                                .WebhookToolRequestStartMessage
                                                .builder()
                                                .content("Let me look that up for you.")
                                                .timingMs(100L)
                                                .build()
                                        )
                                        .addMessage(
                                            InferenceEmbeddingWebhookToolParams.Webhook.Message
                                                .WebhookToolRequestResponseDelayedMessage
                                                .builder()
                                                .content("Still working on that.")
                                                .timingMs(5000L)
                                                .build()
                                        )
                                        .method(
                                            InferenceEmbeddingWebhookToolParams.Webhook.Method.GET
                                        )
                                        .pathParameters(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .PathParameters
                                                .builder()
                                                .properties(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .PathParameters
                                                        .Properties
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "id",
                                                            JsonValue.from("bar"),
                                                        )
                                                        .build()
                                                )
                                                .addRequired("id")
                                                .type(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .PathParameters
                                                        .Type
                                                        .OBJECT
                                                )
                                                .build()
                                        )
                                        .queryParameters(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .QueryParameters
                                                .builder()
                                                .properties(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .QueryParameters
                                                        .Properties
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "page",
                                                            JsonValue.from("bar"),
                                                        )
                                                        .build()
                                                )
                                                .addRequired("page")
                                                .type(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .QueryParameters
                                                        .Type
                                                        .OBJECT
                                                )
                                                .build()
                                        )
                                        .addStoreFieldsAsVariable(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .StoreFieldsAsVariable
                                                .builder()
                                                .name("x")
                                                .valuePath("x")
                                                .build()
                                        )
                                        .timeoutMs(500L)
                                        .build()
                                )
                                .build()
                        )
                    )
                )
                .toolsMode(FlowNode.ToolsMode.REPLACE)
                .transcription(
                    TranscriptionSettings.builder()
                        .apiKeyRef("api_key_ref")
                        .language("language")
                        .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                        .region("region")
                        .settings(
                            TranscriptionSettingsConfig.builder()
                                .eagerEotThreshold(0.3)
                                .enableEndpointDetection(true)
                                .endOfTurnConfidenceThreshold(0.0)
                                .eotThreshold(0.5)
                                .eotTimeoutMs(500L)
                                .interimResults(true)
                                .keyterm("keyterm")
                                .maxEndpointDelayMs(500L)
                                .maxTurnSilence(100L)
                                .minTurnSilence(100L)
                                .numerals(true)
                                .smartFormat(true)
                                .build()
                        )
                        .build()
                )
                .type(FlowNode.Type.PROMPT)
                .voiceSettings(
                    VoiceSettings.builder()
                        .voice("voice")
                        .apiKeyRef("api_key_ref")
                        .backgroundAudio(
                            VoiceSettings.BackgroundAudio.PredefinedMedia.builder()
                                .value(
                                    VoiceSettings.BackgroundAudio.PredefinedMedia
                                        .PredefinedMediaValue
                                        .SILENCE
                                )
                                .volume(0.1)
                                .build()
                        )
                        .expressiveMode(true)
                        .languageBoost(VoiceSettings.LanguageBoost.AUTO)
                        .similarityBoost(0.0)
                        .speed(0.0)
                        .style(0.0)
                        .temperature(0.0)
                        .useSpeakerBoost(true)
                        .voiceSpeed(0.0)
                        .build()
                )
                .build()

        assertThat(flowNode.id()).isEqualTo("id")
        assertThat(flowNode.instructions()).isEqualTo("instructions")
        assertThat(flowNode.externalLlm())
            .contains(
                ExternalLlm.builder()
                    .baseUrl("base_url")
                    .model("model")
                    .authenticationMethod(AuthenticationMethod.TOKEN)
                    .certificateRef("certificate_ref")
                    .forwardMetadata(true)
                    .llmApiKeyRef("llm_api_key_ref")
                    .tokenRetrievalUrl("token_retrieval_url")
                    .build()
            )
        assertThat(flowNode.instructionsMode()).contains(FlowNode.InstructionsMode.REPLACE)
        assertThat(flowNode.llmApiKeyRef()).contains("llm_api_key_ref")
        assertThat(flowNode.model()).contains("model")
        assertThat(flowNode.name()).contains("name")
        assertThat(flowNode.position()).contains(NodePosition.builder().x(0.0).y(0.0).build())
        assertThat(flowNode.sharedToolIds().getOrNull()).containsExactly("string")
        assertThat(flowNode.tools().getOrNull())
            .containsExactly(
                listOf(
                    AssistantTool.ofWebhook(
                        InferenceEmbeddingWebhookToolParams.builder()
                            .type(InferenceEmbeddingWebhookToolParams.Type.WEBHOOK)
                            .webhook(
                                InferenceEmbeddingWebhookToolParams.Webhook.builder()
                                    .description("description")
                                    .name("name")
                                    .url("https://example.com/api/v1/function")
                                    .async(true)
                                    .asyncTimeoutMs(1L)
                                    .bodyParameters(
                                        InferenceEmbeddingWebhookToolParams.Webhook.BodyParameters
                                            .builder()
                                            .properties(
                                                InferenceEmbeddingWebhookToolParams.Webhook
                                                    .BodyParameters
                                                    .Properties
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "age",
                                                        JsonValue.from("bar"),
                                                    )
                                                    .putAdditionalProperty(
                                                        "location",
                                                        JsonValue.from("bar"),
                                                    )
                                                    .build()
                                            )
                                            .addRequired("age")
                                            .addRequired("location")
                                            .type(
                                                InferenceEmbeddingWebhookToolParams.Webhook
                                                    .BodyParameters
                                                    .Type
                                                    .OBJECT
                                            )
                                            .build()
                                    )
                                    .addHeader(
                                        InferenceEmbeddingWebhookToolParams.Webhook.Header.builder()
                                            .name("name")
                                            .value("value")
                                            .build()
                                    )
                                    .addMessage(
                                        InferenceEmbeddingWebhookToolParams.Webhook.Message
                                            .WebhookToolRequestStartMessage
                                            .builder()
                                            .content("Let me look that up for you.")
                                            .timingMs(100L)
                                            .build()
                                    )
                                    .addMessage(
                                        InferenceEmbeddingWebhookToolParams.Webhook.Message
                                            .WebhookToolRequestResponseDelayedMessage
                                            .builder()
                                            .content("Still working on that.")
                                            .timingMs(5000L)
                                            .build()
                                    )
                                    .method(InferenceEmbeddingWebhookToolParams.Webhook.Method.GET)
                                    .pathParameters(
                                        InferenceEmbeddingWebhookToolParams.Webhook.PathParameters
                                            .builder()
                                            .properties(
                                                InferenceEmbeddingWebhookToolParams.Webhook
                                                    .PathParameters
                                                    .Properties
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "id",
                                                        JsonValue.from("bar"),
                                                    )
                                                    .build()
                                            )
                                            .addRequired("id")
                                            .type(
                                                InferenceEmbeddingWebhookToolParams.Webhook
                                                    .PathParameters
                                                    .Type
                                                    .OBJECT
                                            )
                                            .build()
                                    )
                                    .queryParameters(
                                        InferenceEmbeddingWebhookToolParams.Webhook.QueryParameters
                                            .builder()
                                            .properties(
                                                InferenceEmbeddingWebhookToolParams.Webhook
                                                    .QueryParameters
                                                    .Properties
                                                    .builder()
                                                    .putAdditionalProperty(
                                                        "page",
                                                        JsonValue.from("bar"),
                                                    )
                                                    .build()
                                            )
                                            .addRequired("page")
                                            .type(
                                                InferenceEmbeddingWebhookToolParams.Webhook
                                                    .QueryParameters
                                                    .Type
                                                    .OBJECT
                                            )
                                            .build()
                                    )
                                    .addStoreFieldsAsVariable(
                                        InferenceEmbeddingWebhookToolParams.Webhook
                                            .StoreFieldsAsVariable
                                            .builder()
                                            .name("x")
                                            .valuePath("x")
                                            .build()
                                    )
                                    .timeoutMs(500L)
                                    .build()
                            )
                            .build()
                    )
                )
            )
        assertThat(flowNode.toolsMode()).contains(FlowNode.ToolsMode.REPLACE)
        assertThat(flowNode.transcription())
            .contains(
                TranscriptionSettings.builder()
                    .apiKeyRef("api_key_ref")
                    .language("language")
                    .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                    .region("region")
                    .settings(
                        TranscriptionSettingsConfig.builder()
                            .eagerEotThreshold(0.3)
                            .enableEndpointDetection(true)
                            .endOfTurnConfidenceThreshold(0.0)
                            .eotThreshold(0.5)
                            .eotTimeoutMs(500L)
                            .interimResults(true)
                            .keyterm("keyterm")
                            .maxEndpointDelayMs(500L)
                            .maxTurnSilence(100L)
                            .minTurnSilence(100L)
                            .numerals(true)
                            .smartFormat(true)
                            .build()
                    )
                    .build()
            )
        assertThat(flowNode.type()).contains(FlowNode.Type.PROMPT)
        assertThat(flowNode.voiceSettings())
            .contains(
                VoiceSettings.builder()
                    .voice("voice")
                    .apiKeyRef("api_key_ref")
                    .backgroundAudio(
                        VoiceSettings.BackgroundAudio.PredefinedMedia.builder()
                            .value(
                                VoiceSettings.BackgroundAudio.PredefinedMedia.PredefinedMediaValue
                                    .SILENCE
                            )
                            .volume(0.1)
                            .build()
                    )
                    .expressiveMode(true)
                    .languageBoost(VoiceSettings.LanguageBoost.AUTO)
                    .similarityBoost(0.0)
                    .speed(0.0)
                    .style(0.0)
                    .temperature(0.0)
                    .useSpeakerBoost(true)
                    .voiceSpeed(0.0)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val flowNode =
            FlowNode.builder()
                .id("id")
                .instructions("instructions")
                .externalLlm(
                    ExternalLlm.builder()
                        .baseUrl("base_url")
                        .model("model")
                        .authenticationMethod(AuthenticationMethod.TOKEN)
                        .certificateRef("certificate_ref")
                        .forwardMetadata(true)
                        .llmApiKeyRef("llm_api_key_ref")
                        .tokenRetrievalUrl("token_retrieval_url")
                        .build()
                )
                .instructionsMode(FlowNode.InstructionsMode.REPLACE)
                .llmApiKeyRef("llm_api_key_ref")
                .model("model")
                .name("name")
                .position(NodePosition.builder().x(0.0).y(0.0).build())
                .addSharedToolId("string")
                .addTool(
                    listOf(
                        AssistantTool.ofWebhook(
                            InferenceEmbeddingWebhookToolParams.builder()
                                .type(InferenceEmbeddingWebhookToolParams.Type.WEBHOOK)
                                .webhook(
                                    InferenceEmbeddingWebhookToolParams.Webhook.builder()
                                        .description("description")
                                        .name("name")
                                        .url("https://example.com/api/v1/function")
                                        .async(true)
                                        .asyncTimeoutMs(1L)
                                        .bodyParameters(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .BodyParameters
                                                .builder()
                                                .properties(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .BodyParameters
                                                        .Properties
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "age",
                                                            JsonValue.from("bar"),
                                                        )
                                                        .putAdditionalProperty(
                                                            "location",
                                                            JsonValue.from("bar"),
                                                        )
                                                        .build()
                                                )
                                                .addRequired("age")
                                                .addRequired("location")
                                                .type(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .BodyParameters
                                                        .Type
                                                        .OBJECT
                                                )
                                                .build()
                                        )
                                        .addHeader(
                                            InferenceEmbeddingWebhookToolParams.Webhook.Header
                                                .builder()
                                                .name("name")
                                                .value("value")
                                                .build()
                                        )
                                        .addMessage(
                                            InferenceEmbeddingWebhookToolParams.Webhook.Message
                                                .WebhookToolRequestStartMessage
                                                .builder()
                                                .content("Let me look that up for you.")
                                                .timingMs(100L)
                                                .build()
                                        )
                                        .addMessage(
                                            InferenceEmbeddingWebhookToolParams.Webhook.Message
                                                .WebhookToolRequestResponseDelayedMessage
                                                .builder()
                                                .content("Still working on that.")
                                                .timingMs(5000L)
                                                .build()
                                        )
                                        .method(
                                            InferenceEmbeddingWebhookToolParams.Webhook.Method.GET
                                        )
                                        .pathParameters(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .PathParameters
                                                .builder()
                                                .properties(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .PathParameters
                                                        .Properties
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "id",
                                                            JsonValue.from("bar"),
                                                        )
                                                        .build()
                                                )
                                                .addRequired("id")
                                                .type(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .PathParameters
                                                        .Type
                                                        .OBJECT
                                                )
                                                .build()
                                        )
                                        .queryParameters(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .QueryParameters
                                                .builder()
                                                .properties(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .QueryParameters
                                                        .Properties
                                                        .builder()
                                                        .putAdditionalProperty(
                                                            "page",
                                                            JsonValue.from("bar"),
                                                        )
                                                        .build()
                                                )
                                                .addRequired("page")
                                                .type(
                                                    InferenceEmbeddingWebhookToolParams.Webhook
                                                        .QueryParameters
                                                        .Type
                                                        .OBJECT
                                                )
                                                .build()
                                        )
                                        .addStoreFieldsAsVariable(
                                            InferenceEmbeddingWebhookToolParams.Webhook
                                                .StoreFieldsAsVariable
                                                .builder()
                                                .name("x")
                                                .valuePath("x")
                                                .build()
                                        )
                                        .timeoutMs(500L)
                                        .build()
                                )
                                .build()
                        )
                    )
                )
                .toolsMode(FlowNode.ToolsMode.REPLACE)
                .transcription(
                    TranscriptionSettings.builder()
                        .apiKeyRef("api_key_ref")
                        .language("language")
                        .model(TranscriptionSettings.Model.DEEPGRAM_FLUX)
                        .region("region")
                        .settings(
                            TranscriptionSettingsConfig.builder()
                                .eagerEotThreshold(0.3)
                                .enableEndpointDetection(true)
                                .endOfTurnConfidenceThreshold(0.0)
                                .eotThreshold(0.5)
                                .eotTimeoutMs(500L)
                                .interimResults(true)
                                .keyterm("keyterm")
                                .maxEndpointDelayMs(500L)
                                .maxTurnSilence(100L)
                                .minTurnSilence(100L)
                                .numerals(true)
                                .smartFormat(true)
                                .build()
                        )
                        .build()
                )
                .type(FlowNode.Type.PROMPT)
                .voiceSettings(
                    VoiceSettings.builder()
                        .voice("voice")
                        .apiKeyRef("api_key_ref")
                        .backgroundAudio(
                            VoiceSettings.BackgroundAudio.PredefinedMedia.builder()
                                .value(
                                    VoiceSettings.BackgroundAudio.PredefinedMedia
                                        .PredefinedMediaValue
                                        .SILENCE
                                )
                                .volume(0.1)
                                .build()
                        )
                        .expressiveMode(true)
                        .languageBoost(VoiceSettings.LanguageBoost.AUTO)
                        .similarityBoost(0.0)
                        .speed(0.0)
                        .style(0.0)
                        .temperature(0.0)
                        .useSpeakerBoost(true)
                        .voiceSpeed(0.0)
                        .build()
                )
                .build()

        val roundtrippedFlowNode =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(flowNode),
                jacksonTypeRef<FlowNode>(),
            )

        assertThat(roundtrippedFlowNode).isEqualTo(flowNode)
    }
}
